//! Generate `tests/cases/f32_log.wc`: the hard-to-round regression corpus for
//! [`metallic::f32::log`].
//!
//! `metallic::f32::log` computes `(log2_f64(x) / log2_f64(base)) as f32`, so the
//! only way it can mis-round is *double rounding*: the intermediate `f64`
//! quotient lands on the opposite side of an `f32` midpoint from the true
//! result.  That can only happen when the true result sits within a few `f64`
//! ulp of a midpoint — ~2⁻²⁶ of one in `f32`-ulp terms.
//!
//! Scanning uniformly and MPFR-checking every pair almost never lands on such a
//! case.  Instead we scan hundreds of millions of inputs with a cheap `f64`
//! proxy, keep the tiny fraction near an `f32` midpoint (threshold 2⁻¹⁸, a ~2⁸
//! margin over the real band — wide enough to absorb the proxy's own ~1-ulp
//! error), and emit each survivor with its correctly-rounded (MPFR) result.
//!
//! Run with:
//! ```text
//! cargo run --release --features mpfr --example gen_f32_log_cases
//! ```

use rug::Float;
use std::fmt::Write as _;

/// Cheap `f64` proxy for `log(x, base)`; ≤ ~1 ulp, enough to locate candidates.
fn approx(x: f32, base: f32) -> f64 {
    f64::from(x).ln() / f64::from(base).ln()
}

/// Distance from `y` to the nearest `f32` midpoint, normalized so 0 is on a
/// midpoint (hardest to round) and 1 is on an `f32` grid point (trivial).
fn midpoint_frac(y: f64) -> f64 {
    let y32 = y as f32;
    if !y32.is_finite() {
        return 1.0;
    }
    let c = f64::from(y32);
    let mid_hi = 0.5 * (c + f64::from(y32.next_up()));
    let mid_lo = 0.5 * (c + f64::from(y32.next_down()));
    if (y - mid_hi).abs() < (y - mid_lo).abs() {
        (y - mid_hi).abs() / (mid_hi - c)
    } else {
        (y - mid_lo).abs() / (c - mid_lo)
    }
}

/// SplitMix64: turn a counter into well-distributed bits, avoiding the
/// hyperplane lattice a plain multiplicative hash would leave in (x, base).
fn mix(i: u64) -> u64 {
    let mut z = i.wrapping_mul(0x2545_F491_4F6C_DD1D);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Finite positive normal `f32` from a hash: exponent in `[1, 254]`.
fn posf(hash: u32) -> f32 {
    let exp = 1 + (hash >> 23) % 254;
    f32::from_bits((exp << 23) | (hash & 0x007F_FFFF))
}

/// Correctly-rounded `log(x, base)`: `ln(x)/ln(base)` at 200 bits, rounded once
/// to `f32`.
fn correctly_rounded(x: f32, base: f32) -> f32 {
    const PREC: u32 = 200;
    let lx = Float::with_val(PREC, x).ln();
    let lb = Float::with_val(PREC, base).ln();
    (lx / lb).to_f32()
}

/// Exact C99 hexfloat for a finite `f32`, matching the existing `.wc` corpora.
fn hexf32(x: f32) -> String {
    let bits = x.to_bits();
    let sign = if bits >> 31 == 1 { "-" } else { "" };
    let exp = ((bits >> 23) & 0xFF) as i32;
    let frac = (bits & 0x007F_FFFF) << 1; // 23-bit mantissa as 24 bits (6 hex digits)
    let s = match exp {
        0 if frac == 0 => format!("{sign}0x0p+0"),
        0 => format!("{sign}0x0.{frac:06x}p-126"), // subnormal
        _ => format!("{sign}0x1.{frac:06x}p{:+}", exp - 127),
    };
    assert_eq!(
        hexf_parse::parse_hexf32(&s, false).unwrap().to_bits(),
        bits,
        "hexf32 round-trip failed for {x:e}"
    );
    s
}

fn main() {
    const THRESHOLD: f64 = 1.0 / 262_144.0; // 2⁻¹⁸
    const WIDE: u64 = 200_000_000;
    const NEAR1: u64 = 100_000_000;

    // Wide (x, base) over the whole exponent range.
    let wide = (0..WIDE).map(|i| {
        let h = mix(i);
        [posf((h >> 32) as u32), posf(h as u32)]
    });

    // base near 1 (large results — the hardest rounding), x ∈ [1, 2).
    let near1 = (0..NEAR1).map(|i| {
        let h = mix(i ^ 0xDEAD_BEEF);
        let unit = |w: u32| f32::from_bits(0x3F80_0000 | (w >> 9));
        [unit((h >> 32) as u32), unit(h as u32)]
    });

    // Collect candidates, then sort + dedup by bits for a deterministic file.
    let mut cases: Vec<[f32; 2]> = wide
        .chain(near1)
        .filter(|&[x, base]| midpoint_frac(approx(x, base)) < THRESHOLD)
        .collect();
    cases.sort_unstable_by_key(|&[x, base]| (x.to_bits(), base.to_bits()));
    cases.dedup_by_key(|&mut [x, base]| (x.to_bits(), base.to_bits()));

    let mut out = String::new();
    out.push_str("# Hard-to-round cases for metallic::f32::log(x, base).\n");
    out.push_str("# Columns: x, base, correctly-rounded log(x, base).\n");
    out.push_str(
        "# Generated by `cargo run --release --features mpfr --example gen_f32_log_cases`.\n",
    );

    let mut mismatches = 0;
    for &[x, base] in &cases {
        let want = correctly_rounded(x, base);
        let got = metallic::f32::log(x, base);
        if got.to_bits() != want.to_bits() {
            mismatches += 1;
            eprintln!("MISMATCH log({x:e}, {base:e}) = {got:e} != {want:e} (correct)");
        }
        writeln!(out, "{}, {}, {}", hexf32(x), hexf32(base), hexf32(want)).unwrap();
    }

    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/cases/f32_log.wc");
    std::fs::write(path, out).unwrap();
    eprintln!(
        "wrote {} cases to {path} ({mismatches} current mismatches)",
        cases.len(),
    );
    assert_eq!(mismatches, 0, "metallic::f32::log is not correctly rounded");
}
