//! Inverse trigonometric functions: `asin`, `acos`, `atan`, `atan2`.
//!
//! All reduce to one double-double `atan` kernel.  `atan_dd` reduces `q ∈ [0, 1]`
//! into a width-1/8 cell (`ATAN_TABLE` holds `atan(k/8)`) and evaluates the odd
//! series on `|u| ≤ 1/16`; `asin(x) = atan(x/√(1−x²))`, `acos(x) = atan(√(1−x²)/x)`.
//!
//! Constants below were generated by `tools/gen_atan_f64.py`.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::double::{sqrt_dd, Sum};
use super::pow::poly_dd;

/// `(-1)ᵏ/(2k+1)` as a double-double, low-degree first in `u²` — the atan series.
const ATAN_COEFFS: [Sum; 16] = [
    Sum {
        high: 1.0,
        low: 0.0,
    },
    Sum {
        high: -0.3333333333333333,
        low: -1.850371707708594e-17,
    },
    Sum {
        high: 0.2,
        low: -1.1102230246251566e-17,
    },
    Sum {
        high: -0.14285714285714285,
        low: -7.93016446160826e-18,
    },
    Sum {
        high: 0.1111111111111111,
        low: 6.1679056923619804e-18,
    },
    Sum {
        high: -0.09090909090909091,
        low: 2.523234146875356e-18,
    },
    Sum {
        high: 0.07692307692307693,
        low: -4.270088556250602e-18,
    },
    Sum {
        high: -0.06666666666666667,
        low: -9.251858538542971e-19,
    },
    Sum {
        high: 0.058823529411764705,
        low: 8.163404592832033e-19,
    },
    Sum {
        high: -0.05263157894736842,
        low: -2.921639538487254e-18,
    },
    Sum {
        high: 0.047619047619047616,
        low: 2.64338815386942e-18,
    },
    Sum {
        high: -0.043478260869565216,
        low: -1.206764157201257e-18,
    },
    Sum {
        high: 0.04,
        low: -8.326672684688674e-19,
    },
    Sum {
        high: -0.037037037037037035,
        low: -2.05596856412066e-18,
    },
    Sum {
        high: 0.034482758620689655,
        low: 4.785444071660157e-19,
    },
    Sum {
        high: -0.03225806451612903,
        low: -8.953411488912552e-19,
    },
];

/// Fast-path tail of the atan series in `w = u²`: `w²·(1/5 − w/7 + w²/9 − …)`,
/// the remainder after the two leading terms `1 − w/3` are peeled into
/// double-double.  Evaluated in plain `f64`; `|u| ≤ 1/16` so `w ≤ 2⁻⁸` and the
/// 8 terms reach below 2⁻⁶⁴ relative to `atan(u)`.  See [`atan_dd_fast`].
const ATAN_TAIL: [f64; 8] = [
    0.2,
    -0.14285714285714285,
    0.1111111111111111,
    -0.09090909090909091,
    0.07692307692307693,
    -0.06666666666666667,
    0.058823529411764705,
    -0.05263157894736842,
];

/// `atan(k/8)` as a double-double for `k` in `0..=8`.
const ATAN_TABLE: [Sum; 9] = [
    Sum {
        high: 0.0,
        low: 0.0,
    },
    Sum {
        high: 0.12435499454676144,
        low: -3.1253241424539383e-18,
    },
    Sum {
        high: 0.24497866312686414,
        low: 1.0698755618734451e-17,
    },
    Sum {
        high: 0.35877067027057225,
        low: -2.4623815582638635e-17,
    },
    Sum {
        high: 0.4636476090008061,
        low: 2.2698777452961687e-17,
    },
    Sum {
        high: 0.5585993153435624,
        low: -5.4556305485916264e-18,
    },
    Sum {
        high: 0.6435011087932844,
        low: 1.5834785051444286e-17,
    },
    Sum {
        high: 0.7188299996216245,
        low: -2.1478388444456983e-17,
    },
    Sum {
        high: 0.7853981633974483,
        low: 3.061616997868383e-17,
    },
];

/// π/2 as a double-double.
const FRAC_PI_2: Sum = Sum {
    high: 1.5707963267948966,
    low: 6.123233995736766e-17,
};

/// π as a double-double.
const PI: Sum = Sum {
    high: 3.141592653589793,
    low: 1.2246467991473532e-16,
};

/// One as a double-double.
const ONE: Sum = Sum {
    high: 1.0,
    low: 0.0,
};

/// Relative half-width of the inverse-trig fast-path Ziv gate.  Over a dense
/// sweep of the active band the fast kernel's relative error peaks well below
/// 2⁻⁶⁸; the gate at 2⁻⁶³ keeps a comfortable margin and defers the rest to the
/// double-double kernel, which stays the correctly-rounded reference.
const ATAN_ZIV_EPS: f64 = 1.0842021724855044e-19; // 2⁻⁶³

/// Negate a double-double.
#[inline]
fn neg(v: Sum) -> Sum {
    Sum {
        high: -v.high,
        low: -v.low,
    }
}

/// Ziv gate: round `v` to `f64` when both ends of its `±ATAN_ZIV_EPS` (relative)
/// error interval agree, else `None` to fall back to the accurate kernel.
#[inline]
fn ziv(v: Sum) -> Option<f64> {
    let eps = v.high.abs() * ATAN_ZIV_EPS;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// Arctangent of a double-double `q ∈ [0, 1]`, as a double-double.
#[inline]
fn atan_dd(q: Sum) -> Sum {
    // For `q < 2⁻⁴⁰`, `atan(q) = q − q³/3 + …` agrees with `q` far below ½ ulp, so
    // the correctly-rounded `q.high` is the answer; dropping the low word also
    // protects against a `from_quotient` residual that underflowed to subnormal.
    if q.high < 9.094947017729282e-13 {
        return Sum {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    // u = (q − c) / (1 + q·c), |u| ≤ 1/16 (c is an exact power-of-two multiple).
    let denom = q * c
        + Sum {
            high: 1.0,
            low: 0.0,
        };
    let u = (q + Sum { high: -c, low: 0.0 }) * denom.recip();

    // atan(u) = u · Σ (-1)ᵏ u²ᵏ/(2k+1), evaluated in double-double.
    table + u * poly_dd(u * u, &ATAN_COEFFS)
}

/// Lean counterpart of [`atan_dd`], the inverse-trig functions' fast path.
///
/// The cell reduction is identical, but `atan(u)/u = 1 − w/3 + w²·(…)` peels the
/// two leading terms into double-double (`w = u²`, `1/3` carried as a
/// double-double coefficient) and evaluates only the tiny tail ([`ATAN_TAIL`])
/// in plain `f64`, replacing the 16-term double-double Horner.  A [`ziv`] gate on
/// the reconstructed result accepts it or defers to [`atan_dd`].
#[inline]
fn atan_dd_fast(q: Sum) -> Sum {
    if q.high < 9.094947017729282e-13 {
        return Sum {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    let denom = q * c + ONE;
    let u = (q + Sum { high: -c, low: 0.0 }) * denom.recip();

    let w = u * u;
    let wh = w.high;
    let w2 = wh * wh;
    // 1 − w/3 in double-double (ATAN_COEFFS[1] = −1/3); tail w²·(1/5 − w/7 + …).
    let bracket = (ONE + w * ATAN_COEFFS[1])
        + Sum {
            high: w2 * crate::poly(wh, &ATAN_TAIL),
            low: 0.0,
        };
    table + u * bracket
}

/// `asin(|x|)` for `a = |x| ∈ [0, 1]`, as a double-double in `[0, π/2]`.
///
/// `asin(a) = atan(a/√(1−a²))`; the branch keeps the `atan` argument in `[0, 1]`.
#[inline]
fn asin_pos<K: Fn(Sum) -> Sum>(a: f64, kernel: K) -> Sum {
    if a == 1.0 {
        return FRAC_PI_2;
    }

    // c = √(1 − a²) as a double-double (a² exact, so the cancellation near a = 1
    // is captured).
    let c = sqrt_dd(ONE + neg(Sum::from_product(a, a)));

    if a <= c.high {
        kernel(Sum { high: a, low: 0.0 } * c.recip())
    } else {
        // a/c > 1 ⇒ atan(a/c) = π/2 − atan(c/a)
        FRAC_PI_2 + neg(kernel(c / a))
    }
}

/// Magnitude of `atan(|x|)` in `[0, π/2]`, as a double-double, via `kernel`.
#[inline]
fn atan_mag<K: Fn(Sum) -> Sum>(a: f64, kernel: K) -> Sum {
    if a > 1.0 {
        // atan(a) = π/2 − atan(1/a)
        FRAC_PI_2 + neg(kernel(ONE / a))
    } else {
        kernel(Sum { high: a, low: 0.0 })
    }
}

/// Arctangent
#[must_use]
#[inline]
pub fn atan(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    let a = x.abs();
    if a.is_infinite() {
        return core::f64::consts::FRAC_PI_2.copysign(x);
    }

    let magnitude = ziv(atan_mag(a, atan_dd_fast)).unwrap_or_else(|| {
        let m = atan_mag(a, atan_dd);
        m.high + m.low
    });
    magnitude.copysign(x)
}

/// Arcsine
#[must_use]
#[inline]
pub fn asin(x: f64) -> f64 {
    let a = x.abs();
    if !(a <= 1.0) {
        return f64::NAN; // |x| > 1 or NaN
    }

    let magnitude = ziv(asin_pos(a, atan_dd_fast)).unwrap_or_else(|| {
        let m = asin_pos(a, atan_dd);
        m.high + m.low
    });
    magnitude.copysign(x)
}

/// Arccosine
#[must_use]
#[inline]
pub fn acos(x: f64) -> f64 {
    if !(x.abs() <= 1.0) {
        return f64::NAN; // |x| > 1 or NaN
    }

    // acos(x) = π/2 − asin(x): π/2 − asin_pos(x) for x ≥ 0, π/2 + asin_pos(|x|) for x < 0.
    let acos_dd = |kernel: fn(Sum) -> Sum| {
        let s = asin_pos(x.abs(), kernel);
        if x.is_sign_negative() {
            FRAC_PI_2 + s
        } else {
            FRAC_PI_2 + neg(s)
        }
    };
    ziv(acos_dd(atan_dd_fast)).unwrap_or_else(|| {
        let m = acos_dd(atan_dd);
        m.high + m.low
    })
}

/// Magnitude of `atan2(y, x)` in `[0, π]` for finite nonzero `a = |x|`, `b = |y|`.
#[inline]
fn atan2_mag(a: f64, b: f64, x_negative: bool) -> f64 {
    let (big, small, swapped) = if a >= b { (a, b, false) } else { (b, a, true) };

    let theta = |kernel: fn(Sum) -> Sum| {
        // φ = atan(small/big) ∈ [0, π/4], or π/2 − atan(small/big) when `swapped`.
        let q = small / big;
        let inner = if q < 9.094947017729282e-13 {
            // Tiny ratio: atan(q) = q far below ½ ulp, and the *unscaled* IEEE
            // quotient `small/big` is correctly rounded down into the subnormals.
            Sum { high: q, low: 0.0 }
        } else {
            // Scale both legs so the larger lands in [1, 2): exact, ratio-preserving,
            // and it keeps the `from_quotient` residual out of the subnormal range.
            let (_, exp) = super::frexp(big);
            let big = super::ldexp(big, 1 - exp);
            let small = super::ldexp(small, 1 - exp);
            kernel(Sum::from_quotient(small, big))
        };

        let phi = if swapped {
            FRAC_PI_2 + neg(inner)
        } else {
            inner
        };
        if x_negative {
            PI + neg(phi)
        } else {
            phi
        }
    };

    ziv(theta(atan_dd_fast)).unwrap_or_else(|| {
        let m = theta(atan_dd);
        m.high + m.low
    })
}

/// Arctangent of `y / x`, using the signs of both to select the quadrant
///
/// The result is the angle in `(-π, π]` between the positive `x`-axis and the
/// point `(x, y)`, carrying the sign of `y`.
#[must_use]
#[inline]
pub fn atan2(y: f64, x: f64) -> f64 {
    use core::f64::consts::{FRAC_PI_2, FRAC_PI_4, PI};

    /// Correctly-rounded `f64` of 3π/4.
    const THREE_PI_4: f64 = 2.356194490192345;

    if x.is_nan() || y.is_nan() {
        return f64::NAN;
    }

    if x.is_infinite() || y.is_infinite() {
        let magnitude = match (x.is_infinite(), y.is_infinite()) {
            (true, true) if x.is_sign_positive() => FRAC_PI_4,
            (true, true) => THREE_PI_4,
            (true, false) if x.is_sign_positive() => 0.0,
            (true, false) => PI,
            (false, true) => FRAC_PI_2,
            (false, false) => unreachable!(),
        };
        return magnitude.copysign(y);
    }

    if y == 0.0 {
        return if x.is_sign_positive() { 0.0 } else { PI }.copysign(y);
    }
    if x == 0.0 {
        return FRAC_PI_2.copysign(y);
    }

    atan2_mag(x.abs(), y.abs(), x.is_sign_negative()).copysign(y)
}
