//! Inverse trigonometric functions: `asin`, `acos`, `atan`, `atan2`.
//!
//! `atan`/`atan2` use one double-double `atan` kernel: `atan_dd` reduces
//! `q ∈ [0, 1]` into a width-1/8 cell (`ATAN_TABLE` holds `atan(k/8)`) and
//! evaluates the odd series on `|u| ≤ 1/16`.  `asin`/`acos` take a leaner fast
//! path — the direct series [`asin_kernel_fast`] on `t ∈ [−½, ½]` (reflecting
//! through `s = √((1−|x|)/2)` for `|x| ≥ ½`) — and fall back, via a Ziv gate, to
//! the accurate `asin(x) = atan(x/√(1−x²))` (`asin_pos`).
//!
//! Constants below were generated by `tools/gen_atan_f64.py` and
//! `tools/gen_inv_f64.py`.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::double::{DoubleDouble, sqrt_dd};
use super::pow::poly_dd;

/// `(-1)ᵏ/(2k+1)` as a double-double, low-degree first in `u²` — the atan series.
const ATAN_COEFFS: [DoubleDouble; 16] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: -0.3333333333333333,
        low: -1.850371707708594e-17,
    },
    DoubleDouble {
        high: 0.2,
        low: -1.1102230246251566e-17,
    },
    DoubleDouble {
        high: -0.14285714285714285,
        low: -7.93016446160826e-18,
    },
    DoubleDouble {
        high: 0.1111111111111111,
        low: 6.1679056923619804e-18,
    },
    DoubleDouble {
        high: -0.09090909090909091,
        low: 2.523234146875356e-18,
    },
    DoubleDouble {
        high: 0.07692307692307693,
        low: -4.270088556250602e-18,
    },
    DoubleDouble {
        high: -0.06666666666666667,
        low: -9.251858538542971e-19,
    },
    DoubleDouble {
        high: 0.058823529411764705,
        low: 8.163404592832033e-19,
    },
    DoubleDouble {
        high: -0.05263157894736842,
        low: -2.921639538487254e-18,
    },
    DoubleDouble {
        high: 0.047619047619047616,
        low: 2.64338815386942e-18,
    },
    DoubleDouble {
        high: -0.043478260869565216,
        low: -1.206764157201257e-18,
    },
    DoubleDouble {
        high: 0.04,
        low: -8.326672684688674e-19,
    },
    DoubleDouble {
        high: -0.037037037037037035,
        low: -2.05596856412066e-18,
    },
    DoubleDouble {
        high: 0.034482758620689655,
        low: 4.785444071660157e-19,
    },
    DoubleDouble {
        high: -0.03225806451612903,
        low: -8.953411488912552e-19,
    },
];

/// Fast-path tail of the atan series in `w = u²`: `w²·(1/5 − w/7 + w²/9 − …)`,
/// the remainder after the two leading terms `1 − w/3` are peeled into
/// double-double.  Evaluated in plain `f64`; `|u| ≤ 1/16` so `w ≤ 2⁻⁸` and the
/// 8 terms reach below 2⁻⁶⁴ relative to `atan(u)`.  See [`atan_dd_fast`].
const ATAN_TAIL: [f64; 8] = [
    0.2,
    -0.14285714285714285,
    0.1111111111111111,
    -0.09090909090909091,
    0.07692307692307693,
    -0.06666666666666667,
    0.058823529411764705,
    -0.05263157894736842,
];

/// Leading 5 terms of `asin(t)/t = Σ aₖ·u^k` (`u = t²`), as double-doubles,
/// low-degree first — `aₖ = C(2k,k)/(4ᵏ(2k+1))`.  The direct inverse-trig fast
/// path ([`asin_kernel_fast`]) carries these exactly and fits the `u⁵` remainder
/// ([`ASIN_TAIL`]) in plain `f64`.  Generated by `tools/gen_inv_f64.py`.
const ASIN_LEADS: [DoubleDouble; 5] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.16666666666666666,
        low: 9.25185853854297e-18,
    },
    DoubleDouble {
        high: 0.075,
        low: 2.7755575615628915e-18,
    },
    DoubleDouble {
        high: 0.044642857142857144,
        low: -9.912705577010326e-19,
    },
    DoubleDouble {
        high: 0.030381944444444444,
        low: 3.854941057726238e-19,
    },
];

/// Fast-path tail of `asin(t)/t` in `u = t²`: `u⁵·(a₅ + a₆·u + …)`, the remainder
/// after [`ASIN_LEADS`] is peeled into double-double.  Evaluated in plain `f64`;
/// `u ≤ ¼` so the 14 terms reach below 2⁻⁷⁰ relative to `asin(t)/t`.  See
/// [`asin_kernel_fast`].
const ASIN_TAIL: [f64; 14] = [
    0.022372159090909092,
    0.017352764423077784,
    0.013964843749776683,
    0.011551800918881265,
    0.009761608324235905,
    0.008390373922821156,
    0.0073117481531127775,
    0.006457924173680071,
    0.005637927414188107,
    0.005831792719059257,
    0.001546555293032924,
    0.013792526540942715,
    -0.014288966464381174,
    0.02128867462959945,
];

/// `atan(k/8)` as a double-double for `k` in `0..=8`.
const ATAN_TABLE: [DoubleDouble; 9] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.12435499454676144,
        low: -3.1253241424539383e-18,
    },
    DoubleDouble {
        high: 0.24497866312686414,
        low: 1.0698755618734451e-17,
    },
    DoubleDouble {
        high: 0.35877067027057225,
        low: -2.4623815582638635e-17,
    },
    DoubleDouble {
        high: 0.4636476090008061,
        low: 2.2698777452961687e-17,
    },
    DoubleDouble {
        high: 0.5585993153435624,
        low: -5.4556305485916264e-18,
    },
    DoubleDouble {
        high: 0.6435011087932844,
        low: 1.5834785051444286e-17,
    },
    DoubleDouble {
        high: 0.7188299996216245,
        low: -2.1478388444456983e-17,
    },
    DoubleDouble {
        high: 0.7853981633974483,
        low: 3.061616997868383e-17,
    },
];

/// π/2 as a double-double.
const FRAC_PI_2: DoubleDouble = DoubleDouble {
    high: 1.5707963267948966,
    low: 6.123233995736766e-17,
};

/// π as a double-double.
const PI: DoubleDouble = DoubleDouble {
    high: 3.141592653589793,
    low: 1.2246467991473532e-16,
};

/// One as a double-double.
const ONE: DoubleDouble = DoubleDouble {
    high: 1.0,
    low: 0.0,
};

/// Relative half-width of the inverse-trig fast-path Ziv gate.  Over a dense
/// sweep of the active band the fast kernel's relative error peaks well below
/// 2⁻⁶⁸; the gate at 2⁻⁶³ keeps a comfortable margin and defers the rest to the
/// double-double kernel, which stays the correctly-rounded reference.
const ATAN_ZIV_EPS: f64 = 1.0842021724855044e-19; // 2⁻⁶³

/// Negate a double-double.
#[inline]
fn neg(v: DoubleDouble) -> DoubleDouble {
    DoubleDouble {
        high: -v.high,
        low: -v.low,
    }
}

/// Ziv gate: round `v` to `f64` when both ends of its `±ATAN_ZIV_EPS` (relative)
/// error interval agree, else `None` to fall back to the accurate kernel.
#[inline]
fn ziv(v: DoubleDouble) -> Option<f64> {
    let eps = v.high.abs() * ATAN_ZIV_EPS;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// Arctangent of a double-double `q ∈ [0, 1]`, as a double-double.
#[inline]
fn atan_dd(q: DoubleDouble) -> DoubleDouble {
    // For `q < 2⁻⁴⁰`, `atan(q) = q − q³/3 + …` agrees with `q` far below ½ ulp, so
    // the correctly-rounded `q.high` is the answer; dropping the low word also
    // protects against a `from_quotient` residual that underflowed to subnormal.
    if q.high < 9.094947017729282e-13 {
        return DoubleDouble {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    // u = (q − c) / (1 + q·c), |u| ≤ 1/16 (c is an exact power-of-two multiple).
    let denom = q * c
        + DoubleDouble {
            high: 1.0,
            low: 0.0,
        };
    let u = (q + DoubleDouble { high: -c, low: 0.0 }) * denom.recip();

    atan_cell(table, u)
}

/// Accurate counterpart of [`atan_cell_fast`]: finish from a reduced cell via the
/// full double-double series `atan(k/8 + …) = table + u·Σ(−1)ᵏu²ᵏ/(2k+1)`.
///
/// `table = atan(k/8)` and `|u| ≤ 1/16`.  Shared by [`atan_dd`] and the fused
/// `atan2` reduction, which differ only in how they form `u`.
#[inline]
fn atan_cell(table: DoubleDouble, u: DoubleDouble) -> DoubleDouble {
    table + u * poly_dd(u * u, &ATAN_COEFFS)
}

/// Lean counterpart of [`atan_dd`], the inverse-trig functions' fast path.
///
/// The cell reduction is identical, but `atan(u)/u = 1 − w/3 + w²·(…)` peels the
/// two leading terms into double-double (`w = u²`, `1/3` carried as a
/// double-double coefficient) and evaluates only the tiny tail ([`ATAN_TAIL`])
/// in plain `f64`, replacing the 16-term double-double Horner.  A [`ziv`] gate on
/// the reconstructed result accepts it or defers to [`atan_dd`].
#[inline]
fn atan_dd_fast(q: DoubleDouble) -> DoubleDouble {
    if q.high < 9.094947017729282e-13 {
        return DoubleDouble {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    let denom = q * c + ONE;
    let u = (q + DoubleDouble { high: -c, low: 0.0 }) * denom.recip();

    atan_cell_fast(table, u)
}

/// Finish the fast path from a reduced cell: `atan(k/8 + …) = table + u·(1 − u²/3 + …)`.
///
/// `table = atan(k/8)` and `u` is the cell-reduced argument (`|u| ≤ 1/16`).  Shared
/// by [`atan_dd_fast`] and [`atan_recip_fast`], which differ only in how they form `u`.
#[inline]
fn atan_cell_fast(table: DoubleDouble, u: DoubleDouble) -> DoubleDouble {
    let w = u * u;
    let wh = w.high;
    let w2 = wh * wh;
    // 1 − w/3 in double-double (ATAN_COEFFS[1] = −1/3); tail w²·(1/5 − w/7 + …).
    let bracket = (ONE + w * ATAN_COEFFS[1])
        + DoubleDouble {
            high: w2 * crate::poly(wh, &ATAN_TAIL),
            low: 0.0,
        };
    table + u * bracket
}

/// `atan(1/a)` for `a > 1`, the fast path's reflection leg, without ever forming
/// `1/a` as a double-double.
///
/// With `v = 1/a`, the cell reduction `u = (v − c)/(1 + v·c)` becomes
/// `u = (1 − a·c)/(a + c)` after multiplying through by `a`.  So the leg spends one
/// `1/a` (a plain `f64`, only to pick the cell `k = round(8/a)`) plus the cell's own
/// `recip` — **two** divisions, versus the **three** of `atan_dd_fast(ONE / a)`, whose
/// `DoubleDouble / f64` reciprocal alone costs two.  `1 − a·c` is exact (`a·c ≈ 1`
/// inside the cell and `from_product` is exact), so `u` is at least as accurate as
/// the original, and `|u| ≤ 1/16` exactly as in [`atan_dd_fast`].
#[inline]
fn atan_recip_fast(a: f64) -> DoubleDouble {
    let inv = 1.0 / a;

    // a > 1.1e12: atan(1/a) = 1/a to far below ½ ulp (matches `atan_dd_fast`'s guard,
    // since `(ONE / a).high == 1.0 / a`).
    if inv < 9.094947017729282e-13 {
        return DoubleDouble {
            high: inv,
            low: 0.0,
        };
    }

    let k = (inv * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    // u = (1 − a·c)/(a + c).  `1 − a·c` is exact and `a + c` is a normalized pair.
    let num = ONE + neg(DoubleDouble::from_product(a, c));
    let den = DoubleDouble::from_sum(a, c);
    let u = num * den.recip();

    atan_cell_fast(table, u)
}

/// `asin(t)` for `t ∈ [−½, ½]`, as a double-double, via the direct series
/// `asin(t) = t·B(t²)`.  Mirrors the f32 `asin_near_zero` kernel: the 5 leading
/// terms of `B` are carried in double-double ([`ASIN_LEADS`]) and the `u⁵`
/// remainder ([`ASIN_TAIL`]) in plain `f64`.  `t` is a double-double so the
/// reflection's `s = √((1−|x|)/2)` keeps full precision (a single-`f64` `s` would
/// feed ≈2⁻⁵³ straight into the near-linear `asin(s) ≈ s`).
#[inline]
fn asin_kernel_fast(t: DoubleDouble) -> DoubleDouble {
    let w = t * t; // u = t²
    let u = w.high;
    let u2 = u * u;
    let u5 = u2 * u2 * u;
    // 2-way Estrin of `1 + a1·w + … + a4·w⁴` (ASIN_LEADS): the two low pairs evaluate
    // in parallel and `a4·w⁴` folds into the inner term.  The `u⁵` remainder
    // (ASIN_TAIL) is plain `f64`.
    let w2 = w * w;
    let p0 = ASIN_LEADS[0] + w * ASIN_LEADS[1];
    let p1 = ASIN_LEADS[2] + w * ASIN_LEADS[3];
    let bracket = (p0 + w2 * (p1 + w2 * ASIN_LEADS[4]))
        + DoubleDouble {
            high: u5 * crate::poly(u, &ASIN_TAIL),
            low: 0.0,
        };
    bracket * t
}

/// `s = √((1−a)/2)` as a double-double for `a ∈ [½, 1)` — the inverse-trig
/// reflection node.  `1−a` is exact by Sterbenz and `·½` is exact, so this is a
/// double-double `sqrt` of an exact `f64`.
#[inline]
fn asin_reflect_node(a: f64) -> DoubleDouble {
    sqrt_dd(DoubleDouble {
        high: (1.0 - a) * 0.5,
        low: 0.0,
    })
}

/// `asin(|x|)` for `a = |x| ∈ [0, 1]`, the inverse-trig fast path: the direct
/// [`asin_kernel_fast`] for `a < ½`, else the reflection `asin(a) = π/2 − 2·asin(s)`
/// with `s = √((1−a)/2) ∈ [0, ½]`.  A [`ziv`] gate accepts it or defers to the
/// accurate [`asin_pos(a, atan_dd)`](asin_pos).
#[inline]
fn asin_fast(a: f64) -> DoubleDouble {
    if a < 0.5 {
        asin_kernel_fast(DoubleDouble { high: a, low: 0.0 })
    } else if a == 1.0 {
        FRAC_PI_2 // asin(1) = π/2 (and avoids √0 → 0/0 in the reflection)
    } else {
        FRAC_PI_2 + neg(asin_kernel_fast(asin_reflect_node(a)) * 2.0)
    }
}

/// `acos(x)` for `x ∈ [−1, 1]`, the fast path.  `acos(x) = π/2 − asin(x)`: the
/// direct [`asin_kernel_fast`] for `|x| < ½`, else `2·asin(s)` (`x ≥ 0`) or
/// `π − 2·asin(s)` (`x < 0`) with `s = √((1−|x|)/2)`.
#[inline]
fn acos_fast(x: f64) -> DoubleDouble {
    let a = x.abs();
    if a < 0.5 {
        FRAC_PI_2 + neg(asin_kernel_fast(DoubleDouble { high: x, low: 0.0 }))
    } else if a == 1.0 {
        // acos(1) = 0, acos(−1) = π (and avoids √0 → 0/0 in the reflection).
        if x.is_sign_negative() {
            PI
        } else {
            DoubleDouble {
                high: 0.0,
                low: 0.0,
            }
        }
    } else {
        let two = asin_kernel_fast(asin_reflect_node(a)) * 2.0;
        if x.is_sign_negative() {
            PI + neg(two)
        } else {
            two
        }
    }
}

/// `asin(|x|)` for `a = |x| ∈ [0, 1]`, as a double-double in `[0, π/2]`.
///
/// `asin(a) = atan(a/√(1−a²))`; the branch keeps the `atan` argument in `[0, 1]`.
#[inline]
fn asin_pos<K: Fn(DoubleDouble) -> DoubleDouble>(a: f64, kernel: K) -> DoubleDouble {
    if a == 1.0 {
        return FRAC_PI_2;
    }

    // c = √(1 − a²) as a double-double (a² exact, so the cancellation near a = 1
    // is captured).
    let c = sqrt_dd(ONE + neg(DoubleDouble::from_product(a, a)));

    if a <= c.high {
        kernel(DoubleDouble { high: a, low: 0.0 } * c.recip())
    } else {
        // a/c > 1 ⇒ atan(a/c) = π/2 − atan(c/a)
        FRAC_PI_2 + neg(kernel(c / a))
    }
}

/// Magnitude of `atan(|x|)` in `[0, π/2]`, as a double-double, via `kernel`.
#[inline]
fn atan_mag<K: Fn(DoubleDouble) -> DoubleDouble>(a: f64, kernel: K) -> DoubleDouble {
    if a > 1.0 {
        // atan(a) = π/2 − atan(1/a)
        FRAC_PI_2 + neg(kernel(ONE / a))
    } else {
        kernel(DoubleDouble { high: a, low: 0.0 })
    }
}

/// Arctangent
#[must_use]
#[inline]
pub fn atan(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    let a = x.abs();
    if a.is_infinite() {
        return core::f64::consts::FRAC_PI_2.copysign(x);
    }

    // Fast path: for |x| > 1 reflect via atan(a) = π/2 − atan(1/a) using the
    // division-frugal [`atan_recip_fast`]; otherwise the direct cell kernel.  The
    // accurate fallback keeps the shared [`atan_mag`] reflection.
    let fast = if a > 1.0 {
        FRAC_PI_2 + neg(atan_recip_fast(a))
    } else {
        atan_dd_fast(DoubleDouble { high: a, low: 0.0 })
    };
    let magnitude = ziv(fast).unwrap_or_else(|| {
        let m = atan_mag(a, atan_dd);
        m.high + m.low
    });
    magnitude.copysign(x)
}

/// Arcsine
#[must_use]
#[inline]
pub fn asin(x: f64) -> f64 {
    let a = x.abs();
    if !(a <= 1.0) {
        return f64::NAN; // |x| > 1 or NaN
    }

    let magnitude = ziv(asin_fast(a)).unwrap_or_else(|| {
        let m = asin_pos(a, atan_dd);
        m.high + m.low
    });
    magnitude.copysign(x)
}

/// Arccosine
#[must_use]
#[inline]
pub fn acos(x: f64) -> f64 {
    if !(x.abs() <= 1.0) {
        return f64::NAN; // |x| > 1 or NaN
    }

    ziv(acos_fast(x)).unwrap_or_else(|| {
        // acos(x) = π/2 − asin(x): π/2 − asin_pos(x) for x ≥ 0, π/2 + asin_pos(|x|)
        // for x < 0 — via the accurate atan-based `asin_pos`.
        let s = asin_pos(x.abs(), atan_dd);
        let m = if x.is_sign_negative() {
            FRAC_PI_2 + s
        } else {
            FRAC_PI_2 + neg(s)
        };
        m.high + m.low
    })
}

/// Magnitude of `atan2(y, x)` in `[0, π]` for finite nonzero `a = |x|`, `b = |y|`.
#[inline]
fn atan2_mag(a: f64, b: f64, x_negative: bool) -> f64 {
    let (big, small, swapped) = if a >= b { (a, b, false) } else { (b, a, true) };

    let theta = |cell: fn(DoubleDouble, DoubleDouble) -> DoubleDouble| {
        // φ = atan(small/big) ∈ [0, π/4], or π/2 − atan(small/big) when `swapped`.
        let q = small / big;
        let inner = if q < 9.094947017729282e-13 {
            // Tiny ratio: atan(q) = q far below ½ ulp, and the *unscaled* IEEE
            // quotient `small/big` is correctly rounded down into the subnormals.
            DoubleDouble { high: q, low: 0.0 }
        } else {
            // Scale both legs so the larger lands in [1, 2): exact and
            // ratio-preserving, keeping `small − c·big` / `big + c·small` clear of
            // overflow and the small leg out of the subnormals.
            let (_, exp) = super::frexp(big);
            let big = super::ldexp(big, 1 - exp);
            let small = super::ldexp(small, 1 - exp);

            // Cell reduction without forming small/big as a double-double: with
            // ratio = small/big, `u = (ratio − c)/(1 + ratio·c) = (small − c·big)/(big
            // + c·small)`.  `k = round(8·ratio)` reuses the `q` already in hand
            // (scaling preserves the ratio exactly), so the leg spends only that one
            // `q` division plus this `recip` — two, versus the four of the
            // `from_quotient` path (the `q` test, the two-division quotient, the cell
            // `recip`).  `small − c·big` is exact (c·big ≈ small in-cell, `from_product`
            // exact), so `u` is at least as accurate, and `|u| ≤ 1/16` as before.
            let k = (q * 8.0).round_ties_even();
            let c = k * 0.125;
            let table = ATAN_TABLE[k as usize];

            let num = DoubleDouble {
                high: small,
                low: 0.0,
            } + neg(DoubleDouble::from_product(c, big));
            let den = DoubleDouble {
                high: big,
                low: 0.0,
            } + DoubleDouble::from_product(c, small);
            let u = num * den.recip();

            cell(table, u)
        };

        let phi = if swapped {
            FRAC_PI_2 + neg(inner)
        } else {
            inner
        };
        if x_negative { PI + neg(phi) } else { phi }
    };

    ziv(theta(atan_cell_fast)).unwrap_or_else(|| {
        let m = theta(atan_cell);
        m.high + m.low
    })
}

/// Arctangent of `y / x`, using the signs of both to select the quadrant
///
/// The result is the angle in `(-π, π]` between the positive `x`-axis and the
/// point `(x, y)`, carrying the sign of `y`.
#[must_use]
#[inline]
pub fn atan2(y: f64, x: f64) -> f64 {
    use core::f64::consts::{FRAC_PI_2, FRAC_PI_4, PI};

    /// Correctly-rounded `f64` of 3π/4.
    const THREE_PI_4: f64 = 2.356194490192345;

    if x.is_nan() || y.is_nan() {
        return f64::NAN;
    }

    if x.is_infinite() || y.is_infinite() {
        let magnitude = match (x.is_infinite(), y.is_infinite()) {
            (true, true) if x.is_sign_positive() => FRAC_PI_4,
            (true, true) => THREE_PI_4,
            (true, false) if x.is_sign_positive() => 0.0,
            (true, false) => PI,
            (false, true) => FRAC_PI_2,
            (false, false) => unreachable!(),
        };
        return magnitude.copysign(y);
    }

    if y == 0.0 {
        return if x.is_sign_positive() { 0.0 } else { PI }.copysign(y);
    }
    if x == 0.0 {
        return FRAC_PI_2.copysign(y);
    }

    atan2_mag(x.abs(), y.abs(), x.is_sign_negative()).copysign(y)
}
