//! Exponential family: `exp`, `exp2`, `exp10`, `exp_m1`.
//!
//! Constants below were generated by `tools/gen_exp_f64.py`.
//! Do not edit by hand; re-run the generator instead.
#![allow(
    clippy::unreadable_literal,
    clippy::excessive_precision,
    clippy::approx_constant
)]

use super::double::{DoubleDouble, fast_ldexp, fast_sum};

const LN2_OVER_N_HI: f64 = 0.005415212348111709;
const LN2_OVER_N_LO: f64 = 1.2864023111638346e-14;
// check: HI low 17 bits = 0
// rel err of (HI+LO) vs ln2/128: 2^-92.5

const EXP2_TABLE: [(f64, f64); 128] = [
    (1.0, 0.0),
    (1.0054299011128027, 9.499186535455032e-17),
    (1.0108892860517005, -1.5234778603368577e-17),
    (1.016378314910953, -5.77217007319966e-17),
    (1.0218971486541166, 5.109225028973444e-17),
    (1.0274459491187637, -4.9560741746453704e-17),
    (1.0330248790212284, 7.600838874027088e-18),
    (1.0386341019613787, 5.996273788852511e-17),
    (1.0442737824274138, 8.551889705537965e-17),
    (1.0499440858006872, 5.592937848127003e-17),
    (1.0556451783605572, 1.759325738772092e-18),
    (1.061377227289262, -1.1973537085365658e-17),
    (1.0671404006768237, -7.899853966841582e-17),
    (1.0729348675259756, -3.839668843358824e-18),
    (1.0787607977571199, -6.656660436056593e-17),
    (1.0846183622133092, 3.166152845816346e-17),
    (1.0905077326652577, -3.046782079812471e-17),
    (1.0964290818163769, -5.919933484449316e-17),
    (1.102382583307841, 5.2660368715706944e-17),
    (1.1083684117236787, -8.786813845180527e-17),
    (1.1143867425958924, 1.0410278456845571e-16),
    (1.1204377524096067, -6.201085906554179e-17),
    (1.1265216186082418, 5.165856758795457e-17),
    (1.1326385195987192, 3.237356166738e-17),
    (1.1387886347566916, 8.912812676025408e-17),
    (1.1449721444318042, 4.6412898921700107e-17),
    (1.1511892299529827, 3.250710218863827e-17),
    (1.1574400736337511, -9.1238712311344e-17),
    (1.1637248587775775, 3.8292048369240935e-17),
    (1.1700437696832502, -1.8477442017900047e-18),
    (1.1763969916502812, 5.554203254218079e-17),
    (1.182784710984341, 1.542975430079076e-17),
    (1.189207115002721, 3.982015231465646e-17),
    (1.1956643920398273, 4.6166036704814814e-17),
    (1.202156731452703, 6.644981499252301e-17),
    (1.2086843236265816, -4.746725945228984e-17),
    (1.215247359980469, -7.712630692681488e-17),
    (1.2218460329727576, -1.0611021211402691e-16),
    (1.22848053610687, -1.89878163130253e-17),
    (1.2351510639369334, -1.0755244344307841e-16),
    (1.241857812073484, 4.658027591836937e-17),
    (1.2486009771892048, -8.261810999021964e-17),
    (1.255380757024691, -6.7113898212968784e-18),
    (1.2621973503942507, -3.0844648874738465e-17),
    (1.2690509571917332, 2.667932131342186e-18),
    (1.275941778396392, 9.91543024421429e-17),
    (1.2828700160787783, 1.713594918243561e-17),
    (1.2898358734066657, 8.949257530897592e-17),
    (1.2968395546510096, 2.5382502794888315e-17),
    (1.3038812651919358, 8.647675598267871e-17),
    (1.3109612115247644, -7.181536135519454e-17),
    (1.318079601266064, -5.4579558271491535e-17),
    (1.3252366431597413, -2.8587312100388614e-17),
    (1.3324325470831615, -5.101586630916744e-17),
    (1.339667524053303, 8.927282594831732e-17),
    (1.3469417862329458, 3.224065101254679e-17),
    (1.3542555469368927, 7.70094837980299e-17),
    (1.3616090206382248, 1.533787661270668e-18),
    (1.3690024229745905, 9.593797919118849e-17),
    (1.3764359707545302, -6.898588935871801e-17),
    (1.383909881963832, -6.770511658794786e-17),
    (1.3914243757719262, -4.9061748652889893e-17),
    (1.3989796725383112, -9.614213209051323e-17),
    (1.4065759938190154, 7.034914812136422e-18),
    (1.4142135623730951, -9.667293313452913e-17),
    (1.4218926021691656, -1.6077828915890244e-17),
    (1.42961333839197, -1.2031642489053655e-17),
    (1.4373759974489824, -4.2040340164675566e-17),
    (1.4451808069770467, -3.0237581349939873e-17),
    (1.4530279958490526, -5.779948609396106e-17),
    (1.460917794180647, -5.600377186075216e-17),
    (1.4688504333369818, 8.465882756533628e-17),
    (1.4768261459394993, -3.483994556892796e-17),
    (1.4848451658727524, 1.0780086764407481e-16),
    (1.4929077282912648, 1.4192920154284036e-17),
    (1.5010140696264256, -6.413767275790235e-17),
    (1.5091644275934228, -1.016455327754295e-16),
    (1.5173590411982147, -4.308699472043341e-17),
    (1.5255981507445384, -1.1024941712342561e-16),
    (1.533881997840956, 8.875226844438446e-17),
    (1.5422108254079407, 7.949834809697621e-17),
    (1.550584877685, -1.4600706590689385e-17),
    (1.559004400237837, 3.7812070533575275e-17),
    (1.567469639965553, -1.0352061768849722e-16),
    (1.5759808451078865, -1.0136916471278304e-17),
    (1.5845382652524937, -1.9337717034585703e-17),
    (1.593142151342267, -1.0094406542311964e-16),
    (1.6017927556826934, -6.054917453527784e-17),
    (1.6104903319492543, 2.4707192569797888e-17),
    (1.6192351351948637, 2.0941334154229092e-17),
    (1.6280274218573478, -6.712955084707084e-17),
    (1.6368674497669644, 7.698325071319876e-17),
    (1.645755478153965, -1.0125679913674773e-16),
    (1.6546917676561943, 9.643294303196029e-17),
    (1.6636765803267364, 5.8909926967131e-17),
    (1.6727101796415966, -5.476715964599563e-17),
    (1.681792830507429, 8.199010020581497e-17),
    (1.6909247992693053, -9.66967147439488e-17),
    (1.7001063537185235, -8.0237193703977e-18),
    (1.709337763100463, -9.868779456632931e-17),
    (1.718619298122478, -1.851380418263111e-17),
    (1.7279512309618377, -1.0750981861204642e-16),
    (1.7373338352737062, 3.164389299292957e-17),
    (1.746767386199169, -1.0752290483507515e-16),
    (1.7562521603732995, 2.960140695448873e-17),
    (1.7657884359332727, 9.461315018083268e-17),
    (1.7753764925265212, 6.429731796556572e-17),
    (1.785016611318935, 1.5330400121031314e-17),
    (1.7947090750031072, 1.8227458427912087e-17),
    (1.804454167806624, -5.177222408793318e-17),
    (1.8142521755003989, -9.969531538920349e-17),
    (1.8241033854070534, -1.0159627862277083e-16),
    (1.8340080864093424, 3.283107224245627e-17),
    (1.843966568958626, -5.939742026949965e-17),
    (1.8539791250833855, 9.761887490727594e-17),
    (1.864046048397789, 6.540912680620572e-17),
    (1.8741676341103, -6.122763413004143e-17),
    (1.8843441790323345, -8.226593125533711e-17),
    (1.8945759815869656, 3.4034035352165297e-17),
    (1.9048633418176741, 6.533857514718279e-17),
    (1.9152065613971474, -1.0619946056195963e-16),
    (1.925605943636125, -9.914963769693741e-17),
    (1.9360617934922943, 1.0332385960676326e-16),
    (1.9465744175792332, 6.811022349533877e-17),
    (1.9571441241754002, 8.960767791036668e-17),
    (1.9677712232331759, -1.0314928011531132e-16),
    (1.978456026387951, 4.0388753109278167e-17),
    (1.9891988469672663, 8.2051326383692e-18),
];

const EXP_R_COEFFS: [(f64, f64); 9] = [
    (1.0, 0.0),
    (1.0, -2.80175043845722e-28),
    (0.5, 4.957436121490076e-28),
    (0.16666666666666666, 9.25236795203688e-18),
    (0.041666666666666664, 2.312586914244713e-18),
    (0.008333333333333083, -1.6217792309420587e-19),
    (0.0013888888888889642, -6.741971285310136e-20),
    (0.00019841274388185108, 6.979145348335693e-21),
    (2.4801584758888655e-05, -1.6080712309255824e-21),
];

const LN10_HI: f64 = 2.302585092994046;
const LN10_LO: f64 = -2.1707562233822494e-16;
const N_LOG2_10: f64 = 425.20679614558236;

const EXPM1_S_COEFFS: [(f64, f64); 10] = [
    (1.0, 0.0),
    (0.5, 0.0),
    (0.16666666666666666, 9.25185853854297e-18),
    (0.041666666666666664, 2.3129646346357427e-18),
    (0.008333333333333333, 1.1564823173178714e-19),
    (0.001388888888888889, -5.300543954373577e-20),
    (0.0001984126984126984, 1.7209558293420705e-22),
    (2.48015873015873e-05, 2.1511947866775882e-23),
    (2.7557319223985893e-06, -1.858393274046472e-22),
    (2.755731922398589e-07, 2.3767714622250297e-23),
];

/// Plain-`f64` tail of `exp(r)`: `(exp(z) − 1 − z)/z² = ∑ zᵏ/(k+2)!`, low-degree
/// first.  Degree 5 over `|z| ≤ ln2/2N`; the truncation past `z⁵` is below `2⁻⁷⁷`
/// and, scaled by `z² ≲ 2⁻¹⁷`, sits far under the fast path's `2⁻⁶⁸` budget.
const EXP_TAIL_COEFFS: [f64; 6] = [
    0.5,
    0.16666666666666666,
    0.041666666666666664,
    0.008333333333333333,
    0.001388888888888889,
    0.0001984126984126984,
];

/// Ziv gate for the exponential family's fast path.
///
/// The fast double-double mantissa ([`exp_mantissa_fast`]) is good to ≈2⁻⁶⁸
/// relative (measured max ≈2⁻⁶⁸·³ over 200M random arguments across the finite
/// `exp` range); `2⁻⁶³` keeps a ~40× safety margin while still gating in the fast
/// result for all but a ~2⁻¹⁰ fraction of inputs near a rounding boundary.
const EXP_ZIV_EPS: f64 = 1.0842021724855044e-19; // 2^-63

// --- two-level table constants (generated by tools/gen_exp_f64.py, N = 4096) ---
// `eˣ = 2^q · 2^(j/4096) · exp(dx)`, with the table value
// `2^(j/4096) = EXP2_T0[j>>6] · EXP2_T1[j&63]` and `|dx| ≤ ln2/8192 ≈ 2⁻¹³·⁵`.

/// `4096 / ln(2)`, the scale that maps `x` to the two-level reduction index.
const N_OVER_LN2_4096: f64 = 5909.278887481194;

/// `ln(2) / 4096` split so that `HI` has 24 trailing zero significand bits: for
/// `|t| < 2²⁴` the product `t · HI` is exact, hence `x − t·HI` is exact (Sterbenz).
const LN2_OVER_4096_HI: f64 = 0.0001692253854344017;
const LN2_OVER_4096_LO: f64 = 4.444912105723013e-13;
// rel err of (HI + LO) vs ln2/4096: 2^-83.8

/// Degree-3 plain-`f64` coefficients of `(exp(z) − 1)/z = ∑ zᵏ/(k+1)!`, low-degree
/// first.  Over `|z| ≤ ln2/8192` the truncation past `z³` (next term `z⁴/120 ≈
/// 2⁻⁶¹`) is scaled by `tx = th·z ≈ 2⁻¹³·⁵`, landing near `2⁻⁷⁴` — far under the
/// leg's `2⁻⁶⁴` budget.
const EXP_FAST3_COEFFS: [f64; 4] = [1.0, 0.5, 0.16666666666666666, 0.041666666666666664];

/// Ziv gate for [`exp`]'s two-level fast leg.
///
/// [`exp_two_level_fast`] is ≈2⁻⁶⁴ relative (theoretical worst ≈2⁻⁶⁴·⁷, measured
/// ≈2⁻⁶⁴·³ over 1M random arguments) — leaner than [`exp_mantissa_fast`] because
/// the finer table lets the `tl·(exp(dx)−1)` cross term drop and the tail fall to
/// degree 3.  `2⁻⁶²` keeps a ~5× margin (CORE-MATH's budget for this kernel)
/// while still gating in the fast result for all but a ~2⁻⁹ fraction of inputs.
const EXP_TWO_LEVEL_ZIV_EPS: f64 = 2.168_404_344_971_009e-19; // 2^-62

const EXP2_T0: [(f64, f64); 64] = [
    (1.0, 0.0),
    (1.0108892860517005, -1.5234778603368577e-17),
    (1.0218971486541166, 5.109225028973444e-17),
    (1.0330248790212284, 7.600838874027088e-18),
    (1.0442737824274138, 8.551889705537965e-17),
    (1.0556451783605572, 1.759325738772092e-18),
    (1.0671404006768237, -7.899853966841582e-17),
    (1.0787607977571199, -6.656660436056593e-17),
    (1.0905077326652577, -3.046782079812471e-17),
    (1.102382583307841, 5.2660368715706944e-17),
    (1.1143867425958924, 1.0410278456845571e-16),
    (1.1265216186082418, 5.165856758795457e-17),
    (1.1387886347566916, 8.912812676025408e-17),
    (1.1511892299529827, 3.250710218863827e-17),
    (1.1637248587775775, 3.8292048369240935e-17),
    (1.1763969916502812, 5.554203254218079e-17),
    (1.189207115002721, 3.982015231465646e-17),
    (1.202156731452703, 6.644981499252301e-17),
    (1.215247359980469, -7.712630692681488e-17),
    (1.22848053610687, -1.89878163130253e-17),
    (1.241857812073484, 4.658027591836937e-17),
    (1.255380757024691, -6.7113898212968784e-18),
    (1.2690509571917332, 2.667932131342186e-18),
    (1.2828700160787783, 1.713594918243561e-17),
    (1.2968395546510096, 2.5382502794888315e-17),
    (1.3109612115247644, -7.181536135519454e-17),
    (1.3252366431597413, -2.8587312100388614e-17),
    (1.339667524053303, 8.927282594831732e-17),
    (1.3542555469368927, 7.70094837980299e-17),
    (1.3690024229745905, 9.593797919118849e-17),
    (1.383909881963832, -6.770511658794786e-17),
    (1.3989796725383112, -9.614213209051323e-17),
    (1.4142135623730951, -9.667293313452913e-17),
    (1.42961333839197, -1.2031642489053655e-17),
    (1.4451808069770467, -3.0237581349939873e-17),
    (1.460917794180647, -5.600377186075216e-17),
    (1.4768261459394993, -3.483994556892796e-17),
    (1.4929077282912648, 1.4192920154284036e-17),
    (1.5091644275934228, -1.016455327754295e-16),
    (1.5255981507445384, -1.1024941712342561e-16),
    (1.5422108254079407, 7.949834809697621e-17),
    (1.559004400237837, 3.7812070533575275e-17),
    (1.5759808451078865, -1.0136916471278304e-17),
    (1.593142151342267, -1.0094406542311964e-16),
    (1.6104903319492543, 2.4707192569797888e-17),
    (1.6280274218573478, -6.712955084707084e-17),
    (1.645755478153965, -1.0125679913674773e-16),
    (1.6636765803267364, 5.8909926967131e-17),
    (1.681792830507429, 8.199010020581497e-17),
    (1.7001063537185235, -8.0237193703977e-18),
    (1.718619298122478, -1.851380418263111e-17),
    (1.7373338352737062, 3.164389299292957e-17),
    (1.7562521603732995, 2.960140695448873e-17),
    (1.7753764925265212, 6.429731796556572e-17),
    (1.7947090750031072, 1.8227458427912087e-17),
    (1.8142521755003989, -9.969531538920349e-17),
    (1.8340080864093424, 3.283107224245627e-17),
    (1.8539791250833855, 9.761887490727594e-17),
    (1.8741676341103, -6.122763413004143e-17),
    (1.8945759815869656, 3.4034035352165297e-17),
    (1.9152065613971474, -1.0619946056195963e-16),
    (1.9360617934922943, 1.0332385960676326e-16),
    (1.9571441241754002, 8.960767791036668e-17),
    (1.978456026387951, 4.0388753109278167e-17),
];

const EXP2_T1: [(f64, f64); 64] = [
    (1.0, 0.0),
    (1.0001692397053021, 9.336185335478462e-17),
    (1.0003385080526823, -5.141333931318957e-18),
    (1.0005078050469876, 6.962424022020573e-17),
    (1.0006771306930664, -5.1151232976856676e-17),
    (1.0008464849957674, 8.422990024586487e-17),
    (1.001015867959941, -2.824522074776168e-17),
    (1.0011852795904375, -7.180424565592132e-17),
    (1.0013547198921082, -1.8973728416792993e-17),
    (1.0015241888698057, 9.060441067269122e-17),
    (1.0016936865283832, -7.17327634990032e-17),
    (1.0018632128726943, -1.330719624672266e-17),
    (1.002032767907594, 2.5726925943221118e-17),
    (1.002202351637938, -3.929937785484517e-17),
    (1.0023719640685822, 8.461377247994717e-17),
    (1.0025416052043845, -4.19488324163994e-17),
    (1.0027112750502025, -3.636615928692264e-17),
    (1.0028809736108952, -2.6109440632439383e-17),
    (1.0030507008913223, 1.753078477982332e-17),
    (1.0032204568963443, 5.753923525628267e-17),
    (1.0033902416308227, -8.684922005117956e-18),
    (1.0035600550996193, 9.490035430981778e-17),
    (1.0037298973075977, -8.710380605818422e-17),
    (1.003899768259621, 3.4958916958571545e-17),
    (1.004069667960554, 9.753787549840241e-17),
    (1.0042395964152628, -1.0576221196292857e-16),
    (1.0044095536286128, 4.209188738127126e-17),
    (1.0045795396054717, -1.6700166857554788e-17),
    (1.0047495543507072, -1.6231463554124514e-17),
    (1.004919597869188, 2.3028539278028117e-17),
    (1.0050896701657839, 1.6418046976773032e-17),
    (1.005259771245365, 3.7266984318284137e-17),
    (1.0054299011128027, 9.499186535455032e-17),
    (1.0056000597729693, -8.680931314444582e-17),
    (1.005770247230737, 4.000547491030117e-17),
    (1.00594046349098, 7.190499111509974e-17),
    (1.006110708558573, -1.3908068671065783e-17),
    (1.006280982438391, -8.14020864257305e-17),
    (1.00645128513531, -5.762151043749534e-17),
    (1.0066216166542072, 6.745278477310457e-17),
    (1.0067919769999607, 1.8998557240346296e-17),
    (1.006962366177449, -9.637430032316407e-17),
    (1.0071327841915512, -1.2528654462453979e-17),
    (1.007303231047148, 3.020578887843694e-17),
    (1.0074737067491204, -4.869394258608565e-17),
    (1.0076442113023503, 5.224029937687453e-17),
    (1.0078147447117207, -9.361543551478456e-17),
    (1.007985306982115, -8.65251323306195e-17),
    (1.0081558981184175, -3.252058756084308e-17),
    (1.0083265181255139, -9.917232268060914e-17),
    (1.0084971670082898, -7.136047404162523e-17),
    (1.0086678447716324, -1.726868371224322e-17),
    (1.0088385514204294, -6.61995469367394e-17),
    (1.0090092869595693, 3.5654569015130204e-17),
    (1.0091800513939415, 3.717310013708818e-17),
    (1.0093508447284363, 7.062572406825528e-17),
    (1.0095216669679448, -1.432141230342882e-17),
    (1.0096925181173586, 1.566818801313411e-17),
    (1.0098633981815708, -1.1043695780393688e-16),
    (1.0100343071654745, -5.767317427160398e-17),
    (1.0102052450739643, 4.835484978440383e-18),
    (1.0103762119119353, 7.015121289715442e-17),
    (1.0105472076842836, 7.161802873619574e-17),
    (1.010718232395906, 1.050465913408405e-16),
];

/// Table size for the exponential family: `2`<sup>`q`</sup>` · 2`<sup>`j/N`</sup>` · exp(r)`
const EXP_N: i64 = 128;

/// The mantissa `2`<sup>`j/N`</sup>` · exp(r)` of the exponential family, as a
/// double-double normalized into [1, 2), with `q` adjusted for that normalization.
///
/// `r` is the reduced argument, `|r| ≤ ln2/2N`.  The full value is `2`<sup>`q`</sup>
/// times the returned mantissa.
#[inline]
pub(super) fn exp_mantissa(j: usize, q: i64, r: DoubleDouble) -> (DoubleDouble, i64) {
    // exp(r) by double-double Horner over the degree-8 minimax polynomial.
    let (high, low) = EXP_R_COEFFS[EXP_R_COEFFS.len() - 1];
    let mut acc = DoubleDouble { high, low };

    for &(high, low) in EXP_R_COEFFS[..EXP_R_COEFFS.len() - 1].iter().rev() {
        acc = acc * r + DoubleDouble { high, low };
    }

    // Fold the table entry in and normalize the mantissa.
    let (high, low) = EXP2_TABLE[j];
    let scaled = DoubleDouble { high, low } * acc;
    let product = fast_sum(scaled.high, scaled.low);

    // `2^(j/N) · exp(r)` lies in [0.997, 2.005); fold its exponent into `q` so the
    // mantissa is in [1, 2).
    if product.high < 1.0 {
        (product * 2.0, q - 1)
    } else if product.high >= 2.0 {
        (product * 0.5, q + 1)
    } else {
        (product, q)
    }
}

/// Fast double-double mantissa for the exponential family.
///
/// Same contract as [`exp_mantissa`] — returns `2`<sup>`j/N`</sup>` · exp(r)`
/// normalized into [1, 2) with `q` adjusted — but evaluates `exp(r)` with a
/// plain-`f64` tail polynomial instead of a double-double Horner.  This trades
/// the accurate path's ≈2⁻¹⁰⁰ for ≈2⁻⁶⁸ relative error at a fraction of the cost;
/// [`exp_reconstruct`] resolves the rare hard-to-round cases with a Ziv test.
#[inline]
pub(super) fn exp_mantissa_fast(j: usize, q: i64, r: DoubleDouble) -> (DoubleDouble, i64) {
    // The full reduced argument as one `f64`, for the small tail term.  `exp2`
    // and `exp10` hand in an *un-normalized* `r` (the `ln2/N` low word lands in
    // `r.low ≈ 2⁻⁴⁷`), so dropping `r.low` here would lose the `2·r.high·r.low`
    // part of `r²` — a ≈2⁻⁵⁵ slip the Ziv gate could not catch.
    let z = r.high + r.low;

    // exp(r) − 1 − r ≈ z²·P(z), with P evaluated in plain f64: it only forms a
    // term ≲2⁻¹⁷ of exp(r), so its `f64` rounding lands near 2⁻⁶⁸ relative.
    let tail = (z * z) * crate::poly(z, &EXP_TAIL_COEFFS);

    // exp(r) = (1 + r.high) + (r.low + tail) as a double-double.  `1 + r.high` is
    // exact (Fast2Sum, `|r.high| ≤ ln2/2N`); the low word then gathers the
    // reduction tail `r.low` in full and the polynomial tail.
    let head = fast_sum(1.0, r.high);
    let er = DoubleDouble {
        high: head.high,
        low: head.low + (r.low + tail),
    };

    // Fold in the table entry and normalize the mantissa into [1, 2), exactly as
    // the accurate path does.
    let (high, low) = EXP2_TABLE[j];
    let scaled = DoubleDouble { high, low } * er;
    let product = fast_sum(scaled.high, scaled.low);

    if product.high < 1.0 {
        (product * 2.0, q - 1)
    } else if product.high >= 2.0 {
        (product * 0.5, q + 1)
    } else {
        (product, q)
    }
}

/// Two-level fast leg for `eˣ`: `2`<sup>`q`</sup>` · 2`<sup>`j/4096`</sup>` · exp(dx)`.
///
/// Returns the mantissa as a double-double normalized into [1, 2) and the
/// adjusted `q`, like [`exp_mantissa_fast`], but reduces against a 4096-entry
/// (two 64-entry tables) grid so `|dx| ≤ ln2/8192` and a degree-3 plain-`f64`
/// tail suffices.  The table value `2`<sup>`j/4096`</sup>` = EXP2_T0[j>>6] ·
/// EXP2_T1[j&63]` (one `dd × dd`), folded in with CORE-MATH's lean
/// `fl = tl + (th·dx)·p` — no double-double `exp(r)` and no `dd × dd` poly
/// multiply.  `x` must be finite and within the non-overflow range.
#[inline]
fn exp_two_level_fast(x: f64) -> (DoubleDouble, i64) {
    let scaled = (x * N_OVER_LN2_4096).round_ties_even();

    // SAFETY: `|x| < 746`, so `|scaled| < 2^23`.
    let t = unsafe { scaled.to_int_unchecked::<i64>() };
    let i0 = ((t >> 6) & 63) as usize;
    let i1 = (t & 63) as usize;
    let q = t >> 12;

    // `2^(j/4096)` as a double-double, `j = t mod 4096 = 64·i0 + i1`.
    let (t0h, t0l) = EXP2_T0[i0];
    let (t1h, t1l) = EXP2_T1[i1];
    let table = DoubleDouble {
        high: t0h,
        low: t0l,
    } * DoubleDouble {
        high: t1h,
        low: t1l,
    };

    // Cody–Waite reduced argument `dx = x − t·ln2/4096`, `|dx| ≤ ln2/8192`.
    // `scaled · LN2_OVER_4096_HI` is exact (HI has 24 trailing zero bits,
    // `|scaled| < 2²⁴`), so the FMA `x − scaled·HI` is exact; subtracting
    // `scaled · LO` finishes the residual.
    let a = crate::correct_mul_add(scaled, -LN2_OVER_4096_HI, x);
    let dx = crate::correct_mul_add(scaled, -LN2_OVER_4096_LO, a);

    // `exp(dx) − 1 = dx · p(dx)`; fold `th·(exp(dx) − 1)` into the table low word.
    // Dropping the `tl·(exp(dx) − 1) ≈ 2⁻⁶⁶` cross term keeps the leg under its
    // Ziv budget thanks to the finer table.
    let p = crate::poly(dx, &EXP_FAST3_COEFFS);
    let lo = crate::correct_mul_add(table.high * dx, p, table.low);
    let product = fast_sum(table.high, lo);

    // `2^(j/4096) · exp(dx)` lies in (0.9999, 2.0001); fold its exponent into `q`.
    if product.high < 1.0 {
        (product * 2.0, q - 1)
    } else if product.high >= 2.0 {
        (product * 0.5, q + 1)
    } else {
        (product, q)
    }
}

/// Argument reduction for `2`<sup>`e`</sup> with a *double-double* exponent `e`.
///
/// Returns `(j, q, r)` with `2`<sup>`e`</sup>` = 2`<sup>`q`</sup>` · 2`<sup>`j/N`</sup>` · exp(r)`
/// and `|r| ≤ ln2/2N` — the base-2 counterpart of [`exp2`]'s reduction, lifted to a
/// double-double argument for [`powf`](super::powf), where `e = y·log₂x`.  The
/// caller must keep `|e.high|` inside the finite `2`<sup>`e`</sup> range
/// (`< ~1075`) so `round(N·e)` fits an `i64`.
#[inline]
pub(super) fn exp2_reduce_dd(e: DoubleDouble) -> (usize, i64, DoubleDouble) {
    let scaled = (e.high * EXP_N as f64).round_ties_even();

    // SAFETY: the caller keeps `e.high` within the finite 2^e range, so
    // `|scaled| < 2^18`.
    let m = unsafe { scaled.to_int_unchecked::<i64>() };
    let j = (m & (EXP_N - 1)) as usize;
    let q = m >> 7;

    // sigma = N·e − m.  `e.high·N` is exact (N is a power of two) and within ½ of
    // the integer `scaled`, so the high word is exact (Sterbenz); `e.low·N` is also
    // exact, and 2Sum normalizes the pair regardless of their relative size.
    let sigma = DoubleDouble::from_sum(
        crate::correct_mul_add(e.high, EXP_N as f64, -scaled),
        e.low * EXP_N as f64,
    );

    // r = sigma · ln2/N as a double-double, `|r| ≤ ln2/2N`.
    let r = sigma
        * DoubleDouble {
            high: LN2_OVER_N_HI,
            low: LN2_OVER_N_LO,
        };
    (j, q, r)
}

/// Reconstruct `2`<sup>`q`</sup>` · 2`<sup>`j/N`</sup>` · exp(r)` for the exponential family.
///
/// `r` is the reduced argument as a double-double, `|r| ≤ ln2/2N`.  The result is
/// correctly rounded, including gradual underflow into the subnormal range.
#[inline]
fn exp_reconstruct(j: usize, q: i64, r: DoubleDouble) -> f64 {
    // Fast path: a lean mantissa good to ≈2⁻⁶⁸ relative, accepted when both ends
    // of its `±EXP_ZIV_EPS` error interval round to the same `f64`.  Restricting
    // it to comfortably-normal results (`qf ≥ −1021`) keeps the normal/subnormal
    // transition — where the mantissa's normalization can shift `q` — entirely on
    // the accurate path below.
    let (product, qf) = exp_mantissa_fast(j, q, r);
    if qf >= -1021 {
        let lo = product.high + (product.low - EXP_ZIV_EPS);
        let hi = product.high + (product.low + EXP_ZIV_EPS);
        if lo == hi {
            return fast_ldexp(lo, qf);
        }
    }

    // Accurate path.  The mantissa is in [1, 2), so `round_general64` resolves
    // the result correctly across the normal/subnormal boundary.
    let (product, q) = exp_mantissa(j, q, r);
    super::double::round_general64(product, q)
}

/// Argument reduction for the exponential family.
///
/// Returns `(j, q, r)` with `x = (q·N + j)·ln2/N + r` and `|r| ≤ ln2/2N`.  The
/// caller must keep `|x|` small enough that `round(N·x/ln2)` fits an `i64`
/// (`|x| < ~746`, the finite exp range).
#[inline]
fn exp_reduce(x: f64) -> (usize, i64, DoubleDouble) {
    /// `N / ln(2)`, the scale that maps `x` to the reduction index
    const N_OVER_LN2: f64 = 184.664_965_233_787_3;

    let scaled = (x * N_OVER_LN2).round_ties_even();

    // SAFETY: `|x| < 746`, so `|scaled| < 2^18`.
    let n = unsafe { scaled.to_int_unchecked::<i64>() };
    let j = (n & (EXP_N - 1)) as usize;
    let q = n >> 7;

    // r as a double-double.  `scaled · LN2_OVER_N_HI` is exact because the high
    // word has 17 trailing zero bits, and the low word recovers the tail.
    let a = crate::correct_mul_add(scaled, -LN2_OVER_N_HI, x);
    (j, q, DoubleDouble::from_sum(a, scaled * -LN2_OVER_N_LO))
}

/// Argument reduction for `eᵂ` with a *double-double* exponent `W`.
///
/// Returns `(j, q, r)` with `eᵂ = 2`<sup>`q`</sup>` · 2`<sup>`j/N`</sup>` · exp(r)`
/// and `|r| ≤ ln2/2N` — the base-`e` counterpart of [`exp_reduce`], lifted to a
/// double-double argument for `erfc`, where `W = Q(t) − x²`.  The caller must keep
/// `|W.high|` within the finite `eᵂ` range (`< ~746`) so `round(N·W/ln2)` fits an
/// `i64`.
#[inline]
pub(super) fn exp_reduce_dd(w: DoubleDouble) -> (usize, i64, DoubleDouble) {
    /// `N / ln(2)`, the scale that maps `W` to the reduction index
    const N_OVER_LN2: f64 = 184.664_965_233_787_3;

    let scaled = (w.high * N_OVER_LN2).round_ties_even();

    // SAFETY: the caller keeps `|W.high| < 746`, so `|scaled| < 2^18`.
    let n = unsafe { scaled.to_int_unchecked::<i64>() };
    let j = (n & (EXP_N - 1)) as usize;
    let q = n >> 7;

    // r = W − scaled·ln2/N as a double-double.  `scaled · LN2_OVER_N_HI` is exact
    // (the high word has 17 trailing zero bits), giving the high residual; the low
    // residual gathers `W.low` and the `LN2_OVER_N_LO` correction.
    let a = crate::correct_mul_add(scaled, -LN2_OVER_N_HI, w.high);
    let b = crate::correct_mul_add(scaled, -LN2_OVER_N_LO, w.low);
    (j, q, DoubleDouble::from_sum(a, b))
}

/// `eᵂ` as `2`<sup>`q`</sup>` · mantissa` (mantissa a double-double in [1, 2)) for
/// a double-double exponent `W`, the accurate counterpart of [`exp_dd_of_dd_fast`].
#[inline]
pub(super) fn exp_dd_of_dd(w: DoubleDouble) -> (DoubleDouble, i64) {
    let (j, q, r) = exp_reduce_dd(w);
    exp_mantissa(j, q, r)
}

/// Lean `eᵂ` for a double-double exponent `W` (≈2⁻⁶⁸ relative), the fast leg
/// `erfc` Ziv-gates against [`exp_dd_of_dd`].
#[inline]
pub(super) fn exp_dd_of_dd_fast(w: DoubleDouble) -> (DoubleDouble, i64) {
    let (j, q, r) = exp_reduce_dd(w);
    exp_mantissa_fast(j, q, r)
}

/// `eˣ` as `2`<sup>`q`</sup>` · mantissa` with the mantissa a double-double in [1, 2).
///
/// The caller must ensure `x` is finite and within the non-overflow range
/// (`|x| < ~710`); used by the hyperbolic functions, which need the extra words.
#[inline]
pub(super) fn exp_dd(x: f64) -> (DoubleDouble, i64) {
    let (j, q, r) = exp_reduce(x);
    exp_mantissa(j, q, r)
}

/// Lean counterpart of [`exp_dd`], using [`exp_mantissa_fast`] (≈2⁻⁶⁸ relative).
///
/// The hyperbolic functions take this as their fast path and Ziv-gate the result
/// against [`exp_dd`].
#[inline]
pub(super) fn exp_dd_fast(x: f64) -> (DoubleDouble, i64) {
    let (j, q, r) = exp_reduce(x);
    exp_mantissa_fast(j, q, r)
}

/// The exponential function
#[must_use]
#[inline]
pub fn exp(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    // `ln(f64::MAX)` and the threshold below which `exp` rounds to zero
    if x >= 709.782_712_893_384 {
        return f64::INFINITY;
    }
    if x <= -745.133_219_101_941 {
        return 0.0;
    }

    // Fast path: the two-level lean mantissa, accepted when both ends of its
    // `±EXP_TWO_LEVEL_ZIV_EPS` interval round to the same `f64`.  Restricting it to
    // comfortably-normal results (`qf ≥ −1021`) keeps the normal/subnormal
    // transition entirely on the accurate path below.
    let (product, qf) = exp_two_level_fast(x);
    if qf >= -1021 {
        let lo = product.high + (product.low - EXP_TWO_LEVEL_ZIV_EPS);
        let hi = product.high + (product.low + EXP_TWO_LEVEL_ZIV_EPS);
        if lo == hi {
            return fast_ldexp(lo, qf);
        }
    }

    // Accurate path: the existing N=128 reduction and double-double mantissa,
    // correctly rounded across the normal/subnormal boundary.
    let (j, q, r) = exp_reduce(x);
    let (product, q) = exp_mantissa(j, q, r);
    super::double::round_general64(product, q)
}

/// 2 raised to the power `x`
#[must_use]
#[inline]
pub fn exp2(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    // `f64::MAX_EXP` and the threshold below which `exp2` rounds to zero
    if x >= 1024.0 {
        return f64::INFINITY;
    }
    if x <= -1075.0 {
        return 0.0;
    }

    // Argument reduction: m = round(N·x), so 2^x = 2^(m/N) · 2^s with
    // s = x − m/N ∈ [−1/2N, 1/2N].  `sigma = N·x − m` is exact (N is a power of
    // two), and r = s·ln2 = sigma·(ln2/N) is carried as a double-double.
    let scaled = (x * EXP_N as f64).round_ties_even();

    // SAFETY: `|x| < 1075`, so `|scaled| < 2^18`.
    let m = unsafe { scaled.to_int_unchecked::<i64>() };
    let j = (m & (EXP_N - 1)) as usize;
    let q = m >> 7;

    let sigma = crate::correct_mul_add(x, EXP_N as f64, -scaled);
    let product = DoubleDouble::from_product(sigma, LN2_OVER_N_HI);
    let r = DoubleDouble {
        high: product.high,
        low: crate::correct_mul_add(sigma, LN2_OVER_N_LO, product.low),
    };

    exp_reconstruct(j, q, r)
}

/// 10 raised to the power `x`
#[must_use]
#[inline]
pub fn exp10(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    // `log10(f64::MAX)` and the threshold below which `exp10` rounds to zero
    if x >= 308.254_715_559_916_7 {
        return f64::INFINITY;
    }
    if x <= -323.607_245_338_779_8 {
        return 0.0;
    }

    // 10^x = exp(x·ln10) = 2^q · 2^(j/N) · exp(r), with the reduction index
    // n = round(N·x·log2(10)) and r = x·ln10 − n·ln2/N carried as a double-double.
    let scaled = (x * N_LOG2_10).round_ties_even();

    // SAFETY: `|x| < 324`, so `|scaled| < 2^18`.
    let m = unsafe { scaled.to_int_unchecked::<i64>() };
    let j = (m & (EXP_N - 1)) as usize;
    let q = m >> 7;

    let x_ln10 = DoubleDouble::from_product(x, LN10_HI);
    let x_ln10 = DoubleDouble {
        high: x_ln10.high,
        low: crate::correct_mul_add(x, LN10_LO, x_ln10.low),
    };
    let n_ln2 = DoubleDouble::from_product(scaled, LN2_OVER_N_HI);
    let n_ln2 = DoubleDouble {
        high: -n_ln2.high,
        low: crate::correct_mul_add(scaled, -LN2_OVER_N_LO, -n_ln2.low),
    };

    exp_reconstruct(j, q, x_ln10 + n_ln2)
}

/// Compute `exp(x) − 1` accurately, especially for small `x`
#[must_use]
#[inline]
pub fn exp_m1(x: f64) -> f64 {
    /// `N / ln(2)`, the scale that maps `x` to the reduction index
    const N_OVER_LN2: f64 = 184.664_965_233_787_3;

    if x.is_nan() || x == 0.0 {
        // Preserve the sign of zero: exp_m1(±0) = ±0.
        return x;
    }

    if x >= 709.782_712_893_384 {
        return f64::INFINITY;
    }

    // Below this `exp(x) < 2^-54`, so `exp(x) − 1` rounds to exactly −1.  This also
    // keeps the reconstruction below in the normal range (`q ≥ −1022`).
    if x <= -708.0 {
        return -1.0;
    }

    // Same reduction as `exp`: n = round(N·x / ln2), r = x − n·ln2/N.
    let scaled = (x * N_OVER_LN2).round_ties_even();

    // SAFETY: `|x| < 710`, so `|scaled| < 2^18`.
    let n = unsafe { scaled.to_int_unchecked::<i64>() };

    if n == 0 {
        // |x| < ln2/2N ≈ 0.0027.  Computing exp(x) − 1 here would lose the small
        // result in the double-double's floor relative to 1, so evaluate
        // expm1(x) = x · S(x) with S(x) = (exp(x) − 1)/x = ∑ xᵏ/(k+1)!.  S is built
        // by double-double Horner so the result keeps full *relative* accuracy.
        let (high, low) = EXPM1_S_COEFFS[EXPM1_S_COEFFS.len() - 1];
        let mut s = DoubleDouble { high, low };

        for &(high, low) in EXPM1_S_COEFFS[..EXPM1_S_COEFFS.len() - 1].iter().rev() {
            s = s * x + DoubleDouble { high, low };
        }

        let result = s * x;
        return result.high + result.low;
    }

    let j = (n & (EXP_N - 1)) as usize;
    let q0 = n >> 7;

    let a = crate::correct_mul_add(scaled, -LN2_OVER_N_HI, x);
    let r = DoubleDouble::from_sum(a, scaled * -LN2_OVER_N_LO);

    // exp(x) = 2^q · mantissa; form `2^q · mantissa − 1` as a double-double.  The
    // scaling stays normal (`q ∈ [−1022, 1023]`), and the double-double subtraction
    // absorbs the cancellation that plain `exp(x) − 1` would suffer near zero.
    //
    // Fast path: the lean mantissa, accepted by a Ziv test.  Its absolute error is
    // bounded by `EXP_ZIV_EPS` (on the [1, 2) mantissa), so on the result it is
    // bounded by `2^q · EXP_ZIV_EPS`.
    let neg_one = DoubleDouble {
        high: -1.0,
        low: 0.0,
    };
    let (mantissa, q) = exp_mantissa_fast(j, q0, r);
    let result = mantissa * crate::exp2i(q) + neg_one;
    let eps = crate::exp2i(q) * EXP_ZIV_EPS;
    let lo = result.high + (result.low - eps);
    let hi = result.high + (result.low + eps);
    if lo == hi {
        return lo;
    }

    let (mantissa, q) = exp_mantissa(j, q0, r);
    let result = mantissa * crate::exp2i(q) + neg_one;
    result.high + result.low
}
