//! Trigonometric functions: `sin`, `cos`, `sin_cos`, `tan`.
//!
//! Constants below were generated by `tools/gen_trig_f64.py`.
//! Do not edit by hand; re-run the generator instead.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::double::{fast_sum, Sum};
use super::pow::poly_dd;

/// `sin(r)/r` as a double-double in `u = r²`, low-degree first (max error ≈2⁻¹²⁷).
const SIN_KERNEL: [Sum; 13] = [
    Sum {
        high: 1.0,
        low: -5.0987018554029683e-39,
    },
    Sum {
        high: -0.16666666666666666,
        low: -9.25185853854297e-18,
    },
    Sum {
        high: 0.008333333333333333,
        low: 1.156482317317869e-19,
    },
    Sum {
        high: -0.0001984126984126984,
        low: -1.7209558292516092e-22,
    },
    Sum {
        high: 2.7557319223985893e-06,
        low: -1.858393275722529e-22,
    },
    Sum {
        high: -2.505210838544172e-08,
        low: 1.4488159186621237e-24,
    },
    Sum {
        high: 1.6059043836821613e-10,
        low: 1.2572222845296136e-26,
    },
    Sum {
        high: -7.647163731819815e-13,
        low: -4.606435501111483e-29,
    },
    Sum {
        high: 2.81145725434532e-15,
        low: 5.160177200634138e-32,
    },
    Sum {
        high: -8.220635246177278e-18,
        low: -5.582599714358412e-34,
    },
    Sum {
        high: 1.95729403918814e-20,
        low: 1.4084261345322546e-36,
    },
    Sum {
        high: -3.868105107347916e-23,
        low: 2.2080719840678897e-39,
    },
    Sum {
        high: 6.41022925531651e-26,
        low: 2.880120311859419e-42,
    },
];

/// `cos(r)` as a double-double in `u = r²`, low-degree first (max error ≈2⁻¹²²).
const COS_KERNEL: [Sum; 13] = [
    Sum {
        high: 1.0,
        low: -1.3761459043912074e-37,
    },
    Sum {
        high: -0.5,
        low: 7.540540356661797e-35,
    },
    Sum {
        high: 0.041666666666666664,
        low: 2.312964634635736e-18,
    },
    Sum {
        high: -0.001388888888888889,
        low: 5.300543954397993e-20,
    },
    Sum {
        high: 2.48015873015873e-05,
        low: 2.1511943343054862e-23,
    },
    Sum {
        high: -2.755731922398589e-07,
        low: -2.376766475147913e-23,
    },
    Sum {
        high: 2.08767569878681e-09,
        low: -1.2108731843273183e-25,
    },
    Sum {
        high: -1.1470745597729723e-11,
        low: -1.5011050364192592e-28,
    },
    Sum {
        high: 4.779477332386843e-14,
        low: -3.9852328581359e-31,
    },
    Sum {
        high: -1.561920696737958e-16,
        low: 7.95243117129581e-33,
    },
    Sum {
        high: 4.110317442059798e-19,
        low: 1.3835401064045195e-35,
    },
    Sum {
        high: -8.89661576927929e-22,
        low: 1.9801804476213101e-38,
    },
    Sum {
        high: 1.6018249140912734e-24,
        low: -7.728223090239399e-41,
    },
];

/// 2/π as f64, for the medium-range quotient `round(x·2/π)`.
const FRAC_2_PI_F64: f64 = 0.6366197723675814;

/// π/2 in three words; each of `PIO2_1`, `PIO2_2` has its low 21 mantissa bits
/// clear, so `q·PIO2_k` is exact for `|q| < 2²¹` (the medium range `|x| < 2²⁰`).
const PIO2_1: f64 = 1.5707963267341256;
const PIO2_2: f64 = 6.077100506303966e-11;
const PIO2_3: f64 = 2.0222662487959506e-21;

/// π/2 as a double-double, for the Payne–Hanek reconstruction.
const PIO2: Sum = Sum {
    high: 1.5707963267948966,
    low: 6.123233995736766e-17,
};

/// Fractional bits of 2/π, most-significant 64-bit group first (`FRAC_2_PI[0]`
/// holds bits 1..64).  Used by [`payne_hanek`] for `|x| ≥ 2²⁰`.
const FRAC_2_PI: [u64; 24] = [
    0xA2F9836E4E441529,
    0xFC2757D1F534DDC0,
    0xDB6295993C439041,
    0xFE5163ABDEBBC561,
    0xB7246E3A424DD2E0,
    0x06492EEA09D1921C,
    0xFE1DEB1CB129A73E,
    0xE88235F52EBB4484,
    0xE99C7026B45F7E41,
    0x3991D639835339F4,
    0x9C845F8BBDF9283B,
    0x1FF897FFDE05980F,
    0xEF2F118B5A0A6D1F,
    0x6D367ECF27CB09B7,
    0x4F463F669E5FEA2D,
    0x7527BAC7EBE5F17B,
    0x3D0739F78A5292EA,
    0x6BFB5FB11F8D5D08,
    0x56033046FC7B6BAB,
    0xF0CFBC209AF4361D,
    0xA9E391615EE61B08,
    0x6599855F14A06840,
    0x8DFFD8804D732731,
    0x06061556CA73A8C9,
];

/// Negate a double-double.
#[inline]
fn neg(v: Sum) -> Sum {
    Sum {
        high: -v.high,
        low: -v.low,
    }
}

/// Payne–Hanek argument reduction for `|x| ≥ 2²⁰`.
///
/// Returns `(q, r)` with `q` the quadrant (low bits of `round(x·2/π)`) and `r ∈
/// [-π/4, π/4]` a double-double.  Multiplies the 53-bit significand by a 256-bit
/// window of 2/π selected by the exponent, reads off the integer part (for `q`)
/// and a 128-bit signed fraction, and scales the fraction by π/2.
#[inline]
fn payne_hanek(x: f64) -> (i64, Sum) {
    let bits = x.to_bits();
    let e = ((bits >> super::EXP_SHIFT) & 0x7ff) as i64; // biased exponent
    let sig = u128::from((bits & 0x000F_FFFF_FFFF_FFFF) | 0x0010_0000_0000_0000);

    // x = sig · 2ᵐ with m = e − 1023 − 52.  The 2/π bit aligning to 2⁰ of x·2/π is
    // index k = m; pick the 256-bit window starting two bits above that.
    let m = e - 1075;
    let w0 = (((m - 2).max(0)) / 64) as usize;

    let word = |i: usize| u128::from(*FRAC_2_PI.get(w0 + i).unwrap_or(&0));
    let (wa, wb, wc, wd) = (word(0), word(1), word(2), word(3));

    // P = sig · (wa·2¹⁹² + wb·2¹²⁸ + wc·2⁶⁴ + wd), as five 64-bit limbs.
    let (pa, pb, pc, pd) = (sig * wa, sig * wb, sig * wc, sig * wd);
    const MASK: u128 = 0xFFFF_FFFF_FFFF_FFFF;
    let p0 = pd as u64;
    let c = (pd >> 64) + (pc & MASK);
    let p1 = c as u64;
    let c = (c >> 64) + (pc >> 64) + (pb & MASK);
    let p2 = c as u64;
    let c = (c >> 64) + (pb >> 64) + (pa & MASK);
    let p3 = c as u64;
    let p4 = ((c >> 64) + (pa >> 64)) as u64;
    let p = [p0, p1, p2, p3, p4];

    // Units bit of x·2/π is at P bit `b = 256 + 64·w0 − m`.
    let b = 256 + 64 * w0 as i64 - m;
    let bit_at = |start: i64| -> u64 {
        let w = (start / 64) as usize;
        let o = (start % 64) as u32;
        let lo = p.get(w).copied().unwrap_or(0);
        let hi = p.get(w + 1).copied().unwrap_or(0);
        if o == 0 {
            lo
        } else {
            (lo >> o) | (hi << (64 - o))
        }
    };

    // 192-bit window [b−128, b+63]: top 64 bits are the integer part (quadrant),
    // low 128 bits are the signed fraction of x·2/π.
    let frac = (u128::from(bit_at(b - 64)) << 64) | u128::from(bit_at(b - 128));
    let q = bit_at(b) as i64;
    let frac = frac as i128;

    // round-to-nearest: a negative signed fraction means the integer rounded up.
    let quadrant = q.wrapping_sub((frac >> 127) as i64);

    // r = (frac / 2¹²⁸) · π/2 ∈ [-π/4, π/4], as a double-double.
    let hi = frac as f64;
    let lo = (frac - hi as i128) as f64;
    let scale = crate::exp2i(-128);
    let r = Sum {
        high: hi * scale,
        low: lo * scale,
    } * PIO2;

    (quadrant, r)
}

/// Argument reduction: `x ≥ 0` finite → `(quadrant, r)` with `r ∈ [-π/4, π/4]`.
#[inline]
fn rem_pio2(x: f64) -> (i64, Sum) {
    // Medium range: Cody–Waite with the 3-word π/2 (q small enough that q·PIO2_1,
    // q·PIO2_2 are exact).  Handles `q = 0` (no reduction) too.
    if x < 1_048_576.0 {
        let q = (x * FRAC_2_PI_F64).round_ties_even();
        let p3 = q * PIO2_3;
        // ((x − q·PIO2_1) − q·PIO2_2) keeping residuals exactly (2Sum).
        let a = Sum::from_sum(x, q * -PIO2_1);
        let b = Sum::from_sum(a.high, q * -PIO2_2);
        let lo = (a.low + b.low) - p3;
        // SAFETY: |q| < 2²⁰.
        return (unsafe { q.to_int_unchecked() }, fast_sum(b.high, lo));
    }

    payne_hanek(x)
}

/// `(sin(r), cos(r))` for `r ∈ [-π/4, π/4]`, both as double-doubles.
#[inline]
fn sin_cos_kernel(r: Sum) -> (Sum, Sum) {
    let u = r * r;
    let s = r * poly_dd(u, &SIN_KERNEL);
    let c = poly_dd(u, &COS_KERNEL);
    (s, c)
}

/// Sine
#[must_use]
#[inline]
pub fn sin(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    let (q, r) = rem_pio2(x.abs());
    let (s, c) = sin_cos_kernel(r);

    // sin(|x|): quadrant picks sin(r)/cos(r) and its sign; sin is odd in x.
    let v = if q & 1 == 0 { s } else { c };
    let v = if q & 2 == 0 { v } else { neg(v) };
    let magnitude = v.high + v.low;

    if x.is_sign_negative() {
        -magnitude
    } else {
        magnitude
    }
}

/// Cosine
#[must_use]
#[inline]
pub fn cos(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    let (q, r) = rem_pio2(x.abs());
    let (s, c) = sin_cos_kernel(r);

    let v = if q & 1 == 0 { c } else { s };
    let v = if q.wrapping_add(1) & 2 == 0 {
        v
    } else {
        neg(v)
    };
    v.high + v.low
}

/// Simultaneous sine and cosine
#[must_use]
#[inline]
pub fn sin_cos(x: f64) -> (f64, f64) {
    if !x.is_finite() {
        return (f64::NAN, f64::NAN);
    }

    let (q, r) = rem_pio2(x.abs());
    let (s, c) = sin_cos_kernel(r);

    let (sin_v, cos_v) = if q & 1 == 0 { (s, c) } else { (c, s) };
    let sin_v = if q & 2 == 0 { sin_v } else { neg(sin_v) };
    let cos_v = if q.wrapping_add(1) & 2 == 0 {
        cos_v
    } else {
        neg(cos_v)
    };

    let sin = sin_v.high + sin_v.low;
    let sin = if x.is_sign_negative() { -sin } else { sin };
    (sin, cos_v.high + cos_v.low)
}

/// Tangent
#[must_use]
#[inline]
pub fn tan(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    let (q, r) = rem_pio2(x.abs());
    let (s, c) = sin_cos_kernel(r);

    // tan(|x|) = sin(|x|) / cos(|x|), each reconstructed from the quadrant.
    let sin_v = if q & 1 == 0 { s } else { c };
    let sin_v = if q & 2 == 0 { sin_v } else { neg(sin_v) };
    let cos_v = if q & 1 == 0 { c } else { s };
    let cos_v = if q.wrapping_add(1) & 2 == 0 {
        cos_v
    } else {
        neg(cos_v)
    };

    let t = sin_v * cos_v.recip();
    let magnitude = t.high + t.low;

    if x.is_sign_negative() {
        -magnitude
    } else {
        magnitude
    }
}
