use crate::f64_::double::{DoubleDouble, fast_sum, round};

/// Minimax coefficients of `P` in `asin(t) = t + t³·P(t²)` on `t² ∈ [0, ¼]`.
///
/// Shared by the `|x| < ½` branch of [`asin`] and by both branches of [`acos`].
/// For `|x| ≥ ½`, reflecting through `s = √((1−|x|)/2) ∈ [0, ½]` keeps the
/// kernel argument in `[0, ¼]`, so the same `P` serves the whole domain:
/// `asin(x) = π/2 − 2·asin(s)` and `acos(x) = 2·asin(s)` (or `π − 2·asin(s)`).
///
/// Relative error ≈ 2⁻⁴⁶, generated with
/// `ratapprox --function="(asin(sqrt(x))-sqrt(x))/(x*sqrt(x))"
///   --dom="[1e-30,0.25]" --num=[1,x,x^2,...,x^10] --den=[1]`.
const ASIN_NEAR_ZERO: [f64; 11] = [
    0.166_666_666_666_669_68,
    0.074_999_999_997_106_53,
    0.044_642_857_599_726_166,
    0.030_381_916_397_495_97,
    0.022_373_038_603_277_58,
    0.017_336_763_281_738_436,
    0.014_144_868_382_976_405,
    0.010_267_430_424_776_843,
    0.015_521_003_704_904_501,
    -0.006_965_450_747_007_442,
    0.027_986_438_522_030_702,
];

/// `asin(t)` for `t ∈ [0, ½]`, where `u = t²`, via `t + t³·P(t²)`.
#[inline]
fn asin_near_zero(t: f64, u: f64) -> f64 {
    crate::fast_mul_add(t * u, crate::poly(u, &ASIN_NEAR_ZERO), t)
}

/// Minimax coefficients of `P` in `asin(x) ≈ x·P(x²)` on `x² ∈ [0, 0.765625]`
/// (`|x| ≤ 0.875`) — the shared wide fast leg of [`asinf`], [`acosf`],
/// [`asinpif`], and [`acospif`].
///
/// One sqrt-free polynomial covers the whole band, so the reflection through
/// `√((1−|x|)/2)` runs only when the rounding test fails.  Relative error
/// ≤ 2.747e-10 ≈ 2⁻³¹·⁷ (mpmath dense-grid supremum agreeing with rminimax's
/// certificate; f64 evaluation adds ≤ 2⁻⁴⁸), generated with
/// `ratapprox --function="asin(sqrt(x))/sqrt(x)" --dom="[1e-30,0.765625]"
///   --num=[1,x,x^2,...,x^15] --den=[1] --dispCoeff=hex --log`.
const ASIN_WIDE: [f64; 16] = [
    0.999_999_999_725_381_3,
    0.166_666_841_142_576_24,
    0.074_981_624_296_364_12,
    0.045_406_199_671_509_356,
    0.013_782_736_554_599_759,
    0.239_703_546_153_406_17,
    -1.839_902_466_475_237_5,
    10.899_635_812_057_085,
    -45.090_802_252_029_11,
    134.274_603_229_656_58,
    -288.400_686_201_980_76,
    443.397_761_489_090_04,
    -476.123_042_290_353_17,
    339.528_678_702_658_17,
    -144.675_081_916_656_67,
    27.959_718_593_723_323,
];

/// `asin(x)` for `|x| ≤ 0.875` via the wide odd kernel `x·P(x²)`.
#[inline]
fn asin_wide(x: f64) -> f64 {
    x * crate::poly(x * x, &ASIN_WIDE)
}

/// Relative half-width of the wide-leg rounding test: the certified
/// [`ASIN_WIDE`] error (≈ 2⁻³¹·⁷ approximation + ≤ 2⁻⁴⁸ evaluation) with
/// ≈ 1.6× headroom, rounded up to a power of two.  Expected fallback rate
/// ≈ 2·2⁻³¹/2⁻²⁴ ≈ 1.6%; hard ties always land within the interval and thus
/// in the fallback, where the fixups live.
const ASIN_WIDE_EPS: f64 = crate::exp2i(-31);

/// Absolute floor of the rounding test for the π/2- and ½-anchored variants
/// ([`acosf`], [`acospif`]): covers the constant's representation error and
/// the final subtraction's rounding, which do not scale with the kernel
/// result.
const ASIN_WIDE_EPS0: f64 = crate::exp2i(-50);

/// 64-byte-aligned wrapper: [`ASINPI_CELLS`]'s rows are exactly 64 bytes, so
/// aligning the table keeps every cell on its own cache line.
#[repr(C, align(64))]
struct Align64<T>(T);

/// Shared 16-cell table of [`asinpif`] and [`acospif`] (CORE-MATH's one-step
/// shape, our own fits): cell 0 holds `q` in `asinpi(z) ≈ z·q(z²)` for
/// `|x| < 1/16`; cell `i ≥ 1` holds a degree-7 fit of
/// `g(a) = (½ − asinpi(a))/√(1−a) = acospi(a)/√(1−a)` on
/// `a ∈ [i/16, (i+1)/16)`, whence `asinpi(x) = sign(x)·(½ − g·√(1−|x|))` and
/// `acospi(x) = g·√(1−|x|)` for `x ≥ 0` (folded about 1 below).  The deg-7
/// polynomial evaluates in parallel with the square root, and `1 − |x|` is
/// exact there, so a single fused combine lands the result with no rounding
/// test or fallback tier.
///
/// Worst per-cell sup relative error 2⁻⁵³·⁸ (cell 0; the reflection cells sit
/// at 2⁻⁵⁵…2⁻⁶¹ — mpmath dense-grid certificates), leaving ≈ 10⁵× margin on
/// the binding constraint (`asinpif` as `|x| → 1`).  Generated by
/// `tools/gen_asinpi_f32.py` (rminimax `ratapprox`, relative weight).
const ASINPI_CELLS: Align64<[[f64; 8]; 16]> = Align64([
    // asin(sqrt(x))/(pi*sqrt(x)) on [1e-30,0.00390625]
    [
        0.318_309_886_183_790_7,
        0.053_051_647_697_110_49,
        0.023_873_241_983_116_515,
        0.014_209_630_096_882_53,
        0.010_066_529_415_691_305,
        -0.125_385_852_732_165_32,
        22.604_950_105_365_326,
        -1541.745_168_766_115_5,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.0625,0.125]
    [
        0.499_999_999_989_944_43,
        -0.068_309_885_264_917_57,
        0.028_345_020_386_731_24,
        -0.016_167_029_137_249_243,
        0.010_709_433_103_544_396,
        -0.007_652_956_215_503_992,
        0.005_335_453_062_894_584,
        -0.002_633_182_848_797_322_3,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.125,0.1875]
    [
        0.499_999_999_520_619_6,
        -0.068_309_860_731_982_75,
        0.028_344_464_620_786_53,
        -0.016_159_944_926_259_207,
        0.010_654_477_999_610_947,
        -0.007_393_196_617_476_483_5,
        0.004_642_143_981_379_014,
        -0.001_826_817_059_896_801,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.1875,0.25]
    [
        0.499_999_994_835_074_4,
        -0.068_309_691_076_455_15,
        0.028_341_815_413_479_07,
        -0.016_136_809_866_109_74,
        0.010_532_413_281_225_693,
        -0.007_003_995_499_654_292,
        0.003_947_666_530_177_106,
        -0.001_291_816_749_755_188,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.25,0.3125]
    [
        0.499_999_972_030_959_36,
        -0.068_309_062_815_360_56,
        0.028_334_369_088_252_95,
        -0.016_087_586_101_892_974,
        0.010_336_392_174_210_209,
        -0.006_533_718_301_567_086,
        0.003_318_278_131_625_784,
        -0.000_929_328_906_495_311_6,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.3125,0.375]
    [
        0.499_999_898_235_822_1,
        -0.068_307_425_550_361_04,
        0.028_318_761_848_003_3,
        -0.016_004_720_586_946_738,
        0.010_071_724_341_051_507,
        -0.006_025_186_692_701_551,
        0.002_774_020_317_149_146,
        -0.000_679_031_967_369_800_7,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.375,0.4375]
    [
        0.499_999_713_992_137_94,
        -0.068_304_007_238_538_24,
        0.028_291_533_247_659_147,
        -0.015_884_009_516_415_99,
        0.009_750_056_611_689_893,
        -0.005_509_945_561_167_743,
        0.002_314_680_876_495_237_5,
        -0.000_503_210_708_939_110_5,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.4375,0.5]
    [
        0.499_999_328_830_916_6,
        -0.068_297_869_832_541_1,
        0.028_249_564_870_777_677,
        -0.015_724_361_510_075_57,
        0.009_385_188_537_231_672,
        -0.005_008_941_686_462_952,
        0.001_931_983_277_574_931_8,
        -0.000_377_759_633_464_196_1,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.5,0.5625]
    [
        0.499_998_620_450_994_6,
        -0.068_287_980_810_658_15,
        0.028_190_340_050_344_32,
        -0.015_527_108_178_627_364,
        0.008_990_603_504_892_947,
        -0.004_534_859_755_262_382,
        0.001_615_216_972_521_359_5,
        -0.000_286_958_309_246_528_7,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.5625,0.625]
    [
        0.499_997_437_014_669_14,
        -0.068_273_283_824_973_77,
        0.028_112_054_119_440_382,
        -0.015_295_252_879_253_552,
        0.008_578_265_926_102_276,
        -0.004_094_516_022_668_151_5,
        0.001_353_754_196_968_838,
        -0.000_220_369_365_917_356_38,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.625,0.6875]
    [
        0.499_995_601_539_824_7,
        -0.068_252_757_522_555_61,
        0.028_013_612_356_513_17,
        -0.015_032_794_999_562_372,
        0.008_158_143_613_236_038,
        -0.003_690_751_653_155_601_6,
        0.001_138_033_184_478_725_8,
        -0.000_170_942_355_363_996_57,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.6875,0.75]
    [
        0.499_992_917_416_889_2,
        -0.068_225_459_131_178_06,
        0.027_894_562_391_474_708,
        -0.014_744_203_244_927_236,
        0.007_738_167_010_164_63,
        -0.003_323_847_262_850_202_5,
        0.000_959_859_541_937_465_6,
        -0.000_133_840_802_796_145,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.75,0.8125]
    [
        0.499_989_174_594_798_86,
        -0.068_190_556_065_930_75,
        0.027_755_006_469_793_186,
        -0.014_434_063_124_408_477,
        0.007_324_437_416_790_972,
        -0.002_992_545_139_908_372_3,
        0.000_812_405_403_549_153_1,
        -0.000_105_701_699_845_785_58,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.8125,0.875]
    [
        0.499_984_155_353_803_7,
        -0.068_147_341_779_389_08,
        0.027_595_489_126_164_51,
        -0.014_106_809_643_181_34,
        0.006_921_460_342_947_204,
        -0.002_694_696_162_485_659,
        0.000_690_054_344_931_805_6,
        -8.415_351_578_250_548e-05,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.875,0.9375]
    [
        0.499_977_639_529_215_6,
        -0.068_095_241_608_880_78,
        0.027_416_890_922_328_723,
        -0.013_766_567_839_168_02,
        0.006_532_419_904_810_523,
        -0.002_427_704_129_043_811_4,
        0.000_588_224_638_278_460_7,
        -6.750_333_912_089_457e-05,
    ],
    // (0.5 - asin(x)/pi)/sqrt(1-x) on [0.9375,0.999999999999]
    [
        0.499_969_409_009_395_57,
        -0.068_033_811_303_461_34,
        0.027_220_334_322_139_55,
        -0.013_417_068_350_493_22,
        0.006_159_441_894_825_417,
        -0.002_188_814_295_545_167,
        0.000_503_195_842_639_243_7,
        -5.452_904_094_702_049e-05,
    ],
]);

/// Cell index into [`ASINPI_CELLS`]: `floor(16·|x|)` for `|x| ≥ 2⁻¹²` and 0
/// below, straight from the bits (the `& 15` is provably a no-op and elides
/// the bounds check).
#[inline]
fn asinpi_cell_index(bits: u32) -> usize {
    let shift = 146 - ((bits >> 23) & 0xFF);
    if shift < 32 {
        ((((bits & 0x007F_FFFF) | 0x0080_0000) >> shift) & 15) as usize
    } else {
        0
    }
}

/// `atan(k / 8)` as a double-double for `k` in `0..=8`
const ATAN_TABLE: [(f64, f64); 9] = [
    (0.0, 0.0),
    (0.124_354_994_546_761_44, -3.125_324_142_453_938_3e-18),
    (0.244_978_663_126_864_14, 1.069_875_561_873_445_1e-17),
    (0.358_770_670_270_572_25, -2.462_381_558_263_863_5e-17),
    (0.463_647_609_000_806_1, 2.269_877_745_296_168_7e-17),
    (0.558_599_315_343_562_4, -5.455_630_548_591_626_4e-18),
    (0.643_501_108_793_284_4, 1.583_478_505_144_428_6e-17),
    (0.718_829_999_621_624_5, -2.147_838_844_445_698_3e-17),
    (0.785_398_163_397_448_3, 3.061_616_997_868_383e-17),
];

/// π/2 as a double-double
const FRAC_PI_2: DoubleDouble = DoubleDouble {
    high: 1.570_796_326_794_896_6,
    low: 6.123_233_995_736_766e-17,
};

/// π as a double-double
const PI: DoubleDouble = DoubleDouble {
    high: 3.141_592_653_589_793,
    low: 1.224_646_799_147_353_2e-16,
};

/// Arctangent of a double-double in `[0, 1]`, returned as a double-double
///
/// The argument is reduced into a cell of width 1/8 centred on `c = k/8`, where
/// the table holds `atan(c)`.  Inside the cell `atan(q) = atan(c) + atan(u)`
/// with `u = (q - c) / (1 + q·c)` and `|u| ≤ 1/16`, so the Taylor series of the
/// odd part `atan(u) - u` converges in a handful of terms evaluated in `f64`.
#[inline]
fn atan_dd(q: DoubleDouble) -> DoubleDouble {
    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;

    // `q.high ∈ [0, 1]` ⇒ `k ∈ {0, …, 8}`, always a valid index
    let (high, low) = ATAN_TABLE[k as usize];

    // u = (q - c) / (1 + q·c), exact in double-double (c is a power-of-two multiple)
    let u = (q + DoubleDouble { high: -c, low: 0.0 })
        * (q * c
            + DoubleDouble {
                high: 1.0,
                low: 0.0,
            })
        .recip();

    // atan(u) = u - u³/3 + u⁵/5 - u⁷/7 + …, |u| ≤ 1/16.  The cubic and
    // quintic terms carry the low bits (`/3.0`, `/5.0` are compensated
    // divisors), so the plain-`f64` tail starts at u⁷ ≤ 2⁻²⁸ and its rounding
    // stays below ≈2⁻⁷⁷ of the result — deep enough for the hardest
    // `atan2f`/`atan2pif` corpus ties, which the previous u⁵-in-`f64` cut
    // (≈2⁻⁶⁹) mis-rounded.
    let uu = u.high * u.high;
    let u2 = u * u;
    let cubic = u2 * u / 3.0;
    let quintic = (u2 * u2) * u / 5.0;
    let tail = u.high
        * (uu * uu * uu)
        * crate::poly(
            uu,
            &[
                -1.0 / 7.0,
                1.0 / 9.0,
                -1.0 / 11.0,
                1.0 / 13.0,
                -1.0 / 15.0,
                1.0 / 17.0,
                -1.0 / 19.0,
                1.0 / 21.0,
            ],
        );

    DoubleDouble { high, low }
        + u
        + DoubleDouble {
            high: -cubic.high,
            low: -cubic.low,
        }
        + quintic
        + DoubleDouble {
            high: tail,
            low: 0.0,
        }
}

/// Magnitude of `atan2(y, x)` for finite nonzero `a = |x|`, `b = |y|`
///
/// Returns the correctly-rounded angle in `[0, π]`; the caller restores the
/// sign of `y` with `copysign`.
#[inline]
fn atan2_mag(a: f64, b: f64, x_negative: bool) -> f32 {
    let phi = if a >= b {
        atan_dd(DoubleDouble::from_quotient(b, a))
    } else {
        // π/2 - atan(a/b)
        let t = atan_dd(DoubleDouble::from_quotient(a, b));
        FRAC_PI_2
            + DoubleDouble {
                high: -t.high,
                low: -t.low,
            }
    };

    let theta = if x_negative {
        // π - φ
        PI + DoubleDouble {
            high: -phi.high,
            low: -phi.low,
        }
    } else {
        phi
    };

    round(theta)
}

/// Arcsine in half-turns
///
/// One-step 16-cell structure — see [`ASINPI_CELLS`].  The exhaustive 2³²
/// sweep in `tests/asinpif.rs` certifies every input.
#[must_use]
#[inline]
pub fn asinpif(x: f32) -> f32 {
    let bits = x.to_bits();
    let ax = bits & (u32::MAX >> 1);
    if ax >= 0x3F80_0000 {
        return match ax {
            0x3F80_0000 => 0.5_f32.copysign(x), // |x| = 1
            _ => f32::NAN,                      // |x| > 1 or NaN
        };
    }
    let cell = &ASINPI_CELLS.0[asinpi_cell_index(bits)];
    let z: f64 = x.into();
    if ax < 0x3D80_0000 {
        // |x| < 1/16: the odd cell-0 kernel `z·q(z²)`
        (z * crate::poly(z * z, cell)) as f32
    } else {
        let f = (1.0 - z.abs()).sqrt();
        let g = crate::poly(z.abs(), cell);
        crate::fast_mul_add(-g, f.copysign(z), 0.5_f64.copysign(z)) as f32
    }
}

/// `1/π` as a double-double, the half-turn scale of [`atan2pif`].
const FRAC_1_PI_DD: DoubleDouble = DoubleDouble {
    high: 0.318_309_886_183_790_7,
    low: -1.967_867_667_518_248_6e-17,
};

/// Magnitude of `atan2pi(y, x)`: [`atan2_mag`]'s double-double angle times
/// the double-double `1/π` before the one rounding to `f32` — ≈2⁻⁷⁰
/// relative, deep enough for every bivariate corpus tie the promoted f64
/// path double-rounds.
#[inline]
fn atan2pi_mag(a: f64, b: f64, x_negative: bool) -> f32 {
    let phi = if a >= b {
        atan_dd(DoubleDouble::from_quotient(b, a))
    } else {
        // π/2 - atan(a/b)
        let t = atan_dd(DoubleDouble::from_quotient(a, b));
        FRAC_PI_2
            + DoubleDouble {
                high: -t.high,
                low: -t.low,
            }
    };

    let theta = if x_negative {
        // π - φ
        PI + DoubleDouble {
            high: -phi.high,
            low: -phi.low,
        }
    } else {
        phi
    };

    // `Mul` breaks dd normality and `round` requires it (the odd nudge only
    // reaches one ulp); one Fast2Sum renormalizes.
    let t = theta * FRAC_1_PI_DD;
    round(fast_sum(t.high, t.low))
}

/// Arctangent of `y/x` in half-turns, in the correct quadrant
///
/// [`atan2f`]'s quadrant dispatch with exact half-turn rays (`±¼`/`±¾` at
/// infinite corners, `±½` on the axes, `±0`/`±1` at zero `y`), and
/// [`atan2pi_mag`]'s double-double kernel for the finite interior.  The
/// worst-cases corpus in `tests/atan2pif.rs` gates it bit-exactly.
#[must_use]
#[inline]
pub fn atan2pif(y: f32, x: f32) -> f32 {
    if x.is_nan() || y.is_nan() {
        return f32::NAN;
    }

    if x.is_infinite() || y.is_infinite() {
        let magnitude: f32 = match (x.is_infinite(), y.is_infinite()) {
            (true, true) if x.is_sign_positive() => 0.25,
            (true, true) => 0.75,
            (true, false) if x.is_sign_positive() => 0.0,
            (true, false) => 1.0,
            (false, true) => 0.5,
            (false, false) => unreachable!(),
        };
        return magnitude.copysign(y);
    }

    if y == 0.0 {
        return if x.is_sign_positive() {
            0.0_f32
        } else {
            1.0_f32
        }
        .copysign(y);
    }

    if x == 0.0 {
        return 0.5_f32.copysign(y);
    }

    atan2pi_mag(x.abs().into(), y.abs().into(), x.is_sign_negative()).copysign(y)
}

/// Arctangent in half-turns
///
/// [`atanf`]'s rational kernel scaled by `1/π`, with the `|x| > 1`
/// reflection folding into an exact `±½` (`atanpi(±∞) = ±½` falls out).
/// The exhaustive 2³² sweep in `tests/atanpif.rs` certifies every input.
#[must_use]
#[inline]
pub fn atanpif(x: f32) -> f32 {
    use core::f64::consts::FRAC_1_PI;

    // The three f32 ties the kernel's double rounding cannot steer (odd
    // symmetry covers the negatives); the exhaustive sweep found exactly
    // these inputs.
    match x.to_bits() & (u32::MAX >> 1) {
        0x3F69_3531 => return f32::from_bits(0x3E70_D331).copysign(x),
        0x3323_32e9 => return f32::from_bits(0x324f_ca8f).copysign(x),
        0x3905_0b0d => return f32::from_bits(0x3829_6554).copysign(x),
        _ => (),
    }

    let use_outer = x.abs() > 1.0;
    let xd: f64 = x.into();

    if use_outer {
        let recip = xd.recip();
        crate::fast_mul_add(
            -recip * FRAC_1_PI,
            atanf_kernel(recip),
            0.5_f64.copysign(xd),
        ) as f32
    } else {
        (xd * FRAC_1_PI * atanf_kernel(xd)) as f32
    }
}

/// Arccosine in half-turns
///
/// One-step 16-cell structure sharing [`ASINPI_CELLS`] with [`asinpif`]:
/// `acospi(x) = g·√(1−|x|)` for `x ≥ 0`, folded about 1 below, and
/// `½ − z·q(z²)` in the tiny cell.  The exhaustive 2³² sweep in
/// `tests/acospif.rs` certifies every input.
#[must_use]
#[inline]
pub fn acospif(x: f32) -> f32 {
    let bits = x.to_bits();
    let ax = bits & (u32::MAX >> 1);
    if ax >= 0x3F80_0000 {
        return match bits {
            0x3F80_0000 => 0.0, // x = 1
            0xBF80_0000 => 1.0, // x = −1
            _ => f32::NAN,      // |x| > 1 or NaN
        };
    }
    let cell = &ASINPI_CELLS.0[asinpi_cell_index(bits)];
    let z: f64 = x.into();
    if ax < 0x3D80_0000 {
        // |x| < 1/16: fold the odd cell-0 kernel about ½
        (0.5 - z * crate::poly(z * z, cell)) as f32
    } else {
        let f = (1.0 - z.abs()).sqrt();
        let g = crate::poly(z.abs(), cell);
        crate::fast_mul_add(g, f.copysign(z), f64::from(bits >> 31)) as f32
    }
}

/// Arccosine
///
/// Two-step structure like [`asinf`]: for `|x| < 0.875`,
/// `acos(x) = π/2 − asin(x)` with the sqrt-free wide leg [`asin_wide`] and a
/// rounding test whose half-width scales with the kernel result `|r|` (the
/// error carrier) plus the absolute floor [`ASIN_WIDE_EPS0`] for the constant
/// subtraction; failures and `|x| ∈ [0.875, 1]` take [`acosf_fallback`].
#[must_use]
#[inline]
pub fn acosf(x: f32) -> f32 {
    let ax = x.to_bits() & (u32::MAX >> 1);
    if ax > 0x3F80_0000 {
        return f32::NAN; // |x| > 1 or NaN
    }
    if ax < 0x3F60_0000 {
        // |x| < 0.875 — the expected path
        let r = asin_wide(x.into());
        let y = core::f64::consts::FRAC_PI_2 - r;
        let e = crate::fast_mul_add(r.abs(), ASIN_WIDE_EPS, ASIN_WIDE_EPS0);
        let ub = (y + e) as f32;
        if ub == ((y - e) as f32) {
            return ub;
        }
    }
    acosf_fallback(x)
}

/// [`acosf`]'s accurate tier — the previous flat implementation.
///
/// `acos(x) = π/2 − asin(x)`.  For `|x| < ½` this subtracts the near-zero
/// kernel [`asin_near_zero`] directly (no square root); for `|x| ≥ ½` it
/// reflects through `s = √((1−|x|)/2) ∈ [0, ½]`, giving `acos(x) = 2·asin(s)`
/// for `x ≥ 0` and `π − 2·asin(s)` for `x < 0`.  Both forms are evaluated and
/// selected branchlessly so random inputs pay no misprediction penalty.
#[cold]
#[inline(never)]
fn acosf_fallback(x: f32) -> f32 {
    let xf: f64 = x.into();
    let a = xf.abs();

    // |x| < ½:  π/2 − asin(x)
    let near = core::f64::consts::FRAC_PI_2 - asin_near_zero(xf, xf * xf);

    // |x| ≥ ½:  2·asin(s) folded about π for x < 0, s = √((1−|x|)/2)
    let u = 0.5 * (1.0 - a);
    let two = 2.0 * asin_near_zero(u.sqrt(), u);
    let far = if xf.is_sign_positive() {
        two
    } else {
        core::f64::consts::PI - two
    };

    let y = (if a < 0.5 { near } else { far }) as f32;

    // Hard-to-round cases near π/2 (tiny x, near-zero branch).
    match x {
        1.589_325_5e-8 => 1.570_796_4,
        2.486_864_7e-4 => 1.570_547_7,
        _ => y,
    }
}

/// Arcsine
///
/// Two-step structure: `|x| < 0.875` takes the sqrt-free wide leg
/// [`asin_wide`] and returns as soon as the `±ASIN_WIDE_EPS` rounding test
/// certifies the `f32` rounding; the band edge `[0.875, 1]`, the rounding-test
/// failures (≈ 1.6% of the band), and the hard-to-round cases fall back to
/// [`asinf_fallback`].  NaN and `|x| > 1` exit before any arithmetic.
#[must_use]
#[inline]
pub fn asinf(x: f32) -> f32 {
    let ax = x.to_bits() & (u32::MAX >> 1);
    if ax > 0x3F80_0000 {
        return f32::NAN; // |x| > 1 or NaN
    }
    if ax < 0x3F60_0000 {
        // |x| < 0.875 — the expected path.  `r·(1 ± EPS)` via one fused op
        // per bound keeps the rounding test off the serial critical path.
        // Return the upper cast: at `x = −0` it preserves the sign.
        let r = asin_wide(x.into());
        let ub = crate::fast_mul_add(r, ASIN_WIDE_EPS, r) as f32;
        if ub == (crate::fast_mul_add(r, -ASIN_WIDE_EPS, r) as f32) {
            return ub;
        }
    }
    asinf_fallback(x)
}

/// [`asinf`]'s accurate tier — the previous flat implementation.
///
/// For `|x| < ½`, evaluate the near-zero kernel [`asin_near_zero`] directly.
/// For `|x| ≥ ½`, reflect through `s = √((1−|x|)/2) ∈ [0, ½]` with
/// `asin(x) = π/2 − 2·asin(s)` (sign restored afterward), reusing the same
/// kernel.  Both forms are evaluated and selected branchlessly.
#[cold]
#[inline(never)]
fn asinf_fallback(x: f32) -> f32 {
    let xf: f64 = x.into();
    let a = xf.abs();

    // |x| < ½:  asin(x) directly
    let near = asin_near_zero(xf, xf * xf);

    // |x| ≥ ½:  ±(π/2 − 2·asin(s)), s = √((1−|x|)/2)
    let u = 0.5 * (1.0 - a);
    let two = 2.0 * asin_near_zero(u.sqrt(), u);
    let far = if xf.is_sign_positive() {
        core::f64::consts::FRAC_PI_2 - two
    } else {
        two - core::f64::consts::FRAC_PI_2
    };

    let y = (if a < 0.5 { near } else { far }) as f32;

    // Hard-to-round case in the reflection branch.
    match x.abs() {
        0.532_136_56 => 0.561_122_06_f32.copysign(x),
        _ => y,
    }
}

/// `atan(x)/x` as a rational in `x²` on `[−1, 1]` — [`atanf`]'s kernel,
/// shared with [`atanpif`].
#[inline]
fn atanf_kernel(x: f64) -> f64 {
    fast_polynomial::rational_array(
        x * x,
        &[
            3.300_049_005_002_112e-1,
            8.269_936_280_545_194e-1,
            7.536_692_262_484_512e-1,
            3.041_250_192_035_205_3e-1,
            5.258_546_450_061_43e-2,
            3.092_811_576_351_314e-3,
            2.668_044_628_603_543_2e-5,
        ],
        &[
            3.300_049_005_002_111_4e-1,
            9.369_952_615_545_891e-1,
            1.0,
            4.972_028_574_382_380_6e-1,
            1.155_090_051_164_766_6e-1,
            1.090_224_520_186_812_4e-2,
            2.732_269_307_955_130_4e-4,
        ],
    )
}

/// Arctangent
#[must_use]
#[inline]
pub fn atanf(x: f32) -> f32 {
    let use_outer = x.abs() > 1.0;
    let x: f64 = x.into();

    if use_outer {
        use core::f64::consts::FRAC_PI_2;
        let recip = x.recip();
        crate::fast_mul_add(-recip, atanf_kernel(recip), FRAC_PI_2.copysign(x)) as f32
    } else {
        (x * atanf_kernel(x)) as f32
    }
}

/// Arctangent of `y / x` using the signs of both to select the quadrant
///
/// The result is the angle in `(-π, π]` between the positive `x`-axis and the
/// point `(x, y)`, carrying the sign of `y`.
#[must_use]
#[inline]
pub fn atan2f(y: f32, x: f32) -> f32 {
    use core::f32::consts::{FRAC_PI_2, FRAC_PI_4, PI};

    /// Correctly-rounded `f32` of 3π/4
    const THREE_PI_4: f32 = 2.356_194_5;

    if x.is_nan() || y.is_nan() {
        return f32::NAN;
    }

    if x.is_infinite() || y.is_infinite() {
        let magnitude = match (x.is_infinite(), y.is_infinite()) {
            (true, true) if x.is_sign_positive() => FRAC_PI_4,
            (true, true) => THREE_PI_4,
            (true, false) if x.is_sign_positive() => 0.0,
            (true, false) => PI,
            (false, true) => FRAC_PI_2,
            (false, false) => unreachable!(),
        };
        return magnitude.copysign(y);
    }

    if y == 0.0 {
        return if x.is_sign_positive() { 0.0 } else { PI }.copysign(y);
    }

    if x == 0.0 {
        return FRAC_PI_2.copysign(y);
    }

    atan2_mag(x.abs().into(), y.abs().into(), x.is_sign_negative()).copysign(y)
}
