//! Inverse trigonometric functions: `asin`, `acos`, `atan`, `atan2`.
//!
//! `atan`/`atan2` use one double-double `atan` kernel: `atan_dd` reduces
//! `q ∈ [0, 1]` into a width-1/8 cell (`ATAN_TABLE` holds `atan(k/8)`) and
//! evaluates the odd series on `|u| ≤ 1/16`.  `asin`/`acos` share the
//! table-driven [`asin_tail`] fast path, which tabulates `asin(t)/t` on a grid
//! `u = t² = j/128` plus a per-cell `f64` correction in `r = u − j/128`, one
//! cache line per cell ([`ASIN_CELLS`]); the reflection `s = √((1−|x|)/2)` for
//! `|x| ≥ ½` keeps `u ≤ ¼`, and there `u` is exact so only the multiplier
//! `√t = 2s` carries a low word (no double-double `sqrt`).  Both fall back, via
//! a correction-scaled Ziv gate ([`ASIN_EPS_R`]), to the accurate
//! `asin(x) = atan(x/√(1−x²))` (`asin_pos`).
//!
//! Constants below were generated by `tools/gen_atan_f64.py` and
//! `tools/gen_inv_f64.py`.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::double::{DoubleDouble, sqrt_dd};
use super::pow::poly_dd;

/// `(-1)ᵏ/(2k+1)` as a double-double, low-degree first in `u²` — the atan series.
const ATAN_COEFFS: [DoubleDouble; 16] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: -0.3333333333333333,
        low: -1.850371707708594e-17,
    },
    DoubleDouble {
        high: 0.2,
        low: -1.1102230246251566e-17,
    },
    DoubleDouble {
        high: -0.14285714285714285,
        low: -7.93016446160826e-18,
    },
    DoubleDouble {
        high: 0.1111111111111111,
        low: 6.1679056923619804e-18,
    },
    DoubleDouble {
        high: -0.09090909090909091,
        low: 2.523234146875356e-18,
    },
    DoubleDouble {
        high: 0.07692307692307693,
        low: -4.270088556250602e-18,
    },
    DoubleDouble {
        high: -0.06666666666666667,
        low: -9.251858538542971e-19,
    },
    DoubleDouble {
        high: 0.058823529411764705,
        low: 8.163404592832033e-19,
    },
    DoubleDouble {
        high: -0.05263157894736842,
        low: -2.921639538487254e-18,
    },
    DoubleDouble {
        high: 0.047619047619047616,
        low: 2.64338815386942e-18,
    },
    DoubleDouble {
        high: -0.043478260869565216,
        low: -1.206764157201257e-18,
    },
    DoubleDouble {
        high: 0.04,
        low: -8.326672684688674e-19,
    },
    DoubleDouble {
        high: -0.037037037037037035,
        low: -2.05596856412066e-18,
    },
    DoubleDouble {
        high: 0.034482758620689655,
        low: 4.785444071660157e-19,
    },
    DoubleDouble {
        high: -0.03225806451612903,
        low: -8.953411488912552e-19,
    },
];

/// Fast-path tail of the atan series in `w = u²`: `w²·(1/5 − w/7 + w²/9 − …)`,
/// the remainder after the two leading terms `1 − w/3` are peeled into
/// double-double.  Evaluated in plain `f64`; `|u| ≤ 1/16` so `w ≤ 2⁻⁸` and the
/// 8 terms reach below 2⁻⁶⁴ relative to `atan(u)`.  See [`atan_dd_fast`].
const ATAN_TAIL: [f64; 8] = [
    0.2,
    -0.14285714285714285,
    0.1111111111111111,
    -0.09090909090909091,
    0.07692307692307693,
    -0.06666666666666667,
    0.058823529411764705,
    -0.05263157894736842,
];

/// One cache line of the table-driven `asin`/`acos` fast path: `B(u_j)` as a
/// double-double lead plus six per-cell correction coefficients — exactly 64
/// bytes, so a lookup touches a single line (the former split
/// `ASIN_LEAD`/`ASIN_POLY` arrays spread one lookup over two arrays and up to
/// three lines).
///
/// `B(u_j) = asin(t)/t` at the grid points `u_j = t² = j/128` (`j = 0..=32`,
/// covering `u ∈ [0, ¼]`); `poly` is a Chebyshev interpolant of
/// `(B(u_j + r) − B(u_j))/r` over the cell `|r| ≤ 2⁻⁸` (half-cells at the
/// edges `j = 0` and `j = 32`), low-degree first.  Near-minimax fitting pushes
/// the cell-edge truncation (the dominant term of a Taylor expansion, ~2⁻⁵²
/// per unit `r` at degree 5) below the `f64` evaluation rounding (sup error
/// ~2⁻⁵⁵ per unit `r`), which is what lets the Ziv gate scale purely with the
/// correction term — see [`ASIN_EPS_R`].  Generated by `tools/gen_inv_f64.py`.
#[repr(C, align(64))]
struct AsinCell {
    /// `B(u_j)` to ~2⁻¹⁰⁶.
    lead: DoubleDouble,
    /// Per-cell Chebyshev correction `P(r) ≈ (B(u_j + r) − B(u_j))/r`.
    poly: [f64; 6],
}

#[rustfmt::skip]
const ASIN_CELLS: [AsinCell; 33] = [
    AsinCell { lead: DoubleDouble { high: 1.0, low: 0.0 }, poly: [0.16666666666666666, 0.07500000000000046, 0.04464285714151091, 0.030381945914185627, 0.022371434124784886, 0.017517411402689965] },
    AsinCell { lead: DoubleDouble { high: 1.001306682371262, low: -1.0272312753221834e-16 }, poly: [0.16784677438667686, 0.07605755082168192, 0.04560611511575869, 0.03127197994968885, 0.023204118969829043, 0.018136886974879876] },
    AsinCell { lead: DoubleDouble { high: 1.0026226493445232, low: 1.0324808391048493e-17 }, poly: [0.16904358442931514, 0.07713800795263456, 0.04659770185606869, 0.032195230970348244, 0.024073475656062455, 0.018962670853765858] },
    AsinCell { lead: DoubleDouble { high: 1.0039480328184027, low: -4.880658832674078e-17 }, poly: [0.17025745995687916, 0.07824204769439794, 0.04761867877230672, 0.033153209924799525, 0.024982574268493204, 0.019832978331821027] },
    AsinCell { lead: DoubleDouble { high: 1.0052829675705146, low: -5.363981194877168e-17 }, poly: [0.1714887748961512, 0.07937037178898687, 0.04867015579935748, 0.03414751078380546, 0.025933566312932588, 0.02075059068542687] },
    AsinCell { lead: DoubleDouble { high: 1.0066275913431422, low: 2.5043560802184795e-18 }, poly: [0.17273791434494837, 0.08052370858666094, 0.04975329402380281, 0.0351798141637133, 0.02692873824968861, 0.021718487159338145] },
    AsinCell { lead: DoubleDouble { high: 1.0079820449321606, low: -5.1752227787916015e-17 }, poly: [0.17400527499741064, 0.08170281427717768, 0.05086930847588672, 0.03625189278383774, 0.0279705211396371, 0.02273986081407639] },
    AsinCell { lead: DoubleDouble { high: 1.009346472279358, low: -7.629540267778587e-17 }, poly: [0.17529126558904862, 0.08290847418852788, 0.05201947109806524, 0.03736561731555017, 0.029061501065725356, 0.023818135785031936] },
    AsinCell { lead: DoubleDouble { high: 1.0107210205683146, low: 2.633607878967623e-17 }, poly: [0.17659630736263912, 0.08414150415743896, 0.05320511390286878, 0.03852296265469621, 0.030204430399280086, 0.024956986092009286] },
    AsinCell { lead: DoubleDouble { high: 1.012105840324008, low: -7.582727232984953e-17 }, poly: [0.1779208345561254, 0.08540275197624249, 0.05442763233383695, 0.03972601465180409, 0.031402239987338244, 0.026160356152882907] },
    AsinCell { lead: DoubleDouble { high: 1.0135010855163171, low: -8.705804407322068e-17 }, poly: [0.17926529491375298, 0.08669309892103776, 0.05568848884441042, 0.0409769773376698, 0.032658052344806544, 0.027432483171712114] },
    AsinCell { lead: DoubleDouble { high: 1.0149069136676179, low: -5.584635415072094e-17 }, poly: [0.18063015022175236, 0.08801346136644564, 0.05698921671089193, 0.042278180685338985, 0.03397519594366968, 0.028777921590316696] },
    AsinCell { lead: DoubleDouble { high: 1.016323485964662, low: -4.943036930497581e-17 }, poly: [0.1820158768699657, 0.08936479249264098, 0.058331424096928576, 0.04363208895328746, 0.03535722070080701, 0.03020156981319128] },
    AsinCell { lead: DoubleDouble { high: 1.01775096737495, low: 7.704611664224385e-17 }, poly: [0.1834229664409061, 0.09074808409077688, 0.05971679838843155, 0.04504130965876766, 0.036807914776353715, 0.03170869943902355] },
    AsinCell { lead: DoubleDouble { high: 1.0191895267678206, low: -1.0613869097246791e-16 }, poly: [0.18485192632783798, 0.09216436847337664, 0.06114711081945033, 0.04650860323488207, 0.038331322806079496, 0.033304987258306024] },
    AsinCell { lead: DoubleDouble { high: 1.020639337040483, low: 5.046596408196905e-17 }, poly: [0.18630328038357294, 0.09361472049676992, 0.06262422141127005, 0.0480368934300134, 0.03993176570409889, 0.03499655030596615] },
    AsinCell { lead: DoubleDouble { high: 1.0221005752492498, low: -2.632985627554085e-17 }, poly: [0.18777756960179107, 0.09510025970319365, 0.06415008424891891, 0.04962927851384004, 0.0416138621865306, 0.036789984291010665] },
    AsinCell { lead: DoubleDouble { high: 1.023573422746221, low: 4.986625487259925e-17 }, poly: [0.1892753528328202, 0.09662215259076994, 0.06572675312137483, 0.05128904336035387, 0.04338255218267208, 0.03869240576237429] },
    AsinCell { lead: DoubleDouble { high: 1.0250580653217043, low: -7.113659424223031e-17 }, poly: [0.19079720753593998, 0.09818161502021494, 0.06735638755406599, 0.05301967248514469, 0.045243122318055086, 0.040711498412036265] },
    AsinCell { lead: DoubleDouble { high: 1.0265546933526606, low: -4.741503323356409e-17 }, poly: [0.19234373057042067, 0.09977991476783331, 0.06904125926479136, 0.05482486412179762, 0.04720123367363216, 0.04285556396365951] },
    AsinCell { lead: DoubleDouble { high: 1.0280635019574904, low: -6.544150189403774e-17 }, poly: [0.19391553902766198, 0.10141837423511325, 0.0707837590769671, 0.056708545430653734, 0.049262952047579446, 0.0451335781482472] },
    AsinCell { lead: DoubleDouble { high: 1.0295846911574884, low: -1.8862205210991434e-17 }, poly: [0.19551327110696473, 0.10309837332606799, 0.07258640432716265, 0.058674888942507095, 0.05143478097108996, 0.04755525232844154] },
    AsinCell { lead: DoubleDouble { high: 1.03111846604532, low: 1.0973504492523829e-16 }, poly: [0.19713758703764944, 0.10482135250437412, 0.07445184680725425, 0.060728330350163985, 0.053723697757419274, 0.05013110140107482] },
    AsinCell { lead: DoubleDouble { high: 1.032665036960893, low: 5.777325521136841e-17 }, poly: [0.19878917005043126, 0.10658881604334543, 0.07638288128522912, 0.06287358777229668, 0.056137192894725796, 0.052872518684536324] },
    AsinCell { lead: DoubleDouble { high: 1.034224619675018, low: 2.3661883234451118e-17 }, poly: [0.20046872740117394, 0.10840233548285978, 0.07838245465275882, 0.06511568262682592, 0.05868331312836987, 0.05579185858472258] },
    AsinCell { lead: DoubleDouble { high: 1.0357974355812862, low: -6.5788579651732e-17 }, poly: [0.20217699145037335, 0.11026355330853636, 0.08045367575216739, 0.06745996226532305, 0.06137070861781541, 0.05890252793227309] },
    AsinCell { lead: DoubleDouble { high: 1.0373837118966067, low: -6.207970775472474e-18 }, poly: [0.203914720801972, 0.11217418686975164, 0.08259982594039775, 0.06991212453581647, 0.06420868459770185, 0.06221908699616942] },
    AsinCell { lead: DoubleDouble { high: 1.038983681870887, low: 2.310007649575221e-17 }, poly: [0.20568270150537452, 0.11413603255449548, 0.08482437045308279, 0.07247824445912224, 0.06720725802269994, 0.06575736130657349] },
    AsinCell { lead: DoubleDouble { high: 1.0405975850063638, low: 4.0405187993459635e-17 }, poly: [0.2074817483248279, 0.11615097024061824, 0.08713097063791647, 0.07516480322363228, 0.07037721973220704, 0.0695345655652949] },
    AsinCell { lead: DoubleDouble { high: 1.042225667287128, low: 1.0289845986206202e-16 }, poly: [0.20931270608064942, 0.11822096804471928, 0.08952349713326367, 0.07797871972564913, 0.07373020273466649, 0.07356944108817176] },
    AsinCell { lead: DoubleDouble { high: 1.0438681814194257, low: 2.7122202983822705e-17 }, poly: [0.21117645106712984, 0.12034808739179291, 0.09200604407542505, 0.080927384907161, 0.0772787572833403, 0.07788240841302087] },
    AsinCell { lead: DoubleDouble { high: 1.0455253870833516, low: -7.452575137576243e-17 }, poly: [0.21307389255231882, 0.12253448843079867, 0.0945829444262702, 0.08401869917075003, 0.08103643349690327, 0.08249573692326397] },
    AsinCell { lead: DoubleDouble { high: 1.0471975511965979, low: -1.072081766451091e-16 }, poly: [0.21500597436530758, 0.12478243582357537, 0.09725878652559589, 0.08726110356652733, 0.08501097416198228, 0.08634539670964886] },
];

/// Coefficients `a_1..a_60` of `B(u) = asin(t)/t = Σ aₖ uᵏ` (`u = t²`) as
/// double-doubles, low-degree first — the triple-double accurate series for the
/// `|x| < ½` fallback ([`asin_direct_td`]).  A handful of `f64` acos arguments are
/// hard to round beyond double-double's ~2⁻¹⁰⁶ reach (the worst, `acos`'s, lands
/// ~2⁻¹¹¹ from a midpoint); this series resolves them in triple-double.  The 60
/// terms carry the slowly-decaying tail (`aₖ ~ 4⁻ᵏ/k^{3/2}`) below 2⁻¹³⁰ at
/// `u = ¼`.  Generated by `tools/gen_inv_f64.py`.
#[rustfmt::skip]
const ASIN_ACC: [DoubleDouble; 60] = [
    DoubleDouble { high: 0.16666666666666666, low: 9.25185853854297e-18 },
    DoubleDouble { high: 0.075, low: 2.7755575615628915e-18 },
    DoubleDouble { high: 0.044642857142857144, low: -9.912705577010326e-19 },
    DoubleDouble { high: 0.030381944444444444, low: 3.854941057726238e-19 },
    DoubleDouble { high: 0.022372159090909092, low: -9.462128050782583e-19 },
    DoubleDouble { high: 0.017352764423076924, low: -8.006416042969879e-19 },
    DoubleDouble { high: 0.01396484375, low: -6.938893903907229e-19 },
    DoubleDouble { high: 0.011551800896139705, low: 8.163404592832033e-19 },
    DoubleDouble { high: 0.009761609529194078, low: 5.478074134663601e-19 },
    DoubleDouble { high: 0.008390335809616815, low: 4.130293990420969e-19 },
    DoubleDouble { high: 0.0073125258735988454, low: -3.394024192128536e-19 },
    DoubleDouble { high: 0.006447210311889649, low: -3.1225022567582527e-19 },
    DoubleDouble { high: 0.005740037670841924, low: -1.2849803525754126e-19 },
    DoubleDouble { high: 0.005153309682319905, low: -3.888173308223878e-19 },
    DoubleDouble { high: 0.004660143486915096, low: -2.7979410902851727e-20 },
    DoubleDouble { high: 0.004240907093679363, low: -1.5770213417970974e-19 },
    DoubleDouble { high: 0.003880964558837669, low: 1.858632295689436e-19 },
    DoubleDouble { high: 0.0035692053938259347, low: -1.992587776459846e-19 },
    DoubleDouble { high: 0.003297059503473485, low: -1.3344026738283132e-19 },
    DoubleDouble { high: 0.0030578216492580306, low: 2.1155164341180575e-20 },
    DoubleDouble { high: 0.002846178401108942, low: 1.1094161764967953e-19 },
    DoubleDouble { high: 0.00265787063820729, low: -1.4456028966473392e-19 },
    DoubleDouble { high: 0.0024894486782468836, low: -8.304527278612374e-20 },
    DoubleDouble { high: 0.002338091892111975, low: 1.4161007967157608e-19 },
    DoubleDouble { high: 0.0022014739737101384, low: -1.5306383611560064e-19 },
    DoubleDouble { high: 0.0020776610325181676, low: -1.4728784229991757e-19 },
    DoubleDouble { high: 0.0019650336162772837, low: -7.096596038086938e-20 },
    DoubleDouble { high: 0.0018622264064031275, low: -5.325905408700723e-20 },
    DoubleDouble { high: 0.0017680811205154183, low: -5.880418562633244e-20 },
    DoubleDouble { high: 0.0016816093935831068, low: 1.4219044885055797e-20 },
    DoubleDouble { high: 0.001601963275351444, low: 4.818676322157797e-20 },
    DoubleDouble { high: 0.0015284115961225677, low: -3.8364076872564005e-20 },
    DoubleDouble { high: 0.0014603208940791154, low: -1.375480368078625e-20 },
    DoubleDouble { high: 0.0013971399176302534, low: 1.11955659115351e-20 },
    DoubleDouble { high: 0.0013383869512751784, low: -5.506907161304015e-20 },
    DoubleDouble { high: 0.0012836393876290285, low: 3.621355929288591e-20 },
    DoubleDouble { high: 0.001232525098500017, low: -9.357455312634007e-20 },
    DoubleDouble { high: 0.0011847152561624392, low: 8.758128167121453e-20 },
    DoubleDouble { high: 0.0011399183307022236, low: 8.194708704184068e-20 },
    DoubleDouble { high: 0.0010978750465914472, low: 4.854022464579631e-20 },
    DoubleDouble { high: 0.0010583541258722428, low: 9.018646571938304e-20 },
    DoubleDouble { high: 0.0010211486797106276, low: 8.391832465295875e-20 },
    DoubleDouble { high: 0.0009860731369833312, low: 7.622485745671054e-20 },
    DoubleDouble { high: 0.0009529606197429564, low: 3.077887041034637e-20 },
    DoubleDouble { high: 0.0009216606921836334, low: 5.241836681717014e-20 },
    DoubleDouble { high: 0.0008920374230917097, low: 5.279707379901296e-21 },
    DoubleDouble { high: 0.0008639677124658675, low: 1.7643208659492762e-20 },
    DoubleDouble { high: 0.0008373398416027121, low: -3.173157570752775e-20 },
    DoubleDouble { high: 0.0008120522129086701, low: 8.562849812695216e-21 },
    DoubleDouble { high: 0.0007880122513582056, low: -1.684626855858876e-21 },
    DoubleDouble { high: 0.000765135444137165, low: -4.6754051814894244e-20 },
    DoubleDouble { high: 0.0007433444987958959, low: -5.055558498367341e-20 },
    DoubleDouble { high: 0.0007225686033525614, low: 3.139349372897533e-20 },
    DoubleDouble { high: 0.0007027427743614913, low: 5.3529510038453024e-20 },
    DoubleDouble { high: 0.0006838072810965503, low: -5.683687522703426e-21 },
    DoubleDouble { high: 0.0006657071357767537, low: 2.050097394525252e-20 },
    DoubleDouble { high: 0.000648391641245871, low: 3.25712698240824e-20 },
    DoubleDouble { high: 0.0006318139887619101, low: 3.103551903224413e-20 },
    DoubleDouble { high: 0.0006159308995984751, low: -2.234879077638401e-20 },
    DoubleDouble { high: 0.0006007023050422869, low: -2.730684204640525e-20 },
];

/// Third limbs of `a_1..a_8` — the `ASIN_ACC` coefficients whose double-double
/// rounding would otherwise cap the assembled series above 2⁻¹³⁰ at `u = ¼`, so
/// they are carried as triple-doubles `ASIN_ACC[k].high + .low + ASIN_ACC_LO[k]`.
const ASIN_ACC_LO: [f64; 8] = [
    5.135813185032629e-34,
    -1.5407439555097888e-34,
    -5.502656983963531e-35,
    2.139922160430262e-35,
    -7.003381615953585e-35,
    4.4444537178166984e-35,
    3.851859888774472e-35,
    1.1328999672866093e-35,
];

/// π/2 as a triple-double, for the `acos` accurate combine `π/2 − asin`.
const FRAC_PI_2_TD: TripleDouble = TripleDouble {
    high: 1.5707963267948966,
    mid: 6.123233995736766e-17,
    low: -1.4973849048591698e-33,
};

/// `atan(k/8)` as a double-double for `k` in `0..=8`.
const ATAN_TABLE: [DoubleDouble; 9] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.12435499454676144,
        low: -3.1253241424539383e-18,
    },
    DoubleDouble {
        high: 0.24497866312686414,
        low: 1.0698755618734451e-17,
    },
    DoubleDouble {
        high: 0.35877067027057225,
        low: -2.4623815582638635e-17,
    },
    DoubleDouble {
        high: 0.4636476090008061,
        low: 2.2698777452961687e-17,
    },
    DoubleDouble {
        high: 0.5585993153435624,
        low: -5.4556305485916264e-18,
    },
    DoubleDouble {
        high: 0.6435011087932844,
        low: 1.5834785051444286e-17,
    },
    DoubleDouble {
        high: 0.7188299996216245,
        low: -2.1478388444456983e-17,
    },
    DoubleDouble {
        high: 0.7853981633974483,
        low: 3.061616997868383e-17,
    },
];

/// π/2 as a double-double.
const FRAC_PI_2: DoubleDouble = DoubleDouble {
    high: 1.5707963267948966,
    low: 6.123233995736766e-17,
};

/// π as a double-double.
const PI: DoubleDouble = DoubleDouble {
    high: 3.141592653589793,
    low: 1.2246467991473532e-16,
};

/// One as a double-double.
const ONE: DoubleDouble = DoubleDouble {
    high: 1.0,
    low: 0.0,
};

/// Zero as a double-double.
const ZERO: DoubleDouble = DoubleDouble {
    high: 0.0,
    low: 0.0,
};

/// Relative half-width of the `atan`/`atan2` fast-path Ziv gate.  Over a dense
/// sweep of the active band the fast kernel's relative error peaks well below
/// 2⁻⁶⁸; the gate at 2⁻⁶³ keeps a comfortable margin and defers the rest to the
/// double-double kernel, which stays the correctly-rounded reference.
const ATAN_ZIV_EPS: f64 = 1.0842021724855044e-19; // 2⁻⁶³

/// The `asin`/`acos` fast-path Ziv gate is *correction-scaled* rather than a
/// fixed relative width: `eps = |z|·(C·|r| + F) + G`, where `z` is the kernel
/// multiplier (the argument, or the reflection's `√t`) and `r` the in-cell
/// offset.  Every error source of [`asin_tail`] is proportional to the
/// correction `z·r` (polynomial evaluation rounding, fit truncation) or to `z`
/// alone (table-lead rounding, the `√t` low word, product cross terms), plus
/// the absolute offset-fold rounding of `acos`'s π/2 and π folds — so the gate
/// tracks the true error profile and defers ~0.5% to the accurate fallback,
/// versus ~2% for the old fixed `2⁻⁵⁹` relative gate.
///
/// Constants calibrated by `tools/gen_inv_f64.py`, which simulates the exact
/// `f64` operation sequence of [`asin_tail`] over dense sweeps of all five
/// branch/offset cases (worst requirement C ≥ 2⁻⁵³·¹, F ≥ 2⁻⁷⁸·⁷, G ≥ 2⁻¹⁰⁵·³;
/// a denser 3.6-million-point sweep peaks at C ≥ 2⁻⁵²·⁹⁶, leaving a 3.9×
/// margin).
const ASIN_EPS_R: f64 = 4.440892098500626e-16; // C = 2⁻⁵¹
/// Per-`z` floor of the `asin`/`acos` gate; see [`ASIN_EPS_R`].
const ASIN_EPS_Z: f64 = 1.3234889800848443e-23; // F = 2⁻⁷⁶
/// Absolute floor of the `asin`/`acos` gate; see [`ASIN_EPS_R`].
const ASIN_EPS_ABS: f64 = 7.888609052210118e-31; // G = 2⁻¹⁰⁰

/// Relative half-width of the *second-tier* Ziv gate on the double-double accurate
/// fallback.  That fallback (`asin_pos`∘`atan_dd`) is ~2⁻⁹⁸ accurate — correctly
/// rounded everywhere except a handful of hard-to-round points (~2⁻¹¹¹ from a
/// midpoint).  This gate at 2⁻⁹⁰ (well above the dd error) passes the
/// double-double result directly for all but those points, which alone escalate
/// to the slow triple-double [`asin_direct_td`] — so the ~770 ns triple-double
/// path runs ~2⁻³⁷ of the time, not on every fast-leg miss.
const ASIN_DD_ZIV_EPS: f64 = 8.077935669463161e-28; // 2⁻⁹⁰

/// Negate a double-double.
#[inline]
fn neg(v: DoubleDouble) -> DoubleDouble {
    DoubleDouble {
        high: -v.high,
        low: -v.low,
    }
}

/// Ziv gate: round `v` to `f64` when both ends of its `±eps_rel·|v|` (relative)
/// error interval agree, else `None` to fall back to the accurate kernel.
#[inline]
fn ziv_at(v: DoubleDouble, eps_rel: f64) -> Option<f64> {
    let eps = v.high.abs() * eps_rel;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// [`ziv_at`] at the `atan`/`atan2` gate width.
#[inline]
fn ziv(v: DoubleDouble) -> Option<f64> {
    ziv_at(v, ATAN_ZIV_EPS)
}

/// Arctangent of a double-double `q ∈ [0, 1]`, as a double-double.
#[inline]
fn atan_dd(q: DoubleDouble) -> DoubleDouble {
    // For `q < 2⁻⁴⁰`, `atan(q) = q − q³/3 + …` agrees with `q` far below ½ ulp, so
    // the correctly-rounded `q.high` is the answer; dropping the low word also
    // protects against a `from_quotient` residual that underflowed to subnormal.
    if q.high < 9.094947017729282e-13 {
        return DoubleDouble {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    // u = (q − c) / (1 + q·c), |u| ≤ 1/16 (c is an exact power-of-two multiple).
    let denom = q * c
        + DoubleDouble {
            high: 1.0,
            low: 0.0,
        };
    let u = (q + DoubleDouble { high: -c, low: 0.0 }) * denom.recip();

    atan_cell(table, u)
}

/// Accurate counterpart of [`atan_cell_fast`]: finish from a reduced cell via the
/// full double-double series `atan(k/8 + …) = table + u·Σ(−1)ᵏu²ᵏ/(2k+1)`.
///
/// `table = atan(k/8)` and `|u| ≤ 1/16`.  Shared by [`atan_dd`] and the fused
/// `atan2` reduction, which differ only in how they form `u`.
#[inline]
fn atan_cell(table: DoubleDouble, u: DoubleDouble) -> DoubleDouble {
    table + u * poly_dd(u * u, &ATAN_COEFFS)
}

/// Lean counterpart of [`atan_dd`], the inverse-trig functions' fast path.
///
/// The cell reduction is identical, but `atan(u)/u = 1 − w/3 + w²·(…)` peels the
/// two leading terms into double-double (`w = u²`, `1/3` carried as a
/// double-double coefficient) and evaluates only the tiny tail ([`ATAN_TAIL`])
/// in plain `f64`, replacing the 16-term double-double Horner.  A [`ziv`] gate on
/// the reconstructed result accepts it or defers to [`atan_dd`].
#[inline]
fn atan_dd_fast(q: DoubleDouble) -> DoubleDouble {
    if q.high < 9.094947017729282e-13 {
        return DoubleDouble {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    // SAFETY: q ∈ [0, 1] puts k in 0..=8; a plain `as` cast would pay a
    // saturation cmov chain right in front of the table load.
    let table = ATAN_TABLE[unsafe { k.to_int_unchecked::<i64>() } as usize];

    // `q.high − c` is Sterbenz-exact: `k = round(8·q.high)` puts `q.high` in
    // `[c − 1/16, c + 1/16] ⊂ [c/2, 2c]` (for `k ≥ 1`; ties-even keeps
    // `q.high > 1/16` whenever `k ≥ 1`, and `k = 0` means `c = 0`).  `1 ≥ q·c`
    // orders the denominator fold, and the lean quotient replaces
    // `denom.recip()`'s Newton step plus a double-double multiply.
    let num = DoubleDouble {
        high: q.high - c,
        low: q.low,
    };
    let u = num.div_fast(ONE.add_ordered(q * c));

    atan_cell_fast(table, u)
}

/// Finish the fast path from a reduced cell: `atan(k/8 + …) = table + u·(1 − u²/3 + …)`.
///
/// `table = atan(k/8)` and `u` is the cell-reduced argument (`|u| ≤ 1/16`).  Shared
/// by [`atan_dd_fast`] and [`atan_recip_fast`], which differ only in how they form `u`.
#[inline]
fn atan_cell_fast(table: DoubleDouble, u: DoubleDouble) -> DoubleDouble {
    let w = u * u;
    let wh = w.high;
    let w2 = wh * wh;
    // 1 − w/3 in double-double (ATAN_COEFFS[1] = −1/3); tail w²·(1/5 − w/7 + …).
    // Ordered Fast2Sum folds: `|w| ≤ 2⁻⁸` keeps every addend far under its lead,
    // and the final `table ⊕ u·bracket` orders for `k ≥ 1` (`atan(1/8) ≥ 2·…`,
    // see `fold_ordering`) while `k = 0` makes `table` zero, where Fast2Sum is
    // exact regardless.
    let bracket = ONE
        .add_ordered(w * ATAN_COEFFS[1])
        .add_ordered(DoubleDouble {
            high: w2 * crate::poly(wh, &ATAN_TAIL),
            low: 0.0,
        });
    table.add_ordered(u * bracket)
}

/// `atan(1/a)` for `a > 1`, the fast path's reflection leg, without ever forming
/// `1/a` as a double-double.
///
/// With `v = 1/a`, the cell reduction `u = (v − c)/(1 + v·c)` becomes
/// `u = (1 − a·c)/(a + c)` after multiplying through by `a`.  So the leg spends one
/// `1/a` (a plain `f64`, only to pick the cell `k = round(8/a)`) plus the cell's own
/// `recip` — **two** divisions, versus the **three** of `atan_dd_fast(ONE / a)`, whose
/// `DoubleDouble / f64` reciprocal alone costs two.  `1 − a·c` is exact (`a·c ≈ 1`
/// inside the cell and `from_product` is exact), so `u` is at least as accurate as
/// the original, and `|u| ≤ 1/16` exactly as in [`atan_dd_fast`].
#[inline]
fn atan_recip_fast(a: f64) -> DoubleDouble {
    let inv = 1.0 / a;

    // a > 1.1e12: atan(1/a) = 1/a to far below ½ ulp (matches `atan_dd_fast`'s guard,
    // since `(ONE / a).high == 1.0 / a`).
    if inv < 9.094947017729282e-13 {
        return DoubleDouble {
            high: inv,
            low: 0.0,
        };
    }

    let k = (inv * 8.0).round_ties_even();
    let c = k * 0.125;
    // SAFETY: inv ∈ (0, 1] puts k in 0..=8 (see `atan_dd_fast`).
    let table = ATAN_TABLE[unsafe { k.to_int_unchecked::<i64>() } as usize];

    // u = (1 − a·c)/(a + c).  `a·c ∈ (2/3, 2 + ε)` inside a cell (`k ≥ 1`; `k = 0`
    // makes the product zero), so `1 − p.high` is exact (`x − 1` is exact for any
    // `x ∈ [0.5, 4]`) — no double-double `Add` needed — and the lean quotient
    // replaces `den.recip()`'s Newton step plus a double-double multiply.
    let p = DoubleDouble::from_product(a, c);
    let num = DoubleDouble {
        high: 1.0 - p.high,
        low: -p.low,
    };
    let den = DoubleDouble::from_sum(a, c);
    let u = num.div_fast(den);

    atan_cell_fast(table, u)
}

/// Shared Ziv-gated fast-path tail of [`asin`] and [`acos`]:
/// `v = off + B(j/128 + r)·(z + zl)`, returning the rounded `f64` when the
/// gate accepts and `None` to defer to the accurate fallback.
///
/// Both functions' branches only *set up* `(off, z, zl, r, j)` — like
/// CORE-MATH's asin, the table lookup, polynomial, product, offset fold, and
/// gate are one straight-line tail, so the magnitude branch stays short and
/// the sign needs no post-hoc `copysign` (it rides in `z` and `off`).
///
/// The lead multiplies `(z, zl)` via one exact product plus fused folds, and
/// the per-cell correction `d = r·P(r)` enters pre-scaled as `P(r)·(r·z)` —
/// the polynomial is the longest dependency chain, so it lands in the *last*
/// fold instead of serializing behind a `lead.low + d` add as before.
///
/// The gate width is the correction-scaled `|z|·(C·|r| + F) + G` — see
/// [`ASIN_EPS_R`] — computed off the critical path from the early-known `z`
/// and `r`.
#[inline]
fn asin_tail(off: DoubleDouble, z: f64, zl: f64, r: f64, j: usize) -> Option<f64> {
    let cell = &ASIN_CELLS[j];
    let p = DoubleDouble::from_product(cell.lead.high, z);
    let low = crate::fma(cell.lead.high, zl, p.low);
    let low = crate::fma(cell.lead.low, z, low);
    let low = crate::fma(crate::poly(r, &cell.poly), r * z, low);
    // |off| ≥ |p| (`fold_ordering::asin_offsets`), or `off = 0` where Fast2Sum
    // is exact unconditionally.
    let v = off.add_ordered(DoubleDouble { high: p.high, low });

    let eps = crate::fast_mul_add(
        crate::fast_mul_add(ASIN_EPS_R, r.abs(), ASIN_EPS_Z),
        z.abs(),
        ASIN_EPS_ABS,
    );
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// A triple-`f64` value `high + mid + low`, used only by the rare accurate
/// fallback to round the few `f64` `asin`/`acos` arguments beyond double-double's
/// ~2⁻¹⁰⁶ reach (the worst, `acos`'s, lands ~2⁻¹¹¹ from a midpoint).  Normalized
/// forms are non-overlapping: `|mid| ≤ ½ulp(high)`, `|low| ≤ ½ulp(mid)`.
#[derive(Clone, Copy)]
struct TripleDouble {
    high: f64,
    mid: f64,
    low: f64,
}

/// 2Sum: the exact `a + b` as `(sum, error)`.
#[inline]
fn two_sum(a: f64, b: f64) -> (f64, f64) {
    let s = a + b;
    let bb = s - a;
    (s, (a - (s - bb)) + (b - bb))
}

/// Renormalize the exact sum `a + b + c` into a non-overlapping triple-double.
#[inline]
fn renorm3(a: f64, b: f64, c: f64) -> TripleDouble {
    let (s, t1) = two_sum(b, c);
    let (high, t2) = two_sum(a, s);
    let (mid, low) = two_sum(t2, t1);
    TripleDouble { high, mid, low }
}

/// Add an `f64` into a triple-double, dropping only the 4th-order residual
/// (~2⁻²¹²·|t|).
#[inline]
fn td_add_f64(t: TripleDouble, x: f64) -> TripleDouble {
    let (s0, e0) = two_sum(t.high, x);
    let (s1, e1) = two_sum(t.mid, e0);
    renorm3(s0, s1, t.low + e1)
}

/// Add two triple-doubles (fold the addend's limbs in, high-first).
#[inline]
fn td_add(a: TripleDouble, b: TripleDouble) -> TripleDouble {
    td_add_f64(td_add_f64(td_add_f64(a, b.high), b.mid), b.low)
}

/// Negate a triple-double.
#[inline]
fn td_neg(t: TripleDouble) -> TripleDouble {
    TripleDouble {
        high: -t.high,
        mid: -t.mid,
        low: -t.low,
    }
}

/// Multiply a triple-double by an exact `f64`.
#[inline]
fn td_mul_f64(t: TripleDouble, x: f64) -> TripleDouble {
    let p0 = DoubleDouble::from_product(x, t.high);
    let p1 = DoubleDouble::from_product(x, t.mid);
    let mut acc = TripleDouble {
        high: p0.high,
        mid: 0.0,
        low: 0.0,
    };
    for term in [p1.high, p0.low, p1.low, x * t.low] {
        acc = td_add_f64(acc, term);
    }
    acc
}

/// Multiply a double-double by a triple-double.
#[inline]
fn dd_mul_td(d: DoubleDouble, t: TripleDouble) -> TripleDouble {
    let q0 = DoubleDouble::from_product(d.high, t.high);
    let q1 = DoubleDouble::from_product(d.high, t.mid);
    let q2 = DoubleDouble::from_product(d.low, t.high);
    let mut acc = TripleDouble {
        high: q0.high,
        mid: 0.0,
        low: 0.0,
    };
    for term in [
        q1.high,
        q2.high,
        q0.low,
        q1.low,
        q2.low,
        d.high * t.low,
        d.low * t.mid,
    ] {
        acc = td_add_f64(acc, term);
    }
    acc
}

/// Round a normalized triple-double to the nearest `f64`.  Round-to-odd of the
/// low pair `mid + low` (so its dropped tail survives as a sticky bit) followed
/// by one `high + ·` add yields the correctly-rounded result with no
/// double-rounding.
#[inline]
fn td_round(t: TripleDouble) -> f64 {
    let (s, e) = two_sum(t.mid, t.low);
    let s = if e != 0.0 && s.to_bits() & 1 == 0 {
        let bits = s.to_bits();
        f64::from_bits(if (s >= 0.0) == (e > 0.0) {
            bits + 1
        } else {
            bits - 1
        })
    } else {
        s
    };
    t.high + s
}

/// `asin(a)` for `a ∈ [0, ½)` as a triple-double, via the direct series
/// `asin(a) = a·B(a²)`, `B(u) = Σ aₖ uᵏ`.  The accurate fallback's direct leg:
/// the slowly-decaying tail `a₉..a₆₀` runs double-double Horner, then `a₈..a₁`
/// (carried to a third limb in [`ASIN_ACC`]/[`ASIN_ACC_LO`]) finish in
/// triple-double — reaching ~2⁻¹³⁰, enough to round the hard `acos` points the
/// double-double path misses (the worst ~2⁻¹¹¹ from a midpoint).
fn asin_direct_td(a: f64) -> TripleDouble {
    let u = DoubleDouble::from_product(a, a); // exact a²

    let mut p = ASIN_ACC[59];
    let mut idx = 59;
    while idx > 8 {
        idx -= 1;
        p = p * u + ASIN_ACC[idx];
    }

    let mut t = TripleDouble {
        high: p.high,
        mid: p.low,
        low: 0.0,
    };
    for i in (0..8).rev() {
        t = dd_mul_td(u, t);
        t = td_add(
            t,
            TripleDouble {
                high: ASIN_ACC[i].high,
                mid: ASIN_ACC[i].low,
                low: ASIN_ACC_LO[i],
            },
        );
    }

    // B = 1 + u·t,  asin(a) = a·B.
    let b = td_add_f64(dd_mul_td(u, t), 1.0);
    td_mul_f64(b, a)
}

/// `asin(|x|)` for `a = |x| ∈ [0, 1]`, as a double-double in `[0, π/2]`.
///
/// `asin(a) = atan(a/√(1−a²))`; the branch keeps the `atan` argument in `[0, 1]`.
#[inline]
fn asin_pos<K: Fn(DoubleDouble) -> DoubleDouble>(a: f64, kernel: K) -> DoubleDouble {
    if a == 1.0 {
        return FRAC_PI_2;
    }

    // c = √(1 − a²) as a double-double (a² exact, so the cancellation near a = 1
    // is captured).
    let c = sqrt_dd(ONE + neg(DoubleDouble::from_product(a, a)));

    if a <= c.high {
        kernel(DoubleDouble { high: a, low: 0.0 } * c.recip())
    } else {
        // a/c > 1 ⇒ atan(a/c) = π/2 − atan(c/a)
        FRAC_PI_2 + neg(kernel(c / a))
    }
}

/// Magnitude of `atan(|x|)` in `[0, π/2]`, as a double-double, via `kernel`.
#[inline]
fn atan_mag<K: Fn(DoubleDouble) -> DoubleDouble>(a: f64, kernel: K) -> DoubleDouble {
    if a > 1.0 {
        // atan(a) = π/2 − atan(1/a)
        FRAC_PI_2 + neg(kernel(ONE / a))
    } else {
        kernel(DoubleDouble { high: a, low: 0.0 })
    }
}

/// Arctangent
#[must_use]
#[inline]
pub fn atan(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    let a = x.abs();
    if a.is_infinite() {
        return core::f64::consts::FRAC_PI_2.copysign(x);
    }

    // Fast path: for |x| > 1 reflect via atan(a) = π/2 − atan(1/a) using the
    // division-frugal [`atan_recip_fast`]; otherwise the direct cell kernel.  The
    // accurate fallback keeps the shared [`atan_mag`] reflection.
    let fast = if a > 1.0 {
        FRAC_PI_2 + neg(atan_recip_fast(a))
    } else {
        atan_dd_fast(DoubleDouble { high: a, low: 0.0 })
    };
    let magnitude = ziv(fast).unwrap_or_else(|| {
        let m = atan_mag(a, atan_dd);
        m.high + m.low
    });
    magnitude.copysign(x)
}

/// Correctly-rounded `asin(a)` for `a = |x| ∈ [0, 1]`, the accurate fallback.
///
/// Two tiers: the double-double `asin(a) = atan(a/√(1−a²))` (`asin_pos`) handles
/// the bulk of fast-leg misses cheaply, and a second Ziv gate escalates only the
/// hard-to-round direct-branch points to the slow triple-double series
/// [`asin_direct_td`].  Cold and never inlined so the rare-miss bulk stays out of
/// [`asin`]'s hot path.
#[cold]
#[inline(never)]
fn asin_accurate(a: f64) -> f64 {
    let m = asin_pos(a, atan_dd);
    ziv_at(m, ASIN_DD_ZIV_EPS).unwrap_or_else(|| {
        if a < 0.5 {
            td_round(asin_direct_td(a))
        } else {
            m.high + m.low
        }
    })
}

/// Correctly-rounded `acos(x)`, the accurate fallback.  `acos(x) = π/2 − asin(x)`:
/// `π/2 − asin(|x|)` for `x ≥ 0`, `π/2 + asin(|x|)` for `x < 0`.  Same two-tier
/// scheme as [`asin_accurate`]: a double-double result, with a second Ziv gate
/// escalating the hard-to-round direct-branch points (where the `π/2 − asin`
/// subtraction needs the extra limb) to triple-double.
#[cold]
#[inline(never)]
fn acos_accurate(x: f64) -> f64 {
    let a = x.abs();
    let s = asin_pos(a, atan_dd);
    let m = if x.is_sign_negative() {
        FRAC_PI_2 + s
    } else {
        FRAC_PI_2 + neg(s)
    };
    ziv_at(m, ASIN_DD_ZIV_EPS).unwrap_or_else(|| {
        if a < 0.5 {
            let std = asin_direct_td(a);
            let mt = if x.is_sign_negative() {
                td_add(FRAC_PI_2_TD, std)
            } else {
                td_add(FRAC_PI_2_TD, td_neg(std))
            };
            td_round(mt)
        } else {
            m.high + m.low
        }
    })
}

/// Arcsine
#[must_use]
#[inline]
pub fn asin(x: f64) -> f64 {
    let a = x.abs();

    let (off, z, zl, r, j) = if a < 0.5 {
        // For |x| < 0x1.7137449123ef6p-26, `asin(x) − x = x³/6 + …` stays below
        // half an ulp of the result, so x is the correctly-rounded answer (and
        // ±0 keeps its sign without touching the offset fold).
        if a < 2.149119332890821e-8 {
            return x;
        }
        // asin(x) = x·B(x²): the sign rides in z, no offset.
        let jf = (128.0 * (x * x)).round_ties_even();
        let r = crate::fma(x, x, -(jf * 0.0078125)); // x² − j/128, exact-product residual
        // SAFETY: x² < ¼ puts jf in 0..=32; a plain `as` cast would pay a
        // saturation cmov chain right in front of the table load.
        (ZERO, x, 0.0, r, unsafe { jf.to_int_unchecked::<i64>() }
            as usize)
    } else {
        // Route the domain edge and NaN here so the direct branch costs a
        // single compare.
        if !(a < 1.0) {
            if a == 1.0 {
                // asin(±1) = ±π/2 (and avoids √0 → 0/0 in the reflection).
                return core::f64::consts::FRAC_PI_2.copysign(x);
            }
            return f64::NAN; // |x| > 1 or NaN
        }
        // asin(x) = sign(x)·(π/2 − √t·B(u)) with t = 2 − 2|x| and u = ¼t both
        // exact (Sterbenz), so only the multiplier √t = 2s needs a low word
        // (one division), avoiding the double-double `sqrt`.  The sign rides in
        // z = −√t·sign(x) and off = ±π/2.
        let t = 2.0 * (1.0 - a);
        let z = -t.sqrt().copysign(x);
        let zl = crate::fma(z, z, -t) * ((-0.5 / t) * z);
        let u = 0.25 * t;
        let jf = (128.0 * u).round_ties_even();
        let r = u - jf * 0.0078125; // exact
        let off = DoubleDouble {
            high: FRAC_PI_2.high.copysign(x),
            low: FRAC_PI_2.low.copysign(x),
        };
        // SAFETY: u = ¼t ≤ ¼ puts jf in 0..=32 (see the direct branch).
        (off, z, zl, r, unsafe { jf.to_int_unchecked::<i64>() }
            as usize)
    };

    asin_tail(off, z, zl, r, j).unwrap_or_else(|| asin_accurate(a).copysign(x))
}

/// Arccosine
#[must_use]
#[inline]
pub fn acos(x: f64) -> f64 {
    let a = x.abs();

    let (off, z, zl, r, j) = if a < 0.5 {
        // acos(x) = π/2 + (−x)·B(x²)
        let jf = (128.0 * (x * x)).round_ties_even();
        let r = crate::fma(x, x, -(jf * 0.0078125));
        // SAFETY: x² < ¼ puts jf in 0..=32 (see `asin`).
        (
            FRAC_PI_2,
            -x,
            0.0,
            r,
            unsafe { jf.to_int_unchecked::<i64>() } as usize,
        )
    } else {
        // Route the domain edge and NaN here so the direct branch costs a
        // single compare.
        if !(a < 1.0) {
            if a == 1.0 {
                // acos(1) = 0, acos(−1) = π (and avoids √0 → 0/0 below).
                return if x.is_sign_negative() {
                    core::f64::consts::PI
                } else {
                    0.0
                };
            }
            return f64::NAN; // |x| > 1 or NaN
        }
        // acos(x) = √t·B(u) for x ≥ ½, π − √t·B(u) for x ≤ −½: the sign rides
        // in z = √t·sign(x), and the offset is the branchless (and
        // componentwise-exact) `π/2 − copysign(π/2, x)` — 0 for x > 0 and
        // π = 2·(π/2) for x < 0.  A sign branch (or a 2-entry table, which
        // LLVM lowers back to one) mispredicts on a quarter of random inputs.
        let t = 2.0 * (1.0 - a);
        let z = t.sqrt().copysign(x);
        let zl = crate::fma(z, z, -t) * ((-0.5 / t) * z);
        let u = 0.25 * t;
        let jf = (128.0 * u).round_ties_even();
        let r = u - jf * 0.0078125; // exact
        let off = DoubleDouble {
            high: FRAC_PI_2.high - FRAC_PI_2.high.copysign(x),
            low: FRAC_PI_2.low - FRAC_PI_2.low.copysign(x),
        };
        // SAFETY: u = ¼t ≤ ¼ puts jf in 0..=32 (see the direct branch).
        (off, z, zl, r, unsafe { jf.to_int_unchecked::<i64>() }
            as usize)
    };

    asin_tail(off, z, zl, r, j).unwrap_or_else(|| acos_accurate(x))
}

/// Magnitude of `atan2(y, x)` in `[0, π]` for finite nonzero `a = |x|`, `b = |y|`.
#[inline]
fn atan2_mag(a: f64, b: f64, x_negative: bool) -> f64 {
    let (big, small, swapped) = if a >= b { (a, b, false) } else { (b, a, true) };

    let theta = |cell: fn(DoubleDouble, DoubleDouble) -> DoubleDouble| {
        // φ = atan(small/big) ∈ [0, π/4], or π/2 − atan(small/big) when `swapped`.
        let q = small / big;
        let inner = if q < 9.094947017729282e-13 {
            // Tiny ratio: atan(q) = q far below ½ ulp, and the *unscaled* IEEE
            // quotient `small/big` is correctly rounded down into the subnormals.
            DoubleDouble { high: q, low: 0.0 }
        } else {
            // Scale both legs so the larger lands in [1, 2): exact and
            // ratio-preserving, keeping `small − c·big` / `big + c·small` clear of
            // overflow and the small leg out of the subnormals.
            let (_, exp) = super::frexp(big);
            let big = super::ldexp(big, 1 - exp);
            let small = super::ldexp(small, 1 - exp);

            // Cell reduction without forming small/big as a double-double: with
            // ratio = small/big, `u = (ratio − c)/(1 + ratio·c) = (small − c·big)/(big
            // + c·small)`.  `k = round(8·ratio)` reuses the `q` already in hand
            // (scaling preserves the ratio exactly), so the leg spends only that one
            // `q` division plus this `recip` — two, versus the four of the
            // `from_quotient` path (the `q` test, the two-division quotient, the cell
            // `recip`).  `small − c·big` is exact (c·big ≈ small in-cell, `from_product`
            // exact), so `u` is at least as accurate, and `|u| ≤ 1/16` as before.
            let k = (q * 8.0).round_ties_even();
            let c = k * 0.125;
            // SAFETY: q = small/big ∈ [0, 1] puts k in 0..=8 (see `atan_dd_fast`).
            let table = ATAN_TABLE[unsafe { k.to_int_unchecked::<i64>() } as usize];

            let num = DoubleDouble {
                high: small,
                low: 0.0,
            } + neg(DoubleDouble::from_product(c, big));
            let den = DoubleDouble {
                high: big,
                low: 0.0,
            } + DoubleDouble::from_product(c, small);
            let u = num * den.recip();

            cell(table, u)
        };

        let phi = if swapped {
            FRAC_PI_2 + neg(inner)
        } else {
            inner
        };
        if x_negative { PI + neg(phi) } else { phi }
    };

    ziv(theta(atan_cell_fast)).unwrap_or_else(|| {
        let m = theta(atan_cell);
        m.high + m.low
    })
}

/// Arctangent of `y / x`, using the signs of both to select the quadrant
///
/// The result is the angle in `(-π, π]` between the positive `x`-axis and the
/// point `(x, y)`, carrying the sign of `y`.
#[must_use]
#[inline]
pub fn atan2(y: f64, x: f64) -> f64 {
    use core::f64::consts::{FRAC_PI_2, FRAC_PI_4, PI};

    /// Correctly-rounded `f64` of 3π/4.
    const THREE_PI_4: f64 = 2.356194490192345;

    if x.is_nan() || y.is_nan() {
        return f64::NAN;
    }

    if x.is_infinite() || y.is_infinite() {
        let magnitude = match (x.is_infinite(), y.is_infinite()) {
            (true, true) if x.is_sign_positive() => FRAC_PI_4,
            (true, true) => THREE_PI_4,
            (true, false) if x.is_sign_positive() => 0.0,
            (true, false) => PI,
            (false, true) => FRAC_PI_2,
            (false, false) => unreachable!(),
        };
        return magnitude.copysign(y);
    }

    if y == 0.0 {
        return if x.is_sign_positive() { 0.0 } else { PI }.copysign(y);
    }
    if x == 0.0 {
        return FRAC_PI_2.copysign(y);
    }

    atan2_mag(x.abs(), y.abs(), x.is_sign_negative()).copysign(y)
}

/// The Fast2Sum-based folds of [`atan_cell_fast`] need `|a| ≥ |b|`; prove the
/// orderings from coefficient-magnitude bounds at the cell edge `|u| ≤ 1/16`
/// (cf. the same-named modules in `erf.rs` and `trig.rs`).
#[cfg(test)]
mod fold_ordering {
    use super::*;

    #[test]
    fn atan_cell() {
        // Slack for the rounding of u (one lean division) and w = u·u.
        let umax = 0.0625 * 1.0001;
        let wmax = umax * umax;
        let tail_mag = ATAN_TAIL
            .iter()
            .rev()
            .fold(0.0, |acc, c| crate::fast_mul_add(acc, wmax, c.abs()));

        // bracket = 1 ⊕ w·(−1/3) ⊕ w²·tail
        let c1_mag = ATAN_COEFFS[1].high.abs() + ATAN_COEFFS[1].low.abs();
        assert!(wmax * c1_mag <= 0.5);
        let lead_min = 1.0 - wmax * c1_mag;
        assert!(wmax * wmax * tail_mag <= 0.5 * lead_min);

        // table ⊕ u·bracket for k ≥ 1 (k = 0 has table = 0, where Fast2Sum is
        // exact by itself); the k = 1 cell is the tightest at 0.504.
        let bracket_mag = crate::fast_mul_add(wmax * wmax, tail_mag, 1.0 + wmax * c1_mag);
        for cell in &ATAN_TABLE[1..] {
            assert!(umax * bracket_mag <= 0.55 * cell.high.abs());
        }
    }

    /// [`asin_tail`]'s `off ⊕ p` fold: `|off| ≥ |p.high|` for every nonzero
    /// offset (`off = 0`, asin's direct branch, is exact unconditionally).
    /// `|p.high| ≤ Bmax·|z|·(1 + ε)` with `Bmax = B(¼)` the largest table lead;
    /// `|z| ≤ 1` in the reflections (`√t ≤ 1`) and `|z| ≤ ½` in acos's direct
    /// branch.
    #[test]
    fn asin_offsets() {
        let bmax = ASIN_CELLS
            .iter()
            .map(|cell| cell.lead.high)
            .fold(0.0, f64::max)
            * 1.0001;

        // Reflections: off = ±π/2 (asin) or π (acos, x < −½) vs |p| ≤ Bmax.
        assert!(bmax <= 0.7 * FRAC_PI_2.high);
        assert!(bmax <= 0.35 * PI.high);
        // acos direct: off = π/2 vs |p| ≤ Bmax/2.
        assert!(0.5 * bmax <= 0.35 * FRAC_PI_2.high);
    }
}
