//! Inverse trigonometric functions: `asin`, `acos`, `atan`, `atan2`.
//!
//! `atan`/`atan2` use one double-double `atan` kernel: `atan_dd` reduces
//! `q ∈ [0, 1]` into a width-1/8 cell (`ATAN_TABLE` holds `atan(k/8)`) and
//! evaluates the odd series on `|u| ≤ 1/16`.  `asin`/`acos` share the
//! table-driven [`asin_tail`] fast path, which tabulates `asin(t)/t` on a grid
//! `u = t² = j/128` plus a per-cell `f64` correction in `r = u − j/128`, one
//! cache line per cell ([`ASIN_CELLS`]); the reflection `s = √((1−|x|)/2)` for
//! `|x| ≥ ½` keeps `u ≤ ¼`, and there `u` is exact so only the multiplier
//! `√t = 2s` carries a low word (no double-double `sqrt`).  Both fall back, via
//! a correction-scaled Ziv gate ([`ASIN_EPS_R`]), to the accurate
//! `asin(x) = atan(x/√(1−x²))` (`asin_pos`).
//!
//! Constants below were generated by `tools/gen_atan_f64.py` and
//! `tools/gen_inv_f64.py`.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::dint::Dint;
use super::double::{DoubleDouble, sqrt_dd};
use super::pow::poly_dd;

/// `(-1)ᵏ/(2k+1)` as a double-double, low-degree first in `u²` — the atan series.
const ATAN_COEFFS: [DoubleDouble; 16] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: -0.3333333333333333,
        low: -1.850371707708594e-17,
    },
    DoubleDouble {
        high: 0.2,
        low: -1.1102230246251566e-17,
    },
    DoubleDouble {
        high: -0.14285714285714285,
        low: -7.93016446160826e-18,
    },
    DoubleDouble {
        high: 0.1111111111111111,
        low: 6.1679056923619804e-18,
    },
    DoubleDouble {
        high: -0.09090909090909091,
        low: 2.523234146875356e-18,
    },
    DoubleDouble {
        high: 0.07692307692307693,
        low: -4.270088556250602e-18,
    },
    DoubleDouble {
        high: -0.06666666666666667,
        low: -9.251858538542971e-19,
    },
    DoubleDouble {
        high: 0.058823529411764705,
        low: 8.163404592832033e-19,
    },
    DoubleDouble {
        high: -0.05263157894736842,
        low: -2.921639538487254e-18,
    },
    DoubleDouble {
        high: 0.047619047619047616,
        low: 2.64338815386942e-18,
    },
    DoubleDouble {
        high: -0.043478260869565216,
        low: -1.206764157201257e-18,
    },
    DoubleDouble {
        high: 0.04,
        low: -8.326672684688674e-19,
    },
    DoubleDouble {
        high: -0.037037037037037035,
        low: -2.05596856412066e-18,
    },
    DoubleDouble {
        high: 0.034482758620689655,
        low: 4.785444071660157e-19,
    },
    DoubleDouble {
        high: -0.03225806451612903,
        low: -8.953411488912552e-19,
    },
];

/// Fast-path tail of the atan series in `w = u²`: `w²·(1/5 − w/7 + w²/9 − …)`,
/// the remainder after the two leading terms `1 − w/3` are peeled into
/// double-double.  Evaluated in plain `f64`; `|u| ≤ 1/16` so `w ≤ 2⁻⁸` and the
/// 8 terms reach below 2⁻⁶⁴ relative to `atan(u)`.  See [`atan_dd_fast`].
const ATAN_TAIL: [f64; 8] = [
    0.2,
    -0.14285714285714285,
    0.1111111111111111,
    -0.09090909090909091,
    0.07692307692307693,
    -0.06666666666666667,
    0.058823529411764705,
    -0.05263157894736842,
];

/// One cache line of the table-driven `asin`/`acos` fast path: `B(u_j)` as a
/// double-double lead plus six per-cell correction coefficients — exactly 64
/// bytes, so a lookup touches a single line (the former split
/// `ASIN_LEAD`/`ASIN_POLY` arrays spread one lookup over two arrays and up to
/// three lines).
///
/// `B(u_j) = asin(t)/t` at the grid points `u_j = t² = j/128` (`j = 0..=32`,
/// covering `u ∈ [0, ¼]`); `poly` is a Chebyshev interpolant of
/// `(B(u_j + r) − B(u_j))/r` over the cell `|r| ≤ 2⁻⁸` (half-cells at the
/// edges `j = 0` and `j = 32`), low-degree first.  Near-minimax fitting pushes
/// the cell-edge truncation (the dominant term of a Taylor expansion, ~2⁻⁵²
/// per unit `r` at degree 5) below the `f64` evaluation rounding (sup error
/// ~2⁻⁵⁵ per unit `r`), which is what lets the Ziv gate scale purely with the
/// correction term — see [`ASIN_EPS_R`].  Generated by `tools/gen_inv_f64.py`.
#[repr(C, align(64))]
struct AsinCell {
    /// `B(u_j)` to ~2⁻¹⁰⁶.
    lead: DoubleDouble,
    /// Per-cell Chebyshev correction `P(r) ≈ (B(u_j + r) − B(u_j))/r`.
    poly: [f64; 6],
}

#[rustfmt::skip]
const ASIN_CELLS: [AsinCell; 33] = [
    AsinCell { lead: DoubleDouble { high: 1.0, low: 0.0 }, poly: [0.16666666666666666, 0.07500000000000046, 0.04464285714151091, 0.030381945914185627, 0.022371434124784886, 0.017517411402689965] },
    AsinCell { lead: DoubleDouble { high: 1.001306682371262, low: -1.0272312753221834e-16 }, poly: [0.16784677438667686, 0.07605755082168192, 0.04560611511575869, 0.03127197994968885, 0.023204118969829043, 0.018136886974879876] },
    AsinCell { lead: DoubleDouble { high: 1.0026226493445232, low: 1.0324808391048493e-17 }, poly: [0.16904358442931514, 0.07713800795263456, 0.04659770185606869, 0.032195230970348244, 0.024073475656062455, 0.018962670853765858] },
    AsinCell { lead: DoubleDouble { high: 1.0039480328184027, low: -4.880658832674078e-17 }, poly: [0.17025745995687916, 0.07824204769439794, 0.04761867877230672, 0.033153209924799525, 0.024982574268493204, 0.019832978331821027] },
    AsinCell { lead: DoubleDouble { high: 1.0052829675705146, low: -5.363981194877168e-17 }, poly: [0.1714887748961512, 0.07937037178898687, 0.04867015579935748, 0.03414751078380546, 0.025933566312932588, 0.02075059068542687] },
    AsinCell { lead: DoubleDouble { high: 1.0066275913431422, low: 2.5043560802184795e-18 }, poly: [0.17273791434494837, 0.08052370858666094, 0.04975329402380281, 0.0351798141637133, 0.02692873824968861, 0.021718487159338145] },
    AsinCell { lead: DoubleDouble { high: 1.0079820449321606, low: -5.1752227787916015e-17 }, poly: [0.17400527499741064, 0.08170281427717768, 0.05086930847588672, 0.03625189278383774, 0.0279705211396371, 0.02273986081407639] },
    AsinCell { lead: DoubleDouble { high: 1.009346472279358, low: -7.629540267778587e-17 }, poly: [0.17529126558904862, 0.08290847418852788, 0.05201947109806524, 0.03736561731555017, 0.029061501065725356, 0.023818135785031936] },
    AsinCell { lead: DoubleDouble { high: 1.0107210205683146, low: 2.633607878967623e-17 }, poly: [0.17659630736263912, 0.08414150415743896, 0.05320511390286878, 0.03852296265469621, 0.030204430399280086, 0.024956986092009286] },
    AsinCell { lead: DoubleDouble { high: 1.012105840324008, low: -7.582727232984953e-17 }, poly: [0.1779208345561254, 0.08540275197624249, 0.05442763233383695, 0.03972601465180409, 0.031402239987338244, 0.026160356152882907] },
    AsinCell { lead: DoubleDouble { high: 1.0135010855163171, low: -8.705804407322068e-17 }, poly: [0.17926529491375298, 0.08669309892103776, 0.05568848884441042, 0.0409769773376698, 0.032658052344806544, 0.027432483171712114] },
    AsinCell { lead: DoubleDouble { high: 1.0149069136676179, low: -5.584635415072094e-17 }, poly: [0.18063015022175236, 0.08801346136644564, 0.05698921671089193, 0.042278180685338985, 0.03397519594366968, 0.028777921590316696] },
    AsinCell { lead: DoubleDouble { high: 1.016323485964662, low: -4.943036930497581e-17 }, poly: [0.1820158768699657, 0.08936479249264098, 0.058331424096928576, 0.04363208895328746, 0.03535722070080701, 0.03020156981319128] },
    AsinCell { lead: DoubleDouble { high: 1.01775096737495, low: 7.704611664224385e-17 }, poly: [0.1834229664409061, 0.09074808409077688, 0.05971679838843155, 0.04504130965876766, 0.036807914776353715, 0.03170869943902355] },
    AsinCell { lead: DoubleDouble { high: 1.0191895267678206, low: -1.0613869097246791e-16 }, poly: [0.18485192632783798, 0.09216436847337664, 0.06114711081945033, 0.04650860323488207, 0.038331322806079496, 0.033304987258306024] },
    AsinCell { lead: DoubleDouble { high: 1.020639337040483, low: 5.046596408196905e-17 }, poly: [0.18630328038357294, 0.09361472049676992, 0.06262422141127005, 0.0480368934300134, 0.03993176570409889, 0.03499655030596615] },
    AsinCell { lead: DoubleDouble { high: 1.0221005752492498, low: -2.632985627554085e-17 }, poly: [0.18777756960179107, 0.09510025970319365, 0.06415008424891891, 0.04962927851384004, 0.0416138621865306, 0.036789984291010665] },
    AsinCell { lead: DoubleDouble { high: 1.023573422746221, low: 4.986625487259925e-17 }, poly: [0.1892753528328202, 0.09662215259076994, 0.06572675312137483, 0.05128904336035387, 0.04338255218267208, 0.03869240576237429] },
    AsinCell { lead: DoubleDouble { high: 1.0250580653217043, low: -7.113659424223031e-17 }, poly: [0.19079720753593998, 0.09818161502021494, 0.06735638755406599, 0.05301967248514469, 0.045243122318055086, 0.040711498412036265] },
    AsinCell { lead: DoubleDouble { high: 1.0265546933526606, low: -4.741503323356409e-17 }, poly: [0.19234373057042067, 0.09977991476783331, 0.06904125926479136, 0.05482486412179762, 0.04720123367363216, 0.04285556396365951] },
    AsinCell { lead: DoubleDouble { high: 1.0280635019574904, low: -6.544150189403774e-17 }, poly: [0.19391553902766198, 0.10141837423511325, 0.0707837590769671, 0.056708545430653734, 0.049262952047579446, 0.0451335781482472] },
    AsinCell { lead: DoubleDouble { high: 1.0295846911574884, low: -1.8862205210991434e-17 }, poly: [0.19551327110696473, 0.10309837332606799, 0.07258640432716265, 0.058674888942507095, 0.05143478097108996, 0.04755525232844154] },
    AsinCell { lead: DoubleDouble { high: 1.03111846604532, low: 1.0973504492523829e-16 }, poly: [0.19713758703764944, 0.10482135250437412, 0.07445184680725425, 0.060728330350163985, 0.053723697757419274, 0.05013110140107482] },
    AsinCell { lead: DoubleDouble { high: 1.032665036960893, low: 5.777325521136841e-17 }, poly: [0.19878917005043126, 0.10658881604334543, 0.07638288128522912, 0.06287358777229668, 0.056137192894725796, 0.052872518684536324] },
    AsinCell { lead: DoubleDouble { high: 1.034224619675018, low: 2.3661883234451118e-17 }, poly: [0.20046872740117394, 0.10840233548285978, 0.07838245465275882, 0.06511568262682592, 0.05868331312836987, 0.05579185858472258] },
    AsinCell { lead: DoubleDouble { high: 1.0357974355812862, low: -6.5788579651732e-17 }, poly: [0.20217699145037335, 0.11026355330853636, 0.08045367575216739, 0.06745996226532305, 0.06137070861781541, 0.05890252793227309] },
    AsinCell { lead: DoubleDouble { high: 1.0373837118966067, low: -6.207970775472474e-18 }, poly: [0.203914720801972, 0.11217418686975164, 0.08259982594039775, 0.06991212453581647, 0.06420868459770185, 0.06221908699616942] },
    AsinCell { lead: DoubleDouble { high: 1.038983681870887, low: 2.310007649575221e-17 }, poly: [0.20568270150537452, 0.11413603255449548, 0.08482437045308279, 0.07247824445912224, 0.06720725802269994, 0.06575736130657349] },
    AsinCell { lead: DoubleDouble { high: 1.0405975850063638, low: 4.0405187993459635e-17 }, poly: [0.2074817483248279, 0.11615097024061824, 0.08713097063791647, 0.07516480322363228, 0.07037721973220704, 0.0695345655652949] },
    AsinCell { lead: DoubleDouble { high: 1.042225667287128, low: 1.0289845986206202e-16 }, poly: [0.20931270608064942, 0.11822096804471928, 0.08952349713326367, 0.07797871972564913, 0.07373020273466649, 0.07356944108817176] },
    AsinCell { lead: DoubleDouble { high: 1.0438681814194257, low: 2.7122202983822705e-17 }, poly: [0.21117645106712984, 0.12034808739179291, 0.09200604407542505, 0.080927384907161, 0.0772787572833403, 0.07788240841302087] },
    AsinCell { lead: DoubleDouble { high: 1.0455253870833516, low: -7.452575137576243e-17 }, poly: [0.21307389255231882, 0.12253448843079867, 0.0945829444262702, 0.08401869917075003, 0.08103643349690327, 0.08249573692326397] },
    AsinCell { lead: DoubleDouble { high: 1.0471975511965979, low: -1.072081766451091e-16 }, poly: [0.21500597436530758, 0.12478243582357537, 0.09725878652559589, 0.08726110356652733, 0.08501097416198228, 0.08634539670964886] },
];

/// Coefficients `a_1..a_60` of `B(u) = asin(t)/t = Σ aₖ uᵏ` (`u = t²`) as
/// double-doubles, low-degree first — the triple-double accurate series for the
/// `|x| < ½` fallback ([`asin_direct_td`]).  A handful of `f64` acos arguments are
/// hard to round beyond double-double's ~2⁻¹⁰⁶ reach (the worst, `acos`'s, lands
/// ~2⁻¹¹¹ from a midpoint); this series resolves them in triple-double.  The 60
/// terms carry the slowly-decaying tail (`aₖ ~ 4⁻ᵏ/k^{3/2}`) below 2⁻¹³⁰ at
/// `u = ¼`.  Generated by `tools/gen_inv_f64.py`.
#[rustfmt::skip]
const ASIN_ACC: [DoubleDouble; 60] = [
    DoubleDouble { high: 0.16666666666666666, low: 9.25185853854297e-18 },
    DoubleDouble { high: 0.075, low: 2.7755575615628915e-18 },
    DoubleDouble { high: 0.044642857142857144, low: -9.912705577010326e-19 },
    DoubleDouble { high: 0.030381944444444444, low: 3.854941057726238e-19 },
    DoubleDouble { high: 0.022372159090909092, low: -9.462128050782583e-19 },
    DoubleDouble { high: 0.017352764423076924, low: -8.006416042969879e-19 },
    DoubleDouble { high: 0.01396484375, low: -6.938893903907229e-19 },
    DoubleDouble { high: 0.011551800896139705, low: 8.163404592832033e-19 },
    DoubleDouble { high: 0.009761609529194078, low: 5.478074134663601e-19 },
    DoubleDouble { high: 0.008390335809616815, low: 4.130293990420969e-19 },
    DoubleDouble { high: 0.0073125258735988454, low: -3.394024192128536e-19 },
    DoubleDouble { high: 0.006447210311889649, low: -3.1225022567582527e-19 },
    DoubleDouble { high: 0.005740037670841924, low: -1.2849803525754126e-19 },
    DoubleDouble { high: 0.005153309682319905, low: -3.888173308223878e-19 },
    DoubleDouble { high: 0.004660143486915096, low: -2.7979410902851727e-20 },
    DoubleDouble { high: 0.004240907093679363, low: -1.5770213417970974e-19 },
    DoubleDouble { high: 0.003880964558837669, low: 1.858632295689436e-19 },
    DoubleDouble { high: 0.0035692053938259347, low: -1.992587776459846e-19 },
    DoubleDouble { high: 0.003297059503473485, low: -1.3344026738283132e-19 },
    DoubleDouble { high: 0.0030578216492580306, low: 2.1155164341180575e-20 },
    DoubleDouble { high: 0.002846178401108942, low: 1.1094161764967953e-19 },
    DoubleDouble { high: 0.00265787063820729, low: -1.4456028966473392e-19 },
    DoubleDouble { high: 0.0024894486782468836, low: -8.304527278612374e-20 },
    DoubleDouble { high: 0.002338091892111975, low: 1.4161007967157608e-19 },
    DoubleDouble { high: 0.0022014739737101384, low: -1.5306383611560064e-19 },
    DoubleDouble { high: 0.0020776610325181676, low: -1.4728784229991757e-19 },
    DoubleDouble { high: 0.0019650336162772837, low: -7.096596038086938e-20 },
    DoubleDouble { high: 0.0018622264064031275, low: -5.325905408700723e-20 },
    DoubleDouble { high: 0.0017680811205154183, low: -5.880418562633244e-20 },
    DoubleDouble { high: 0.0016816093935831068, low: 1.4219044885055797e-20 },
    DoubleDouble { high: 0.001601963275351444, low: 4.818676322157797e-20 },
    DoubleDouble { high: 0.0015284115961225677, low: -3.8364076872564005e-20 },
    DoubleDouble { high: 0.0014603208940791154, low: -1.375480368078625e-20 },
    DoubleDouble { high: 0.0013971399176302534, low: 1.11955659115351e-20 },
    DoubleDouble { high: 0.0013383869512751784, low: -5.506907161304015e-20 },
    DoubleDouble { high: 0.0012836393876290285, low: 3.621355929288591e-20 },
    DoubleDouble { high: 0.001232525098500017, low: -9.357455312634007e-20 },
    DoubleDouble { high: 0.0011847152561624392, low: 8.758128167121453e-20 },
    DoubleDouble { high: 0.0011399183307022236, low: 8.194708704184068e-20 },
    DoubleDouble { high: 0.0010978750465914472, low: 4.854022464579631e-20 },
    DoubleDouble { high: 0.0010583541258722428, low: 9.018646571938304e-20 },
    DoubleDouble { high: 0.0010211486797106276, low: 8.391832465295875e-20 },
    DoubleDouble { high: 0.0009860731369833312, low: 7.622485745671054e-20 },
    DoubleDouble { high: 0.0009529606197429564, low: 3.077887041034637e-20 },
    DoubleDouble { high: 0.0009216606921836334, low: 5.241836681717014e-20 },
    DoubleDouble { high: 0.0008920374230917097, low: 5.279707379901296e-21 },
    DoubleDouble { high: 0.0008639677124658675, low: 1.7643208659492762e-20 },
    DoubleDouble { high: 0.0008373398416027121, low: -3.173157570752775e-20 },
    DoubleDouble { high: 0.0008120522129086701, low: 8.562849812695216e-21 },
    DoubleDouble { high: 0.0007880122513582056, low: -1.684626855858876e-21 },
    DoubleDouble { high: 0.000765135444137165, low: -4.6754051814894244e-20 },
    DoubleDouble { high: 0.0007433444987958959, low: -5.055558498367341e-20 },
    DoubleDouble { high: 0.0007225686033525614, low: 3.139349372897533e-20 },
    DoubleDouble { high: 0.0007027427743614913, low: 5.3529510038453024e-20 },
    DoubleDouble { high: 0.0006838072810965503, low: -5.683687522703426e-21 },
    DoubleDouble { high: 0.0006657071357767537, low: 2.050097394525252e-20 },
    DoubleDouble { high: 0.000648391641245871, low: 3.25712698240824e-20 },
    DoubleDouble { high: 0.0006318139887619101, low: 3.103551903224413e-20 },
    DoubleDouble { high: 0.0006159308995984751, low: -2.234879077638401e-20 },
    DoubleDouble { high: 0.0006007023050422869, low: -2.730684204640525e-20 },
];

/// Third limbs of `a_1..a_8` — the `ASIN_ACC` coefficients whose double-double
/// rounding would otherwise cap the assembled series above 2⁻¹³⁰ at `u = ¼`, so
/// they are carried as triple-doubles `ASIN_ACC[k].high + .low + ASIN_ACC_LO[k]`.
const ASIN_ACC_LO: [f64; 8] = [
    5.135813185032629e-34,
    -1.5407439555097888e-34,
    -5.502656983963531e-35,
    2.139922160430262e-35,
    -7.003381615953585e-35,
    4.4444537178166984e-35,
    3.851859888774472e-35,
    1.1328999672866093e-35,
];

/// π/2 as a triple-double, for the `acos` accurate combine `π/2 − asin`.
const FRAC_PI_2_TD: TripleDouble = TripleDouble {
    high: 1.5707963267948966,
    mid: 6.123233995736766e-17,
    low: -1.4973849048591698e-33,
};

/// `atan(k/8)` as a double-double for `k` in `0..=8`.
const ATAN_TABLE: [DoubleDouble; 9] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.12435499454676144,
        low: -3.1253241424539383e-18,
    },
    DoubleDouble {
        high: 0.24497866312686414,
        low: 1.0698755618734451e-17,
    },
    DoubleDouble {
        high: 0.35877067027057225,
        low: -2.4623815582638635e-17,
    },
    DoubleDouble {
        high: 0.4636476090008061,
        low: 2.2698777452961687e-17,
    },
    DoubleDouble {
        high: 0.5585993153435624,
        low: -5.4556305485916264e-18,
    },
    DoubleDouble {
        high: 0.6435011087932844,
        low: 1.5834785051444286e-17,
    },
    DoubleDouble {
        high: 0.7188299996216245,
        low: -2.1478388444456983e-17,
    },
    DoubleDouble {
        high: 0.7853981633974483,
        low: 3.061616997868383e-17,
    },
];

/// π/2 as a double-double.
const FRAC_PI_2: DoubleDouble = DoubleDouble {
    high: 1.5707963267948966,
    low: 6.123233995736766e-17,
};

/// π as a double-double.
const PI: DoubleDouble = DoubleDouble {
    high: 3.141592653589793,
    low: 1.2246467991473532e-16,
};

/// One as a double-double.
const ONE: DoubleDouble = DoubleDouble {
    high: 1.0,
    low: 0.0,
};

/// Zero as a double-double.
const ZERO: DoubleDouble = DoubleDouble {
    high: 0.0,
    low: 0.0,
};

/// Relative half-width of the `atan`/`atan2` fast-path Ziv gate.  Over a dense
/// sweep of the active band the fast kernel's relative error peaks well below
/// 2⁻⁶⁸; the gate at 2⁻⁶³ keeps a comfortable margin and defers the rest to the
/// double-double kernel, which stays the correctly-rounded reference.
const ATAN_ZIV_EPS: f64 = 1.0842021724855044e-19; // 2⁻⁶³

/// The `asin`/`acos` fast-path Ziv gate is *correction-scaled* rather than a
/// fixed relative width: `eps = |z|·(C·|r| + F) + G`, where `z` is the kernel
/// multiplier (the argument, or the reflection's `√t`) and `r` the in-cell
/// offset.  Every error source of [`asin_tail`] is proportional to the
/// correction `z·r` (polynomial evaluation rounding, fit truncation) or to `z`
/// alone (table-lead rounding, the `√t` low word, product cross terms), plus
/// the absolute offset-fold rounding of `acos`'s π/2 and π folds — so the gate
/// tracks the true error profile and defers ~0.5% to the accurate fallback,
/// versus ~2% for the old fixed `2⁻⁵⁹` relative gate.
///
/// Constants calibrated by `tools/gen_inv_f64.py`, which simulates the exact
/// `f64` operation sequence of [`asin_tail`] over dense sweeps of all five
/// branch/offset cases (worst requirement C ≥ 2⁻⁵³·¹, F ≥ 2⁻⁷⁸·⁷, G ≥ 2⁻¹⁰⁵·³;
/// a denser 3.6-million-point sweep peaks at C ≥ 2⁻⁵²·⁹⁶, leaving a 3.9×
/// margin).
const ASIN_EPS_R: f64 = 4.440892098500626e-16; // C = 2⁻⁵¹
/// Per-`z` floor of the `asin`/`acos` gate; see [`ASIN_EPS_R`].
const ASIN_EPS_Z: f64 = 1.3234889800848443e-23; // F = 2⁻⁷⁶
/// Absolute floor of the `asin`/`acos` gate; see [`ASIN_EPS_R`].
const ASIN_EPS_ABS: f64 = 7.888609052210118e-31; // G = 2⁻¹⁰⁰

/// Relative half-width of the *second-tier* Ziv gate on the double-double accurate
/// fallback.  That fallback (`asin_pos`∘`atan_dd`) is ~2⁻⁹⁸ accurate — correctly
/// rounded everywhere except a handful of hard-to-round points (~2⁻¹¹¹ from a
/// midpoint).  This gate at 2⁻⁹⁰ (well above the dd error) passes the
/// double-double result directly for all but those points, which alone escalate
/// to the slow triple-double [`asin_direct_td`] — so the ~770 ns triple-double
/// path runs ~2⁻³⁷ of the time, not on every fast-leg miss.
const ASIN_DD_ZIV_EPS: f64 = 8.077935669463161e-28; // 2⁻⁹⁰

/// Negate a double-double.
#[inline]
fn neg(v: DoubleDouble) -> DoubleDouble {
    DoubleDouble {
        high: -v.high,
        low: -v.low,
    }
}

/// Ziv gate: round `v` to `f64` when both ends of its `±eps_rel·|v|` (relative)
/// error interval agree, else `None` to fall back to the accurate kernel.
#[inline]
fn ziv_at(v: DoubleDouble, eps_rel: f64) -> Option<f64> {
    let eps = v.high.abs() * eps_rel;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// [`ziv_at`] at the `atan`/`atan2` gate width.
#[inline]
fn ziv(v: DoubleDouble) -> Option<f64> {
    ziv_at(v, ATAN_ZIV_EPS)
}

/// Arctangent of a double-double `q ∈ [0, 1]`, as a double-double.
#[inline]
fn atan_dd(q: DoubleDouble) -> DoubleDouble {
    // For `q < 2⁻⁴⁰`, `atan(q) = q − q³/3 + …` agrees with `q` far below ½ ulp, so
    // the correctly-rounded `q.high` is the answer; dropping the low word also
    // protects against a `from_quotient` residual that underflowed to subnormal.
    if q.high < 9.094947017729282e-13 {
        return DoubleDouble {
            high: q.high,
            low: 0.0,
        };
    }

    let k = (q.high * 8.0).round_ties_even();
    let c = k * 0.125;
    let table = ATAN_TABLE[k as usize];

    // u = (q − c) / (1 + q·c), |u| ≤ 1/16 (c is an exact power-of-two multiple).
    let denom = q * c
        + DoubleDouble {
            high: 1.0,
            low: 0.0,
        };
    let u = (q + DoubleDouble { high: -c, low: 0.0 }) * denom.recip();

    atan_cell(table, u)
}

/// Accurate counterpart of [`atan_cell_fast`]: finish from a reduced cell via the
/// full double-double series `atan(k/8 + …) = table + u·Σ(−1)ᵏu²ᵏ/(2k+1)`.
///
/// `table = atan(k/8)` and `|u| ≤ 1/16`.  Shared by [`atan_dd`] and the fused
/// `atan2` reduction, which differ only in how they form `u`.
#[inline]
fn atan_cell(table: DoubleDouble, u: DoubleDouble) -> DoubleDouble {
    table + u * poly_dd(u * u, &ATAN_COEFFS)
}

/// Finish a reduced cell in double-double: `atan(k/8 + …) = table + u·(1 − u²/3 + …)`.
///
/// `table = atan(k/8)` and `u` is the cell-reduced argument (`|u| ≤ 1/16`).  The
/// `atan2` fast path's only cell finisher (the standalone `atan` fast path lives
/// in [`atan_fast`], a separate CORE-MATH-style fine-table kernel).
#[inline]
fn atan_cell_fast(table: DoubleDouble, u: DoubleDouble) -> DoubleDouble {
    let w = u * u;
    let wh = w.high;
    let w2 = wh * wh;
    // 1 − w/3 in double-double (ATAN_COEFFS[1] = −1/3); tail w²·(1/5 − w/7 + …).
    // Ordered Fast2Sum folds: `|w| ≤ 2⁻⁸` keeps every addend far under its lead,
    // and the final `table ⊕ u·bracket` orders for `k ≥ 1` (`atan(1/8) ≥ 2·…`,
    // see `fold_ordering`) while `k = 0` makes `table` zero, where Fast2Sum is
    // exact regardless.
    let bracket = ONE
        .add_ordered(w * ATAN_COEFFS[1])
        .add_ordered(DoubleDouble {
            high: w2 * crate::poly(wh, &ATAN_TAIL),
            low: 0.0,
        });
    table.add_ordered(u * bracket)
}

/// Shared Ziv-gated fast-path tail of [`asin`] and [`acos`]:
/// `v = off + B(j/128 + r)·(z + zl)`, returning the rounded `f64` when the
/// gate accepts and `None` to defer to the accurate fallback.
///
/// Both functions' branches only *set up* `(off, z, zl, r, j)` — like
/// CORE-MATH's asin, the table lookup, polynomial, product, offset fold, and
/// gate are one straight-line tail, so the magnitude branch stays short and
/// the sign needs no post-hoc `copysign` (it rides in `z` and `off`).
///
/// The lead multiplies `(z, zl)` via one exact product plus fused folds, and
/// the per-cell correction `d = r·P(r)` enters pre-scaled as `P(r)·(r·z)` —
/// the polynomial is the longest dependency chain, so it lands in the *last*
/// fold instead of serializing behind a `lead.low + d` add as before.
///
/// The gate width is the correction-scaled `|z|·(C·|r| + F) + G` — see
/// [`ASIN_EPS_R`] — computed off the critical path from the early-known `z`
/// and `r`.
#[inline]
fn asin_tail(off: DoubleDouble, z: f64, zl: f64, r: f64, j: usize) -> Option<f64> {
    let cell = &ASIN_CELLS[j];
    let p = DoubleDouble::from_product(cell.lead.high, z);
    let low = crate::fma(cell.lead.high, zl, p.low);
    let low = crate::fma(cell.lead.low, z, low);
    let low = crate::fma(crate::poly(r, &cell.poly), r * z, low);
    // |off| ≥ |p| (`fold_ordering::asin_offsets`), or `off = 0` where Fast2Sum
    // is exact unconditionally.
    let v = off.add_ordered(DoubleDouble { high: p.high, low });

    let eps = crate::fast_mul_add(
        crate::fast_mul_add(ASIN_EPS_R, r.abs(), ASIN_EPS_Z),
        z.abs(),
        ASIN_EPS_ABS,
    );
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// A triple-`f64` value `high + mid + low`, used only by the rare accurate
/// fallback to round the few `f64` `asin`/`acos` arguments beyond double-double's
/// ~2⁻¹⁰⁶ reach (the worst, `acos`'s, lands ~2⁻¹¹¹ from a midpoint).  Normalized
/// forms are non-overlapping: `|mid| ≤ ½ulp(high)`, `|low| ≤ ½ulp(mid)`.
#[derive(Clone, Copy)]
struct TripleDouble {
    high: f64,
    mid: f64,
    low: f64,
}

/// 2Sum: the exact `a + b` as `(sum, error)`.
#[inline]
fn two_sum(a: f64, b: f64) -> (f64, f64) {
    let s = a + b;
    let bb = s - a;
    (s, (a - (s - bb)) + (b - bb))
}

/// Renormalize the exact sum `a + b + c` into a non-overlapping triple-double.
#[inline]
fn renorm3(a: f64, b: f64, c: f64) -> TripleDouble {
    let (s, t1) = two_sum(b, c);
    let (high, t2) = two_sum(a, s);
    let (mid, low) = two_sum(t2, t1);
    TripleDouble { high, mid, low }
}

/// Add an `f64` into a triple-double, dropping only the 4th-order residual
/// (~2⁻²¹²·|t|).
#[inline]
fn td_add_f64(t: TripleDouble, x: f64) -> TripleDouble {
    let (s0, e0) = two_sum(t.high, x);
    let (s1, e1) = two_sum(t.mid, e0);
    renorm3(s0, s1, t.low + e1)
}

/// Add two triple-doubles (fold the addend's limbs in, high-first).
#[inline]
fn td_add(a: TripleDouble, b: TripleDouble) -> TripleDouble {
    td_add_f64(td_add_f64(td_add_f64(a, b.high), b.mid), b.low)
}

/// Negate a triple-double.
#[inline]
fn td_neg(t: TripleDouble) -> TripleDouble {
    TripleDouble {
        high: -t.high,
        mid: -t.mid,
        low: -t.low,
    }
}

/// Multiply a triple-double by an exact `f64`.
#[inline]
fn td_mul_f64(t: TripleDouble, x: f64) -> TripleDouble {
    let p0 = DoubleDouble::from_product(x, t.high);
    let p1 = DoubleDouble::from_product(x, t.mid);
    let mut acc = TripleDouble {
        high: p0.high,
        mid: 0.0,
        low: 0.0,
    };
    for term in [p1.high, p0.low, p1.low, x * t.low] {
        acc = td_add_f64(acc, term);
    }
    acc
}

/// Multiply a double-double by a triple-double.
#[inline]
fn dd_mul_td(d: DoubleDouble, t: TripleDouble) -> TripleDouble {
    let q0 = DoubleDouble::from_product(d.high, t.high);
    let q1 = DoubleDouble::from_product(d.high, t.mid);
    let q2 = DoubleDouble::from_product(d.low, t.high);
    let mut acc = TripleDouble {
        high: q0.high,
        mid: 0.0,
        low: 0.0,
    };
    for term in [
        q1.high,
        q2.high,
        q0.low,
        q1.low,
        q2.low,
        d.high * t.low,
        d.low * t.mid,
    ] {
        acc = td_add_f64(acc, term);
    }
    acc
}

/// Round a normalized triple-double to the nearest `f64`.  Round-to-odd of the
/// low pair `mid + low` (so its dropped tail survives as a sticky bit) followed
/// by one `high + ·` add yields the correctly-rounded result with no
/// double-rounding.
#[inline]
fn td_round(t: TripleDouble) -> f64 {
    let (s, e) = two_sum(t.mid, t.low);
    let s = if e != 0.0 && s.to_bits() & 1 == 0 {
        let bits = s.to_bits();
        f64::from_bits(if (s >= 0.0) == (e > 0.0) {
            bits + 1
        } else {
            bits - 1
        })
    } else {
        s
    };
    t.high + s
}

/// `B(u) = asin(√u)/√u = Σ aₖ uᵏ` as a triple-double, for `u ∈ [0, ¼]`.  The
/// slowly-decaying tail `a₉..a₆₀` runs double-double Horner, then `a₈..a₁`
/// (carried to a third limb in [`ASIN_ACC`]/[`ASIN_ACC_LO`]) finish in
/// triple-double — reaching ~2⁻¹³⁰, enough to round the hard `asin`/`acos`
/// points the double-double path misses (the worst ~2⁻¹¹¹ from a midpoint).
/// Shared by the direct leg [`asin_direct_td`] (`u = a²`) and `acos`'s
/// reflection leg ([`acos_accurate`], `u = (1−|x|)/2` exact).
fn asin_b_td(u: DoubleDouble) -> TripleDouble {
    let mut p = ASIN_ACC[59];
    let mut idx = 59;
    while idx > 8 {
        idx -= 1;
        p = p * u + ASIN_ACC[idx];
    }

    let mut t = TripleDouble {
        high: p.high,
        mid: p.low,
        low: 0.0,
    };
    for i in (0..8).rev() {
        t = dd_mul_td(u, t);
        t = td_add(
            t,
            TripleDouble {
                high: ASIN_ACC[i].high,
                mid: ASIN_ACC[i].low,
                low: ASIN_ACC_LO[i],
            },
        );
    }

    // B = 1 + u·t.
    td_add_f64(dd_mul_td(u, t), 1.0)
}

/// `asin(a)` for `a ∈ [0, ½]` as a triple-double, via the direct series
/// `asin(a) = a·B(a²)`.  The accurate fallback's direct leg.
fn asin_direct_td(a: f64) -> TripleDouble {
    td_mul_f64(asin_b_td(DoubleDouble::from_product(a, a)), a)
}

/// `√u` as a triple-double, for an exact non-negative `f64` `u`.
///
/// One Newton step `s + (u − s²)/(2s)` from the double-double seed `sqrt_dd(u)`
/// lifts ~2⁻¹⁰⁵ to ~2⁻¹⁵⁰: `s²` is assembled in triple-double (`high²` exact,
/// the `2·hi·lo` cross term, and `lo²`), the residual `u − s²` is tiny, and the
/// correction `÷2s` only needs the seed's high word.
fn sqrt_td(u: f64) -> TripleDouble {
    let s = sqrt_dd(DoubleDouble { high: u, low: 0.0 });

    // s² = high² + 2·high·lo + lo², in triple-double.
    let hh = DoubleDouble::from_product(s.high, s.high);
    let hl = DoubleDouble::from_product(s.high, s.low); // exact high·lo
    let mut sq = renorm3(hh.high, hh.low, 2.0 * hl.high);
    for term in [2.0 * hl.low, s.low * s.low] {
        sq = td_add_f64(sq, term);
    }

    // s ← s + (u − s²)/(2s).
    let residual = td_add_f64(td_neg(sq), u);
    let correction = td_mul_f64(residual, 0.5 / s.high);
    td_add(
        TripleDouble {
            high: s.high,
            mid: s.low,
            low: 0.0,
        },
        correction,
    )
}

/// `asin(|x|)` for `a = |x| ∈ [0, 1]`, as a double-double in `[0, π/2]`.
///
/// `asin(a) = atan(a/√(1−a²))`; the branch keeps the `atan` argument in `[0, 1]`.
#[inline]
fn asin_pos<K: Fn(DoubleDouble) -> DoubleDouble>(a: f64, kernel: K) -> DoubleDouble {
    if a == 1.0 {
        return FRAC_PI_2;
    }

    // c = √(1 − a²) as a double-double (a² exact, so the cancellation near a = 1
    // is captured).
    let c = sqrt_dd(ONE + neg(DoubleDouble::from_product(a, a)));

    if a <= c.high {
        kernel(DoubleDouble { high: a, low: 0.0 } * c.recip())
    } else {
        // a/c > 1 ⇒ atan(a/c) = π/2 − atan(c/a)
        FRAC_PI_2 + neg(kernel(c / a))
    }
}

// ---------------------------------------------------------------------------
// Accurate `Dint` (128-bit fixed-point) path for `atan`.
//
// The double-double accurate kernel above caps at ≈2⁻¹⁰²; ~492 of CORE-MATH's
// hardest `atan` near-ties land closer than that to a midpoint and mis-round
// (the worst at ≈2⁻¹¹⁶ relative).  The `Dint` path runs the *same* cell reduction
// (`atan(k/8 + …) = atan(k/8) + u·Σ(−1)ᵏu²ᵏ/(2k+1)`) but in a 128-bit significand
// (≈2⁻¹²⁶ — clear of the 2⁻¹¹⁶ ties), then rounds once with the sound
// `Dint::to_f64` (explicit round + sticky) — no hard-case database, exactly as
// the trig and inverse-hyperbolic accurate legs do.  It sits behind the existing
// Ziv gate, so the hot path is untouched.
//
// `atan2` is *harder*: its hardest corpus tie is ≈2⁻¹⁵⁴ relative, beyond a
// 128-bit significand's reach, so its accurate fallback uses the wider 192-bit
// `Tint` path below ([`atan2_tint_mag`]) instead.
//
// The per-function `Dint` helpers below mirror `trig.rs`; per the house
// convention each consuming module keeps its own copies rather than making
// `trig`'s `pub`.  Constants were generated by `tools/gen_dint_atan.py`; do not
// edit by hand — re-run the generator instead.
// ---------------------------------------------------------------------------

/// π/2 as a `Dint`, for the `atan(a) = π/2 − atan(1/a)` reflection.
const PIO2_DINT: Dint = Dint {
    sgn: false,
    ex: 0,
    m: 0xc90fdaa22168c234c4c6628b80dc1cd1,
};

/// `2` as a `Dint`, for the Newton reciprocal `y·(2 − c·y)` of the cell fold.
const TWO_DINT: Dint = Dint {
    sgn: false,
    ex: 1,
    m: 0x80000000000000000000000000000000,
};

/// `atan(k/8)` as a `Dint` for `k` in `0..=8` — the cell-table leads.
const ATAN_TABLE_DINT: [Dint; 9] = [
    Dint {
        sgn: false,
        ex: 0,
        m: 0x00000000000000000000000000000000,
    },
    Dint {
        sgn: false,
        ex: -4,
        m: 0xfeadd4d5617b6e32c897989f3e888ef8,
    },
    Dint {
        sgn: false,
        ex: -3,
        m: 0xfadbafc96406eb156dc79ef5f7a217e6,
    },
    Dint {
        sgn: false,
        ex: -2,
        m: 0xb7b0ca0f26f784738aa32122dcfe4483,
    },
    Dint {
        sgn: false,
        ex: -2,
        m: 0xed63382b0dda7b456fe445ecbc3a8d03,
    },
    Dint {
        sgn: false,
        ex: -1,
        m: 0x8f005d5ef7f59f9b5c835e1665c43748,
    },
    Dint {
        sgn: false,
        ex: -1,
        m: 0xa4bc7d1934f7092419a87f2a457dac9f,
    },
    Dint {
        sgn: false,
        ex: -1,
        m: 0xb8053e2bc2319e73cb2da55210a4443d,
    },
    Dint {
        sgn: false,
        ex: -1,
        m: 0xc90fdaa22168c234c4c6628b80dc1cd1,
    },
];

/// `(−1)ᵏ/(2k+1)` as `Dint` coefficients of `atan(u)/u` in `v = u²`, low-degree
/// first.  16 terms — the tail at `v = (1/16)² = 1/256` is ≈2⁻¹³³, below the
/// `Dint` arithmetic floor.
const ATAN_COEFFS_DINT: [Dint; 16] = [
    Dint {
        sgn: false,
        ex: 0,
        m: 0x80000000000000000000000000000000,
    },
    Dint {
        sgn: true,
        ex: -2,
        m: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab,
    },
    Dint {
        sgn: false,
        ex: -3,
        m: 0xcccccccccccccccccccccccccccccccd,
    },
    Dint {
        sgn: true,
        ex: -3,
        m: 0x92492492492492492492492492492492,
    },
    Dint {
        sgn: false,
        ex: -4,
        m: 0xe38e38e38e38e38e38e38e38e38e38e4,
    },
    Dint {
        sgn: true,
        ex: -4,
        m: 0xba2e8ba2e8ba2e8ba2e8ba2e8ba2e8ba,
    },
    Dint {
        sgn: false,
        ex: -4,
        m: 0x9d89d89d89d89d89d89d89d89d89d89e,
    },
    Dint {
        sgn: true,
        ex: -4,
        m: 0x88888888888888888888888888888889,
    },
    Dint {
        sgn: false,
        ex: -5,
        m: 0xf0f0f0f0f0f0f0f0f0f0f0f0f0f0f0f1,
    },
    Dint {
        sgn: true,
        ex: -5,
        m: 0xd79435e50d79435e50d79435e50d7943,
    },
    Dint {
        sgn: false,
        ex: -5,
        m: 0xc30c30c30c30c30c30c30c30c30c30c3,
    },
    Dint {
        sgn: true,
        ex: -5,
        m: 0xb21642c8590b21642c8590b21642c859,
    },
    Dint {
        sgn: false,
        ex: -5,
        m: 0xa3d70a3d70a3d70a3d70a3d70a3d70a4,
    },
    Dint {
        sgn: true,
        ex: -5,
        m: 0x97b425ed097b425ed097b425ed097b42,
    },
    Dint {
        sgn: false,
        ex: -5,
        m: 0x8d3dcb08d3dcb08d3dcb08d3dcb08d3e,
    },
    Dint {
        sgn: true,
        ex: -5,
        m: 0x84210842108421084210842108421084,
    },
];

/// Negate a `Dint` (mirrors `trig::neg_dint`).
#[inline]
const fn neg_dint(v: Dint) -> Dint {
    Dint { sgn: !v.sgn, ..v }
}

/// Horner evaluation of a `Dint` Taylor polynomial in `u`, low-degree first
/// (mirrors `trig::poly_dint`).
#[inline]
fn poly_dint(u: &Dint, coeffs: &[Dint]) -> Dint {
    let mut acc = coeffs[coeffs.len() - 1];
    for c in coeffs[..coeffs.len() - 1].iter().rev() {
        acc = c.add(&u.mul(&acc));
    }
    acc
}

/// `1 / c` as a `Dint`, two Newton steps `y·(2 − c·y)` from the `f64` seed `1/c`
/// (mirrors `trig::recip_dint`).  The cell denominator `1 + q·c ∈ [1, 1.13]` and
/// the `atan2` denominator `big + c·small ≥ big` are both well away from zero, so
/// two steps reach the `Dint` arithmetic floor.
#[inline]
fn recip_dint(c: &Dint) -> Dint {
    let mut y = Dint::from_f64(1.0 / c.to_f64());
    for _ in 0..2 {
        y = y.mul(&TWO_DINT.add(&neg_dint(c.mul(&y))));
    }
    y
}

/// Finish from a reduced cell in `Dint`: `atan(k/8 + …) = table + u·Σ(−1)ᵏu²ᵏ/(2k+1)`.
///
/// The `Dint` counterpart of [`atan_cell`]: `table = atan(k/8)` and `|u| ≤ 1/16`.
#[inline]
fn atan_cell_dint(table: &Dint, u: &Dint) -> Dint {
    table.add(&u.mul(&poly_dint(&u.mul(u), &ATAN_COEFFS_DINT)))
}

/// `atan(q)` for a `Dint` `q ∈ [0, 1]` via the cell reduction
/// `u = (q − c)/(1 + q·c)`, `c = k/8`, `k = round(8q)` — the `Dint` counterpart
/// of [`atan_dd`]'s reduction.  Used by both the `atan` reflection (where `q` is
/// a `Dint` reciprocal `1/a`) and the direct branch (`q = a` exact).
#[inline]
fn atan_reduce_dint(q: &Dint) -> Dint {
    let qf = q.to_f64();
    // k = round(8q); q ∈ [0, 1] puts k in 0..=8.
    let k = (qf * 8.0).round_ties_even();
    let kc = k as i64;
    let c = k * 0.125; // exact (power-of-two multiple of 1/8)
    let cd = Dint::from_f64(c);

    // u = (q − c) / (1 + q·c); c = 0 (k = 0) makes the numerator q and the
    // denominator 1, so `u = q` — handled uniformly by the general formula.
    let num = q.add(&neg_dint(cd));
    let den = ONE_DINT.add(&q.mul(&cd));
    let u = num.mul(&recip_dint(&den));

    atan_cell_dint(&ATAN_TABLE_DINT[kc as usize], &u)
}

/// `1` as a `Dint`, for the cell denominator `1 + q·c`.
const ONE_DINT: Dint = Dint {
    sgn: false,
    ex: 0,
    m: 0x80000000000000000000000000000000,
};

/// Magnitude of `atan(|x|)` in `[0, π/2]` as a `Dint` — the accurate fallback,
/// mirroring the (now-`Dint`) reflection the double-double path used.  For
/// `a > 1` reflect `π/2 − atan(1/a)` with `1/a` formed to `Dint` precision
/// (`recip_dint`); otherwise reduce `a` directly.
#[inline]
fn atan_dint_mag(a: f64) -> Dint {
    if a > 1.0 {
        let recip = recip_dint(&Dint::from_f64(a));
        PIO2_DINT.add(&neg_dint(atan_reduce_dint(&recip)))
    } else {
        atan_reduce_dint(&Dint::from_f64(a))
    }
}

/// CORE-MATH's fine atan reduction table: `A[i] = tan(i·π/256)` as a
/// double-double, `i = 0..=127`.  Picking the cell `i` from `|x|`'s bits puts
/// the residual angle within `tan(π/512)`, so a single f64 division and a
/// degree-7 poly reach correct rounding without double-double reduction.
/// Generated by tools/gen_atan_fast_f64.py from CORE-MATH atan.c.
const ATAN_FAST_TABLE: [DoubleDouble; 128] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.012272462379566276,
        low: 3.555765684818314e-19,
    },
    DoubleDouble {
        high: 0.024548622108925444,
        low: 5.834854161337051e-20,
    },
    DoubleDouble {
        high: 0.03683218099484564,
        low: 2.1067819371007694e-18,
    },
    DoubleDouble {
        high: 0.049126849769467254,
        low: -9.075861541377107e-20,
    },
    DoubleDouble {
        high: 0.061436352581593766,
        low: 1.7816411675633553e-18,
    },
    DoubleDouble {
        high: 0.07376443152244928,
        low: -5.278932630666519e-18,
    },
    DoubleDouble {
        high: 0.0861148511976279,
        low: -1.5678193105312258e-18,
    },
    DoubleDouble {
        high: 0.09849140335716425,
        low: -5.259051390942549e-18,
    },
    DoubleDouble {
        high: 0.11089791159591303,
        low: 4.337394303627698e-18,
    },
    DoubleDouble {
        high: 0.12333823613673868,
        low: 1.8297202500785388e-18,
    },
    DoubleDouble {
        high: 0.13581627870938773,
        low: 3.4130533520298278e-18,
    },
    DoubleDouble {
        high: 0.14833598753834742,
        low: -3.9912431039375455e-18,
    },
    DoubleDouble {
        high: 0.16090136245348916,
        low: -1.085108372224721e-17,
    },
    DoubleDouble {
        high: 0.17351646013785577,
        low: 5.445710695806514e-18,
    },
    DoubleDouble {
        high: 0.18618539952758373,
        low: -3.3242042151979862e-18,
    },
    DoubleDouble {
        high: 0.198912367379658,
        low: -8.07240081828309e-19,
    },
    DoubleDouble {
        high: 0.21170162402398335,
        low: -5.036514114884015e-18,
    },
    DoubleDouble {
        high: 0.2245575093171293,
        low: -8.524537892459856e-18,
    },
    DoubleDouble {
        high: 0.23748444881607017,
        low: -1.2885716860577882e-17,
    },
    DoubleDouble {
        high: 0.25048696019130545,
        low: -8.83555859166591e-18,
    },
    DoubleDouble {
        high: 0.263569659899918,
        low: -9.610855418635516e-18,
    },
    DoubleDouble {
        high: 0.2767372701404143,
        low: -1.1577675320243282e-17,
    },
    DoubleDouble {
        high: 0.2899946261126061,
        low: -8.101130151610375e-19,
    },
    DoubleDouble {
        high: 0.3033466836073424,
        low: 1.1691177889169384e-17,
    },
    DoubleDouble {
        high: 0.3167985269526038,
        low: 1.285806508222281e-17,
    },
    DoubleDouble {
        high: 0.3303553773443339,
        low: -2.1827616435782727e-17,
    },
    DoubleDouble {
        high: 0.3440226015924263,
        low: -1.0384601646900657e-17,
    },
    DoubleDouble {
        high: 0.3578057213145241,
        low: -9.056713942825596e-18,
    },
    DoubleDouble {
        high: 0.37171042261274345,
        low: 2.354338854400786e-17,
    },
    DoubleDouble {
        high: 0.38574256627112125,
        low: 8.757134942172942e-18,
    },
    DoubleDouble {
        high: 0.3999081985145372,
        low: -1.485057909629851e-17,
    },
    DoubleDouble {
        high: 0.41421356237309503,
        low: -1.2247952842778023e-17,
    },
    DoubleDouble {
        high: 0.4286651096994995,
        low: 9.563183748944196e-18,
    },
    DoubleDouble {
        high: 0.44326951389086433,
        low: -2.895975402054566e-18,
    },
    DoubleDouble {
        high: 0.4580336833706724,
        low: -1.0789951953407575e-17,
    },
    DoubleDouble {
        high: 0.4729647758913199,
        low: -1.423462408803522e-17,
    },
    DoubleDouble {
        high: 0.48807021372286286,
        low: -1.8748963792094843e-18,
    },
    DoubleDouble {
        high: 0.5033576997992942,
        low: -2.3181776247031463e-17,
    },
    DoubleDouble {
        high: 0.5188352348999757,
        low: 1.7981389592709095e-18,
    },
    DoubleDouble {
        high: 0.5345111359507917,
        low: 4.0932084625426755e-17,
    },
    DoubleDouble {
        high: 0.5503940555372641,
        low: 2.781630117382078e-17,
    },
    DoubleDouble {
        high: 0.566493002730344,
        low: -4.42039855975346e-18,
    },
    DoubleDouble {
        high: 0.5828173653349761,
        low: -1.4827496899423528e-17,
    },
    DoubleDouble {
        high: 0.5993769336819238,
        low: 2.175212986778241e-17,
    },
    DoubleDouble {
        high: 0.6161819260948661,
        low: 3.557374281725727e-17,
    },
    DoubleDouble {
        high: 0.6332430161775692,
        low: 3.279927931291694e-17,
    },
    DoubleDouble {
        high: 0.6505713620801533,
        low: 1.4944554437080147e-17,
    },
    DoubleDouble {
        high: 0.6681786379192989,
        low: -2.837423353933172e-17,
    },
    DoubleDouble {
        high: 0.6860770675448629,
        low: -3.709036277500186e-17,
    },
    DoubleDouble {
        high: 0.7042794608650442,
        low: -1.1726428260896895e-17,
    },
    DoubleDouble {
        high: 0.7227992529642059,
        low: -3.057415347618549e-17,
    },
    DoubleDouble {
        high: 0.7416505462720354,
        low: 2.982922573366765e-17,
    },
    DoubleDouble {
        high: 0.7608481560702512,
        low: -3.1210538940343614e-17,
    },
    DoubleDouble {
        high: 0.7804076596539437,
        low: 1.2693028137126565e-17,
    },
    DoubleDouble {
        high: 0.8003454494993201,
        low: -1.8667355083286445e-17,
    },
    DoubleDouble {
        high: 0.8206787908286604,
        low: 1.3697615920272132e-17,
    },
    DoubleDouble {
        high: 0.8414258840072548,
        low: -1.3781600473511285e-18,
    },
    DoubleDouble {
        high: 0.8626059322567399,
        low: -1.1431434768209771e-17,
    },
    DoubleDouble {
        high: 0.8842392152253499,
        low: 2.3060634500897344e-18,
    },
    DoubleDouble {
        high: 0.9063471690191471,
        low: -1.1839022437919416e-17,
    },
    DoubleDouble {
        high: 0.9289524733703675,
        low: -4.0486446058344625e-19,
    },
    DoubleDouble {
        high: 0.9520791467009253,
        low: -2.2825930096084175e-17,
    },
    DoubleDouble {
        high: 0.9757526499323765,
        low: 2.2758940764856317e-18,
    },
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 1.0248498941502273,
        low: -5.192502513549596e-17,
    },
    DoubleDouble {
        high: 1.0503328462398598,
        low: -3.397402228340294e-17,
    },
    DoubleDouble {
        high: 1.076481336415266,
        low: 3.330404344066333e-17,
    },
    DoubleDouble {
        high: 1.1033299757334756,
        low: -3.95499878138913e-17,
    },
    DoubleDouble {
        high: 1.1309156874988273,
        low: 3.997022789196374e-17,
    },
    DoubleDouble {
        high: 1.1592779073334347,
        low: -1.1986546386526189e-17,
    },
    DoubleDouble {
        high: 1.1884588042829662,
        low: -4.2345963685969836e-17,
    },
    DoubleDouble {
        high: 1.2185035255879764,
        low: 8.55006801533348e-18,
    },
    DoubleDouble {
        high: 1.2494604681335788,
        low: 2.439868444909347e-17,
    },
    DoubleDouble {
        high: 1.2813815800365544,
        low: -4.140089560728253e-17,
    },
    DoubleDouble {
        high: 1.31432269635108,
        low: -2.720740369445052e-17,
    },
    DoubleDouble {
        high: 1.3483439134867201,
        low: -1.392875322075665e-17,
    },
    DoubleDouble {
        high: 1.3835100076528737,
        low: -3.258872748382433e-17,
    },
    DoubleDouble {
        high: 1.4198909034940925,
        low: 2.421912180525479e-17,
    },
    DoubleDouble {
        high: 1.4575622000871054,
        low: -1.1018931582399467e-17,
    },
    DoubleDouble {
        high: 1.496605762665489,
        low: -2.1526140115556586e-17,
    },
    DoubleDouble {
        high: 1.5371103898618819,
        low: -2.8751398359022675e-17,
    },
    DoubleDouble {
        high: 1.5791725679602089,
        low: -2.8596003249434097e-17,
    },
    DoubleDouble {
        high: 1.6228973256934547,
        low: 2.8067634844374685e-17,
    },
    DoubleDouble {
        high: 1.668399205583507,
        low: 6.289659338573465e-18,
    },
    DoubleDouble {
        high: 1.7158033707956641,
        low: 2.015230798772186e-17,
    },
    DoubleDouble {
        high: 1.7652468700941915,
        low: -1.4024935317617867e-17,
    },
    DoubleDouble {
        high: 1.8168800878924023,
        low: 3.981317068068186e-18,
    },
    DoubleDouble {
        high: 1.8708684117893895,
        low: -6.5460218324344e-18,
    },
    DoubleDouble {
        high: 1.9273941566300643,
        low: 1.6589883917528817e-17,
    },
    DoubleDouble {
        high: 1.986658792343365,
        low: -9.623226887484272e-18,
    },
    DoubleDouble {
        high: 2.04888553303075,
        low: -1.3947227916996688e-17,
    },
    DoubleDouble {
        high: 2.1143223575486405,
        low: -1.5098616889246607e-17,
    },
    DoubleDouble {
        high: 2.183245547884152,
        low: -9.178521891131575e-18,
    },
    DoubleDouble {
        high: 2.2559638519291587,
        low: 1.0580493190911606e-17,
    },
    DoubleDouble {
        high: 2.3328234031013504,
        low: 3.1332035083654735e-17,
    },
    DoubleDouble {
        high: 2.414213562373095,
        low: -1.836025624937195e-17,
    },
    DoubleDouble {
        high: 2.5005738909942568,
        low: -2.207868765763124e-17,
    },
    DoubleDouble {
        high: 2.5924025177380727,
        low: 2.172588189518176e-17,
    },
    DoubleDouble {
        high: 2.690266237279613,
        low: 2.3386835224767844e-17,
    },
    DoubleDouble {
        high: 2.7948127724904768,
        low: -2.637365777071167e-18,
    },
    DoubleDouble {
        high: 2.9067857616655353,
        low: -1.850484486824546e-17,
    },
    DoubleDouble {
        high: 3.027043204317774,
        low: -4.6444931832965504e-18,
    },
    DoubleDouble {
        high: 3.1565803339407887,
        low: 4.4892674471274045e-18,
    },
    DoubleDouble {
        high: 3.2965582089383205,
        low: 8.0329653691558e-18,
    },
    DoubleDouble {
        high: 3.448339762033024,
        low: -2.650011172948169e-18,
    },
    DoubleDouble {
        high: 3.6135356813074284,
        low: -1.4498116294014568e-18,
    },
    DoubleDouble {
        high: 3.794063400088301,
        low: 6.2559686487820676e-18,
    },
    DoubleDouble {
        high: 3.9922237837700845,
        low: 2.5219389745244403e-18,
    },
    DoubleDouble {
        high: 4.2108020335028,
        low: -2.0627827669039212e-17,
    },
    DoubleDouble {
        high: 4.453202224414411,
        low: 1.0293977616949511e-17,
    },
    DoubleDouble {
        high: 4.723629327882301,
        low: 2.9204606579431894e-18,
    },
    DoubleDouble {
        high: 5.027339492125848,
        low: -1.1242200673498819e-18,
    },
    DoubleDouble {
        high: 5.370990435003729,
        low: 3.684977524078479e-18,
    },
    DoubleDouble {
        high: 5.76314200511881,
        low: 6.917964102580692e-18,
    },
    DoubleDouble {
        high: 6.214987771089038,
        low: 3.640640587118668e-18,
    },
    DoubleDouble {
        high: 6.7414524054149885,
        low: 4.0170380453361145e-18,
    },
    DoubleDouble {
        high: 7.362887641324245,
        low: 7.368009079543718e-18,
    },
    DoubleDouble {
        high: 8.107785803676908,
        low: 6.09083500396278e-18,
    },
    DoubleDouble {
        high: 9.017302360424734,
        low: 4.926430357629524e-18,
    },
    DoubleDouble {
        high: 10.15317038760886,
        low: -5.151761162135913e-18,
    },
    DoubleDouble {
        high: 11.612398861435247,
        low: 5.516144024233879e-18,
    },
    DoubleDouble {
        high: 13.556669242352426,
        low: -1.6893253257870288e-18,
    },
    DoubleDouble {
        high: 16.27700795993541,
        low: 6.325118845392731e-18,
    },
    DoubleDouble {
        high: 20.355467624987188,
        low: 5.728461403643232e-20,
    },
    DoubleDouble {
        high: 27.150170665699697,
        low: -9.090111443989645e-20,
    },
    DoubleDouble {
        high: 40.7354838720833,
        low: -1.0077222670348913e-18,
    },
    DoubleDouble {
        high: 81.48324020654617,
        low: 1.277782632177919e-19,
    },
];

/// Per-exponent-bucket index-fit (CORE-MATH's `c[31][3]`): a quadratic in
/// `|x|`'s top mantissa bits that yields the fine cell `i`, avoiding an atan
/// to pick the cell.  Kept as `u64` so the index arithmetic needs no casts.
const ATAN_FAST_IDX: [[u64; 3]; 31] = [
    [419, 81, 0],
    [500, 81, 0],
    [582, 163, 0],
    [745, 163, 0],
    [908, 326, 0],
    [1234, 326, 0],
    [1559, 651, 0],
    [2210, 650, 1],
    [2860, 1299, 3],
    [4156, 1293, 4],
    [5444, 2569, 24],
    [7989, 2520, 32],
    [10476, 4917, 168],
    [15224, 4576, 200],
    [19601, 8341, 838],
    [27105, 6648, 731],
    [33036, 10210, 1998],
    [41266, 6292, 1117],
    [46469, 7926, 2048],
    [52375, 4038, 849],
    [55587, 4591, 1291],
    [58906, 2172, 479],
    [60612, 2390, 688],
    [62325, 1107, 247],
    [63192, 1207, 349],
    [64056, 556, 124],
    [64491, 605, 175],
    [64923, 278, 62],
    [65141, 303, 88],
    [65358, 139, 31],
    [65467, 151, 44],
];

/// `atan(h)/h ≈ Σ ch[k]·h²ᵏ` on `|h| ≤ tan(π/512)`, low-degree first.
const ATAN_FAST_CH: [f64; 4] = [
    1.0,
    -0.333333333333331,
    0.1999999997326265,
    -0.1428473928322857,
];

/// Small-`|x|` poly: `atan(x) = x + x³·Σ ch2[k]·x²ᵏ`, low-degree first.
const ATAN_FAST_CH2: [f64; 4] = [
    -0.3333333333333333,
    0.199999999999994,
    -0.1428571424743179,
    0.11110113960028833,
];

const ATAN_STEP_HI: f64 = 0.012271846303085088; // 0x1.921fb54442dp-7
const ATAN_STEP_LO: f64 = 4.2111741079360304e-17; // 0x1.8469898cc517p-55
const ATAN_PI2_HI: f64 = 1.5707963267948966; // 0x1.921fb54442d18p+0
const ATAN_PI2_LO: f64 = 6.123233995736766e-17; // 0x1.1a62633145c07p-54
const ATAN_TINY_NUDGE: f64 = 5.551115123125783e-17; // 0x1p-54
const ATAN_ZIV_E: f64 = 8.743006318923108e-16; // 0x3.fp-52
const ATAN_SMALL_UB: f64 = 9.992007221626409e-16; // 0x4.8p-52
const ATAN_SMALL_LB: f64 = 5.551115123125783e-16; // 0x2.8p-52

/// `|x|` threshold below which the fine table is bypassed for the direct
/// small-`|x|` polynomial (`0x1.b21c475e6362ap-8`), as raw `|x|` bits.
const ATAN_SMALL: u64 = 0x3f7b21c475e6362a;
/// `|x| < 2⁻²⁷`: `atan(x)` rounds to `x` (with a one-ulp nudge), as raw bits.
const ATAN_TINY: u64 = 0x3e40000000000000;
/// `|x|` threshold above which the reflection `atan(x) = π/2 + atan(−1/x)` is
/// used (`0x1.2ded8e34a9035p+7`), as raw `|x|` bits.
const ATAN_BIG: u64 = 0x4062ded8e34a9035;
/// `|x| ≥ 0x1.d02967c31cdb5p+53`: `atan(x)` rounds to `±π/2`, as raw bits.
const ATAN_HUGE: u64 = 0x434d02967c31cdb5;

/// CORE-MATH's plain-`f64` `atan` fast path (port of `cr_atan`'s hot path).
///
/// Three regions of `|x|`: a direct degree-7 series for `|x| < ATAN_SMALL`; the
/// reflection `atan(x) = π/2 + atan(−1/x)` (`h = −1/x`) for `|x| > ATAN_BIG`; and
/// in between, the [`ATAN_FAST_TABLE`] reduction `h = (x − tan c)/(1 + x·tan c)`
/// with the cell `c = i·π/256` picked from `|x|`'s bits via [`ATAN_FAST_IDX`].
/// The middle and reflection regions share the degree-7 tail.  A Ziv test (CORE-
/// MATH's own proven `h·ATAN_ZIV_E` bound) returns the correctly-rounded result
/// or `None` to defer to the sound `Dint` accurate path ([`atan_dint_mag`]).
#[inline]
fn atan_fast(x: f64) -> Option<f64> {
    let bits = x.to_bits();
    let at = bits & (u64::MAX >> 1); // |x| bits

    if at < ATAN_SMALL {
        if at == 0 {
            return Some(x); // atan(±0) = ±0
        }
        if at < ATAN_TINY {
            // atan(x) = x to far below ½ ulp; the nudge rounds the tie down.
            return Some(crate::fma(-ATAN_TINY_NUDGE, x, x));
        }
        let x2 = x * x;
        let x3 = x * x2;
        let f = x3 * crate::poly(x2, &ATAN_FAST_CH2);
        // Asymmetric gate (atan(x) < x for x > 0): products bound off the hot path.
        let d_ub = f * ATAN_SMALL_UB;
        let d_lb = f * ATAN_SMALL_LB;
        let ub = (f + d_ub) + x;
        let lb = (f - d_lb) + x;
        return (ub == lb).then_some(ub);
    }

    let (h, ah, al_pre);
    if at > ATAN_BIG {
        ah = ATAN_PI2_HI.copysign(x);
        let al = ATAN_PI2_LO.copysign(x);
        if at >= ATAN_HUGE {
            return Some(ah + al); // atan(x) = ±π/2
        }
        h = -1.0 / x;
        al_pre = al;
    } else {
        // 0x1.b21c…p-8 ≤ |x| ≤ 0x1.2ded…p+7 ⇒ coarse bucket 1..=30, refined to a
        // fine cell i ∈ 0..=127 by a per-bucket quadratic in |x|'s top bits.
        let bucket = ((at >> 51) - 2030) as usize;
        let m = bits & (u64::MAX >> 13); // low 51 bits of x
        let ut = m >> 35; // top 16 of them
        let ut2 = (ut * ut) >> 16;
        // SAFETY: ATAN_SMALL ≤ at ≤ ATAN_BIG ⇒ at>>51 ∈ 2031..=2060 ⇒ bucket ∈ 1..=30,
        // and CORE-MATH's quadratic fit keeps i ∈ 0..=127 over that range.
        let c = unsafe { *ATAN_FAST_IDX.get_unchecked(bucket) };
        let i = (((c[0] << 16) + ut * c[1] - ut2 * c[2]) >> 25) as usize;
        let tab = unsafe { *ATAN_FAST_TABLE.get_unchecked(i) };
        let sign = 1.0_f64.copysign(x);
        let ta = sign * tab.high;
        let id = sign * i as f64;
        // al = sign·A[i].low + (π/256 low)·i — the cell lead's low words.
        al_pre = crate::fast_mul_add(ATAN_STEP_LO, id, sign * tab.low);
        // h = (x − tan c)/(1 + x·tan c); split the product so the add is unfused.
        let p = x * ta;
        h = (x - ta) / (1.0 + p);
        ah = ATAN_STEP_HI * id;
    }

    let f = crate::poly(h * h, &ATAN_FAST_CH); // atan(h)/h
    let al = crate::fma(h, f, al_pre);
    let e = h * ATAN_ZIV_E;
    let ub = (al + e) + ah;
    let lb = (al - e) + ah;
    (ub == lb).then_some(ub)
}

/// Relative half-width of the second-tier Ziv gate on the double-double accurate
/// kernel.  [`atan_fast`]'s gate inherently defers ~5% (it tests f64 rounding near
/// midpoints), so that miss bulk must be cheap: the ≈2⁻¹⁰² double-double kernel
/// resolves all of it here, and only the genuine hard-to-round points (≈2⁻¹¹⁶ from
/// a midpoint) clear this 2⁻⁹⁰ gate to escalate to the slow 128-bit [`atan_dint_mag`].
const ATAN_DD_ZIV_EPS: f64 = 8.077935669463161e-28; // 2⁻⁹⁰

/// `atan(a)` as a double-double for `a ∈ [0, 1]`, via the fine [`ATAN_FAST_TABLE`]
/// reduction — the cheap refine tier for [`atan_fast`]'s Ziv misses.
///
/// The fine table keeps the residual `|h| ≤ tan(π/512)`, so the odd series
/// `atan(h) = h·(1 − h²/3 + …)` needs only 8 double-double terms (vs the 16 of the
/// coarse-cell [`atan_dd`] over `|u| ≤ 1/16`), halving the dominant poly cost while
/// staying ≈2⁻¹⁰² — well inside the [`ATAN_DD_ZIV_EPS`] gate.  Below `ATAN_SMALL`
/// the cell is `i = 0` (`h = a`, angle 0); otherwise the same bit-trick index as
/// the fast path picks the cell.
///
/// As in the fast path, the tangent is the single `f64` `A[i].high`; `A[i].low` is
/// CORE-MATH's *angle defect* `atan(A[i].high) − i·π/256`, so the cell angle is
/// `i·π/256 + A[i].low = atan(A[i].high)`, reconstructed with the same truncated
/// `ATAN_STEP_HI/LO` the defect was generated against (not a fresh π/256, whose
/// low word would double-count the defect).
fn atan_fine_dd(a: f64) -> DoubleDouble {
    let at = a.to_bits(); // a ≥ 0
    let (h, angle) = if at < ATAN_SMALL {
        (DoubleDouble { high: a, low: 0.0 }, ZERO)
    } else {
        let bucket = ((at >> 51) - 2030) as usize;
        let mbits = at & (u64::MAX >> 13);
        let ut = mbits >> 35;
        let ut2 = (ut * ut) >> 16;
        let c = ATAN_FAST_IDX[bucket];
        let i = (((c[0] << 16) + ut * c[1] - ut2 * c[2]) >> 25) as usize;
        let tab = ATAN_FAST_TABLE[i];
        let ta = DoubleDouble {
            high: tab.high,
            low: 0.0,
        };
        let ad = DoubleDouble { high: a, low: 0.0 };
        // h = (a − tan c)/(1 + a·tan c), all double-double (tan c = A[i].high).
        let h = (ad + neg(ta)) * (ONE + ad * ta).recip();
        // angle = atan(A[i].high) = i·π/256 + A[i].low.
        let ih = i as f64;
        let angle = DoubleDouble::from_product(ih, ATAN_STEP_HI)
            + DoubleDouble {
                high: crate::fast_mul_add(ih, ATAN_STEP_LO, tab.low),
                low: 0.0,
            };
        (h, angle)
    };
    // atan(h) = h·(1 − h²/3 + …); 8 terms reach ≈2⁻¹²¹ over |h| ≤ tan(π/512).
    angle + h * poly_dd(h * h, &ATAN_COEFFS[..8])
}

/// Correctly-rounded magnitude `atan(|x|)`, the accurate fallback to [`atan_fast`].
///
/// Cheap double-double tier behind a second Ziv gate; only the hard-to-round points
/// escalate to the sound 128-bit [`atan_dint_mag`].  `a ≤ 1` (the bulk of the fast
/// path's misses, where the result is small and its gate deferred most) takes the
/// lean fine-table [`atan_fine_dd`]; `a > 1` is rare here, so it reflects through the
/// general coarse [`atan_dd`].  Cold and never inlined so the miss bulk stays out of
/// [`atan`]'s hot path.
#[cold]
#[inline(never)]
fn atan_accurate(a: f64) -> f64 {
    let m = if a > 1.0 {
        FRAC_PI_2 + neg(atan_dd(DoubleDouble { high: a, low: 0.0 }.recip()))
    } else {
        atan_fine_dd(a)
    };
    ziv_at(m, ATAN_DD_ZIV_EPS).unwrap_or_else(|| atan_dint_mag(a).to_f64())
}

/// Arctangent
#[must_use]
#[inline]
pub fn atan(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    let a = x.abs();
    if a.is_infinite() {
        return core::f64::consts::FRAC_PI_2.copysign(x);
    }

    // CORE-MATH-style fine-table fast path; the ~5% Ziv miss bulk defers to the
    // cheap double-double tier, hard-to-round points alone to the 128-bit `Dint`.
    atan_fast(x).unwrap_or_else(|| atan_accurate(a).copysign(x))
}

/// Correctly-rounded `asin(a)` for `a = |x| ∈ [0, 1]`, the accurate fallback.
///
/// Two tiers: the double-double `asin(a) = atan(a/√(1−a²))` (`asin_pos`) handles
/// the bulk of fast-leg misses cheaply, and a second Ziv gate escalates only the
/// hard-to-round direct-branch points to the slow triple-double series
/// [`asin_direct_td`].  Cold and never inlined so the rare-miss bulk stays out of
/// [`asin`]'s hot path.
#[cold]
#[inline(never)]
fn asin_accurate(a: f64) -> f64 {
    let m = asin_pos(a, atan_dd);
    ziv_at(m, ASIN_DD_ZIV_EPS).unwrap_or_else(|| {
        if a < 0.5 {
            td_round(asin_direct_td(a))
        } else {
            m.high + m.low
        }
    })
}

/// Correctly-rounded `acos(x)`, the accurate fallback.  `acos(x) = π/2 − asin(x)`:
/// `π/2 − asin(|x|)` for `x ≥ 0`, `π/2 + asin(|x|)` for `x < 0`.  Same two-tier
/// scheme as [`asin_accurate`]: a double-double result, with a second Ziv gate
/// escalating the hard-to-round direct-branch points (where the `π/2 − asin`
/// subtraction needs the extra limb) to triple-double.
#[cold]
#[inline(never)]
fn acos_accurate(x: f64) -> f64 {
    let a = x.abs();
    let s = asin_pos(a, atan_dd);
    let m = if x.is_sign_negative() {
        FRAC_PI_2 + s
    } else {
        FRAC_PI_2 + neg(s)
    };
    ziv_at(m, ASIN_DD_ZIV_EPS).unwrap_or_else(|| {
        if a < 0.5 {
            let std = asin_direct_td(a);
            let mt = if x.is_sign_negative() {
                td_add(FRAC_PI_2_TD, std)
            } else {
                td_add(FRAC_PI_2_TD, td_neg(std))
            };
            td_round(mt)
        } else {
            // Reflection: with `u = (1−|x|)/2` exact (Sterbenz) and `s = √u`,
            // `asin(√u) = √u·B(u)`, so `acos(x) = 2·asin(√u)` for `x ≥ 0` and
            // `π − 2·asin(√u)` for `x < 0`.  The double-double `m` lands within a
            // hard-to-round point's reach, so resolve the series in triple-double.
            let u = 0.5 * (1.0 - a);
            let b = asin_b_td(DoubleDouble { high: u, low: 0.0 });
            let s = sqrt_td(u);
            // asin(√u) = √u·B(u): fold the seed's low limb in as an `f64` (`B ≈ 1`).
            let asin_s = td_add_f64(
                dd_mul_td(
                    DoubleDouble {
                        high: s.high,
                        low: s.mid,
                    },
                    b,
                ),
                s.low * b.high,
            );
            let two_asin = td_mul_f64(asin_s, 2.0);
            let mt = if x.is_sign_negative() {
                td_add(td_mul_f64(FRAC_PI_2_TD, 2.0), td_neg(two_asin))
            } else {
                two_asin
            };
            td_round(mt)
        }
    })
}

/// Arcsine
#[must_use]
#[inline]
pub fn asin(x: f64) -> f64 {
    let a = x.abs();

    let (off, z, zl, r, j) = if a < 0.5 {
        // For |x| < 0x1.7137449123ef6p-26, `asin(x) − x = x³/6 + …` stays below
        // half an ulp of the result, so x is the correctly-rounded answer (and
        // ±0 keeps its sign without touching the offset fold).
        if a < 2.149119332890821e-8 {
            return x;
        }
        // asin(x) = x·B(x²): the sign rides in z, no offset.
        let jf = (128.0 * (x * x)).round_ties_even();
        let r = crate::fma(x, x, -(jf * 0.0078125)); // x² − j/128, exact-product residual
        // SAFETY: x² < ¼ puts jf in 0..=32; a plain `as` cast would pay a
        // saturation cmov chain right in front of the table load.
        (ZERO, x, 0.0, r, unsafe { jf.to_int_unchecked::<i64>() }
            as usize)
    } else {
        // Route the domain edge and NaN here so the direct branch costs a
        // single compare.
        if !(a < 1.0) {
            if a == 1.0 {
                // asin(±1) = ±π/2 (and avoids √0 → 0/0 in the reflection).
                return core::f64::consts::FRAC_PI_2.copysign(x);
            }
            return f64::NAN; // |x| > 1 or NaN
        }
        // asin(x) = sign(x)·(π/2 − √t·B(u)) with t = 2 − 2|x| and u = ¼t both
        // exact (Sterbenz), so only the multiplier √t = 2s needs a low word
        // (one division), avoiding the double-double `sqrt`.  The sign rides in
        // z = −√t·sign(x) and off = ±π/2.
        let t = 2.0 * (1.0 - a);
        let z = -t.sqrt().copysign(x);
        let zl = crate::fma(z, z, -t) * ((-0.5 / t) * z);
        let u = 0.25 * t;
        let jf = (128.0 * u).round_ties_even();
        let r = u - jf * 0.0078125; // exact
        let off = DoubleDouble {
            high: FRAC_PI_2.high.copysign(x),
            low: FRAC_PI_2.low.copysign(x),
        };
        // SAFETY: u = ¼t ≤ ¼ puts jf in 0..=32 (see the direct branch).
        (off, z, zl, r, unsafe { jf.to_int_unchecked::<i64>() }
            as usize)
    };

    asin_tail(off, z, zl, r, j).unwrap_or_else(|| asin_accurate(a).copysign(x))
}

/// Arccosine
#[must_use]
#[inline]
pub fn acos(x: f64) -> f64 {
    let a = x.abs();

    let (off, z, zl, r, j) = if a < 0.5 {
        // acos(x) = π/2 + (−x)·B(x²)
        let jf = (128.0 * (x * x)).round_ties_even();
        let r = crate::fma(x, x, -(jf * 0.0078125));
        // SAFETY: x² < ¼ puts jf in 0..=32 (see `asin`).
        (
            FRAC_PI_2,
            -x,
            0.0,
            r,
            unsafe { jf.to_int_unchecked::<i64>() } as usize,
        )
    } else {
        // Route the domain edge and NaN here so the direct branch costs a
        // single compare.
        if !(a < 1.0) {
            if a == 1.0 {
                // acos(1) = 0, acos(−1) = π (and avoids √0 → 0/0 below).
                return if x.is_sign_negative() {
                    core::f64::consts::PI
                } else {
                    0.0
                };
            }
            return f64::NAN; // |x| > 1 or NaN
        }
        // acos(x) = √t·B(u) for x ≥ ½, π − √t·B(u) for x ≤ −½: the sign rides
        // in z = √t·sign(x), and the offset is the branchless (and
        // componentwise-exact) `π/2 − copysign(π/2, x)` — 0 for x > 0 and
        // π = 2·(π/2) for x < 0.  A sign branch (or a 2-entry table, which
        // LLVM lowers back to one) mispredicts on a quarter of random inputs.
        let t = 2.0 * (1.0 - a);
        let z = t.sqrt().copysign(x);
        let zl = crate::fma(z, z, -t) * ((-0.5 / t) * z);
        let u = 0.25 * t;
        let jf = (128.0 * u).round_ties_even();
        let r = u - jf * 0.0078125; // exact
        let off = DoubleDouble {
            high: FRAC_PI_2.high - FRAC_PI_2.high.copysign(x),
            low: FRAC_PI_2.low - FRAC_PI_2.low.copysign(x),
        };
        // SAFETY: u = ¼t ≤ ¼ puts jf in 0..=32 (see the direct branch).
        (off, z, zl, r, unsafe { jf.to_int_unchecked::<i64>() }
            as usize)
    };

    asin_tail(off, z, zl, r, j).unwrap_or_else(|| acos_accurate(x))
}

/// Magnitude of `atan2(y, x)` in `[0, π]` for finite nonzero `a = |x|`, `b = |y|`.
#[inline]
fn atan2_mag(a: f64, b: f64, x_negative: bool) -> f64 {
    let (big, small, swapped) = if a >= b { (a, b, false) } else { (b, a, true) };
    let q = small / big;

    // Subnormal-result corner: the magnitude can only be subnormal in the
    // first-quadrant direct case (`!swapped && !x_negative`), where it is
    // `atan(q) ≈ q` with `q = small/big`.  The fast leg's tiny-ratio shortcut
    // returns the bare IEEE quotient with a degenerate (point) Ziv interval, so it
    // cannot defer the handful of subnormal-boundary ties where `atan(t) < t` tips
    // the last bit — route them straight to the 192-bit accurate path.  The danger
    // zone is `0 < q ≤ 2⁻¹⁰²²`: for normal `q > 2⁻¹⁰²²` the dropped `−q³/3` is
    // `≪ ulp(q)` so the bare `q` is already correctly rounded, and `q = 0` (a fully
    // underflowed quotient) means the true ratio is `≤ 2⁻¹⁰⁷⁵`, whose `atan` rounds
    // to `0` — which the fast leg's `0` already gives.  Astronomically rare on real
    // input (needs `|y/x| ≤ 2⁻¹⁰²²`), and `q` is the quotient the fast leg already
    // needs, so the hot path is untouched.
    if !swapped && !x_negative && q > 0.0 && q <= f64::MIN_POSITIVE {
        return atan2_tint_mag(a, b, x_negative);
    }

    let theta = |cell: fn(DoubleDouble, DoubleDouble) -> DoubleDouble| {
        // φ = atan(q) ∈ [0, π/4] (`q = small/big`), or π/2 − atan(q) when `swapped`.
        let inner = if q < 9.094947017729282e-13 {
            // Tiny ratio: atan(q) = q far below ½ ulp, and the *unscaled* IEEE
            // quotient `small/big` is correctly rounded down into the subnormals.
            DoubleDouble { high: q, low: 0.0 }
        } else {
            // Scale both legs so the larger lands in [1, 2): exact and
            // ratio-preserving, keeping `small − c·big` / `big + c·small` clear of
            // overflow and the small leg out of the subnormals.
            let (_, exp) = super::frexp(big);
            let big = super::ldexp(big, 1 - exp);
            let small = super::ldexp(small, 1 - exp);

            // Cell reduction without forming small/big as a double-double: with
            // ratio = small/big, `u = (ratio − c)/(1 + ratio·c) = (small − c·big)/(big
            // + c·small)`.  `k = round(8·ratio)` reuses the `q` already in hand
            // (scaling preserves the ratio exactly), so the leg spends only that one
            // `q` division plus this `recip` — two, versus the four of the
            // `from_quotient` path (the `q` test, the two-division quotient, the cell
            // `recip`).  `small − c·big` is exact (c·big ≈ small in-cell, `from_product`
            // exact), so `u` is at least as accurate, and `|u| ≤ 1/16` as before.
            let k = (q * 8.0).round_ties_even();
            let c = k * 0.125;
            // SAFETY: q = small/big ∈ [0, 1] puts k in 0..=8 (see `atan_dd_fast`).
            let table = ATAN_TABLE[unsafe { k.to_int_unchecked::<i64>() } as usize];

            let num = DoubleDouble {
                high: small,
                low: 0.0,
            } + neg(DoubleDouble::from_product(c, big));
            let den = DoubleDouble {
                high: big,
                low: 0.0,
            } + DoubleDouble::from_product(c, small);
            let u = num * den.recip();

            cell(table, u)
        };

        let phi = if swapped {
            FRAC_PI_2 + neg(inner)
        } else {
            inner
        };
        if x_negative { PI + neg(phi) } else { phi }
    };

    ziv(theta(atan_cell_fast)).unwrap_or_else(|| atan2_tint_mag(a, b, x_negative))
}

/// Arctangent of `y / x`, using the signs of both to select the quadrant
///
/// The result is the angle in `(-π, π]` between the positive `x`-axis and the
/// point `(x, y)`, carrying the sign of `y`.
#[must_use]
#[inline]
pub fn atan2(y: f64, x: f64) -> f64 {
    use core::f64::consts::{FRAC_PI_2, FRAC_PI_4, PI};

    /// Correctly-rounded `f64` of 3π/4.
    const THREE_PI_4: f64 = 2.356194490192345;

    if x.is_nan() || y.is_nan() {
        return f64::NAN;
    }

    if x.is_infinite() || y.is_infinite() {
        let magnitude = match (x.is_infinite(), y.is_infinite()) {
            (true, true) if x.is_sign_positive() => FRAC_PI_4,
            (true, true) => THREE_PI_4,
            (true, false) if x.is_sign_positive() => 0.0,
            (true, false) => PI,
            (false, true) => FRAC_PI_2,
            (false, false) => unreachable!(),
        };
        return magnitude.copysign(y);
    }

    if y == 0.0 {
        return if x.is_sign_positive() { 0.0 } else { PI }.copysign(y);
    }
    if x == 0.0 {
        return FRAC_PI_2.copysign(y);
    }

    atan2_mag(x.abs(), y.abs(), x.is_sign_negative()).copysign(y)
}

// ===========================================================================
// Accurate 192-bit fixed-point (`Tint`) path for `atan2`.
//
// `atan2`'s hardest hard-to-round corpus tie is ≈2⁻¹⁵⁴ relative — beyond the
// 128-bit `Dint` path's ≈2⁻¹²⁶ reach.  This is an idiomatic Rust port of
// CORE-MATH's `binary64/atan2/tint.h` 192-bit arithmetic and the `atan2_accurate`
// rational kernel (`atan2.c`); reproducing CORE-MATH's own correctly-rounded
// algorithm is the surest route to bit-exact agreement with the `core-math`
// oracle on the strict worst-case gate.
//
// A [`Tint`] represents `(-1)^sgn·(hi/2¹²⁸ + lo/2¹⁹²)·2^ex`, with `hi`'s bit 127
// set for nonzero values — CORE-MATH packs the significand as three `u64` words
// `{h, m, l}`; here `hi = (h << 64) | m` and `lo = l`.  The kernel is a [29, 29]
// rational approximation `z·P(z)/Q(z)` of `atan(z)` on `[0, 1]` (`P`/`Q` from
// rminimax, relative error ≈2⁻¹⁹⁶), divided in `Tint` (`div_tint`, relative error
// ≈2⁻¹⁸⁵·⁵³), then rounded once with the error-bound-aware [`tint_tod`].  Constants
// `P_TINT`/`Q_TINT`/`PI2_TINT`/`PI_TINT` are copied verbatim from `atan2.c`.
//
// This block sits behind the existing Ziv gate, so the hot path is untouched.
// ===========================================================================

/// 192-bit fixed-point number used by the accurate `atan2` path.
///
/// Value = `(-1)^sgn · (hi/2¹²⁸ + lo/2¹⁹²) · 2^ex`.  For nonzero values bit 127
/// of `hi` is set.  `hi` packs CORE-MATH's `{h, m}` words, `lo` is its `l`.
#[derive(Debug, Clone, Copy)]
struct Tint {
    sgn: bool,
    ex: i64,
    hi: u128,
    lo: u64,
}

/// `0` as a `Tint` (port of CORE-MATH's `ZERO`).
const ZERO_TINT: Tint = Tint {
    sgn: false,
    ex: -1076,
    hi: 0,
    lo: 0,
};

/// `1` as a `Tint` (port of CORE-MATH's `ONE`).
const ONE_TINT: Tint = Tint {
    sgn: false,
    ex: 1,
    hi: 0x80000000000000000000000000000000,
    lo: 0,
};

/// π/2 as a `Tint`, error < 2⁻¹⁹⁷·⁹⁶ (port of CORE-MATH's `PI2`).
const PI2_TINT: Tint = Tint {
    sgn: false,
    ex: 1,
    hi: 0xc90fdaa22168c234c4c6628b80dc1cd1,
    lo: 0x29024e088a67cc74,
};

/// π as a `Tint`, error < 2⁻¹⁹⁶·⁹⁶ (port of CORE-MATH's `PI`).
const PI_TINT: Tint = Tint {
    sgn: false,
    ex: 2,
    hi: 0xc90fdaa22168c234c4c6628b80dc1cd1,
    lo: 0x29024e088a67cc74,
};

impl Tint {
    /// `true` if `self` is zero.
    #[inline]
    const fn is_zero(&self) -> bool {
        self.hi == 0
    }

    /// Negate (flip the sign bit).
    #[inline]
    const fn neg(self) -> Self {
        Self {
            sgn: !self.sgn,
            ..self
        }
    }

    /// Compare magnitudes: `Less`/`Equal`/`Greater` like `cmp_tint_abs`.
    #[inline]
    fn cmp_abs(&self, other: &Self) -> core::cmp::Ordering {
        use core::cmp::Ordering;
        if self.is_zero() {
            return if other.is_zero() {
                Ordering::Equal
            } else {
                Ordering::Less
            };
        }
        if other.is_zero() {
            return Ordering::Greater;
        }
        self.ex
            .cmp(&other.ex)
            .then_with(|| self.hi.cmp(&other.hi))
            .then_with(|| self.lo.cmp(&other.lo))
    }

    /// Significand `(hi, lo)` shifted right by `k` bits (port of `rshift`).
    #[inline]
    const fn rshift(&self, k: u32) -> (u128, u64) {
        if k == 0 {
            (self.hi, self.lo)
        } else if k < 64 {
            let hi = self.hi >> k;
            let lo = ((self.hi << (64 - k)) as u64) | (self.lo >> k);
            (hi, lo)
        } else if k == 64 {
            (self.hi >> 64, self.hi as u64)
        } else if k < 128 {
            (self.hi >> k, (self.hi >> (k - 64)) as u64)
        } else if k < 192 {
            (0, (self.hi >> (k - 64)) as u64)
        } else {
            (0, 0)
        }
    }

    /// Significand `(hi, lo)` shifted left by `k` bits (port of `lshift`).
    #[inline]
    fn lshift(&self, k: u32) -> (u128, u64) {
        if k == 0 {
            (self.hi, self.lo)
        } else if k < 64 {
            let hi = (self.hi << k) | u128::from(self.lo >> (64 - k));
            let lo = self.lo << k;
            (hi, lo)
        } else if k == 64 {
            ((self.hi << 64) | u128::from(self.lo), 0)
        } else if k < 128 {
            ((self.hi << k) | (u128::from(self.lo) << (k - 64)), 0)
        } else if k < 192 {
            (u128::from(self.lo) << (k - 64), 0)
        } else {
            (0, 0)
        }
    }

    /// Leading-zero count of the 192-bit significand `(hi, lo)`.
    #[inline]
    const fn clz192(hi: u128, lo: u64) -> u32 {
        if hi != 0 {
            hi.leading_zeros()
        } else {
            128 + lo.leading_zeros()
        }
    }

    /// Round-to-nearest product, error < 10 ulp / 2⁻¹⁸⁷·⁶⁷·|r| (port of `mul_tint`).
    #[inline]
    fn mul(&self, other: &Self) -> Self {
        let ah = u128::from((self.hi >> 64) as u64);
        let am = u128::from(self.hi as u64);
        let al = u128::from(self.lo);
        let bh = u128::from((other.hi >> 64) as u64);
        let bm = u128::from(other.hi as u64);
        let bl = u128::from(other.lo);

        let rh = ah * bh;
        let rm1 = ah * bm;
        let rm2 = am * bh;
        let rl1 = ah * bl;
        let rl2 = am * bm;
        let rl3 = al * bh;

        let mut r_h = (rh >> 64) as u64;
        let mut r_m = rh as u64;
        let mut r_l = rm1 as u64;

        // accumulate rm1
        let h = (rm1 >> 64) as u64;
        let (nm, c) = r_m.overflowing_add(h);
        r_m = nm;
        r_h = r_h.wrapping_add(u64::from(c));
        // accumulate rm2
        let l = rm2 as u64;
        let h = (rm2 >> 64) as u64;
        let (nl, c0) = r_l.overflowing_add(l);
        r_l = nl;
        let mut cm = u64::from(c0);
        let (nm, c) = r_m.overflowing_add(h);
        r_m = nm;
        r_h = r_h.wrapping_add(u64::from(c));
        // accumulate rl1 + rl2 + rl3 (high words)
        let rl = (rl1 >> 64) + (rl2 >> 64) + (rl3 >> 64);
        let l = rl as u64;
        cm = cm.wrapping_add((rl >> 64) as u64);
        let (nl, c0) = r_l.overflowing_add(l);
        r_l = nl;
        cm = cm.wrapping_add(u64::from(c0));
        // accumulate cm
        let (nm, c) = r_m.overflowing_add(cm);
        r_m = nm;
        r_h = r_h.wrapping_add(u64::from(c));

        let mut hi = (u128::from(r_h) << 64) | u128::from(r_m);
        let mut lo = r_l;
        let mut ex = self.ex + other.ex;

        // normalize so bit 127 is set (unless zero)
        if hi >> 127 == 0 {
            hi = (hi << 1) | u128::from(lo >> 63);
            lo <<= 1;
            ex -= 1;
        }

        Self {
            sgn: self.sgn ^ other.sgn,
            ex,
            hi,
            lo,
        }
    }

    /// Round-to-nearest sum, error ≤ 2 ulp (port of `add_tint`).
    #[inline]
    fn add(&self, other: &Self) -> Self {
        use core::cmp::Ordering;
        let (a, b) = match self.cmp_abs(other) {
            Ordering::Equal => {
                // |a| = |b|: return 0 (opposite signs) or 2·a (same sign), exact.
                if self.sgn != other.sgn {
                    return ZERO_TINT;
                }
                return Self {
                    ex: self.ex + 1,
                    ..*self
                };
            }
            Ordering::Less => (other, self),
            Ordering::Greater => (self, other),
        };

        // |a| > |b|, so a.ex >= b.ex.
        let sh = (a.ex - b.ex) as u32;
        let (t_hi, t_lo) = b.rshift(sh);

        if a.sgn != b.sgn {
            // opposite signs: subtraction a - (shifted b)
            let (l, borrow0) = a.lo.overflowing_sub(t_lo);
            let h = a.hi.wrapping_sub(t_hi).wrapping_sub(u128::from(borrow0));
            let ex = Self::clz192(h, l);
            if ex <= 1 || sh == 0 {
                let tmp = Self {
                    sgn: false,
                    ex: 0,
                    hi: h,
                    lo: l,
                };
                let (rhi, rlo) = tmp.lshift(ex);
                Self {
                    sgn: a.sgn,
                    ex: a.ex - i64::from(ex),
                    hi: rhi,
                    lo: rlo,
                }
            } else {
                // ex >= 2 and sh >= 1: re-do the subtraction with no neglected
                // bits of b (shift both a and b left by `ex`).
                let (tb_hi, tb_lo) = b.lshift(ex - sh);
                let (ra_hi, ra_lo) = a.lshift(ex);
                let (l2, borrow) = ra_lo.overflowing_sub(tb_lo);
                let h2 = ra_hi.wrapping_sub(tb_hi).wrapping_sub(u128::from(borrow));
                let ex1 = Self::clz192(h2, l2);
                let tmp = Self {
                    sgn: false,
                    ex: 0,
                    hi: h2,
                    lo: l2,
                };
                let (rhi, rlo) = tmp.lshift(ex1);
                Self {
                    sgn: a.sgn,
                    ex: a.ex - i64::from(ex + ex1),
                    hi: rhi,
                    lo: rlo,
                }
            }
        } else {
            // same signs: addition
            let (l, cl) = a.lo.overflowing_add(t_lo);
            let (mut h, ch0) = a.hi.overflowing_add(t_hi);
            let mut ch = u128::from(ch0);
            let (h2, ch1) = h.overflowing_add(u128::from(cl));
            h = h2;
            ch += u128::from(ch1);
            if ch != 0 {
                // carry out of bit 127: shift right one, restoring the carry bit.
                let lo = ((h as u64) << 63) | (l >> 1);
                let hi = (ch << 127) | (h >> 1);
                Self {
                    sgn: a.sgn,
                    ex: a.ex + 1,
                    hi,
                    lo,
                }
            } else {
                Self {
                    sgn: a.sgn,
                    ex: a.ex,
                    hi: h,
                    lo: l,
                }
            }
        }
    }

    /// Convert a finite nonzero `f64` to a `Tint`, exactly (port of `tint_fromd`).
    #[inline]
    fn from_f64(x: f64) -> Self {
        let u = x.to_bits();
        let sgn = u >> 63 == 1;
        let ax = u & 0x7fff_ffff_ffff_ffff;
        let e = (ax >> 52) as i64;
        let (ex, h) = if e != 0 {
            // normal: 1 has e = 0x3ff
            (e - 0x3fe, (1u64 << 63) | (ax << 11))
        } else {
            // subnormal: 2^-1074 has ax = 1
            let lz = ax.leading_zeros();
            (-0x3f2 - i64::from(lz), ax << lz)
        };
        Self {
            sgn,
            ex,
            hi: u128::from(h) << 64,
            lo: 0,
        }
    }

    /// Convert to `f64` with correct rounding (port of `tint_tod`).
    ///
    /// `err` is a bound in ulps (of 2⁻¹⁹²) on the error of `lo`; `err == 0` means
    /// an exact value.  `atan2` magnitudes fed here are in `[0, π]` but can be
    /// subnormal in the first-quadrant `atan(small/big)` corner, so the subnormal
    /// (and the extreme-underflow) branches do fire and are ported faithfully;
    /// the overflow branch cannot but is kept for completeness.
    #[inline]
    #[allow(clippy::wrong_self_convention)] // `Tint` is `Copy`; `&self` avoids a move (cf. `Dint::to_f64`)
    fn to_f64(&self, err: u64) -> f64 {
        if self.ex >= 1025 {
            return if self.sgn {
                f64::NEG_INFINITY
            } else {
                f64::INFINITY
            };
        }
        if self.ex <= -1074 {
            if self.ex < -1074 {
                return (if self.sgn { -1.0 } else { 1.0 })
                    * f64::from_bits(0x0000_0000_0000_0001)
                    * 0.5;
            }
            let mid = self.hi == (1u128 << 127) && self.lo == 0;
            return (if self.sgn { -1.0 } else { 1.0 })
                * f64::from_bits(0x0000_0000_0000_0001)
                * if mid { 0.5 } else { 0.75 };
        }

        let mut hh = (self.hi >> 64) as u64;
        let mut mm = self.hi as u64;
        let mut ll = self.lo;
        let mut ex = self.ex;
        let mut low = hh & 0x7ff;

        if ex <= -1022 {
            // subnormal result: shift the significand right by `sh`.
            let sh = (-1021 - ex) as u32; // 1..=52
            ll = (mm << (64 - sh)) | (ll >> sh) | u64::from(ll > 0);
            mm = (hh << (64 - sh)) | (mm >> sh);
            hh >>= sh;
            low = hh & 0x7ff;
            ex += i64::from(sh);
        }

        let h_top = (hh >> 11) as f64; // top 53 bits
        let l = if err == 0 {
            0.0
        } else if low < 0x400 {
            0.25 // round toward zero
        } else if low > 0x400 {
            0.75 // round away
        } else if mm == 0 && ll == 0 {
            0.5 // exact midpoint
        } else {
            0.75 // round away
        };

        let s = if self.sgn { -1.0 } else { 1.0 };
        let mut h = crate::fma(l, s, s * h_top);
        h *= f64::from_bits(0x3cb0_0000_0000_0000); // 2^-52
        // -1021 <= ex <= 1024, so 2^(ex-1) neither under- nor overflows.
        h * super::ldexp(1.0, (ex - 1) as i32)
    }

    /// Approximate `1/self`, relative error ≤ 2⁻¹⁰³·⁹ (port of `inv_tint`).
    #[inline]
    fn inv(&self) -> Self {
        let a = self.to_f64(0); // exact
        let subnormal = a.abs() < f64::MIN_POSITIVE;
        let a = if subnormal {
            a * f64::from_bits(0x4350_0000_0000_0000) // 2^53
        } else {
            a
        };
        let mut r = Self::from_f64(1.0 / a);
        if subnormal {
            r.ex += 53;
        }
        // Newton: r ← r + r·(1 − a·r).
        let mut q = self.mul(&r);
        q.sgn = !q.sgn; // -a·r
        q = ONE_TINT.add(&q); // 1 - a·r
        q = r.mul(&q); // r·(1 - a·r)
        r.add(&q)
    }

    /// Approximate `b/self` (= `b/a`), relative error ≤ 2⁻¹⁸⁵·⁵³ (port of `div_tint`).
    #[inline]
    fn div(b: &Self, a: &Self) -> Self {
        let y = a.inv(); // |y - 1/a| small
        let mut r = y.mul(b); // r ≈ b/a
        // Karp–Markstein: r ← r + y·(b − a·r).
        let mut z = a.mul(&r); // a·r
        z.sgn = !z.sgn; // -a·r
        z = b.add(&z); // b - a·r
        z = y.mul(&z); // y·(b - a·r)
        r = r.add(&z);
        r
    }

    /// `b / a` for `f64` inputs (port of `div_tint_d`).
    #[inline]
    fn div_d(b: f64, a: f64) -> Self {
        Self::div(&Self::from_f64(b), &Self::from_f64(a))
    }
}

/// `P(z)` coefficients of the [29, 29] `atan` rational, high-degree last — copied
/// verbatim from CORE-MATH `atan2.c`.
#[rustfmt::skip]
const P_TINT: [Tint; 30] = [
    Tint { sgn: false, ex: -10, hi: 0x82703f8b53112eca71ce6279d467aa45, lo: 0x019c9b28466b6fc0 },
    Tint { sgn: false, ex: -8, hi: 0xb3cf74b427d53e03ee590b839e751890, lo: 0xf2570b12bcb2381a },
    Tint { sgn: false, ex: -6, hi: 0xb08498b17b88c39a11e37821d784d8fa, lo: 0x2795b14b84b9d78c },
    Tint { sgn: false, ex: -5, hi: 0xfd4baa7bb52b0d83b25425beb0a04dc3, lo: 0x92008d9fb34b68ff },
    Tint { sgn: false, ex: -3, hi: 0x96541948b85fb386e0b815ace425a859, lo: 0xbeca17c69bb4f7a0 },
    Tint { sgn: false, ex: -2, hi: 0x96aaa5d4baffc590f23db783b6e4ce55, lo: 0x2c54e054d3b69f7e },
    Tint { sgn: false, ex: -1, hi: 0x83cd41b5fa862b11ad8f9d6e3eb9d833, lo: 0x4ef470d801fa03ca },
    Tint { sgn: false, ex: -1, hi: 0xcbbc7752197cc106bc66cfb3edefa6e3, lo: 0x568b2f9e4feb8910 },
    Tint { sgn: false, ex: 0, hi: 0x8cf8f7c585767042cd92a5b9ac13d8c8, lo: 0x043bd4a023dbe04d },
    Tint { sgn: false, ex: 0, hi: 0xafdc36d6b36139bf11df63474e3859d4, lo: 0x42b30b2c089a2b6c },
    Tint { sgn: false, ex: 0, hi: 0xc6f8fb14638225192f9f04cf55c10377, lo: 0x1c44675c6d483606 },
    Tint { sgn: false, ex: 0, hi: 0xcce79f10f754e31591ce47edcbc8a4ee, lo: 0xb2a6f721ac656b42 },
    Tint { sgn: false, ex: 0, hi: 0xc090384dbd77132e1dfb4d9a1d595de7, lo: 0xe506ca899a394f70 },
    Tint { sgn: false, ex: 0, hi: 0xa556ac9eee25e867d84dafa25141d203, lo: 0xf1c7c2a5156b3ec3 },
    Tint { sgn: false, ex: 0, hi: 0x81bd2677ddfcbc381df33f27dbb60939, lo: 0xcb4c2c73286a6c29 },
    Tint { sgn: false, ex: -1, hi: 0xb9ed12169d72e8d9c81d95dcef13c227, lo: 0x974b95796b93c332 },
    Tint { sgn: false, ex: -2, hi: 0xf2df6da875b666fac29dd3a69c274c65, lo: 0x83b9260976c8f0c5 },
    Tint { sgn: false, ex: -2, hi: 0x902d34d4db910ed86f3ecddfd6af0a9f, lo: 0x8e950d7e70a8e9b2 },
    Tint { sgn: false, ex: -3, hi: 0x9aefa41961ce1207acd0317666753751, lo: 0x3eaf42a53fcc6534 },
    Tint { sgn: false, ex: -4, hi: 0x95db9977c5e6e26385367a63fab8a720, lo: 0xfc2b63bd115998d8 },
    Tint { sgn: false, ex: -5, hi: 0x817cb6d8236d5f4d70c7815f28909d9b, lo: 0x0c54e97155d12158 },
    Tint { sgn: false, ex: -7, hi: 0xc5eec4228c352098789e56be1dee9b67, lo: 0xba25bda81292ccc1 },
    Tint { sgn: false, ex: -8, hi: 0x840c38ccfcb5dc64b55a44095bf7f312, lo: 0x6668b8792d4ecd08 },
    Tint { sgn: false, ex: -10, hi: 0x97074af7b286b19ec20aac21f3130f1d, lo: 0x369e9fdbdd48528a },
    Tint { sgn: false, ex: -12, hi: 0x9054011c32d4b7a5c68d3c5d525f4af4, lo: 0xeeb3c98615dee188 },
    Tint { sgn: false, ex: -15, hi: 0xdddb4a2eaab2bb15753761a8f0e9aa8d, lo: 0x3f20620cd3e075bb },
    Tint { sgn: false, ex: -17, hi: 0x80ef9a1b3e59abe518e6afe0651fdf49, lo: 0xd1c0329e6a702d9d },
    Tint { sgn: false, ex: -21, hi: 0xca16dd49cd30854cbad8ca379401027c, lo: 0x1fc7f47985486f16 },
    Tint { sgn: false, ex: -25, hi: 0xa0ba01b8742ba801e6dc14a9516d7f04, lo: 0x1f5303d878905d2f },
    Tint { sgn: true, ex: -59, hi: 0x9c0440896ce6515c0cf3470fa7f10ac3, lo: 0xa9dc80682c111a9d },
];

/// `Q(z)` coefficients of the [29, 29] `atan` rational, high-degree last — copied
/// verbatim from CORE-MATH `atan2.c`.
#[rustfmt::skip]
const Q_TINT: [Tint; 30] = [
    Tint { sgn: false, ex: -10, hi: 0x82703f8b53112eca71ce6279d467aa45, lo: 0x019c9b28466b6fc0 },
    Tint { sgn: false, ex: -8, hi: 0xb3cf74b427d53e03ee590b839e751890, lo: 0xf2570b12bcb238cf },
    Tint { sgn: false, ex: -6, hi: 0xb33c44af0d43c9e8f4426f84614701db, lo: 0x979e49dc5b858442 },
    Tint { sgn: false, ex: -4, hi: 0x8264d256f0bf4d61ee21431cc0f29764, lo: 0xce0cc1b593ac9952 },
    Tint { sgn: false, ex: -3, hi: 0x9d97c4947687b2eeef4087c49dde5229, lo: 0x742bc6e02bfb6df8 },
    Tint { sgn: false, ex: -2, hi: 0xa0f888dc7aab949ef623f19ac413db23, lo: 0x854744a164f70ecd },
    Tint { sgn: false, ex: -1, hi: 0x8fd9c7172ab0828e1a9f72fadafc3dfb, lo: 0xaf96a180ea297178 },
    Tint { sgn: false, ex: -1, hi: 0xe38168b78a51ee15604a47815c8091eb, lo: 0x9faaa42312e8eb30 },
    Tint { sgn: false, ex: 0, hi: 0xa164ccdbb65ee133e623433c5e086402, lo: 0xcb228afd335a245f },
    Tint { sgn: false, ex: 0, hi: 0xced0c0cbe44fac2fd7c2adfc7c5dda9e, lo: 0xa22b4a311cf5a5b1 },
    Tint { sgn: false, ex: 0, hi: 0xf0e6660438c903713dca1a0f58f0d943, lo: 0x8a92b9de68c4488c },
    Tint { sgn: false, ex: 1, hi: 0x80000000000000000000000000000000, lo: 0x0000000000000000 },
    Tint { sgn: false, ex: 0, hi: 0xf8ea68f9ad849103b257e4bfc606967f, lo: 0x818fa2816928c4aa },
    Tint { sgn: false, ex: 0, hi: 0xddc64eeee350623447a33ea40a2b22e4, lo: 0xa6a2c129ace2470a },
    Tint { sgn: false, ex: 0, hi: 0xb52ddfba2d37c8e224551a9b19fa064a, lo: 0x3d78c68b54bc3850 },
    Tint { sgn: false, ex: 0, hi: 0x87ac113d26b683a14e97756c38785b0b, lo: 0xf75f0a4506931ba8 },
    Tint { sgn: false, ex: -1, hi: 0xba065070b900f3d5e49d8f9f238f1eeb, lo: 0x6805d48d67f1dcd9 },
    Tint { sgn: false, ex: -2, hi: 0xe902d2a4bfc22441945cfe6c83a5b828, lo: 0x519ebb457f8ccca0 },
    Tint { sgn: false, ex: -2, hi: 0x84e405c915f7769b0faaf34c3c51dd39, lo: 0xa97fa0ae99382c93 },
    Tint { sgn: false, ex: -3, hi: 0x896da46c7e6cebb3e0afc0b6db3dbbf5, lo: 0x061ccff6e78efff4 },
    Tint { sgn: false, ex: -4, hi: 0x801a0c1a0dfefc92f8e0a97902e08d47, lo: 0x81898e0b7d8ef0bc },
    Tint { sgn: false, ex: -6, hi: 0xd59d088930df07dba8cb00021849fbaf, lo: 0xf80cc91aa0bddf89 },
    Tint { sgn: false, ex: -7, hi: 0x9db56a6984b77231cf7c2074e0480959, lo: 0x3316ecaa6aa4604e },
    Tint { sgn: false, ex: -9, hi: 0xcb7450d9d62d2e689787b4265977d004, lo: 0xba615cee00a841d7 },
    Tint { sgn: false, ex: -11, hi: 0xe12a52e02b64b23e97c9139a8ced716c, lo: 0x70a176ad2b5f16d2 },
    Tint { sgn: false, ex: -13, hi: 0xd057b6d0900ed30d5e04bb17eb879a5e, lo: 0x23ed135b60bea070 },
    Tint { sgn: false, ex: -15, hi: 0x9b1f1ca22fef7ae519a687f0a4073eee, lo: 0x05a9ccbc8c14578b },
    Tint { sgn: false, ex: -18, hi: 0xaeba710f053aac3b30ea5d6fb116f775, lo: 0x8a9bcfef5698f8f1 },
    Tint { sgn: false, ex: -21, hi: 0x84b9ada076cd007d13e55006073f76b1, lo: 0x4cf4259968228f3e },
    Tint { sgn: false, ex: -26, hi: 0xcca4b9046786937d233c1e691c127c1f, lo: 0xf493e0b7a3de459a },
];

/// `atan2`'s magnitude in `[0, π]` for finite nonzero `a = |x|`, `b = |y|`, as a
/// correctly-rounded `f64`.  The 192-bit accurate fallback, mirroring CORE-MATH's
/// `atan2_accurate` for the non-degenerate finite case (the NaN/∞/zero/axis and
/// underflow special cases are already handled upstream by [`atan2`]/[`atan2_mag`]
/// before the Ziv gate escalates here).
#[cold]
#[inline(never)]
fn atan2_tint_mag(a: f64, b: f64, x_negative: bool) -> f64 {
    // inv = |y| > |x| (CORE-MATH's `inv`), i.e. metallic's `swapped`.  In either
    // case z = small/big ∈ [0, 1].
    let inv = b > a;
    let (num, den) = if inv { (a, b) } else { (b, a) };
    let mut z = Tint::div_d(num, den);

    // Tiny ratio with the larger leg as x (inv = 0): atan(z) rounds to z perturbed
    // a hair toward zero — match CORE-MATH's `z->l -= 2; … tint_tod(z, 1)`.
    if !inv && z.ex <= -96 {
        let (lo, borrow) = z.lo.overflowing_sub(2);
        z.lo = lo;
        z.hi = z.hi.wrapping_sub(u128::from(borrow));
        return z.to_f64(1);
    }

    // z·P(z)/Q(z), the [29, 29] rational approximation of atan on [0, 1].
    let mut p = P_TINT[29];
    let mut q = Q_TINT[29];
    for i in (0..29).rev() {
        p = p.mul(&z);
        q = q.mul(&z);
        p = p.add(&P_TINT[i]);
        q = q.add(&Q_TINT[i]);
    }
    p = p.mul(&z); // p ← z·P(z)
    let mut z = Tint::div(&p, &q); // z ← atan(small/big) ∈ [0, π/4]

    // φ = atan(small/big), or π/2 − atan(small/big) when swapped (`inv`); then
    // x < 0 ⇒ opposite quadrant θ = π − φ.  Since a, b ≥ 0, z ≥ 0, the magnitude
    // stays non-negative throughout.  `err` is the ulp bound CORE-MATH attaches to
    // the *last* applied fold (z·P/Q: 662, +π/2: 524, +π: 266).
    if inv {
        z = PI2_TINT.add(&z.neg());
    }
    if x_negative {
        z = PI_TINT.add(&z.neg());
    }
    let err = if x_negative {
        266
    } else if inv {
        524
    } else {
        662
    };

    z.to_f64(err)
}

/// The Fast2Sum-based folds of [`atan_cell_fast`] need `|a| ≥ |b|`; prove the
/// orderings from coefficient-magnitude bounds at the cell edge `|u| ≤ 1/16`
/// (cf. the same-named modules in `erf.rs` and `trig.rs`).
#[cfg(test)]
mod fold_ordering {
    use super::*;

    #[test]
    fn atan_cell() {
        // Slack for the rounding of u (one lean division) and w = u·u.
        let umax = 0.0625 * 1.0001;
        let wmax = umax * umax;
        let tail_mag = ATAN_TAIL
            .iter()
            .rev()
            .fold(0.0, |acc, c| crate::fast_mul_add(acc, wmax, c.abs()));

        // bracket = 1 ⊕ w·(−1/3) ⊕ w²·tail
        let c1_mag = ATAN_COEFFS[1].high.abs() + ATAN_COEFFS[1].low.abs();
        assert!(wmax * c1_mag <= 0.5);
        let lead_min = 1.0 - wmax * c1_mag;
        assert!(wmax * wmax * tail_mag <= 0.5 * lead_min);

        // table ⊕ u·bracket for k ≥ 1 (k = 0 has table = 0, where Fast2Sum is
        // exact by itself); the k = 1 cell is the tightest at 0.504.
        let bracket_mag = crate::fast_mul_add(wmax * wmax, tail_mag, 1.0 + wmax * c1_mag);
        for cell in &ATAN_TABLE[1..] {
            assert!(umax * bracket_mag <= 0.55 * cell.high.abs());
        }
    }

    /// [`asin_tail`]'s `off ⊕ p` fold: `|off| ≥ |p.high|` for every nonzero
    /// offset (`off = 0`, asin's direct branch, is exact unconditionally).
    /// `|p.high| ≤ Bmax·|z|·(1 + ε)` with `Bmax = B(¼)` the largest table lead;
    /// `|z| ≤ 1` in the reflections (`√t ≤ 1`) and `|z| ≤ ½` in acos's direct
    /// branch.
    #[test]
    fn asin_offsets() {
        let bmax = ASIN_CELLS
            .iter()
            .map(|cell| cell.lead.high)
            .fold(0.0, f64::max)
            * 1.0001;

        // Reflections: off = ±π/2 (asin) or π (acos, x < −½) vs |p| ≤ Bmax.
        assert!(bmax <= 0.7 * FRAC_PI_2.high);
        assert!(bmax <= 0.35 * PI.high);
        // acos direct: off = π/2 vs |p| ≤ Bmax/2.
        assert!(0.5 * bmax <= 0.35 * FRAC_PI_2.high);
    }
}
