//! Error function family: `erf`, `erfc`.
//!
//! `erf(x) = x·P(x²)` for `|x| < 0.4375`; otherwise `erfc(x) = t·exp(Q(t) − x²)`
//! with `t = 2/(2+x)`, `Q` a per-segment double-double minimax (see
//! `tools/gen_erf_f64.py`), and `x²` formed exactly so the Gaussian decay is
//! subtracted without loss.  `erf` is odd; for `|x| ∈ [0.4375, 6.25]` it skips
//! the `erfc` bridge entirely, reading `erf(x) = P_i(x − i/8)` from a per-cell
//! table ([`ERF_TABLE`], no `exp`) and Ziv-gating against the bridge.  Each
//! kernel has a lean lower-degree double-double fast leg (a plain-f64 polynomial
//! cannot gate, since erfc's relative error equals `Q`'s *absolute* error)
//! accepted by a Ziv test, falling back to the ≈2⁻¹⁰⁰ accurate path on a
//! rounding-boundary straddle — past `f64` correct-rounding hardness.
//!
//! Constants below were generated by `tools/gen_erf_f64.py`.
//! Do not edit by hand; re-run the generator instead.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::double::{DoubleDouble, fast_ldexp, round_general64};
use super::exp::{exp_dd_of_dd, exp_dd_of_dd_fast};
use super::pow::poly_dd;

/// `1` as a double-double.
const ONE: DoubleDouble = DoubleDouble {
    high: 1.0,
    low: 0.0,
};

/// `2` as a double-double.
const TWO: DoubleDouble = DoubleDouble {
    high: 2.0,
    low: 0.0,
};

/// `erfc` rounds to `2` (covering `−∞`) below this; `erf` rounds to `±1`.
const ERF_ONE_THRESHOLD: f64 = 6.2499218008406645;

/// `erfc` underflows to `+0` (covering `+∞`) at and above this.
const ERFC_ZERO_THRESHOLD: f64 = 27.226017111108362;

// generated by tools/gen_erf_f64.py
// erf(x) = x·P(x²) on |x| < 0.4375;  P degree 15 in u=x², err 2^-118.4
const ERF_SMALL_DD: [DoubleDouble; 16] = [
    DoubleDouble {
        high: 1.1283791670955126,
        low: 1.533545961316588e-17,
    },
    DoubleDouble {
        high: -0.37612638903183754,
        low: 1.3391897206030655e-17,
    },
    DoubleDouble {
        high: 0.11283791670955126,
        low: -4.0175691618118906e-18,
    },
    DoubleDouble {
        high: -0.026866170645131252,
        low: 4.609288077678567e-19,
    },
    DoubleDouble {
        high: 0.005223977625442188,
        low: -8.96250895042019e-20,
    },
    DoubleDouble {
        high: -0.0008548327023450853,
        low: 5.015132978976641e-20,
    },
    DoubleDouble {
        high: 0.00012055332981789664,
        low: 6.391221799534458e-21,
    },
    DoubleDouble {
        high: -1.4925650358406249e-05,
        low: -6.848769611544024e-23,
    },
    DoubleDouble {
        high: 1.6462114365888842e-06,
        low: -4.6549092472916755e-23,
    },
    DoubleDouble {
        high: -1.6365844691181628e-07,
        low: -2.1878263605639336e-24,
    },
    DoubleDouble {
        high: 1.4807192810742006e-08,
        low: 1.248256796417369e-25,
    },
    DoubleDouble {
        high: -1.2290554938446621e-09,
        low: -2.899240073963671e-26,
    },
    DoubleDouble {
        high: 9.422740442099754e-11,
        low: -2.771104336145256e-27,
    },
    DoubleDouble {
        high: -6.710693195377349e-12,
        low: -2.808745663185989e-28,
    },
    DoubleDouble {
        high: 4.446897629064001e-13,
        low: 1.0803824271972625e-29,
    },
    DoubleDouble {
        high: -2.5445305753090255e-14,
        low: -7.771717274552761e-32,
    },
];

/// Fast double-double `P(x²)` for `erf` (degree 10, err 2^-77.0)
const ERF_SMALL_FAST: [DoubleDouble; 11] = [
    DoubleDouble {
        high: 1.1283791670955126,
        low: 1.533545278214139e-17,
    },
    DoubleDouble {
        high: -0.37612638903183754,
        low: 1.3400534378241897e-17,
    },
    DoubleDouble {
        high: 0.11283791670955126,
        low: -5.8231177902760304e-18,
    },
    DoubleDouble {
        high: -0.026866170645131103,
        low: -1.4844550912107413e-18,
    },
    DoubleDouble {
        high: 0.005223977625436028,
        low: 3.1372627882040133e-19,
    },
    DoubleDouble {
        high: -0.0008548327021947103,
        low: 9.1017920370759e-21,
    },
    DoubleDouble {
        high: 0.000120553327528045,
        low: -2.061800885865239e-21,
    },
    DoubleDouble {
        high: -1.492562794601489e-05,
        low: 5.246582608852405e-22,
    },
    DoubleDouble {
        high: 1.6460703039923511e-06,
        low: -9.013357578406715e-23,
    },
    DoubleDouble {
        high: -1.6310490278943735e-07,
        low: -2.744612567485127e-24,
    },
    DoubleDouble {
        high: 1.3570810993535321e-08,
        low: -1.7588057602646025e-25,
    },
];

// erfc(x) = t·exp(Q(t) − x²), t = 2/(2+x); Q fit per x-segment in v = t − anchor
/// Upper x-bounds of the 5 erfc segments (last = erfc→0 threshold)
const ERFC_BREAKS: [f64; 5] = [1.0, 2.0, 4.0, 8.0, 27.226017111108362];
// segment 0: x∈[0.4375,1] t∈[0.6667,0.8205] deg 22/14 err 2^-111.1/2^-73.7 max|c|=1.38e+00
// segment 1: x∈[1,2] t∈[0.5000,0.6667] deg 23/15 err 2^-114.1/2^-76.4 max|c|=1.35e+00
// segment 2: x∈[2,4] t∈[0.3333,0.5000] deg 24/15 err 2^-114.5/2^-73.6 max|c|=6.47e+00
// segment 3: x∈[4,8] t∈[0.2000,0.3333] deg 23/14 err 2^-112.9/2^-72.2 max|c|=2.40e+01
// segment 4: x∈[8,27.226] t∈[0.0684,0.2000] deg 23/14 err 2^-112.1/2^-72.9 max|c|=4.29e+01

/// Per-segment anchors `t_anchor` (the segment's smallest `t`)
const ERFC_ANCHORS: [f64; 5] = [
    0.6666666666666666,
    0.5,
    0.3333333333333333,
    0.2,
    0.06843217782281495,
];

/// Q(t) for erfc segment 0, double-double, in v = t − ERFC_ANCHORS[0]
const ERFC_Q0: [DoubleDouble; 23] = [
    DoubleDouble {
        high: -0.4441404018250839,
        low: -9.41351714273149e-18,
    },
    DoubleDouble {
        high: 1.3753538140565607,
        low: 2.0031530411639827e-17,
    },
    DoubleDouble {
        high: -0.010952662344169231,
        low: 7.764778580560139e-19,
    },
    DoubleDouble {
        high: -0.3994330351052538,
        low: -1.3990052301547717e-17,
    },
    DoubleDouble {
        high: 0.0784305485061834,
        low: 3.922223167988192e-18,
    },
    DoubleDouble {
        high: 0.23793229996552565,
        low: -7.985980966721028e-18,
    },
    DoubleDouble {
        high: -0.16291716598150036,
        low: -3.7885129382489175e-18,
    },
    DoubleDouble {
        high: -0.11567708828558147,
        low: 6.4507183660161446e-18,
    },
    DoubleDouble {
        high: 0.21353879979545554,
        low: 8.835005329524048e-18,
    },
    DoubleDouble {
        high: -0.029330251130265304,
        low: -1.4042005532721465e-18,
    },
    DoubleDouble {
        high: -0.18427806430324156,
        low: -1.7715304388190658e-19,
    },
    DoubleDouble {
        high: 0.16212327825812206,
        low: 6.651727118649996e-18,
    },
    DoubleDouble {
        high: 0.058766061391490015,
        low: 1.6320451650378991e-18,
    },
    DoubleDouble {
        high: -0.20582885276154994,
        low: 4.804647886901292e-18,
    },
    DoubleDouble {
        high: 0.10663574237424135,
        low: -6.910084712637336e-18,
    },
    DoubleDouble {
        high: 0.11487811900541839,
        low: 5.413339579425691e-18,
    },
    DoubleDouble {
        high: -0.1981522073296446,
        low: 3.6182543736731205e-18,
    },
    DoubleDouble {
        high: 0.05374140836680304,
        low: -3.615104975328466e-19,
    },
    DoubleDouble {
        high: 0.14575275669341278,
        low: 5.48745242361761e-18,
    },
    DoubleDouble {
        high: -0.18359575699777783,
        low: -9.961854137628347e-18,
    },
    DoubleDouble {
        high: 0.05259233378499451,
        low: -1.7104035402157247e-18,
    },
    DoubleDouble {
        high: 0.06345765633428617,
        low: 2.9141674880660926e-19,
    },
    DoubleDouble {
        high: -0.050809147317222914,
        low: 1.439228639206579e-18,
    },
];

/// Q(t) for erfc segment 1, double-double, in v = t − ERFC_ANCHORS[1]
const ERFC_Q1: [DoubleDouble; 24] = [
    DoubleDouble {
        high: -0.6717940840566923,
        low: 1.0502374833696444e-17,
    },
    DoubleDouble {
        high: 1.3452864479553135,
        low: 9.246277860269923e-17,
    },
    DoubleDouble {
        high: 0.189373227367616,
        low: 4.198422702282501e-18,
    },
    DoubleDouble {
        high: -0.37516488184947366,
        low: 2.1184806795294514e-17,
    },
    DoubleDouble {
        high: -0.15796302986172733,
        low: -1.1427291835575572e-17,
    },
    DoubleDouble {
        high: 0.2823980338376569,
        low: 1.776448344421225e-17,
    },
    DoubleDouble {
        high: 0.11257174763857569,
        low: 2.5377193190030884e-18,
    },
    DoubleDouble {
        high: -0.3002640009585259,
        low: 1.982753539331692e-18,
    },
    DoubleDouble {
        high: -0.03743919326846465,
        low: 1.99310782836026e-18,
    },
    DoubleDouble {
        high: 0.3449235820158272,
        low: 1.0436957269477124e-17,
    },
    DoubleDouble {
        high: -0.09598481238739336,
        low: -4.918705205179117e-18,
    },
    DoubleDouble {
        high: -0.35697347682698743,
        low: -1.807973994389437e-17,
    },
    DoubleDouble {
        high: 0.29246198522833705,
        low: 1.2183341030257904e-17,
    },
    DoubleDouble {
        high: 0.26007504393736897,
        low: 2.1211765195817654e-17,
    },
    DoubleDouble {
        high: -0.49465584428513715,
        low: -2.66889979202106e-17,
    },
    DoubleDouble {
        high: 0.004288120742416014,
        low: -2.9478327536717557e-19,
    },
    DoubleDouble {
        high: 0.5618423254126301,
        low: 2.9156512798635925e-17,
    },
    DoubleDouble {
        high: -0.38454418838680854,
        low: -1.459906206314984e-17,
    },
    DoubleDouble {
        high: -0.33903666254822123,
        low: 2.0837193920267655e-17,
    },
    DoubleDouble {
        high: 0.6428819440072338,
        low: 3.141730881919712e-17,
    },
    DoubleDouble {
        high: -0.13211292944690015,
        low: 1.0821653113462724e-17,
    },
    DoubleDouble {
        high: -0.5209331316024544,
        low: 2.551488493585705e-17,
    },
    DoubleDouble {
        high: 0.5869002443592323,
        low: 2.6726157838127785e-18,
    },
    DoubleDouble {
        high: -0.22291257098763628,
        low: -1.3120918190301473e-17,
    },
];

/// Q(t) for erfc segment 2, double-double, in v = t − ERFC_ANCHORS[2]
const ERFC_Q2: [DoubleDouble; 25] = [
    DoubleDouble {
        high: -0.8891660234348968,
        low: -2.2007380872116625e-17,
    },
    DoubleDouble {
        high: 1.2547840686031693,
        low: 1.9527086129603606e-17,
    },
    DoubleDouble {
        high: 0.33960111954263317,
        low: -2.143585237334713e-17,
    },
    DoubleDouble {
        high: -0.20905256625384147,
        low: 1.1700850977138275e-17,
    },
    DoubleDouble {
        high: -0.30529831874339497,
        low: -1.38005414131868e-17,
    },
    DoubleDouble {
        high: 0.036951537390938774,
        low: 1.97629687612779e-18,
    },
    DoubleDouble {
        high: 0.30867398646575783,
        low: 4.33860426942207e-18,
    },
    DoubleDouble {
        high: 0.042149146979421466,
        low: -3.4353329104295814e-18,
    },
    DoubleDouble {
        high: -0.3605409280136133,
        low: 2.3547167769897533e-17,
    },
    DoubleDouble {
        high: -0.09298175434407617,
        low: -1.6842175814463783e-18,
    },
    DoubleDouble {
        high: 0.4751512460856378,
        low: -2.365294922070134e-17,
    },
    DoubleDouble {
        high: 0.10829348109250458,
        low: -6.488005983774582e-19,
    },
    DoubleDouble {
        high: -0.6779617924790925,
        low: -3.61575414368262e-17,
    },
    DoubleDouble {
        high: -0.029442921600623475,
        low: -1.139498395053481e-18,
    },
    DoubleDouble {
        high: 0.9816087576845257,
        low: 4.3467203395777805e-17,
    },
    DoubleDouble {
        high: -0.2786109369544757,
        low: -6.177075722073667e-18,
    },
    DoubleDouble {
        high: -1.3088736079141718,
        low: 7.641567446531467e-17,
    },
    DoubleDouble {
        high: 1.0310565234095188,
        low: 1.064938951049364e-16,
    },
    DoubleDouble {
        high: 1.3069438900906667,
        low: -1.0635493614790847e-16,
    },
    DoubleDouble {
        high: -2.2961145119264748,
        low: -2.0812619449051355e-16,
    },
    DoubleDouble {
        high: -0.4415690091524493,
        low: 1.7457978545025302e-17,
    },
    DoubleDouble {
        high: 4.732344741776964,
        low: -1.868928133895255e-16,
    },
    DoubleDouble {
        high: -6.469687490657929,
        low: 3.7723212676496956e-16,
    },
    DoubleDouble {
        high: 4.483144073662452,
        low: 1.3217053441083032e-16,
    },
    DoubleDouble {
        high: -1.4103172809629871,
        low: -1.1087712344316814e-16,
    },
];

/// Q(t) for erfc segment 3, double-double, in v = t − ERFC_ANCHORS[3]
const ERFC_Q3: [DoubleDouble; 24] = [
    DoubleDouble {
        high: -1.050034058371061,
        low: -9.469138345815766e-17,
    },
    DoubleDouble {
        high: 1.1559530034446581,
        low: -5.22724207987229e-17,
    },
    DoubleDouble {
        high: 0.3911549146038319,
        low: 9.469230023513723e-18,
    },
    DoubleDouble {
        high: -0.05305693644291159,
        low: -2.4049499108474746e-18,
    },
    DoubleDouble {
        high: -0.258096766656279,
        low: 1.8338370242077207e-17,
    },
    DoubleDouble {
        high: -0.15448858028865609,
        low: -8.21492982076798e-18,
    },
    DoubleDouble {
        high: 0.1346173863707568,
        low: 1.119122026451349e-17,
    },
    DoubleDouble {
        high: 0.26321997508385914,
        low: -1.798422616914883e-17,
    },
    DoubleDouble {
        high: 0.0003669537015422858,
        low: 2.0551294523745942e-20,
    },
    DoubleDouble {
        high: -0.3518631504049094,
        low: -5.297620065115467e-18,
    },
    DoubleDouble {
        high: -0.17903144610212418,
        low: -1.1683577252515706e-17,
    },
    DoubleDouble {
        high: 0.4514166213421324,
        low: -9.910282174961888e-18,
    },
    DoubleDouble {
        high: 0.4477748333368963,
        low: 1.436818375474809e-17,
    },
    DoubleDouble {
        high: -0.6084574881738201,
        low: 1.759662100128412e-17,
    },
    DoubleDouble {
        high: -0.8896015269583238,
        low: -3.952686409076577e-17,
    },
    DoubleDouble {
        high: 0.9465759871870241,
        low: -1.2079809995499831e-17,
    },
    DoubleDouble {
        high: 1.6575167219741056,
        low: 7.346143339605215e-17,
    },
    DoubleDouble {
        high: -1.8480158282479335,
        low: -8.962848839851095e-17,
    },
    DoubleDouble {
        high: -2.810753795308886,
        low: -4.474646159026742e-18,
    },
    DoubleDouble {
        high: 3.38602520206728,
        low: 1.658902774550083e-16,
    },
    DoubleDouble {
        high: 8.824261539847624,
        low: 5.498769619246449e-16,
    },
    DoubleDouble {
        high: -23.99866584402199,
        low: -1.0133717508307968e-15,
    },
    DoubleDouble {
        high: 23.284386890322516,
        low: 7.911871218758754e-17,
    },
    DoubleDouble {
        high: -8.728041368640426,
        low: -4.605109921430439e-16,
    },
];

/// Q(t) for erfc segment 4, double-double, in v = t − ERFC_ANCHORS[4]
const ERFC_Q4: [DoubleDouble; 24] = [
    DoubleDouble {
        high: -1.1952992386078944,
        low: -7.412714436667033e-18,
    },
    DoubleDouble {
        high: 1.052368154525527,
        low: -6.494237750914792e-17,
    },
    DoubleDouble {
        high: 0.3892038699910064,
        low: 9.739890180964621e-18,
    },
    DoubleDouble {
        high: 0.052524537654967694,
        low: 1.8597917878970155e-18,
    },
    DoubleDouble {
        high: -0.14101369755382964,
        low: -1.1227304967939925e-17,
    },
    DoubleDouble {
        high: -0.17583232105835417,
        low: -4.933172881835985e-18,
    },
    DoubleDouble {
        high: -0.05721133224057063,
        low: -2.774463702633207e-18,
    },
    DoubleDouble {
        high: 0.12010887080309327,
        low: -3.3568557498826156e-18,
    },
    DoubleDouble {
        high: 0.1893846703776019,
        low: -6.435341919435475e-18,
    },
    DoubleDouble {
        high: 0.03871824817702789,
        low: 1.5147664736757973e-18,
    },
    DoubleDouble {
        high: -0.22473503611540002,
        low: 7.124320376567769e-18,
    },
    DoubleDouble {
        high: -0.2750487450585747,
        low: 2.1370761161945726e-17,
    },
    DoubleDouble {
        high: 0.10215856578047475,
        low: -2.98089616139543e-19,
    },
    DoubleDouble {
        high: 0.5586232090328016,
        low: -4.2868956654831594e-17,
    },
    DoubleDouble {
        high: 0.2966782524535586,
        low: 2.1109345630911265e-17,
    },
    DoubleDouble {
        high: -0.815668283118732,
        low: -4.5383535263884994e-17,
    },
    DoubleDouble {
        high: -1.226675339504503,
        low: 5.395564992734882e-17,
    },
    DoubleDouble {
        high: 0.8281881334583524,
        low: -1.4714866056276918e-17,
    },
    DoubleDouble {
        high: 3.2155868427728906,
        low: -1.1476543178564067e-16,
    },
    DoubleDouble {
        high: 0.34375463520667016,
        low: -6.631531971851399e-18,
    },
    DoubleDouble {
        high: -7.43565155053688,
        low: -1.5545856960070035e-16,
    },
    DoubleDouble {
        high: -10.372913295493666,
        low: -4.80358016570724e-16,
    },
    DoubleDouble {
        high: 42.942223565886295,
        low: 3.2116089563528873e-15,
    },
    DoubleDouble {
        high: -34.39003245838553,
        low: -1.4214983323137476e-15,
    },
];

/// Fast double-double Q(t) for erfc segment 0, in v = t − ERFC_ANCHORS[0]
const ERFC_QF0: [DoubleDouble; 15] = [
    DoubleDouble {
        high: -0.4441404018250839,
        low: -9.413571623416256e-18,
    },
    DoubleDouble {
        high: 1.3753538140565607,
        low: 2.01907876319407e-17,
    },
    DoubleDouble {
        high: -0.010952662344169308,
        low: 5.2602609340083754e-20,
    },
    DoubleDouble {
        high: -0.39943303510523914,
        low: 3.783506563601499e-18,
    },
    DoubleDouble {
        high: 0.07843054850472489,
        low: -8.742234798414336e-19,
    },
    DoubleDouble {
        high: 0.23793230005249114,
        low: 6.141978798249759e-18,
    },
    DoubleDouble {
        high: -0.16291716934869277,
        low: 1.1360269290729113e-17,
    },
    DoubleDouble {
        high: -0.11567699950806917,
        low: -1.533141545185197e-18,
    },
    DoubleDouble {
        high: 0.2135371623855158,
        low: -1.2259236688866044e-17,
    },
    DoubleDouble {
        high: -0.029308898740981592,
        low: -9.577843992683643e-19,
    },
    DoubleDouble {
        high: -0.18447366718987593,
        low: -7.907518024584856e-18,
    },
    DoubleDouble {
        high: 0.16334252681139813,
        low: 5.888171924016564e-18,
    },
    DoubleDouble {
        high: 0.05404475797394964,
        low: 1.3131493136145105e-18,
    },
    DoubleDouble {
        high: -0.1979874054269295,
        low: -9.528690121998993e-18,
    },
    DoubleDouble {
        high: 0.12404776237794504,
        low: -2.4887993633919456e-18,
    },
];

/// Fast double-double Q(t) for erfc segment 1, in v = t − ERFC_ANCHORS[1]
const ERFC_QF1: [DoubleDouble; 16] = [
    DoubleDouble {
        high: -0.6717940840566923,
        low: 1.0502376103114448e-17,
    },
    DoubleDouble {
        high: 1.3452864479553135,
        low: 9.245893713088854e-17,
    },
    DoubleDouble {
        high: 0.189373227367616,
        low: 6.0084769224396755e-18,
    },
    DoubleDouble {
        high: -0.37516488184947394,
        low: -1.0935631738445955e-17,
    },
    DoubleDouble {
        high: -0.15796302986170332,
        low: -1.3419977106012667e-17,
    },
    DoubleDouble {
        high: 0.28239803383689793,
        low: -2.6554461672342862e-17,
    },
    DoubleDouble {
        high: 0.11257174762689019,
        low: -3.2581261506461437e-19,
    },
    DoubleDouble {
        high: -0.30026399895826955,
        low: -2.765614529326533e-17,
    },
    DoubleDouble {
        high: -0.03743927983262288,
        low: -2.636054402308022e-18,
    },
    DoubleDouble {
        high: 0.3449257874443551,
        low: -1.891403366838235e-17,
    },
    DoubleDouble {
        high: -0.0960226753467256,
        low: 3.0605986101511697e-18,
    },
    DoubleDouble {
        high: -0.356514026738353,
        low: 2.4832213866777348e-17,
    },
    DoubleDouble {
        high: 0.2884551321749626,
        low: 2.5124872909337443e-17,
    },
    DoubleDouble {
        high: 0.2851282333542925,
        low: 5.474700806776177e-18,
    },
    DoubleDouble {
        high: -0.6046022620881454,
        low: 2.0025432090467322e-17,
    },
    DoubleDouble {
        high: 0.3264978607019354,
        low: 1.0976171470159206e-17,
    },
];

/// Fast double-double Q(t) for erfc segment 2, in v = t − ERFC_ANCHORS[2]
const ERFC_QF2: [DoubleDouble; 16] = [
    DoubleDouble {
        high: -0.8891660234348968,
        low: -2.2007431021260536e-17,
    },
    DoubleDouble {
        high: 1.2547840686031693,
        low: 1.9680989202741723e-17,
    },
    DoubleDouble {
        high: 0.33960111954263306,
        low: 1.1493381590167724e-17,
    },
    DoubleDouble {
        high: -0.20905256625382587,
        low: 9.28746672052993e-18,
    },
    DoubleDouble {
        high: -0.3052983187450225,
        low: -1.4809001520695418e-17,
    },
    DoubleDouble {
        high: 0.03695153749302028,
        low: -2.0826110409650896e-18,
    },
    DoubleDouble {
        high: 0.3086739822952209,
        low: -1.2562121564848919e-17,
    },
    DoubleDouble {
        high: 0.04214926349874961,
        low: 6.34529021956204e-19,
    },
    DoubleDouble {
        high: -0.36054321789928484,
        low: -2.2393092755739615e-17,
    },
    DoubleDouble {
        high: -0.09294972121196617,
        low: -2.391259511928581e-18,
    },
    DoubleDouble {
        high: 0.47483404928246353,
        low: 1.9484519259825492e-17,
    },
    DoubleDouble {
        high: 0.11044408301093449,
        low: 6.9306849702702615e-18,
    },
    DoubleDouble {
        high: -0.6869507904988973,
        low: -1.2343140304915807e-17,
    },
    DoubleDouble {
        high: -0.01601867004311672,
        low: 1.4301510477097097e-18,
    },
    DoubleDouble {
        high: 1.0597311710134574,
        low: 1.6832446964212672e-17,
    },
    DoubleDouble {
        high: -0.8076644091341626,
        low: 4.1864767388733236e-17,
    },
];

/// Fast double-double Q(t) for erfc segment 3, in v = t − ERFC_ANCHORS[3]
const ERFC_QF3: [DoubleDouble; 15] = [
    DoubleDouble {
        high: -1.050034058371061,
        low: -9.469120319403637e-17,
    },
    DoubleDouble {
        high: 1.1559530034446581,
        low: -5.288091444738644e-17,
    },
    DoubleDouble {
        high: 0.3911549146038322,
        low: 1.744626990946188e-17,
    },
    DoubleDouble {
        high: -0.05305693644298708,
        low: -9.195277573239204e-19,
    },
    DoubleDouble {
        high: -0.2580967666475242,
        low: -2.30702480159379e-17,
    },
    DoubleDouble {
        high: -0.15448858090045336,
        low: -9.389868602221076e-18,
    },
    DoubleDouble {
        high: 0.13461741429049737,
        low: 2.4226477055469738e-18,
    },
    DoubleDouble {
        high: 0.2632191009192392,
        low: -2.660183815102158e-17,
    },
    DoubleDouble {
        high: 0.00038630438545178016,
        low: -1.5222179080913286e-20,
    },
    DoubleDouble {
        high: -0.35217089122468953,
        low: -2.1141305584399652e-17,
    },
    DoubleDouble {
        high: -0.17550138648636449,
        low: -1.05028498714739e-17,
    },
    DoubleDouble {
        high: 0.42246749122416605,
        low: -2.4542438290189543e-17,
    },
    DoubleDouble {
        high: 0.6131045694399055,
        low: -4.35004023316743e-17,
    },
    DoubleDouble {
        high: -1.229510719708045,
        low: 7.312751233393504e-17,
    },
    DoubleDouble {
        high: 0.4501686397084009,
        low: -2.2181190412639284e-17,
    },
];

/// Fast double-double Q(t) for erfc segment 4, in v = t − ERFC_ANCHORS[4]
const ERFC_QF4: [DoubleDouble; 15] = [
    DoubleDouble {
        high: -1.1952992386078944,
        low: -7.412831991727512e-18,
    },
    DoubleDouble {
        high: 1.052368154525527,
        low: -6.454020849270659e-17,
    },
    DoubleDouble {
        high: 0.3892038699910062,
        low: 3.2720751814025094e-18,
    },
    DoubleDouble {
        high: 0.05252453765501899,
        low: 1.1879066132038152e-18,
    },
    DoubleDouble {
        high: -0.14101369755986407,
        low: 1.2054770491941131e-17,
    },
    DoubleDouble {
        high: -0.1758323206304412,
        low: -1.3487108584253005e-17,
    },
    DoubleDouble {
        high: -0.057211352064103105,
        low: -1.969251332961876e-18,
    },
    DoubleDouble {
        high: 0.12010950113285201,
        low: -6.042791999713952e-18,
    },
    DoubleDouble {
        high: 0.1893704933141736,
        low: -3.002669202098016e-19,
    },
    DoubleDouble {
        high: 0.038947459382043415,
        low: 1.7810514655574603e-18,
    },
    DoubleDouble {
        high: -0.22740978110188811,
        low: -9.145227227682586e-18,
    },
    DoubleDouble {
        high: -0.2527168111302227,
        low: -1.3904371790630048e-17,
    },
    DoubleDouble {
        high: -0.027808797201266132,
        low: -1.4135183140727587e-18,
    },
    DoubleDouble {
        high: 1.0567076837582308,
        low: 9.690035128804747e-17,
    },
    DoubleDouble {
        high: -0.8020777689283721,
        low: -2.974060326089948e-17,
    },
];

/// One cell of [`ERF_TABLE`]: the degree-10 minimax of `erf(i/16 + h)` in `h`,
/// with `c0`/`c1` carried in double-double and `c2..c10` as a plain-`f64`
/// tail (`tail[k]` is the coefficient of `h`<sup>`k+2`</sup>).
struct ErfCell {
    c0: DoubleDouble,
    c1: DoubleDouble,
    tail: [f64; 9],
}

/// Fast-path table for `erf` on `x ∈ [0.4375, 6.25]`: per-cell minimax of
/// `erf(i/16 + h)` in `h ∈ [−1/32, 1/32]`, cells of width 1/16, `i ∈ [7, 100]`.
/// Degree 10 (`c0`/`c1` double-double, `c2..c10` plain `f64`); worst-cell
/// minimax error 2^-75.  From `tools/gen_erf_f64.py`.
const ERF_TABLE: [ErfCell; 94] = [
    ErfCell {
        c0: DoubleDouble {
            high: 0.463898135749933,
            low: -2.081342854423416e-17,
        },
        c1: DoubleDouble {
            high: 0.9318121761288343,
            low: 3.523396817623085e-17,
        },
        tail: [
            -0.407667827056365,
            -0.19170094248483838,
            0.17782385685401333,
            0.026391107796364374,
            -0.05126839838103188,
            0.0001249518485008689,
            0.010972417990849243,
            -0.0010901837957174737,
            -0.001854493639742113,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.5204998778130465,
            low: 1.900077467916287e-17,
        },
        c1: DoubleDouble {
            high: 0.8787825789354448,
            low: 3.6003692069333284e-17,
        },
        tail: [
            -0.4393912894677224,
            -0.14646376315590756,
            0.1830797039448843,
            0.0073231881583524115,
            -0.05004178574471509,
            0.0054052090030995165,
            0.010047587999269138,
            -0.0021660765763539514,
            -0.0015689695396592699,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.5736744566155919,
            low: 4.3932481677630634e-17,
        },
        c1: DoubleDouble {
            high: 0.8223213592243077,
            low: 2.7482099925958698e-17,
        },
        tail: [
            -0.4625557645636731,
            -0.10064870803005863,
            0.18249270398801162,
            -0.010866245987593847,
            -0.0466272999405303,
            0.010080873012604028,
            0.00857394095971671,
            -0.0030302558246043773,
            -0.0011828400280011644,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.623240882188418,
            low: -2.7016816836135297e-17,
        },
        c1: DoubleDouble {
            high: 0.7634995357606049,
            low: -3.423826022850379e-17,
        },
        tail: [
            -0.47718720985037805,
            -0.05567184114921091,
            0.1764598536425877,
            -0.027413411065124266,
            -0.04134483366591872,
            0.013910006868941838,
            0.006686168256464645,
            -0.0036315380181445762,
            -0.0007343731463576778,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.6690846628860813,
            low: 2.1626326156388987e-17,
        },
        c1: DoubleDouble {
            high: 0.7033687321576001,
            low: -6.4397800069335095e-18,
        },
        tail: [
            -0.48356600335835004,
            -0.012821825846623051,
            0.16559617042089333,
            -0.04169239911099852,
            -0.03460447064916899,
            0.016724066648401873,
            0.004540794548167417,
            -0.003943812311840118,
            -0.00026482865727940315,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.7111556336535151,
            low: 4.69744077164289e-17,
        },
        c1: DoubleDouble {
            high: 0.6429310691952074,
            low: -4.290961908272124e-17,
        },
        tail: [
            -0.4821983018964055,
            0.026788794549800182,
            0.15068696934262674,
            -0.05324272916702915,
            -0.026872509532887348,
            0.018435233541895687,
            0.0023017885823703272,
            -0.003966585056561181,
            0.00018574719494827293,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.749464025586362,
            low: 1.9451069995767674e-17,
        },
        c1: DoubleDouble {
            high: 0.5831131597762814,
            low: -2.0132556817871327e-17,
        },
        tail: [
            -0.47377944231822866,
            0.06225947799694661,
            0.1326335678364833,
            -0.0617837529453548,
            -0.018635851667048096,
            0.019036595847052543,
            0.00012658839284272535,
            -0.0037230114524607603,
            0.0005822858766223486,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.7840750610598597,
            low: -3.204544978890348e-17,
        },
        c1: DoubleDouble {
            high: 0.5247450452901482,
            low: 1.4398689252028978e-17,
        },
        tail: [
            -0.45915191462887966,
            0.09292360177013034,
            0.11239656243519454,
            -0.06721587738292023,
            -0.010367785746122155,
            0.018595725743064753,
            -0.001846146350003004,
            -0.003255815388146654,
            0.0008976367806111885,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.8151024010343998,
            low: 1.1420613234291201e-17,
        },
        c1: DoubleDouble {
            high: 0.46854458689539813,
            low: -1.2948396230447946e-17,
        },
        tail: [
            -0.4392605502144357,
            0.11835631491888958,
            0.09094066078658244,
            -0.06960964227036744,
            -0.002497829667079514,
            0.017242785241130026,
            -0.003506028182649988,
            -0.0026216992888916445,
            0.001114429110490635,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.8427007929497149,
            low: -2.4801011789118602e-17,
        },
        c1: DoubleDouble {
            high: 0.4151074974205947,
            low: -1.4333106831366616e-17,
        },
        tail: [
            -0.4151074974205947,
            0.1383691658068649,
            0.06918458290343249,
            -0.06918458290333657,
            0.004612305526671402,
            0.015154717935393094,
            -0.004777030199759507,
            -0.0018849586055661937,
            0.0012257504318800227,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.8670582694349528,
            low: -3.319524979800146e-17,
        },
        c1: DoubleDouble {
            high: 0.36490289117800395,
            low: 4.969432546405032e-18,
        },
        tail: [
            -0.3877093218766292,
            0.15299313926994437,
            0.047958835388385156,
            -0.06628044682111056,
            0.010685302145353072,
            0.012537306478697295,
            -0.00561992913217998,
            -0.0011110341927690756,
            0.0012346854847891185,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.8883882317017078,
            low: -1.158643993739769e-17,
        },
        c1: DoubleDouble {
            high: 0.3182739585007693,
            low: 2.0587355498056926e-17,
        },
        tail: [
            -0.35805820331336546,
            0.1624523329847677,
            0.027973297133856705,
            -0.061323683605863946,
            0.015536835449604311,
            0.009606894689620326,
            -0.006031260511918535,
            -0.00036066698405430163,
            0.0011528872421794887,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9069217197816865,
            low: 3.640648704844757e-17,
        },
        c1: DoubleDouble {
            high: 0.2754431531414426,
            low: -1.24312560492883e-17,
        },
        tail: [
            -0.32708874435546303,
            0.1671308715675941,
            0.009795626458562063,
            -0.0547921840383945,
            0.01907640579268586,
            0.006573406839493149,
            -0.006039280930692496,
            0.0003148194036175006,
            0.0009984456706059505,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9229001282564583,
            low: -5.51775442986392e-17,
        },
        c1: DoubleDouble {
            high: 0.2365211224472908,
            low: -8.320204489434162e-19,
        },
        tail: [
            -0.29565140305911347,
            0.16753579506683103,
            -0.006159404230398187,
            -0.04718103640521303,
            0.02130127296340133,
            0.0036259834587224547,
            -0.005697677919292113,
            0.0008767664305226609,
            0.0007933698554694656,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9365685747113888,
            low: -5.454829038530475e-17,
        },
        c1: DoubleDouble {
            high: 0.20151851572462268,
            low: -2.7629007977898656e-18,
        },
        tail: [
            -0.26449305188856725,
            0.1642585818276222,
            -0.0196303436948546,
            -0.038971644108876526,
            0.02228485261608114,
            0.0009221440614082128,
            -0.005077903758350956,
            0.0013008182856812584,
            0.0005610046321589115,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9481700727820903,
            low: 1.071691533519912e-17,
        },
        c1: DoubleDouble {
            high: 0.1703597736875156,
            low: 3.053476145885286e-18,
        },
        tail: [
            -0.23424468882033395,
            0.1579377068561343,
            -0.03050061052348099,
            -0.03060597626930558,
            0.02216123526288466,
            -0.0014190614715802732,
            -0.004261033516426447,
            0.0015770007513220608,
            0.00032366843843289025,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.95794060605646,
            low: 3.2564962193065506e-17,
        },
        c1: DoubleDouble {
            high: 0.14289802537593801,
            low: 1.1545144119414279e-17,
        },
        tail: [
            -0.2054159114779109,
            0.14922424004101867,
            -0.03878295203684517,
            -0.02246707459146239,
            0.021107593784801888,
            -0.003319886028065993,
            -0.003329971633564052,
            0.0017084528368305938,
            0.00010073441505117742,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9661051464753108,
            low: -3.3867031441680696e-17,
        },
        c1: DoubleDouble {
            high: 0.11893028922362937,
            low: -1.9676257098875072e-18,
        },
        tail: [
            -0.17839543383544407,
            0.13875200409423433,
            -0.04459885845886103,
            -0.01486628615323873,
            0.019326171998926785,
            -0.004743052533969337,
            -0.0023626778244040182,
            0.001709136300909248,
            -9.270571293132334e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9728746138209335,
            low: -5.1905257916652814e-18,
        },
        c1: DoubleDouble {
            high: 0.09821228080128248,
            low: 6.160165606296501e-18,
        },
        tail: [
            -0.15345668875200388,
            0.12711329051624326,
            -0.048155028631813736,
            -0.008037094260204446,
            0.017027327562326,
            -0.005687891144068689,
            -0.0014268806033493322,
            0.0016009080592090954,
            -0.00024654263051476837,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9784437332399837,
            low: -1.7028513178925588e-17,
        },
        c1: DoubleDouble {
            high: 0.08047225902251116,
            low: 1.034776674070838e-18,
        },
        tail: [
            -0.13076742091158064,
            0.11484061964670866,
            -0.049718863159090576,
            -0.0021349248407445485,
            0.014414781131183043,
            -0.006184261185887414,
            -0.0005765256609315121,
            0.0014103475380807442,
            -0.0003557430267163105,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.982989716601978,
            low: 4.892216560995362e-17,
        },
        c1: DoubleDouble {
            high: 0.06542348334839115,
            low: -4.396708550345715e-18,
        },
        tail: [
            -0.11040212815041006,
            0.10239456638641428,
            -0.04959470600506704,
            0.002758056637426599,
            0.011673848076183867,
            -0.006285142454713664,
            0.0001500054555770831,
            0.0011656927308760095,
            -0.0004199274140603763,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9866716712191824,
            low: 2.1431190289565338e-17,
        },
        c1: DoubleDouble {
            high: 0.05277499593015037,
            low: 3.1147502000348724e-18,
        },
        tail: [
            -0.09235624287776316,
            0.09015728471400689,
            -0.04810220983216832,
            0.006624361468309599,
            0.008963045098804296,
            -0.006058751456004951,
            0.0007300510670690607,
            0.0008941670399265124,
            -0.0004425660994770601,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9896306257947752,
            low: -4.6662088208165306e-17,
        },
        c1: DoubleDouble {
            high: 0.042240575617668474,
            low: 3.2867081535306065e-18,
        },
        tail: [
            -0.07656104330702411,
            0.07843106879009797,
            -0.045557808322018264,
            0.009500090396478957,
            0.006409110938085456,
            -0.005580930269095494,
            0.0011554779260859022,
            0.0006198881522609763,
            -0.0004299462749616584,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9919900576701199,
            low: 3.0126779045582727e-17,
        },
        c1: DoubleDouble {
            high: 0.03354582842421607,
            low: 2.8446343047242136e-18,
        },
        tail: [
            -0.06289842829540514,
            0.06744109256118438,
            -0.04225988151097534,
            0.011462583364958732,
            0.004105187133252901,
            -0.004928394101480373,
            0.0014305015927569991,
            0.00036245435549233594,
            -0.0003900606956085836,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9938568063952132,
            low: -3.254802273021928e-17,
        },
        c1: DoubleDouble {
            high: 0.02643347677803051,
            low: -8.008191902126551e-19,
        },
        tail: [
            -0.05121486125743411,
            0.057341370198175534,
            -0.03847783196033787,
            0.012617908709915087,
            0.002111689147693757,
            -0.004173235004596788,
            0.0015689057162225973,
            0.00013621509251047432,
            -0.0003315486203089205,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9953222650189527,
            low: 2.20719858329765e-17,
        },
        c1: DoubleDouble {
            high: 0.020666985354092053,
            low: 7.40422410732621e-19,
        },
        tail: [
            -0.041333970708184106,
            0.04822296582621477,
            -0.03444497559015342,
            0.013089090724374525,
            0.00045926634120791696,
            -0.0033788883537409406,
            0.0015910298111389493,
            -4.983975762697183e-05,
            -0.00026278834286567717,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9964637508747902,
            low: -1.068842421162785e-17,
        },
        c1: DoubleDouble {
            high: 0.01603271410867742,
            low: -1.3294385665761363e-18,
        },
        tail: [
            -0.03306747284914718,
            0.04012353713135154,
            -0.030354906716990572,
            0.013005736902227252,
            -0.0008468023290115878,
            -0.0025975957793421345,
            0.0015208428432166826,
            -0.0001916881039709948,
            -0.00019120388710223483,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9973459706405177,
            low: -6.548583264315741e-18,
        },
        c1: DoubleDouble {
            high: 0.012340820614333696,
            low: -5.437789570801291e-19,
        },
        tail: [
            -0.026224243805459103,
            0.03303740518628914,
            -0.026360828408612532,
            0.012495482591540165,
            -0.0018214125933191264,
            -0.001869257505500569,
            0.001383345655525011,
            -0.00028952515881836585,
            -0.00012281191325197837,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9980225088163892,
            low: -5.888411957796996e-18,
        },
        c1: DoubleDouble {
            high: 0.009425146402332227,
            low: 5.284838282558066e-19,
        },
        tail: [
            -0.02061750775510175,
            0.026925483342079292,
            -0.02257724482036532,
            0.01167744421528709,
            -0.0024942044548389676,
            -0.0012214662900165583,
            0.0012024616969750121,
            -0.0003468040260387185,
            -6.200303639098945e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9985372834133188,
            low: 2.6956405885413457e-17,
        },
        c1: DoubleDouble {
            high: 0.007142319022017983,
            low: -1.5477643073060547e-19,
        },
        tail: [
            -0.016070217799540463,
            0.021724553691971352,
            -0.019083383636954294,
            0.010657679165740438,
            -0.0029043570710881937,
            -0.0006704561407671822,
            0.000999493772093423,
            -0.00036920550087970013,
            -1.1527497807888493e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9989259267092776,
            low: 1.4448505662670296e-17,
        },
        c1: DoubleDouble {
            high: 0.0053702865406233535,
            low: -2.969309239079098e-19,
        },
        tail: [
            -0.012418787625191505,
            0.017355535408629108,
            -0.01592774194116358,
            0.009526500673041364,
            -0.0030959464178096797,
            -0.00022267854580163885,
            0.0007921531104351063,
            -0.00036365116188755256,
            2.7360246305139772e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9992170617821089,
            low: -1.4349117332555682e-17,
        },
        c1: DoubleDouble {
            high: 0.004006477861670219,
            low: 2.45691040160735e-19,
        },
        tail: [
            -0.009515384921466771,
            0.013730533505098974,
            -0.013133213563482779,
            0.008357392833814375,
            -0.0031140790431695617,
            0.00012326954546206027,
            0.0005941113647951023,
            -0.0003374429401250896,
            5.465008292778316e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9994334567454198,
            low: 2.833424893807958e-19,
        },
        c1: DoubleDouble {
            high: 0.0029657539001367375,
            low: -8.46932990176914e-20,
        },
        tail: [
            -0.007229025131583297,
            0.010758581205443943,
            -0.010702345800273707,
            0.007207212793652851,
            -0.0030019015147742657,
            0.00037460689252500175,
            0.0004149885543830382,
            -0.00029757974775939094,
            7.126911726512667e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999593047982555,
            low: 4.6925151097042234e-17,
        },
        c1: DoubleDouble {
            high: 0.0021782842303527095,
            low: 2.076622761010506e-19,
        },
        tail: [
            -0.005445710575881774,
            0.008350089549685386,
            -0.008622375078479473,
            0.006117348213579629,
            -0.0027984901570661325,
            0.0005424100478277993,
            0.00026067021082036465,
            -0.0002502715691191153,
            7.876351720377872e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9997098311383266,
            low: 2.828981513568499e-17,
        },
        c1: DoubleDouble {
            high: 0.0015874536692229567,
            low: 6.699620222847107e-20,
        },
        tail: [
            -0.004067850027383827,
            0.006420092573706386,
            -0.006869793600933362,
            0.0051155106688403245,
            -0.00253755373606753,
            0.0006398731222297066,
            0.00013384282956421171,
            -0.00020064650687163173,
            7.900399471500667e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9997946242638588,
            low: -6.2556665556923804e-18,
        },
        c1: DoubleDouble {
            high: 0.001147875125882675,
            low: 5.605330905934597e-20,
        },
        tail: [
            -0.003013172205442022,
            0.004890426317562649,
            -0.005414293806653632,
            0.004217880601705962,
            -0.002246833844736024,
            0.0006808681244803113,
            3.4644723908292335e-05,
            -0.00015262814362681333,
            7.393820403773829e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9998557114825746,
            low: -5.179809999505048e-17,
        },
        c1: DoubleDouble {
            high: 0.0008235601143850599,
            low: 1.6994249842265276e-20,
        },
        tail: [
            -0.0022133178074098484,
            0.003691007700147628,
            -0.0042220189946034214,
            0.003431368109138556,
            -0.00194806219922724,
            0.0006788411045269905,
            -3.865443298128204e-05,
            -0.0001089495419025396,
            6.540226611137376e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9998993780778803,
            low: 4.451378916214761e-17,
        },
        c1: DoubleDouble {
            high: 0.0005862772470937923,
            low: 1.9259883292688924e-21,
        },
        tail: [
            -0.001612262429507929,
            0.0027603887050666087,
            -0.003258113659630606,
            0.00275580841405594,
            -0.0016573274036672525,
            0.0006460409982085615,
            -8.901156839786383e-05,
            -7.126565166868045e-05,
            5.499411164749842e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999303492456073,
            low: 4.7859074825595774e-17,
        },
        c1: DoubleDouble {
            high: 0.0004141120318701683,
            low: 9.654879965142294e-21,
        },
        tail: [
            -0.0011646900896348483,
            0.002045756574108621,
            -0.0024886151524619615,
            0.0021859650742693,
            -0.001385711549820103,
            0.0005930503765593159,
            -0.00012005032950999063,
            -4.0326604133794924e-05,
            4.4004086304293235e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999521451602562,
            low: 1.4933598125858e-17,
        },
        c1: DoubleDouble {
            high: 0.00029022828286249803,
            low: 2.481662500973928e-21,
        },
        tail: [
            -0.0008344063132296819,
            0.0015025360060693937,
            -0.0018817600709815224,
            0.0017132632797913399,
            -0.0011400746242185814,
            0.0005285700802087501,
            -0.00013560801738641133,
            -1.6178828525477487e-05,
            3.339351939773723e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999673647128524,
            low: 2.5303870529434582e-17,
        },
        c1: DoubleDouble {
            high: 0.00020182208573230978,
            low: -2.652693169117523e-21,
        },
        tail: [
            -0.0005928523768386599,
            0.0010937285427316083,
            -0.0014087963381908266,
            0.0013272171345401905,
            -0.0009238877540642141,
            0.0004594017479882931,
            -0.00013939719358307693,
            1.632404400028334e-06,
            2.3809583457297062e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999779095030014,
            low: 5.363397058636269e-17,
        },
        c1: DoubleDouble {
            high: 0.00013925305194674786,
            low: -1.0217485100638985e-20,
        },
        tail: [
            -0.00041775915584024356,
            0.00078910062769824,
            -0.0010443978896006094,
            0.0010165472791991655,
            -0.000738041175314369,
            0.00039057168352872796,
            -0.00013477706893699773,
            1.387789927747477e-05,
            1.5624372156187023e-05,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999851585892071,
            low: -9.829334083526714e-18,
        },
        c1: DoubleDouble {
            high: 9.53340029043727e-05,
            low: 5.280355675078618e-22,
        },
        tail: [
            -0.0002919603838946414,
            0.0005643077828167703,
            -0.000766776164473297,
            0.0007700084666252106,
            -0.0005815766658267553,
            0.0003255442557478796,
            -0.00012462124028454175,
            2.1488523203058543e-05,
            8.987174007243595e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999901032653747,
            low: 1.3132336543493276e-17,
        },
        c1: DoubleDouble {
            high: 6.475868323471298e-05,
            low: -5.900218423956852e-22,
        },
        tail: [
            -0.00020237088510847805,
            0.0004000197828977595,
            -0.0005575739490749219,
            0.0005769615014671904,
            -0.00045231517761271854,
            0.0002664810677883428,
            -0.00011126364740235314,
            2.543356007762721e-05,
            3.8808688019297705e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999993449849224,
            low: -3.361347945844607e-17,
        },
        c1: DoubleDouble {
            high: 4.364708704085379e-05,
            low: 1.5325570478006814e-22,
        },
        tail: [
            -0.00013912508994272146,
            0.00028109178711466606,
            -0.0004016150057330909,
            0.0004277315961702937,
            -0.000347367486071464,
            0.00021451168742384565,
            -9.650310786678977e-05,
            2.6633784449439285e-05,
            1.7572643064540593e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999956972205363,
            low: 5.224680575187069e-17,
        },
        c1: DoubleDouble {
            high: 2.9189025383581702e-05,
            low: -1.5485039257306597e-21,
        },
        tail: [
            -9.486433249664052e-05,
            0.00019580971194819446,
            -0.00028656933775026864,
            0.00031379722548767957,
            -0.0002635285042129261,
            0.0001699914220265619,
            -8.164763552452264e-05,
            2.5906152279452867e-05,
            -2.3237519896118465e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999971946873958,
            low: 4.197440018386497e-17,
        },
        c1: DoubleDouble {
            high: 1.936827746725363e-05,
            low: 8.106001320599255e-22,
        },
        tail: [
            -6.415741911027765e-05,
            0.0001352248747127789,
            -0.00020258039237294729,
            0.00022785155747852525,
            -0.00019756465675009182,
            0.0001327304692288633,
            -6.758213660677794e-05,
            2.393495400694785e-05,
            -3.841217284148618e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999981847185726,
            low: -4.284756581330801e-17,
        },
        c1: DoubleDouble {
            high: 1.2751740799765088e-05,
            low: 4.975126160329345e-22,
        },
        tail: [
            -4.303712519920718e-05,
            9.25829514316279e-05,
            -0.00014188802214113637,
            0.00016377394446031042,
            -0.00014640888161317864,
            0.00010218619840519773,
            -5.4846274474312415e-05,
            2.1263404752657666e-05,
            -4.600675625945654e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999988341746511,
            low: -4.8685282324006045e-17,
        },
        c1: DoubleDouble {
            high: 8.330192337095466e-06,
            low: -6.336858432159386e-22,
        },
        tail: [
            -2.863503615876566e-05,
            6.284522708480614e-05,
            -9.847022199908883e-05,
            0.0001165429871233171,
            -0.00010728011354488743,
            7.761606693658613e-05,
            -4.371271368246977e-05,
            1.8299671404223317e-05,
            -4.807915384018891e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999992569016276,
            low: 4.9647279187212204e-17,
        },
        c1: DoubleDouble {
            high: 5.399426777384783e-06,
            low: -3.762452308559173e-22,
        },
        tail: [
            -1.8897993720846738e-05,
            4.229550975618071e-05,
            -6.771781083303424e-05,
            8.2116282239891e-05,
            -7.774424638998588e-05,
            5.819274945470398e-05,
            -3.425917658680028e-05,
            1.5331961151856468e-05,
            -4.639825510009927e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999999529912161,
            low: -4.4789324442289504e-17,
        },
        c1: DoubleDouble {
            high: 3.4725408019520497e-06,
            low: -3.089394034481868e-23,
        },
        tail: [
            -1.2370926606954177e-05,
            2.822343709086535e-05,
            -4.614935511578614e-05,
            5.729579991351216e-05,
            -5.573226769857182e-05,
            4.3085627824901826e-05,
            -2.643051071338474e-05,
            1.2548254375805194e-05,
            -4.239927538216205e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999997048598075,
            low: -3.8108336724873686e-18,
        },
        c1: DoubleDouble {
            high: 2.2159202846331124e-06,
            low: 6.13304011166797e-23,
        },
        tail: [
            -8.032711031795032e-06,
            1.86737448986268e-05,
            -3.11685922848297e-05,
            3.9592335344317076e-05,
            -3.95291139305856e-05,
            3.1514119377698336e-05,
            -2.0089148387698776e-05,
            1.0057341580511747e-05,
            -3.7183942280538095e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999998160959875,
            low: -1.200825156255013e-17,
        },
        c1: DoubleDouble {
            high: 1.4030333138998202e-06,
            low: 6.896009825743657e-24,
        },
        tail: [
            -5.173685345005587e-06,
            1.2250965368505302e-05,
            -2.086315561651341e-05,
            2.709786492472575e-05,
            -2.7744284137804076e-05,
            2.2778710319194822e-05,
            -1.5053921747106408e-05,
            7.908863969137646e-06,
            -3.1549796109284004e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999998862727434,
            low: 4.2276182391829615e-17,
        },
        c1: DoubleDouble {
            high: 8.814321912318039e-07,
            low: 3.4995606465297205e-23,
        },
        tail: [
            -3.305370717119265e-06,
            7.96961606238741e-06,
            -1.3841239877936904e-05,
            1.837097499905773e-05,
            -1.927272144705411e-05,
            1.6275300708122065e-05,
            -1.1128227202217868e-05,
            6.110962636791965e-06,
            -2.603550866450527e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999302015868,
            low: -2.5272105766689423e-17,
        },
        c1: DoubleDouble {
            high: 5.494357401381652e-07,
            low: -4.33457400654645e-23,
        },
        tail: [
            -2.0947237592767544e-06,
            5.14094430811556e-06,
            -9.10168383425327e-06,
            1.2337784555578853e-05,
            -1.3252152182730645e-05,
            1.1497810485580368e-05,
            -8.119105134122628e-06,
            4.644863858005068e-06,
            -2.0972221165550113e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999999957486056,
            low: -5.0616648789558536e-17,
        },
        c1: DoubleDouble {
            high: 3.398223817809154e-07,
            low: 7.131470982774905e-24,
        },
        tail: [
            -1.3168117294010471e-06,
            3.288489507025617e-06,
            -5.93251117672865e-06,
            8.208845472489596e-06,
            -9.021089087459395e-06,
            8.033145766365664e-06,
            -5.849020604199128e-06,
            3.476256785061287e-06,
            -1.6533936005447648e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999743008093,
            low: 5.150733041349465e-17,
        },
        c1: DoubleDouble {
            high: 2.0854228461413665e-07,
            low: 1.1380096194949488e-23,
        },
        tail: [
            -8.211352456681631e-07,
            2.085965925007452e-06,
            -3.8330336663025326e-06,
            5.4112382474795844e-06,
            -6.0801078882215045e-06,
            5.5517300155313055e-06,
            -4.162104906697205e-06,
            2.5636697243021307e-06,
            -1.278265331865317e-06,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999845827421,
            low: 1.44826531920025e-17,
        },
        c1: DoubleDouble {
            high: 1.2698234671866558e-07,
            low: 3.0787317869913974e-24,
        },
        tail: [
            -5.079293868746623e-07,
            1.3121509160927994e-06,
            -2.4549920365608444e-06,
            3.534341984118645e-06,
            -4.0577914352777725e-06,
            3.7959648785809346e-06,
            -2.926438878533769e-06,
            1.8642511847996925e-06,
            -9.706066829009588e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999908210709,
            low: 3.646274373650921e-17,
        },
        c1: DoubleDouble {
            high: 7.671841912446447e-08,
            low: -5.2560363283824146e-24,
        },
        tail: [
            -3.116685776931369e-07,
            8.185295915440291e-07,
            -1.558748706926202e-06,
            2.287407771646446e-06,
            -2.681865035227801e-06,
            2.5682573308206877e-06,
            -2.0337015558508293e-06,
            1.3374470369370152e-06,
            -7.247188082025021e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999945765992,
            low: 3.99675667392096e-17,
        },
        c1: DoubleDouble {
            high: 4.598995828846052e-08,
            low: -8.257163619983033e-25,
        },
        tail: [
            -1.8970857793989965e-07,
            5.063686032385227e-07,
            -9.811490515329014e-07,
            1.466985354331685e-06,
            -1.7554651148518636e-06,
            1.719658159782287e-06,
            -1.3972268132921483e-06,
            9.470698763728593e-07,
            -5.326297632555923e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999999996819877,
            low: 2.118325093396126e-18,
        },
        c1: DoubleDouble {
            high: 2.7354794758006757e-08,
            low: 9.357958929545389e-26,
        },
        tail: [
            -1.1454820304915329e-07,
            3.106621352595145e-07,
            -6.122661113499527e-07,
            9.323470961408692e-07,
            -1.1381301917929921e-06,
            1.139703589827391e-06,
            -9.492424772492113e-07,
            6.622112876790685e-07,
            -3.8562139215085366e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999981494259,
            low: 9.86675034192752e-19,
        },
        c1: DoubleDouble {
            high: 1.6143993719507412e-08,
            low: 7.003460586738958e-25,
        },
        tail: [
            -6.86119733079065e-08,
            1.8901925979920568e-07,
            -3.787952693040562e-07,
            5.872461800315586e-07,
            -7.30920016407523e-07,
            7.477248537082553e-07,
            -6.378321766290303e-07,
            4.573762350740093e-07,
            -2.752129971911523e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999989312964,
            low: -3.8689675291216215e-17,
        },
        c1: DoubleDouble {
            high: 9.453564107008233e-09,
            low: -8.66516706739971e-26,
        },
        tail: [
            -4.0768495211473e-08,
            1.1405823569729577e-07,
            -2.323485723185037e-07,
            3.665838166532007e-07,
            -4.6500461703995763e-07,
            4.856699918978431e-07,
            -4.239692855079903e-07,
            3.121388336963756e-07,
            -1.9372967742254879e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999993875167,
            low: -9.046130618729546e-18,
        },
        c1: DoubleDouble {
            high: 5.492717228853464e-09,
            low: 3.386886436606046e-25,
        },
        tail: [
            -2.4030637876233904e-08,
            6.825845472938355e-08,
            -1.4130515709513987e-07,
            2.2680648857901811e-07,
            -2.9307808720354426e-07,
            3.123458737239845e-07,
            -2.7882597500752544e-07,
            2.105418408641472e-07,
            -1.34571862459748e-07,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999996516503,
            low: -1.680023973865754e-17,
        },
        c1: DoubleDouble {
            high: 3.1665473319522913e-09,
            low: 2.0118701314645762e-25,
        },
        tail: [
            -1.4051553785538291e-08,
            4.0513664171556624e-08,
            -8.520584111881278e-08,
            1.3908626879210987e-07,
            -1.8301021489831826e-07,
            1.98914894874961e-07,
            -1.8145482347597404e-07,
            1.403949791227078e-07,
            -9.228390903270292e-08,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999998033839,
            low: 1.2614727975054947e-17,
        },
        c1: DoubleDouble {
            high: 1.8113058959086902e-09,
            low: 6.159504906735143e-26,
        },
        tail: [
            -8.150876531589104e-09,
            2.384886096279072e-08,
            -5.094297832242848e-08,
            8.454270273185589e-08,
            -1.1322925983761914e-07,
            1.2545116762029679e-07,
            -1.1686921097463156e-07,
            9.257257224894727e-08,
            -6.249864010809923e-08,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999998898706,
            low: 2.9269750388241815e-17,
        },
        c1: DoubleDouble {
            high: 1.0280274043253109e-09,
            low: -7.433829350049007e-26,
        },
        tail: [
            -4.69037503223423e-09,
            1.392388158826583e-08,
            -3.020039652916196e-08,
            5.093855921703754e-08,
            -6.941561970656644e-08,
            7.835992509974786e-08,
            -7.450455526635973e-08,
            6.036931231669376e-08,
            -4.181459723643465e-08,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999387839,
            low: 3.813525439388226e-17,
        },
        c1: DoubleDouble {
            high: 5.789281366587476e-10,
            low: -1.7302417631566812e-26,
        },
        tail: [
            -2.677542632046707e-09,
            8.062780403254466e-09,
            -1.775266547184962e-08,
            3.042359702085267e-08,
            -4.2169001262054354e-08,
            4.8479565265383395e-08,
            -4.7018310822475375e-08,
            3.894311015249092e-08,
            -2.7645331307841505e-08,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999999999966232,
            low: -2.0091072344248352e-17,
        },
        c1: DoubleDouble {
            high: 3.2348317508052726e-10,
            low: -1.0201933356232392e-27,
        },
        tail: [
            -1.5163273831899711e-09,
            4.630695347439604e-09,
            -1.034774975950224e-08,
            1.801282220752962e-08,
            -2.5385634750413393e-08,
            2.9709821063348292e-08,
            -2.9376436468395146e-08,
            2.4853972295769264e-08,
            -1.806601648466655e-08,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999815149,
            low: 5.461622108299497e-17,
        },
        c1: DoubleDouble {
            high: 1.7934357034341344e-10,
            low: -6.687102157423963e-28,
        },
        tail: [
            -8.518819591312136e-10,
            2.637845013799571e-09,
            -5.980921254732912e-09,
            1.0572396888269488e-08,
            -1.514471606318671e-08,
            1.8036286173651487e-08,
            -1.8172805967605676e-08,
            1.569552441832921e-08,
            -1.1672083852926302e-08,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999899583,
            low: -6.645105416157948e-18,
        },
        c1: DoubleDouble {
            high: 9.865679436750356e-11,
            low: -3.261943681236381e-27,
        },
        tail: [
            -4.747858228936107e-10,
            1.4903855836602052e-09,
            -3.4279783697195944e-09,
            6.151742692124492e-09,
            -8.95429299767072e-09,
            1.0847439328503333e-08,
            -1.113205650831776e-08,
            9.809103879933092e-09,
            -7.457076658925329e-09,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999945866,
            low: 4.1001774321813545e-17,
        },
        c1: DoubleDouble {
            high: 5.384870492099461e-11,
            low: -2.0413532120130008e-27,
        },
        tail: [
            -2.625124364898486e-10,
            8.352158502843876e-10,
            -1.948334489572729e-09,
            3.5486875031485796e-09,
            -5.247061325032347e-09,
            6.463472900394763e-09,
            -6.752992577383138e-09,
            6.0675053048627736e-09,
            -4.71197914756757e-09,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.999999999997104,
            low: -9.826339493232495e-18,
        },
        c1: DoubleDouble {
            high: 2.916289271117543e-11,
            low: -1.2094205968462625e-27,
        },
        tail: [
            -1.439917827614286e-10,
            4.6425198735224614e-10,
            -1.0981248328561235e-09,
            2.0295209509665053e-09,
            -3.0474199406601505e-09,
            3.815814231051564e-09,
            -4.057130499997907e-09,
            3.715077899442904e-09,
            -2.945273487601561e-09,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999984626,
            low: -2.294992711807301e-17,
        },
        c1: DoubleDouble {
            high: 1.567086653101735e-11,
            low: -1.4687758721645693e-27,
        },
        tail: [
            -7.835433265508668e-11,
            2.5595748667303165e-10,
            -6.137756057980233e-10,
            1.1507639670364722e-09,
            -1.7542664486702256e-09,
            2.232100129966789e-09,
            -2.414213053749786e-09,
            2.25189655908635e-09,
            -1.821385882288407e-09,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.99999999999919,
            low: 4.1294737322387633e-17,
        },
        c1: DoubleDouble {
            high: 8.355308652070836e-12,
            low: 7.7356729883685285e-28,
        },
        tail: [
            -4.2298750051108576e-11,
            1.399731785383106e-10,
            -3.402075248250275e-10,
            6.46928285110827e-10,
            -1.0009694735545889e-09,
            1.2937981911896599e-09,
            -1.4229712102332055e-09,
            1.3514318536652866e-09,
            -1.1145339380306472e-09,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999995766,
            low: -1.727604158766289e-17,
        },
        c1: DoubleDouble {
            high: 4.4201708693385774e-12,
            low: -3.257569268104341e-28,
        },
        tail: [
            -2.2653375705360186e-11,
            7.592564337010391e-11,
            -1.8700833590095722e-10,
            3.6058939614333596e-10,
            -5.66137994913943e-10,
            7.431318554514611e-10,
            -8.308232305224637e-10,
            8.030535156108641e-10,
            -6.749251045578985e-10,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999997803,
            low: 2.3469117127182534e-17,
        },
        c1: DoubleDouble {
            high: 2.3201854169035015e-12,
            low: -1.623124038437096e-28,
        },
        tail: [
            -1.20359618501869e-11,
            4.085097292620243e-11,
            -1.0194522374405666e-10,
            1.9928104773189907e-10,
            -3.174047516746517e-10,
            4.229905192187626e-10,
            -4.805510312694568e-10,
            4.725373524212381e-10,
            -4.045203590878661e-10,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999998869,
            low: 2.859354043191264e-17,
        },
        c1: DoubleDouble {
            high: 1.2084074716006773e-12,
            low: -3.6921652700459885e-29,
        },
        tail: [
            -6.344139225903548e-12,
            2.1801684800092904e-11,
            -5.511470952501271e-11,
            1.0920038476867973e-10,
            -1.7640341725071375e-10,
            2.3860455166694914e-10,
            -2.753680482746336e-10,
            2.753615864154932e-10,
            -2.399912197075986e-10,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999423,
            low: -5.171334842093867e-17,
        },
        c1: DoubleDouble {
            high: 6.244694333342769e-13,
            low: 4.5281328984544066e-29,
        },
        tail: [
            -3.317493864588341e-12,
            1.1541300959284099e-11,
            -2.955074938494455e-11,
            5.933295227862266e-11,
            -9.718856969089345e-11,
            1.3339118247126495e-10,
            -1.56334226009819e-10,
            1.5891984341852092e-10,
            -1.4094985852271972e-10,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999707,
            low: 1.5002305232589177e-17,
        },
        c1: DoubleDouble {
            high: 3.2019610382476285e-13,
            low: 1.9970455157147226e-29,
        },
        tail: [
            -1.7210540580580976e-12,
            6.060378340087185e-12,
            -1.57135821029902e-11,
            3.196608809248604e-11,
            -5.308228585886056e-11,
            7.390808029351936e-11,
            -8.793931653428645e-11,
            9.084278598413115e-11,
            -8.195760866790754e-11,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999852,
            low: 2.7861467917110073e-17,
        },
        c1: DoubleDouble {
            high: 1.6290258474469528e-13,
            low: -1.0269311185388288e-29,
        },
        tail: [
            -8.857828045492788e-13,
            3.156661804902101e-12,
            -8.286913347242763e-12,
            1.707703803161766e-11,
            -2.874228782621507e-11,
            4.058713545956825e-11,
            -4.901413976489513e-11,
            5.143614819330344e-11,
            -4.718537955652814e-11,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999927,
            low: -3.03759554483649e-17,
        },
        c1: DoubleDouble {
            high: 8.223316045262944e-14,
            low: -3.5523520435497835e-30,
        },
        tail: [
            -4.5228238248946086e-13,
            1.6309576823061469e-12,
            -4.3343728321874905e-12,
            9.04633295097011e-12,
            -1.5429110960851447e-11,
            2.2091798833456192e-11,
            -2.7070022677858485e-11,
            2.8849517850383654e-11,
            -2.690015717173245e-11,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999963,
            low: 1.8562282380943798e-17,
        },
        c1: DoubleDouble {
            high: 4.118822368239724e-14,
            low: 2.4553688914397015e-30,
        },
        tail: [
            -2.2910949423333407e-13,
            8.358849665519931e-13,
            -2.2484352318166825e-12,
            4.752002915096053e-12,
            -8.211422660783237e-12,
            1.1918834062987248e-11,
            -1.4815059564018928e-11,
            1.6029711651157256e-11,
            -1.5186745398774787e-11,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999982,
            low: -1.5663166250755952e-17,
        },
        c1: DoubleDouble {
            high: 2.0469452084237998e-14,
            low: -5.250790614132172e-31,
        },
        tail: [
            -1.151406679738384e-13,
            4.249543542057335e-13,
            -1.1568038985485829e-12,
            2.4753224735844595e-12,
            -4.3327485893121016e-12,
            6.373964466163621e-12,
            -8.034953677597141e-12,
            8.823753704441665e-12,
            -8.491186470462275e-12,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999991,
            low: 1.3952524473675248e-17,
        },
        c1: DoubleDouble {
            high: 1.0093608306173617e-14,
            low: 2.268314342138259e-31,
        },
        tail: [
            -5.740739724136226e-14,
            2.1430517843731123e-13,
            -5.902945521022982e-13,
            1.2786285570670496e-12,
            -2.266654753753355e-12,
            3.3788679177230374e-12,
            -4.318623020334184e-12,
            4.8122008098353436e-12,
            -4.7021355517713255e-12,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999996,
            low: 2.0875548107488853e-17,
        },
        c1: DoubleDouble {
            high: 4.938485140964241e-15,
            low: -3.798031893932481e-31,
        },
        tail: [
            -2.8396289560544276e-14,
            1.0720628160132133e-13,
            -2.987526297512107e-13,
            6.549691664915961e-13,
            -1.1756901982993877e-12,
            1.7755400452429432e-12,
            -2.3004090791459724e-12,
            2.6002660295736665e-12,
            -2.5791261965619175e-12,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999998,
            low: 1.8738728654048252e-17,
        },
        c1: DoubleDouble {
            high: 2.39744211251108e-15,
            low: 9.606919448763983e-33,
        },
        tail: [
            -1.3935132278970593e-14,
            5.3199490209929216e-14,
            -1.4996597433013235e-13,
            3.327110446585029e-13,
            -6.046367209399857e-13,
            9.24908638593829e-13,
            -1.2144450021758763e-12,
            1.392179919712895e-12,
            -1.4012857409955164e-12,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 0.9999999999999999,
            low: 1.4106746009743903e-17,
        },
        c1: DoubleDouble {
            high: 1.1548074643502594e-15,
            low: 8.853152355852188e-32,
        },
        tail: [
            -6.784493853057742e-15,
            2.6187665102892293e-14,
            -7.466476828901115e-14,
            1.6760590671548379e-13,
            -3.083176282282552e-13,
            4.776251976845333e-13,
            -6.354451246385677e-13,
            7.385762343499426e-13,
            -7.541921117520988e-13,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 1.0,
            low: -4.5844734362343966e-17,
        },
        c1: DoubleDouble {
            high: 5.519225130576599e-16,
            low: 1.945587350668117e-32,
        },
        tail: [
            -3.2770399212798378e-15,
            1.2787642183974408e-14,
            -3.6870966093402596e-14,
            8.373225223181811e-14,
            -1.55887824438147e-13,
            2.445153369761073e-13,
            -3.29548560085545e-13,
            3.882715387281928e-13,
            -4.0212548658720195e-13,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 1.0,
            low: -2.1519736712498913e-17,
        },
        c1: DoubleDouble {
            high: 2.6173012392492837e-16,
            low: 7.602469937416523e-33,
        },
        tail: [
            -1.5703807435495605e-15,
            6.1942795995177956e-15,
            -1.8059378550787426e-14,
            4.1484224864567786e-14,
            -7.815261519035127e-14,
            1.2409819447551428e-13,
            -1.6940064755729883e-13,
            2.0227073210272403e-13,
            -2.1241611152253936e-13,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 1.0,
            low: -1.0023862905439418e-17,
        },
        c1: DoubleDouble {
            high: 1.2315055872807974e-16,
            low: -4.531466923484116e-33,
        },
        tail: [
            -7.466002622889781e-16,
            2.9764592071546596e-15,
            -8.773525217636156e-15,
            2.0382861008761906e-14,
            -3.885075809227054e-14,
            6.244172444726936e-14,
            -8.631326002846217e-14,
            1.044248764302763e-13,
            -1.1116813206188829e-13,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 1.0,
            low: -4.6332221552992656e-18,
        },
        c1: DoubleDouble {
            high: 5.749447817932618e-17,
            low: -3.787063897678053e-33,
        },
        tail: [
            -3.5215367884837006e-16,
            1.4187960292269025e-15,
            -4.227678279915089e-15,
            9.932173039149922e-15,
            -1.9150805673753272e-14,
            3.114896140579919e-14,
            -4.3593200199432776e-14,
            5.3427362043470945e-14,
            -5.764476215007722e-14,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 1.0,
            low: -2.125103881975198e-18,
        },
        c1: DoubleDouble {
            high: 2.6633176128522054e-17,
            low: 1.0397787029394594e-34,
        },
        tail: [
            -1.6479277729522875e-16,
            6.708924809610015e-16,
            -2.0206426872205373e-15,
            4.799822938944997e-15,
            -9.36079672325e-15,
            1.5405660613435266e-14,
            -2.182479707172912e-14,
            2.7091123569529472e-14,
            -2.9617253616549885e-14,
        ],
    },
    ErfCell {
        c0: DoubleDouble {
            high: 1.0,
            low: -9.672204131876253e-19,
        },
        c1: DoubleDouble {
            high: 1.2241280792599667e-17,
            low: 4.169102433140375e-34,
        },
        tail: [
            -7.650800495374716e-17,
            3.147029270401679e-16,
            -9.579439786891218e-16,
            2.3004490853111207e-15,
            -4.537150513460116e-15,
            7.554289424854922e-15,
            -1.0831357036132325e-14,
            1.3614692670890314e-14,
            -1.507831759872033e-14,
        ],
    },
];

/// Ziv gate for the erfc / erf-bridge fast leg, as an absolute bound on the
/// double-double mantissa (erfc) or result (1 − erfc, 2 − erfc).
///
/// The lean leg (prefix `Q` ≈2⁻⁷² plus [`exp_dd_of_dd_fast`] ≈2⁻⁶⁸) is good to
/// ≈2⁻⁶⁷; `2⁻⁶²` keeps a ~30× margin.
const ERFC_ZIV_EPS: f64 = 1.084_202_172_485_504_4e-19; // 2^-62

/// Ziv gate for the `erf_small` fast leg, relative (its result ≈ `x` can be tiny).
const ERF_SMALL_ZIV_EPS: f64 = 1.355_252_715_606_88e-20; // 2^-66

/// Ziv gate for the table-driven `erf` fast leg, relative (`erf ∈ [0.46, 1)`).
///
/// The cell polynomial is good to ≈2⁻⁶⁷ (degree-11 minimax ≈2⁻⁷¹ plus the `f64`
/// tail's ≈2⁻⁶⁷); `2⁻⁶²` keeps a ~30× margin.
const ERF_TABLE_ZIV_EPS: f64 = 1.084_202_172_485_504_4e-19; // 2^-62

/// Negate a double-double.
#[inline]
fn neg(a: DoubleDouble) -> DoubleDouble {
    DoubleDouble {
        high: -a.high,
        low: -a.low,
    }
}

/// `value · 2`<sup>`q`</sup> as a double-double at true magnitude.
///
/// Used to bring an `erfc` mantissa back to its actual value for the benign
/// subtractions `1 − erfc` (erf) and `2 − erfc` (erfc of a negative argument),
/// where `q ≤ 0` keeps the scaling exact and the result normal.
#[inline]
const fn scale_dd(value: DoubleDouble, q: i64) -> DoubleDouble {
    DoubleDouble {
        high: fast_ldexp(value.high, q),
        low: fast_ldexp(value.low, q),
    }
}

/// Double-double prefix length for the mixed-precision fast-leg evaluator.
///
/// The first `SPLIT` coefficients are kept in double-double; the rest become a
/// plain-`f64` tail.  A power of two so [`poly_dd_split`] reaches `vᵏ` by repeated
/// squaring.  `|v| ≤ 0.154` here, so the first dropped term `c·v^SPLIT` is ≲2⁻¹⁰
/// of `Q` and the whole tail's `f64` slip stays well under the fast leg's 2⁻⁶²
/// Ziv budget — confirmed by the fast-leg fallback rate being unchanged from the
/// all-double-double evaluation.
const SPLIT: usize = 4;

/// Fast-leg `Q(v) = Σ coeffs[k]·vᵏ` with the high-degree tail in plain `f64`.
///
/// The tail terms (degree `≥ SPLIT`) are a small fraction of `Q` (see [`SPLIT`]),
/// so evaluating them in `f64` instead of double-double costs no extra Ziv
/// fallbacks while doing roughly half the double-double work.  The double-double
/// prefix, the `f64` tail, and `vᵏ` are independent, so the critical path is
/// shallow.
///
/// Only for the Ziv-gated *fast* legs; the accurate path stays full double-double
/// (it is what guarantees correct rounding).  `coeffs.len()` must exceed `SPLIT`.
#[inline]
fn poly_dd_split(v: DoubleDouble, coeffs: &[DoubleDouble]) -> DoubleDouble {
    // Tail Σ coeffs[SPLIT+d].high · v.high^d in plain-f64 Horner (the low words and
    // v.low are dropped — harmless, the tail is a small fraction of `Q`).
    let mut tail = 0.0_f64;
    for c in coeffs[SPLIT..].iter().rev() {
        tail = crate::fast_mul_add(tail, v.high, c.high);
    }

    // vᵏ = v^SPLIT by repeated squaring (SPLIT is a power of two).
    let mut vk = v;
    let mut e = 1;
    while e < SPLIT {
        vk = vk * vk;
        e *= 2;
    }

    // Q = prefix(v) + v^SPLIT · tail; the three parts are computed independently.
    poly_dd(v, &coeffs[..SPLIT]) + vk * tail
}

/// `erf(x) = x·P(x²)` as a double-double for `|x| < 0.4375`
///
/// `coeffs` is the full [`ERF_SMALL_DD`] for the accurate path or
/// [`ERF_SMALL_FAST`] for the fast leg.  Forming `x²` exactly and multiplying by
/// `x` last keeps the through-origin zero and the leading `2/√π` behaviour exact.
/// `split` routes the fast leg through [`poly_dd_split`] (mixed precision).
#[inline]
fn erf_small_eval(x: f64, coeffs: &[DoubleDouble], split: bool) -> DoubleDouble {
    let u = DoubleDouble::from_product(x, x);
    let p = if split {
        poly_dd_split(u, coeffs)
    } else {
        poly_dd(u, coeffs)
    };
    p * x
}

/// `erf(ax)` as a double-double for `ax ∈ [0.4375, 6.25]`, straight from
/// [`ERF_TABLE`] — the fast leg that sidesteps the `erfc` bridge's `exp`.
///
/// `i = round(8·ax)` picks the cell (`xi = i/8`); `h = ax − xi` is exact
/// (Sterbenz, `|h| ≤ 1/16`).  The `c3..c11` tail is summed in `f64`, then the
/// `c2`/`c1`/`c0` leads fold in double-double — a few double-double FMAs versus
/// the bridge's reciprocal + `Q` polynomial + `exp`.
#[inline]
fn erf_table_eval(ax: f64) -> DoubleDouble {
    let fi = (ax * 16.0).round_ties_even();
    // SAFETY: ax ∈ [0.4375, 6.25] ⇒ 16·ax ∈ [7, 100] ⇒ fi ∈ [7, 100].
    let cell = &ERF_TABLE[unsafe { fi.to_int_unchecked::<usize>() } - 7];
    let h = ax - fi * 0.0625;

    // P(h) = c0 + h·(c1 + h·tail), tail = c2 + c3·h + … in f64.  The finer 1/16
    // cell (|h| ≤ 1/32) keeps the `c2..` tail accurate enough in plain `f64` to
    // need only two double-double folds (`c1`, `c0`) — one fewer than the 1/8 table.
    let tail = crate::poly(h, &cell.tail);
    let acc = cell.c1
        + DoubleDouble {
            high: h * tail,
            low: 0.0,
        };
    cell.c0 + acc * h
}

/// Select the `erfc` segment for `x ≥ 0.4375`: its anchor `t`, the accurate `Q`
/// coefficients, and the lower-degree fast-leg `Q` coefficients.
#[inline]
fn erfc_segment(x: f64) -> (f64, &'static [DoubleDouble], &'static [DoubleDouble]) {
    let i = if x <= ERFC_BREAKS[0] {
        0
    } else if x <= ERFC_BREAKS[1] {
        1
    } else if x <= ERFC_BREAKS[2] {
        2
    } else if x <= ERFC_BREAKS[3] {
        3
    } else {
        4
    };
    // Return the slices by `match` rather than indexing a freshly-built array of
    // fat pointers (which the optimizer would materialize on the stack each call).
    let (accurate, fast): (&[DoubleDouble], &[DoubleDouble]) = match i {
        0 => (&ERFC_Q0, &ERFC_QF0),
        1 => (&ERFC_Q1, &ERFC_QF1),
        2 => (&ERFC_Q2, &ERFC_QF2),
        3 => (&ERFC_Q3, &ERFC_QF3),
        _ => (&ERFC_Q4, &ERFC_QF4),
    };
    (ERFC_ANCHORS[i], accurate, fast)
}

/// `erfc(x)` for `x ∈ [0.4375, 27.226…]` as `(mantissa ∈ [1, 2), q)`, i.e.
/// `erfc(x) = mantissa · 2`<sup>`q`</sup>
///
/// `erfc(x) = t·exp(Q(t) − x²)`, `t = 2/(2+x)`: `Q(t)` from the per-segment
/// double-double minimax in `v = t − anchor`, `x²` exact, the exponent `W = Q − x²`
/// carried in double-double, and the `t` factor folded into the mantissa before
/// renormalizing into `[1, 2)`.  `coeffs` selects accuracy; `fast` picks both the
/// mixed-precision `Q` ([`poly_dd_split`]) and the matching `exp` leg.
#[inline]
fn erfc_eval(x: f64, anchor: f64, coeffs: &[DoubleDouble], fast: bool) -> (DoubleDouble, i64) {
    // t = 2/(2+x) to ≈2⁻¹⁰⁶: `2 + x` must be exact (a plain `2.0 + x` would round
    // first, injecting a ≈2⁻⁵³ error into both the t-factor and the Q variable).
    // `t` is on the critical path (feeds the Q variable `v` and the final `t·m`),
    // so the fast leg fuses `2/(2+x)` into one division — one reciprocal `iqh =
    // 1/d.high` driving the double-double division correction (the atan quotient
    // trick) — instead of the accurate leg's dd reciprocal + Newton step and ×2.
    let d = DoubleDouble::from_sum(2.0, x);
    let t = if fast {
        let iqh = 1.0 / d.high;
        let th = 2.0 * iqh;
        let tl = crate::fast_mul_add(
            2.0 * crate::fast_mul_add(-d.low, iqh, crate::fma(-d.high, iqh, 1.0)),
            iqh,
            crate::fma(2.0, iqh, -th),
        );
        DoubleDouble { high: th, low: tl }
    } else {
        d.recip() * 2.0
    };
    let v = t + DoubleDouble {
        high: -anchor,
        low: 0.0,
    };
    let q = if fast {
        poly_dd_split(v, coeffs)
    } else {
        poly_dd(v, coeffs)
    };

    // W = Q(t) − x², with x² exact and the difference in double-double.
    let w = q + neg(DoubleDouble::from_product(x, x));

    // exp(W) = m · 2^qe, then erfc = t·m·2^qe renormalized so the high word ∈ [1, 2).
    let (m, qe) = if fast {
        exp_dd_of_dd_fast(w)
    } else {
        exp_dd_of_dd(w)
    };
    let prod = t * m;
    let e2 = (prod.high.to_bits() >> super::EXP_SHIFT) as i64 - 1023;
    let mantissa = DoubleDouble {
        high: fast_ldexp(prod.high, -e2),
        low: fast_ldexp(prod.low, -e2),
    };
    (mantissa, qe + e2)
}

/// Below this `|x|`, `x²` underflows to zero and the result needs subnormal-safe
/// rounding (its ulp drops below the double-double low word in the first binade).
const ERF_TINY: f64 = crate::exp2i(-1000);

/// `erf(x) = x·(2/√π)` correctly rounded for tiny `|x|` (below [`ERF_TINY`])
///
/// There `x²` underflows to zero, so every higher term of `erf(x) = x·P(x²)`
/// vanishes and `erf(x) = x·(2/√π)` exactly.  A plain `x·c` would round near the
/// subnormal grid first and lose bits, so the product is formed at normal
/// magnitude and finished once with [`round_general64`].
#[cold]
fn erf_tiny(x: f64) -> f64 {
    // Normalize `|x|` to `mant ∈ [1, 2) · 2^ex` (×2⁵⁴ first so a subnormal is normal).
    let scaled = (x.abs() * crate::exp2i(54)).to_bits();
    let ex = (scaled >> super::EXP_SHIFT) as i64 - 1023 - 54;
    let mant = f64::from_bits((scaled & 0x000f_ffff_ffff_ffff) | 0x3ff0_0000_0000_0000);

    let p = ERF_SMALL_DD[0] * mant; // (2/√π)·mant ∈ [1.128, 2.256)
    let (m, q) = if p.high >= 2.0 {
        (p * 0.5, ex + 1)
    } else {
        (p, ex)
    };
    round_general64(m, q).copysign(x)
}

/// The error function
#[must_use]
#[inline]
pub fn erf(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    let ax = x.abs();

    if ax < 0.4375 {
        if ax < ERF_TINY {
            return erf_tiny(x);
        }
        // Fast leg: a lower-degree double-double minimax, accepted unless its
        // relative error interval straddles a rounding boundary.
        let e = erf_small_eval(x, &ERF_SMALL_FAST, true);
        let eps = e.high.abs() * ERF_SMALL_ZIV_EPS;
        let lo = e.high + (e.low - eps);
        let hi = e.high + (e.low + eps);
        if lo == hi {
            return lo;
        }
        let e = erf_small_eval(x, &ERF_SMALL_DD, false);
        return e.high + e.low;
    }

    // erf rounds to ±1 (covering ±∞) once erfc drops below ½ ulp.
    if ax > ERF_ONE_THRESHOLD {
        return 1.0_f64.copysign(x);
    }

    // Table-driven fast leg: erf(ax) = P_i(ax − i/8) directly, no `exp`.  Accepted
    // unless its relative error interval straddles a rounding boundary.
    let e = erf_table_eval(ax);
    let eps = e.high.abs() * ERF_TABLE_ZIV_EPS;
    let lo = e.high + (e.low - eps);
    let hi = e.high + (e.low + eps);
    if lo == hi {
        return lo.copysign(x);
    }

    // Accurate fallback: erf(x) = sign(x)·(1 − erfc(|x|)); erfc ∈ (0, 0.536] here,
    // so 1 − erfc ∈ [0.46, 1) — no cancellation, and the result is always normal.
    let (anchor, accurate, _) = erfc_segment(ax);
    let (m, q) = erfc_eval(ax, anchor, accurate, false);
    let r = ONE + neg(scale_dd(m, q));
    (r.high + r.low).copysign(x)
}

/// The complementary error function `1 − erf(x)`
#[must_use]
#[inline]
pub fn erfc(x: f64) -> f64 {
    if x.is_nan() {
        return x;
    }

    // erfc → 2 for very negative x (covering −∞) and → +0 for large x (covering +∞).
    if x < -ERF_ONE_THRESHOLD {
        return 2.0;
    }
    if x >= ERFC_ZERO_THRESHOLD {
        return 0.0;
    }

    let ax = x.abs();

    if ax < 0.4375 {
        // erfc(x) = 1 − erf(x); the result is ≈ 1, so carry 1 − erf in double-double
        // (the accurate small kernel — this regime is cheap and not the hot path).
        let r = ONE + neg(erf_small_eval(x, &ERF_SMALL_DD, false));
        return r.high + r.low;
    }

    if x > 0.0 {
        // erfc(x) = t·exp(Q − x²) and spans the full underflow range; this leg
        // genuinely needs the `exp`.  Fast leg, Ziv-gated against the accurate
        // path, keeping the normal/subnormal transition (`q < −1021`) accurate.
        let (anchor, accurate, fast) = erfc_segment(ax);
        let (m, q) = erfc_eval(ax, anchor, fast, true);
        if q >= -1021 {
            let lo = m.high + (m.low - ERFC_ZIV_EPS);
            let hi = m.high + (m.low + ERFC_ZIV_EPS);
            if lo == hi {
                return fast_ldexp(lo, q);
            }
        }
        let (m, q) = erfc_eval(ax, anchor, accurate, false);
        round_general64(m, q)
    } else {
        // erfc(−|x|) = 1 + erf(|x|) ∈ [1.46, 2): the table fast leg gives erf
        // directly, no `exp`, and `1 +` cannot cancel.  Ziv-gated against the
        // accurate erfc bridge (`2 − erfc(|x|)`).
        let e = ONE + erf_table_eval(ax);
        let eps = e.high.abs() * ERF_TABLE_ZIV_EPS;
        let lo = e.high + (e.low - eps);
        let hi = e.high + (e.low + eps);
        if lo == hi {
            return lo;
        }
        let (anchor, accurate, _) = erfc_segment(ax);
        let (m, q) = erfc_eval(ax, anchor, accurate, false);
        let r = TWO + neg(scale_dd(m, q));
        r.high + r.low
    }
}
