//! Trigonometric functions: `sin`, `cos`, `sincos`, `tan`.
//!
//! Double-double constants below were generated by `tools/gen_trig_f64.py`; the
//! accurate-path `Dint` constants (`PIO2_DINT`, `SIN_DINT`, `COS_DINT`) by
//! `tools/gen_dint_trig.py`.  Do not edit by hand; re-run the generators instead.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::dint::Dint;
use super::double::{DoubleDouble, fast_sum};
use super::pow::poly_dd;

/// `sin(r)/r` as a double-double in `u = r²`, low-degree first (max error ≈2⁻¹²⁷).
const SIN_KERNEL: [DoubleDouble; 13] = [
    DoubleDouble {
        high: 1.0,
        low: -5.0987018554029683e-39,
    },
    DoubleDouble {
        high: -0.16666666666666666,
        low: -9.25185853854297e-18,
    },
    DoubleDouble {
        high: 0.008333333333333333,
        low: 1.156482317317869e-19,
    },
    DoubleDouble {
        high: -0.0001984126984126984,
        low: -1.7209558292516092e-22,
    },
    DoubleDouble {
        high: 2.7557319223985893e-06,
        low: -1.858393275722529e-22,
    },
    DoubleDouble {
        high: -2.505210838544172e-08,
        low: 1.4488159186621237e-24,
    },
    DoubleDouble {
        high: 1.6059043836821613e-10,
        low: 1.2572222845296136e-26,
    },
    DoubleDouble {
        high: -7.647163731819815e-13,
        low: -4.606435501111483e-29,
    },
    DoubleDouble {
        high: 2.81145725434532e-15,
        low: 5.160177200634138e-32,
    },
    DoubleDouble {
        high: -8.220635246177278e-18,
        low: -5.582599714358412e-34,
    },
    DoubleDouble {
        high: 1.95729403918814e-20,
        low: 1.4084261345322546e-36,
    },
    DoubleDouble {
        high: -3.868105107347916e-23,
        low: 2.2080719840678897e-39,
    },
    DoubleDouble {
        high: 6.41022925531651e-26,
        low: 2.880120311859419e-42,
    },
];

/// `cos(r)` as a double-double in `u = r²`, low-degree first (max error ≈2⁻¹²²).
const COS_KERNEL: [DoubleDouble; 13] = [
    DoubleDouble {
        high: 1.0,
        low: -1.3761459043912074e-37,
    },
    DoubleDouble {
        high: -0.5,
        low: 7.540540356661797e-35,
    },
    DoubleDouble {
        high: 0.041666666666666664,
        low: 2.312964634635736e-18,
    },
    DoubleDouble {
        high: -0.001388888888888889,
        low: 5.300543954397993e-20,
    },
    DoubleDouble {
        high: 2.48015873015873e-05,
        low: 2.1511943343054862e-23,
    },
    DoubleDouble {
        high: -2.755731922398589e-07,
        low: -2.376766475147913e-23,
    },
    DoubleDouble {
        high: 2.08767569878681e-09,
        low: -1.2108731843273183e-25,
    },
    DoubleDouble {
        high: -1.1470745597729723e-11,
        low: -1.5011050364192592e-28,
    },
    DoubleDouble {
        high: 4.779477332386843e-14,
        low: -3.9852328581359e-31,
    },
    DoubleDouble {
        high: -1.561920696737958e-16,
        low: 7.95243117129581e-33,
    },
    DoubleDouble {
        high: 4.110317442059798e-19,
        low: 1.3835401064045195e-35,
    },
    DoubleDouble {
        high: -8.89661576927929e-22,
        low: 1.9801804476213101e-38,
    },
    DoubleDouble {
        high: 1.6018249140912734e-24,
        low: -7.728223090239399e-41,
    },
];

/// Fast-path tail of `sin(r)/r`: coefficients of the `u³` remainder after the
/// three exact leading terms are peeled off, low-degree first in `u = r²`
/// (`sin(r)/r = 1 − u/6 + u²/120 + u³·SIN_TAIL(u)`).  Approximation error on
/// `sin(r)/r` ≈ 2⁻⁷⁴, so once evaluated in plain `f64` the fast kernel is good
/// to ≈2⁻⁶⁰ — enough for the Ziv gate, far cheaper than the double-double Horner.
const SIN_TAIL: [f64; 6] = [
    -0.0001984126984126984,
    2.7557319223985634e-06,
    -2.505210838495563e-08,
    1.6059043500527755e-10,
    -7.647058546227501e-13,
    2.7962863666189794e-15,
];

/// Fast-path tail of `cos(r)`: the `u³` remainder after the three exact leading
/// terms (`cos(r) = 1 − u/2 + u²/24 + u³·COS_TAIL(u)`).  Approximation error on
/// `cos(r)` ≈ 2⁻⁷⁰.  See [`SIN_TAIL`].
const COS_TAIL: [f64; 6] = [
    -0.001388888888888889,
    2.4801587301586814e-05,
    -2.755731922306274e-07,
    2.087675634918288e-09,
    -1.1470545821738428e-11,
    4.750660993437302e-14,
];

/// Leading 6 terms of `tan(r)/r = Σ bₖ·v^k` (`v = r²`), as double-doubles,
/// low-degree first.  `tan`'s pole at `π/2` makes the series converge only
/// geometrically (like `asin`), so [`tan_kernel_fast`] carries these exactly and
/// fits the `v⁶` remainder ([`TAN_TAIL`]) in plain `f64`.  Generated by
/// `tools/gen_trig_f64.py`.
const TAN_LEADS: [DoubleDouble; 6] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.3333333333333333,
        low: 1.850371707708594e-17,
    },
    DoubleDouble {
        high: 0.13333333333333333,
        low: 1.8503717077085942e-18,
    },
    DoubleDouble {
        high: 0.05396825396825397,
        low: -2.5552752154071065e-18,
    },
    DoubleDouble {
        high: 0.021869488536155203,
        low: -1.7377829530067485e-19,
    },
    DoubleDouble {
        high: 0.008863235529902197,
        low: -7.63300580171831e-19,
    },
];

/// Fast-path tail of `tan(r)/r` in `v = r²`: the `v⁶` remainder after
/// [`TAN_LEADS`] is peeled into double-double.  Evaluated in plain `f64`; over the
/// `[−π/4, π/4]` octant the assembled kernel reaches ≈2⁻⁶¹ relative — enough that
/// the reciprocal of the odd-quadrant path still clears the `2⁻⁵⁹` gate.
const TAN_TAIL: [f64; 15] = [
    0.003592128036572481,
    0.001455834387051282,
    0.0005900274409499761,
    0.0002391291140349121,
    9.691538474772203e-05,
    3.9278246728957075e-05,
    1.591965246822141e-05,
    6.44674860195779e-06,
    2.6377035355686352e-06,
    9.839484146788608e-07,
    6.078285342856009e-07,
    -1.204289917739238e-07,
    3.9928830670121667e-07,
    -2.0027017684620337e-07,
    9.276165196030918e-08,
];

/// Relative half-width of the trig fast-path Ziv gate.  Over a dense sweep of
/// the `[-π/4, π/4]` octant the fast kernel's relative error peaks at ≈2⁻⁶¹·⁶
/// (cos) and ≈2⁻⁶⁵ (sin); `2⁻⁵⁹` keeps a ~6× margin over that while the gate
/// stays tight enough that only a few percent of inputs fall through to the
/// accurate kernel.
const TRIG_ZIV_EPS: f64 = 1.734723475976807e-18; // 2⁻⁵⁹

/// `1` as a double-double.
const ONE: DoubleDouble = DoubleDouble {
    high: 1.0,
    low: 0.0,
};

/// `1/120` as a double-double — the exact `u²` coefficient peeled from
/// `sin(r)/r`.  Carried in double-double so the term does not cap the fast
/// kernel at the `f64` rounding of `1/120` (≈2⁻⁵⁹).
const FRAC_1_120: DoubleDouble = DoubleDouble {
    high: 0.008333333333333333,
    low: 1.1564823173178714e-19,
};

/// `−1/6` as a double-double — the exact `u` coefficient peeled from
/// `sin(r)/r`, carried as a constant so the term is one double-double multiply
/// instead of `Div<f64>`'s two serial divisions.  See [`FRAC_1_120`].
const NEG_FRAC_1_6: DoubleDouble = DoubleDouble {
    high: -0.16666666666666666,
    low: -9.25185853854297e-18,
};

/// `1/24` as a double-double — the exact `u²` coefficient peeled from `cos(r)`.
/// See [`FRAC_1_120`].
const FRAC_1_24: DoubleDouble = DoubleDouble {
    high: 0.041666666666666664,
    low: 2.3129646346357427e-18,
};

/// 2/π as f64, for the medium-range quotient `round(x·2/π)`.
const FRAC_2_PI_F64: f64 = 0.6366197723675814;

/// π/2 in four words (≈2⁻¹⁵⁶ relative); each of `PIO2_1..PIO2_4` has ≥21 low
/// mantissa bits clear, so `q·PIO2_k` is exact for `|q| < 2²¹` (the medium range
/// `|x| < 2²⁰`).  The first three words are subtracted exactly (capturing every
/// residual), the fourth folds into the low part, leaving the reduced angle
/// accurate to ≈2⁻¹³⁰ — past the ≈117-bit ceiling of a 3-word split, which is what
/// keeps the relative Ziv gate sound near a multiple of π/2.
const PIO2_1: f64 = 1.5707963267341256;
const PIO2_2: f64 = 6.077100506303966e-11;
const PIO2_3: f64 = 2.0222662487111665e-21;
const PIO2_4: f64 = 8.478427660348229e-32;

/// π/2 as a double-double, for the Payne–Hanek reconstruction.
const PIO2: DoubleDouble = DoubleDouble {
    high: 1.5707963267948966,
    low: 6.123233995736766e-17,
};

/// Below this magnitude `sin(x)` and `tan(x)` round to `x`, and `cos(x)` rounds
/// to `1`.  The corrections `x³/6` (sin), `x³/3` (tan) and `x²/2` (cos) all stay
/// under half an ulp here, so the fast return is correctly rounded (with a ~6×
/// margin) — the same short-circuit `core-math` takes, sparing the kernel on the
/// roughly half of all `f64` bit patterns that are this small.
const SMALL: f64 = 7.450580596923828e-9; // 2⁻²⁷

/// Fractional bits of 2/π, most-significant 64-bit group first (`FRAC_2_PI[0]`
/// holds bits 1..64).  Used by [`payne_hanek`] for `|x| ≥ 2²⁰`.
const FRAC_2_PI: [u64; 24] = [
    0xA2F9836E4E441529,
    0xFC2757D1F534DDC0,
    0xDB6295993C439041,
    0xFE5163ABDEBBC561,
    0xB7246E3A424DD2E0,
    0x06492EEA09D1921C,
    0xFE1DEB1CB129A73E,
    0xE88235F52EBB4484,
    0xE99C7026B45F7E41,
    0x3991D639835339F4,
    0x9C845F8BBDF9283B,
    0x1FF897FFDE05980F,
    0xEF2F118B5A0A6D1F,
    0x6D367ECF27CB09B7,
    0x4F463F669E5FEA2D,
    0x7527BAC7EBE5F17B,
    0x3D0739F78A5292EA,
    0x6BFB5FB11F8D5D08,
    0x56033046FC7B6BAB,
    0xF0CFBC209AF4361D,
    0xA9E391615EE61B08,
    0x6599855F14A06840,
    0x8DFFD8804D732731,
    0x06061556CA73A8C9,
];

// ---------------------------------------------------------------------------
// Accurate-path `Dint` (128-bit fixed-point) trig.
//
// The double-double accurate kernels above cap at ≈2⁻¹⁰⁶ — both in the
// `sin`/`cos` polynomial *and*, more critically, in the Payne–Hanek collapse of
// the 128-bit reduced fraction into a double-double `r`.  That ceiling mis-rounds
// the corpus's hardest near-ties (≈58-bit, needing ≈2⁻¹¹¹).  The `Dint` path
// feeds the reduced fraction's bits straight into a 128-bit significand (no dd
// collapse) and evaluates the Taylor kernels in `Dint` (≈2⁻¹²⁶), then rounds once
// with the sound `Dint::to_f64` (explicit round + sticky) — no hard-case database,
// exactly as the inverse-hyperbolic `ln`-of-a-double-double legs do.
//
// Constants below were generated by `tools/gen_dint_trig.py`; do not edit by hand.
// ---------------------------------------------------------------------------

/// π/2 as a `Dint`, for the accurate-path reconstruction `r = frac · π/2`.
const PIO2_DINT: Dint = Dint {
    sgn: false,
    ex: 0,
    m: 0xc90fdaa22168c234c4c6628b80dc1cd1,
};

/// `2` as a `Dint`, for the Newton reciprocal `y·(2 − c·y)` behind accurate `tan`.
const TWO_DINT: Dint = Dint {
    sgn: false,
    ex: 1,
    m: 0x80000000000000000000000000000000,
};

/// `sin(r)/r` as `Dint` minimax coefficients in `u = r²`, low-degree first.
/// 14 terms — the max error over `[0, (π/4)²]` is ≈2⁻¹³⁹ (≈2⁻¹³³ after
/// quantizing the coefficients to `Dint`), below the `Dint` arithmetic floor.
const SIN_DINT: [Dint; 14] = [
    Dint {
        sgn: false,
        ex: 0,
        m: 0x80000000000000000000000000000000,
    },
    Dint {
        sgn: true,
        ex: -3,
        m: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    },
    Dint {
        sgn: false,
        ex: -7,
        m: 0x88888888888888888888888888888304,
    },
    Dint {
        sgn: true,
        ex: -13,
        m: 0xd00d00d00d00d00d00d00d00cfd3c095,
    },
    Dint {
        sgn: false,
        ex: -19,
        m: 0xb8ef1d2ab6399c7d560e44714a1cf810,
    },
    Dint {
        sgn: true,
        ex: -26,
        m: 0xd7322b3faa271c7f3a3f1de7e8537244,
    },
    Dint {
        sgn: false,
        ex: -33,
        m: 0xb092309d43684be51bf8946b51ffd81a,
    },
    Dint {
        sgn: true,
        ex: -41,
        m: 0xd73f9f399dc0f88e072a304aab268f7a,
    },
    Dint {
        sgn: false,
        ex: -49,
        m: 0xca963b81856a506e6987c48d14c9f8fc,
    },
    Dint {
        sgn: true,
        ex: -57,
        m: 0x97a4da340a028ffc77b0b12c8f37e854,
    },
    Dint {
        sgn: false,
        ex: -66,
        m: 0xb8dc77b6c7a286d623f9a0ebf12f4b58,
    },
    Dint {
        sgn: true,
        ex: -75,
        m: 0xbb0da042577331ee2548b4a4a2bba83e,
    },
    Dint {
        sgn: false,
        ex: -84,
        m: 0x9f9dceae8bd1c3807edcb35637352631,
    },
    Dint {
        sgn: true,
        ex: -94,
        m: 0xe79967c7c1fd457e8bad5620ab5c78a2,
    },
];

/// `cos(r)` as `Dint` minimax coefficients in `u = r²`, low-degree first.
/// 14 terms — the max error over `[0, (π/4)²]` is ≈2⁻¹³⁴ (≈2⁻¹³³ after
/// quantizing the coefficients to `Dint`).
const COS_DINT: [Dint; 14] = [
    Dint {
        sgn: false,
        ex: 0,
        m: 0x80000000000000000000000000000000,
    },
    Dint {
        sgn: true,
        ex: -2,
        m: 0xfffffffffffffffffffffffffffffff4,
    },
    Dint {
        sgn: false,
        ex: -5,
        m: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaa82ad,
    },
    Dint {
        sgn: true,
        ex: -10,
        m: 0xb60b60b60b60b60b60b60b60b53be8cd,
    },
    Dint {
        sgn: false,
        ex: -16,
        m: 0xd00d00d00d00d00d00d00cfc6ce73cc3,
    },
    Dint {
        sgn: true,
        ex: -22,
        m: 0x93f27dbbc4fae397780b5bbb83a5f0ac,
    },
    Dint {
        sgn: false,
        ex: -29,
        m: 0x8f76c77fc6c4bdaa269903347e0ad492,
    },
    Dint {
        sgn: true,
        ex: -37,
        m: 0xc9cba54603e4e904825156e42e86c60a,
    },
    Dint {
        sgn: false,
        ex: -45,
        m: 0xd73f9f399dc0f345a3a45aadb465b2fa,
    },
    Dint {
        sgn: true,
        ex: -53,
        m: 0xb413c31dcbddf25e5a6dd8bae52be772,
    },
    Dint {
        sgn: false,
        ex: -62,
        m: 0xf2a15d1fd60500d69438ba5d2031b4d0,
    },
    Dint {
        sgn: true,
        ex: -70,
        m: 0x8671cb1f833c0957987226ca65cb7c1a,
    },
    Dint {
        sgn: false,
        ex: -80,
        m: 0xf9666cf2db6b1cb738dd68ce5a1a05c4,
    },
    Dint {
        sgn: true,
        ex: -89,
        m: 0xc355ba2967b5ca732d6ab7f31ee13ec5,
    },
];

/// Negate a double-double.
#[inline]
fn neg(v: DoubleDouble) -> DoubleDouble {
    DoubleDouble {
        high: -v.high,
        low: -v.low,
    }
}

/// Payne–Hanek argument reduction for `|x| ≥ 2²⁰`.
///
/// Returns `(q, r)` with `q` the quadrant (low bits of `round(x·2/π)`) and `r ∈
/// [-π/4, π/4]` a double-double.  Multiplies the 53-bit significand by a 256-bit
/// window of 2/π selected by the exponent, reads off the integer part (for `q`)
/// and a 128-bit signed fraction, and scales the fraction by π/2.
#[inline]
fn payne_hanek(x: f64) -> (i64, DoubleDouble) {
    let bits = x.to_bits();
    let e = ((bits >> super::EXP_SHIFT) & 0x7ff) as i64; // biased exponent
    let sig = u128::from((bits & 0x000F_FFFF_FFFF_FFFF) | 0x0010_0000_0000_0000);

    // x = sig · 2ᵐ with m = e − 1023 − 52.  The 2/π bit aligning to 2⁰ of x·2/π is
    // index k = m; pick the 256-bit window starting two bits above that.
    let m = e - 1075;
    let w0 = (((m - 2).max(0)) / 64) as usize;

    let word = |i: usize| u128::from(*FRAC_2_PI.get(w0 + i).unwrap_or(&0));
    let (wa, wb, wc, wd) = (word(0), word(1), word(2), word(3));

    // P = sig · (wa·2¹⁹² + wb·2¹²⁸ + wc·2⁶⁴ + wd), as five 64-bit limbs.
    let (pa, pb, pc, pd) = (sig * wa, sig * wb, sig * wc, sig * wd);
    const MASK: u128 = 0xFFFF_FFFF_FFFF_FFFF;
    let p0 = pd as u64;
    let c = (pd >> 64) + (pc & MASK);
    let p1 = c as u64;
    let c = (c >> 64) + (pc >> 64) + (pb & MASK);
    let p2 = c as u64;
    let c = (c >> 64) + (pb >> 64) + (pa & MASK);
    let p3 = c as u64;
    let p4 = ((c >> 64) + (pa >> 64)) as u64;
    let p = [p0, p1, p2, p3, p4];

    // Units bit of x·2/π is at P bit `b = 256 + 64·w0 − m`.
    let b = 256 + 64 * w0 as i64 - m;
    let bit_at = |start: i64| -> u64 {
        let w = (start / 64) as usize;
        let o = (start % 64) as u32;
        let lo = p.get(w).copied().unwrap_or(0);
        let hi = p.get(w + 1).copied().unwrap_or(0);
        if o == 0 {
            lo
        } else {
            (lo >> o) | (hi << (64 - o))
        }
    };

    // 192-bit window [b−128, b+63]: top 64 bits are the integer part (quadrant),
    // low 128 bits are the signed fraction of x·2/π.
    let frac = (u128::from(bit_at(b - 64)) << 64) | u128::from(bit_at(b - 128));
    let q = bit_at(b) as i64;
    let frac = frac as i128;

    // round-to-nearest: a negative signed fraction means the integer rounded up.
    let quadrant = q.wrapping_sub((frac >> 127) as i64);

    // r = (frac / 2¹²⁸) · π/2 ∈ [-π/4, π/4], as a double-double.  Split the
    // 128-bit signed `frac` into two limbs (`frac = h·2⁶⁴ + l` in two's
    // complement) and convert with native `i64`/`u64` → `f64`: a direct
    // `frac as f64` (and the residual's `as i128`) lowers to the slow
    // `__floattidf`/`__fixdfti` compiler-rt libcalls.  `hf` carries the top
    // ≈53 bits; `lf` folds `h`'s lost low bits and `l` into the next ≈53, so the
    // pair keeps the same ≈2⁻¹⁰⁶ precision the i128 casts gave.
    let h = (frac >> 64) as i64;
    let l = frac as u64;
    let hf = h as f64;
    let hr = h.wrapping_sub(hf as i64);
    let lf = crate::fma(hr as f64, crate::exp2i(64), l as f64);
    let r = DoubleDouble {
        high: hf * crate::exp2i(-64),
        low: lf * crate::exp2i(-128),
    } * PIO2;

    (quadrant, r)
}

/// Payne–Hanek argument reduction to a 128-bit `Dint` reduced angle — the
/// accurate-path counterpart of [`payne_hanek`], called only on the Ziv
/// fallback (any finite `x ≥ 2⁻²⁷`, so it subsumes the medium Cody–Waite range
/// too).
///
/// Returns `(quadrant, r)` with `r ∈ [−π/4, π/4]` a `Dint`.  Unlike the
/// double-double path, the residual fraction of `x·2/π` is read out **normalized**
/// — a 128-bit window taken at its own leading bit — so it keeps full 128-bit
/// relative precision even when `x` lies very close to a multiple of `π/2` and the
/// residual is tiny (the leading zeros the dd path absorbs into its 53-bit `hi`).
/// A 5-word (320-bit) window of 2/π and a 256-bit fraction extraction give ample
/// headroom over the ≈61-bit worst-case cancellation.
#[inline]
fn payne_hanek_dint(x: f64) -> (i64, Dint) {
    let bits = x.to_bits();
    let e = ((bits >> super::EXP_SHIFT) & 0x7ff) as i64;
    let sig = u128::from((bits & 0x000F_FFFF_FFFF_FFFF) | 0x0010_0000_0000_0000);

    let m = e - 1075;
    let w0 = (((m - 2).max(0)) / 64) as usize;
    let word = |i: usize| u128::from(*FRAC_2_PI.get(w0 + i).unwrap_or(&0));
    let (wa, wb, wc, wd, we) = (word(0), word(1), word(2), word(3), word(4));

    // P = sig · (wa·2²⁵⁶ + wb·2¹⁹² + wc·2¹²⁸ + wd·2⁶⁴ + we), as six 64-bit limbs.
    let (pa, pb, pc, pd, pe) = (sig * wa, sig * wb, sig * wc, sig * wd, sig * we);
    const MASK: u128 = 0xFFFF_FFFF_FFFF_FFFF;
    let p0 = pe as u64;
    let c = (pe >> 64) + (pd & MASK);
    let p1 = c as u64;
    let c = (c >> 64) + (pd >> 64) + (pc & MASK);
    let p2 = c as u64;
    let c = (c >> 64) + (pc >> 64) + (pb & MASK);
    let p3 = c as u64;
    let c = (c >> 64) + (pb >> 64) + (pa & MASK);
    let p4 = c as u64;
    let p5 = ((c >> 64) + (pa >> 64)) as u64;
    let p = [p0, p1, p2, p3, p4, p5];

    // Units bit of x·2/π is at P bit `b = 320 + 64·w0 − m`.
    let b = 320 + 64 * w0 as i64 - m;

    // Bits [start, start+63] of the zero-extended P (any signed `start`).
    let safe_word = |start: i64| -> u64 {
        let idx = start.div_euclid(64);
        let off = start.rem_euclid(64) as u32;
        let get = |i: i64| -> u64 {
            if i < 0 {
                0
            } else {
                p.get(i as usize).copied().unwrap_or(0)
            }
        };
        let lo = get(idx);
        if off == 0 {
            lo
        } else {
            (lo >> off) | (get(idx + 1) << (64 - off))
        }
    };

    // 256-bit signed fraction window [b−256, b−1]; its top bit (b−1) is the 2⁻¹
    // place, so the window read as a two's-complement integer is `resid · 2²⁵⁶`.
    let hi = (u128::from(safe_word(b - 64)) << 64) | u128::from(safe_word(b - 128));
    let lo = (u128::from(safe_word(b - 192)) << 64) | u128::from(safe_word(b - 256));

    // Sign of the residual; a negative residual means the integer rounded up.
    let sgn = hi >> 127 == 1;
    let quadrant = (safe_word(b) as i64).wrapping_add(i64::from(sgn));

    // |resid| · 2²⁵⁶ as an unsigned 256-bit pair.
    let (mag_hi, mag_lo) = if sgn {
        let (nlo, carry) = (!lo).overflowing_add(1);
        ((!hi).wrapping_add(u128::from(carry)), nlo)
    } else {
        (hi, lo)
    };

    // Normalize to a 128-bit significand: shift the leading set bit to bit 255,
    // keep the top 128 bits.  `value = mag/2²⁵⁶ = m/2^(128+lz)`, so `ex = −1 − lz`.
    let lz = if mag_hi != 0 {
        mag_hi.leading_zeros()
    } else {
        128 + mag_lo.leading_zeros()
    };
    let m128 = if lz == 0 {
        mag_hi
    } else if lz < 128 {
        (mag_hi << lz) | (mag_lo >> (128 - lz))
    } else {
        mag_lo << (lz - 128)
    };

    let frac = Dint {
        sgn,
        ex: -1 - i64::from(lz),
        m: m128,
    };
    (quadrant, frac.mul(&PIO2_DINT))
}

/// Negate a `Dint`.
#[inline]
const fn neg_dint(v: Dint) -> Dint {
    Dint { sgn: !v.sgn, ..v }
}

/// Horner evaluation of a `Dint` polynomial in `u`, low-degree first.
#[inline]
fn poly_dint(u: &Dint, coeffs: &[Dint]) -> Dint {
    let mut acc = coeffs[coeffs.len() - 1];
    for c in coeffs[..coeffs.len() - 1].iter().rev() {
        acc = c.add(&u.mul(&acc));
    }
    acc
}

/// `(sin(r), cos(r))` for `r ∈ [−π/4, π/4]` as `Dint`s — the accurate kernel.
#[inline]
fn sin_cos_dint(r: &Dint) -> (Dint, Dint) {
    let u = r.mul(r);
    (r.mul(&poly_dint(&u, &SIN_DINT)), poly_dint(&u, &COS_DINT))
}

/// `sin(r)` for `r ∈ [−π/4, π/4]` as a `Dint`.
#[inline]
fn sin_dint(r: &Dint) -> Dint {
    let u = r.mul(r);
    r.mul(&poly_dint(&u, &SIN_DINT))
}

/// `cos(r)` for `r ∈ [−π/4, π/4]` as a `Dint`.
#[inline]
fn cos_dint(r: &Dint) -> Dint {
    let u = r.mul(r);
    poly_dint(&u, &COS_DINT)
}

/// `1 / c` as a `Dint`, two Newton steps `y·(2 − c·y)` from the `f64` seed
/// `1/c`.  `c = cos(|x|)` is well away from a catastrophic seed (`|c| ≥ ≈2⁻⁶¹`),
/// so two steps reach the `Dint` arithmetic floor — the divide behind accurate
/// `tan`.
#[inline]
fn recip_dint(c: &Dint) -> Dint {
    let mut y = Dint::from_f64(1.0 / c.to_f64());
    for _ in 0..2 {
        y = y.mul(&TWO_DINT.add(&neg_dint(c.mul(&y))));
    }
    y
}

/// Reconstruct `sin(|x|)` (`Dint`) from the kernel pair and quadrant `q`.
#[inline]
const fn select_sin_dint(q: i64, s: Dint, c: Dint) -> Dint {
    let v = if q & 1 == 0 { s } else { c };
    if q & 2 == 0 { v } else { neg_dint(v) }
}

/// Reconstruct `cos(|x|)` (`Dint`) from the kernel pair and quadrant `q`.
#[inline]
const fn select_cos_dint(q: i64, s: Dint, c: Dint) -> Dint {
    let v = if q & 1 == 0 { c } else { s };
    if q.wrapping_add(1) & 2 == 0 {
        v
    } else {
        neg_dint(v)
    }
}

/// Argument reduction: `x ≥ 0` finite → `(quadrant, r)` with `r ∈ [-π/4, π/4]`.
#[inline]
fn rem_pio2(x: f64) -> (i64, DoubleDouble) {
    // Medium range: Cody–Waite with the 4-word π/2 (q small enough that
    // q·PIO2_1..PIO2_4 are exact).  Handles `q = 0` (no reduction) too.
    if x < 1_048_576.0 {
        let q = (x * FRAC_2_PI_F64).round_ties_even();
        // Subtract `q·π/2` word by word.  Each `q·PIO2_k` (k ≤ 4) is exact
        // (cleared low bits, |q| < 2²¹), so the three 2Sums capture every
        // residual of the first three words exactly; the fourth word folds into
        // the accumulated low part and the tail beyond PIO2_4 (≈2⁻¹²² after the
        // `q` scale) is dropped.  This flat fold — versus renormalizing the pair
        // after each word — keeps `r` accurate to ≈2⁻¹³⁰, so the relative Ziv
        // gate stays sound for any |r| ≳ 2⁻⁷⁰, far below the medium range's
        // worst-case cancellation; tinier residuals fall through to the
        // `payne_hanek_dint` accurate path.
        let a = DoubleDouble::from_sum(x, q * -PIO2_1);
        let b = DoubleDouble::from_sum(a.high, q * -PIO2_2);
        let c = DoubleDouble::from_sum(b.high, q * -PIO2_3);
        let lo = crate::fma(-q, PIO2_4, a.low + b.low + c.low);
        // SAFETY: |q| < 2²⁰.
        return (unsafe { q.to_int_unchecked() }, fast_sum(c.high, lo));
    }

    payne_hanek(x)
}

/// `sin(r)` for `r ∈ [-π/4, π/4]` as a double-double, by full double-double
/// Horner of [`SIN_KERNEL`] (≈2⁻¹²⁷) — the accurate `sin` half.
#[inline]
fn sin_kernel(r: DoubleDouble) -> DoubleDouble {
    r * poly_dd(r * r, &SIN_KERNEL)
}

/// `cos(r)` for `r ∈ [-π/4, π/4]` as a double-double, by full double-double
/// Horner of [`COS_KERNEL`] (≈2⁻¹²²) — the accurate `cos` half.
#[inline]
fn cos_kernel(r: DoubleDouble) -> DoubleDouble {
    poly_dd(r * r, &COS_KERNEL)
}

/// The squares shared by the fast sin/cos parts: `uu = r²`, `u2 = uu²`, and
/// `u3 = uu.high³`.
#[inline]
fn fast_squares(r: DoubleDouble) -> (DoubleDouble, DoubleDouble, f64) {
    let uu = r * r;
    let u = uu.high;
    (uu, uu * uu, u * u * u)
}

/// `sin(r)` from the precomputed squares — the `sin` half of the fast path.
///
/// Peels the three exact leading terms of `sin(r)/r` into double-double and
/// evaluates only the tiny `u³` tail ([`SIN_TAIL`]) in plain `f64`, so the result
/// comes out to ≈2⁻⁶⁰ for a fraction of [`sin_kernel`]'s cost.
#[inline]
fn sin_part_fast(r: DoubleDouble, uu: DoubleDouble, u2: DoubleDouble, u3: f64) -> DoubleDouble {
    // sin(r)/r = 1 − u/6 + u²/120 + u³·SIN_TAIL(u); every addend stays under
    // half its lead at the octant edge (`fold_ordering` below), so the folds
    // are ordered Fast2Sums, and `−u/6` is a multiply by the double-double
    // constant rather than `Div<f64>`'s two serial divisions.
    let sin_lead = ONE
        .add_ordered(uu * NEG_FRAC_1_6)
        .add_ordered(u2 * FRAC_1_120);
    let sin_over_r = sin_lead.add_ordered(DoubleDouble {
        high: u3 * crate::poly(uu.high, &SIN_TAIL),
        low: 0.0,
    });
    r * sin_over_r
}

/// `cos(r)` from the precomputed squares — the `cos` half of the fast path.  See
/// [`sin_part_fast`]; the `u³` tail is [`COS_TAIL`].
#[inline]
fn cos_part_fast(uu: DoubleDouble, u2: DoubleDouble, u3: f64) -> DoubleDouble {
    // cos(r) = 1 − u/2 + u²/24 + u³·COS_TAIL(u); ordered Fast2Sum folds as in
    // [`sin_part_fast`] (`|u/2| ≤ 0.309` is the tightest — see `fold_ordering`).
    let cos_lead = ONE.add_ordered(uu * -0.5).add_ordered(u2 * FRAC_1_24);
    cos_lead.add_ordered(DoubleDouble {
        high: u3 * crate::poly(uu.high, &COS_TAIL),
        low: 0.0,
    })
}

/// `sin(r)` for `r ∈ [-π/4, π/4]`, the fast path — only the `sin` half.
#[inline]
fn sin_kernel_fast(r: DoubleDouble) -> DoubleDouble {
    let (uu, u2, u3) = fast_squares(r);
    sin_part_fast(r, uu, u2, u3)
}

/// `cos(r)` for `r ∈ [-π/4, π/4]`, the fast path — only the `cos` half.
#[inline]
fn cos_kernel_fast(r: DoubleDouble) -> DoubleDouble {
    let (uu, u2, u3) = fast_squares(r);
    cos_part_fast(uu, u2, u3)
}

/// Lean fast kernel computing both halves, for `sincos`.
#[inline]
fn sin_cos_kernel_fast(r: DoubleDouble) -> (DoubleDouble, DoubleDouble) {
    let (uu, u2, u3) = fast_squares(r);
    (sin_part_fast(r, uu, u2, u3), cos_part_fast(uu, u2, u3))
}

/// `tan(r)` for `r ∈ [−π/4, π/4]`, as a double-double, via the direct series
/// `tan(r) = r·T(r²)`.  The 6 leading terms of `T` are carried in double-double
/// ([`TAN_LEADS`], 2-way Estrin) and the `v⁶` remainder ([`TAN_TAIL`]) in plain
/// `f64`.  One kernel — versus the sin/cos pair plus a reciprocal — feeds [`tan`].
///
/// Every fold uses [`DoubleDouble::add_ordered`]: `tan`'s series coefficients
/// decay fast enough that each addend stays under half its lead even at
/// `v = (π/4)²` (asserted in `fold_ordering` below).
#[inline]
fn tan_kernel_fast(r: DoubleDouble) -> DoubleDouble {
    let w = r * r; // v = r²
    let v = w.high;
    let v2 = v * v;
    let v6 = v2 * v2 * v2;
    let w2 = w * w;
    let p0 = TAN_LEADS[0].add_ordered(w * TAN_LEADS[1]);
    let p1 = TAN_LEADS[2].add_ordered(w * TAN_LEADS[3]);
    let p2 = TAN_LEADS[4].add_ordered(w * TAN_LEADS[5]);
    let t = p0
        .add_ordered(w2 * p1.add_ordered(w2 * p2))
        .add_ordered(DoubleDouble {
            high: v6 * crate::poly(v, &TAN_TAIL),
            low: 0.0,
        });
    r * t
}

/// Reconstruct `sin(|x|)` from the kernel pair and quadrant `q` (before the sign
/// of `x` is restored).  Shared by the fast and accurate paths so they select
/// identically.
#[inline]
fn select_sin(q: i64, s: DoubleDouble, c: DoubleDouble) -> DoubleDouble {
    let v = if q & 1 == 0 { s } else { c };
    if q & 2 == 0 { v } else { neg(v) }
}

/// Reconstruct `cos(|x|)` from the kernel pair and quadrant `q`.
#[inline]
fn select_cos(q: i64, s: DoubleDouble, c: DoubleDouble) -> DoubleDouble {
    let v = if q & 1 == 0 { c } else { s };
    if q.wrapping_add(1) & 2 == 0 {
        v
    } else {
        neg(v)
    }
}

/// Ziv gate: round `v` to `f64` when both ends of its `±TRIG_ZIV_EPS` (relative)
/// error interval agree, else `None` to fall back to the accurate kernel.
#[inline]
fn ziv(v: DoubleDouble) -> Option<f64> {
    let eps = v.high.abs() * TRIG_ZIV_EPS;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// π as a double-double, for `sin(πx)` (the lgamma reflection).
const PI_DD: DoubleDouble = DoubleDouble {
    high: 3.141_592_653_589_793,
    low: 1.224_646_799_147_353_2e-16,
};

/// `sin(πk/128)` as a double-double, `k = 0..=64` — the grid table of the lean
/// table-driven `|sin(πx)|` ([`abs_sinpi_dd_lean`]), CORE-MATH's `stpi`.  Indexing
/// it at `64 − k` gives `cos(πk/128)` by the complement identity, so one table
/// serves both the sine and cosine of the grid angle.
///
/// Generated to ≈2⁻¹⁰⁵ (200-bit MPFR, `tests/gen_sinpi_table.rs`).
const SINPI_TABLE: [DoubleDouble; 65] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.024541228522912288,
        low: -9.186849012577878e-20,
    },
    DoubleDouble {
        high: 0.049067674327418015,
        low: -6.79610372051828e-19,
    },
    DoubleDouble {
        high: 0.07356456359966743,
        low: -2.7784941506273593e-18,
    },
    DoubleDouble {
        high: 0.0980171403295606,
        low: -1.634582362244256e-18,
    },
    DoubleDouble {
        high: 0.1224106751992162,
        low: 2.8354501489965335e-18,
    },
    DoubleDouble {
        high: 0.14673047445536175,
        low: 3.726947147046568e-18,
    },
    DoubleDouble {
        high: 0.17096188876030122,
        low: 9.19199801817591e-18,
    },
    DoubleDouble {
        high: 0.19509032201612828,
        low: -7.991079068461731e-18,
    },
    DoubleDouble {
        high: 0.2191012401568698,
        low: -3.6513812299150776e-19,
    },
    DoubleDouble {
        high: 0.2429801799032639,
        low: -8.751431529719663e-18,
    },
    DoubleDouble {
        high: 0.26671275747489837,
        low: 2.0941222578826688e-17,
    },
    DoubleDouble {
        high: 0.2902846772544624,
        low: -1.892797870777425e-17,
    },
    DoubleDouble {
        high: 0.31368174039889146,
        low: 1.4560447299968912e-17,
    },
    DoubleDouble {
        high: 0.33688985339222005,
        low: -4.200094003347509e-19,
    },
    DoubleDouble {
        high: 0.35989503653498817,
        low: -1.7601687123839282e-17,
    },
    DoubleDouble {
        high: 0.3826834323650898,
        low: -1.0050772696461588e-17,
    },
    DoubleDouble {
        high: 0.40524131400498986,
        low: 9.911140194289988e-18,
    },
    DoubleDouble {
        high: 0.4275550934302821,
        low: 9.411189816295473e-18,
    },
    DoubleDouble {
        high: 0.4496113296546066,
        low: 4.883192423203524e-18,
    },
    DoubleDouble {
        high: 0.47139673682599764,
        low: 6.516678136069013e-18,
    },
    DoubleDouble {
        high: 0.49289819222978404,
        low: -1.0257831676562186e-18,
    },
    DoubleDouble {
        high: 0.5141027441932218,
        low: -4.5712707523615624e-17,
    },
    DoubleDouble {
        high: 0.5349976198870973,
        low: -5.3683132708358134e-17,
    },
    DoubleDouble {
        high: 0.5555702330196022,
        low: 4.709410940561677e-17,
    },
    DoubleDouble {
        high: 0.5758081914178453,
        low: -3.7909495458942734e-17,
    },
    DoubleDouble {
        high: 0.5956993044924334,
        low: -1.3438641936579467e-17,
    },
    DoubleDouble {
        high: 0.6152315905806268,
        low: 2.623141776726695e-17,
    },
    DoubleDouble {
        high: 0.6343932841636455,
        low: 1.0420901929280035e-17,
    },
    DoubleDouble {
        high: 0.6531728429537768,
        low: 8.569564206002624e-18,
    },
    DoubleDouble {
        high: 0.6715589548470184,
        low: -4.048903774929669e-17,
    },
    DoubleDouble {
        high: 0.6895405447370669,
        low: -1.588932329480679e-17,
    },
    DoubleDouble {
        high: 0.7071067811865476,
        low: -4.833646656726457e-17,
    },
    DoubleDouble {
        high: 0.7242470829514669,
        low: 2.9198471334403004e-17,
    },
    DoubleDouble {
        high: 0.7409511253549591,
        low: -1.4708616952297345e-17,
    },
    DoubleDouble {
        high: 0.7572088465064846,
        low: -1.9909098777335502e-17,
    },
    DoubleDouble {
        high: 0.773010453362737,
        low: -3.256590703364977e-17,
    },
    DoubleDouble {
        high: 0.7883464276266062,
        low: 3.439699315405971e-17,
    },
    DoubleDouble {
        high: 0.8032075314806449,
        low: -3.306060980481491e-17,
    },
    DoubleDouble {
        high: 0.8175848131515837,
        low: -1.4883149812426772e-17,
    },
    DoubleDouble {
        high: 0.8314696123025452,
        low: 1.4073856984728024e-18,
    },
    DoubleDouble {
        high: 0.8448535652497071,
        low: -4.363136029687964e-17,
    },
    DoubleDouble {
        high: 0.8577286100002721,
        low: -4.818344793633662e-17,
    },
    DoubleDouble {
        high: 0.8700869911087115,
        low: -4.188851086854997e-17,
    },
    DoubleDouble {
        high: 0.881921264348355,
        low: -1.9843248405890562e-17,
    },
    DoubleDouble {
        high: 0.8932243011955153,
        low: -4.116123915190891e-18,
    },
    DoubleDouble {
        high: 0.9039892931234433,
        low: -6.609754468748431e-18,
    },
    DoubleDouble {
        high: 0.9142097557035307,
        low: -3.631618252781442e-17,
    },
    DoubleDouble {
        high: 0.9238795325112867,
        low: 1.7645047084336677e-17,
    },
    DoubleDouble {
        high: 0.9329927988347388,
        low: 4.2041415555384355e-17,
    },
    DoubleDouble {
        high: 0.9415440651830208,
        low: -2.789637954769834e-17,
    },
    DoubleDouble {
        high: 0.9495281805930367,
        low: -7.55441519280433e-18,
    },
    DoubleDouble {
        high: 0.9569403357322088,
        low: 4.05538698618757e-17,
    },
    DoubleDouble {
        high: 0.9637760657954398,
        low: 2.646395056122003e-17,
    },
    DoubleDouble {
        high: 0.970031253194544,
        low: 1.8365300348428844e-17,
    },
    DoubleDouble {
        high: 0.9757021300385286,
        low: -2.5572556081259686e-17,
    },
    DoubleDouble {
        high: 0.9807852804032304,
        low: 1.8546939997825006e-17,
    },
    DoubleDouble {
        high: 0.9852776423889412,
        low: 2.3155637027900207e-17,
    },
    DoubleDouble {
        high: 0.989176509964781,
        low: -4.098730993704711e-17,
    },
    DoubleDouble {
        high: 0.99247953459871,
        low: 3.1093055095428906e-17,
    },
    DoubleDouble {
        high: 0.9951847266721969,
        low: -4.248691367830441e-17,
    },
    DoubleDouble {
        high: 0.9972904566786902,
        low: 9.164769537110173e-18,
    },
    DoubleDouble {
        high: 0.9987954562051724,
        low: -1.2291693337075465e-17,
    },
    DoubleDouble {
        high: 0.9996988186962042,
        low: -2.985148640379975e-17,
    },
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
];

/// Taylor coefficients of `(cos(πd/128) − 1)/d² = C1 + d²(C2 + d²·C3)` in the grid
/// unit `d = 128·a − round(128·a) ∈ [−½, ½]` (`Cₖ = (−1)ᵏ(π/128)^{2k}/(2k)!`); the
/// leading `C1` is double-double, the rest `f64`.  Residual angle `|πd/128| ≤
/// π/256`, so the dropped `d⁸` term is ≈2⁻⁶⁶.  See [`abs_sinpi_dd_lean`].
const SINPI_C1: DoubleDouble = DoubleDouble {
    high: -0.0003011964233730883,
    low: -1.9120164516417576e-20,
};
const SINPI_C2: f64 = 1.5119880908790113e-8;
const SINPI_C3: f64 = -3.036036034369748e-13;

/// Taylor coefficients of `sin(πd/128)/d = S0 + d²(S1 + d²(S2 + d²·S3))`
/// (`Sₖ = (−1)ᵏ(π/128)^{2k+1}/(2k+1)!`); `S0`, `S1` double-double, the rest `f64`.
/// See [`SINPI_C1`].
const SINPI_S0: DoubleDouble = DoubleDouble {
    high: 0.02454369260617026,
    low: 9.567553118338697e-19,
};
const SINPI_S1: DoubleDouble = DoubleDouble {
    high: -2.4641574764489986e-6,
    low: 1.0807811177153324e-22,
};
const SINPI_S2: f64 = 7.421954185344935e-11;
const SINPI_S3: f64 = -1.064507645268961e-15;

/// `sin(πx)` as a double-double for `|x| < 2⁵²`, where `x − q/2` is exact — the
/// accurate ≈2⁻¹²² kernel for the `lgamma` middle Ziv tier ([`abs_sinpi_dd`]).
///
/// Reduces `x = q/2 + r`, `r ∈ [−¼, ¼]`, and selects `±sin(πr)`/`±cos(πr)` by
/// `q mod 4`, with `πr ∈ [−π/4, π/4]` carried as a double-double into the full
/// double-double [`sin_kernel`]/[`cos_kernel`] (the middle tier needs their
/// ≈2⁻¹²² for its ≈2⁻⁹³ gate; the reflection *fast* leg takes the leaner
/// table-driven [`abs_sinpi_dd_lean`] instead).
#[inline]
fn sinpi_dd(x: f64) -> DoubleDouble {
    let q = (2.0 * x).round_ties_even();
    let theta = PI_DD * (x - q * 0.5);
    // SAFETY: `|x| < 2⁵²`, so `|q| < 2⁵³` fits an `i64`.
    match unsafe { q.to_int_unchecked::<i64>() } & 3 {
        0 => sin_kernel(theta),
        1 => cos_kernel(theta),
        2 => neg(sin_kernel(theta)),
        _ => neg(cos_kernel(theta)),
    }
}

/// `|sin(πx)|` as a double-double for `|x| < 2⁵²`, accurate ≈2⁻¹²² (see
/// [`sinpi_dd`]) — for the `lgamma` middle Ziv tier.
///
/// The lgamma reflection needs `ln|sin(πz)|` accurate even as `z` nears an
/// integer; there `|sin(πz)| ≈ π·|r|` with `r = z − round(z)` exact, so the
/// kernel's leading term keeps full relative accuracy.
#[inline]
pub(super) fn abs_sinpi_dd(x: f64) -> DoubleDouble {
    let v = sinpi_dd(x);
    if v.high < 0.0 { neg(v) } else { v }
}

/// `|sin(πx)|` as a double-double for `|x| < 2⁵²`, the lean table-driven kernel
/// (≈2⁻⁶⁶) — for the `lgamma` reflection *fast* leg, whose ≈2⁻⁶²–2⁻⁶⁶ gate has
/// ample room for it (the middle tier still uses the accurate [`abs_sinpi_dd`]).
///
/// Mirrors CORE-MATH's `as_sinpipid`.  `|sin(πx)| = sin(π·a)` with the period-1
/// even reduction `a = |x − round(x)| ∈ [0, ½]`; then `a = (k + d)/128` against the
/// [`SINPI_TABLE`] grid (`k = round(128·a)`, `d ∈ [−½, ½]`), and angle addition
///
/// `sin(π(k+d)/128) = sin(πk/128)·cos(πd/128) + cos(πk/128)·sin(πd/128)`
///
/// folds the tiny residual angle `πd/128 ∈ [−π/256, π/256]` through the short
/// [`SINPI_S0`]/[`SINPI_C1`] polynomials — far cheaper than a full-octant kernel.
/// Factoring `d` back out last keeps the leading `sin(π·a) ≈ π·a` exact as `a → 0`
/// (the near-integer case the gate cares about).  The result is non-negative
/// (`a ∈ [0, ½] ⇒ π·a ∈ [0, π/2]`), so no sign fixup.
#[inline]
pub(super) fn abs_sinpi_dd_lean(x: f64) -> DoubleDouble {
    let a = (x - x.round_ties_even()).abs();
    let s = a * 128.0;
    let kf = s.round_ties_even();
    let d = s - kf;
    // SAFETY: a ∈ [0, ½] ⇒ s ∈ [0, 64] ⇒ k ∈ 0..=64.
    let k = unsafe { kf.to_int_unchecked::<usize>() };
    let sg = SINPI_TABLE[k]; // sin(πk/128)
    let cg = SINPI_TABLE[64 - k]; // cos(πk/128) = sin(π(64−k)/128)

    let d2 = d * d;
    // sin(πd/128)/d = S0 + d²(S1 + d²(S2 + d²·S3))  (leading word double-double)
    let sin_over_d = SINPI_S0.add_ordered(DoubleDouble {
        high: d2 * crate::poly(d2, &[SINPI_S1.high, SINPI_S2, SINPI_S3]),
        low: 0.0,
    });
    // (cos(πd/128) − 1)/d² = C1 + d²(C2 + d²·C3)
    let cosm1_over_d2 = SINPI_C1.add_ordered(DoubleDouble {
        high: d2 * crate::poly(d2, &[SINPI_C2, SINPI_C3]),
        low: 0.0,
    });
    // sin(π·a) = sg + d·(cg·[sin θ/d] + sg·d·[(cos θ − 1)/d²]),  θ = πd/128.
    let bracket = cg * sin_over_d + sg * (cosm1_over_d2 * d);
    sg + bracket * d
}

/// Sine
#[must_use]
#[inline]
pub fn sin(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    // |x| < 2⁻²⁷: sin(x) = x to within ½ ulp; preserves ±0.
    if x.abs() < SMALL {
        return x;
    }

    let (q, r) = rem_pio2(x.abs());

    // sin(|x|): even quadrants use sin(r), odd use cos(r); q&2 sets the sign.
    // Only the selected half is computed (vs. both for `sincos`).
    let need_cos = q & 1 != 0;
    let negate = q & 2 != 0;
    let signed = |v: DoubleDouble| if negate { neg(v) } else { v };

    let fast = signed(if need_cos {
        cos_kernel_fast(r)
    } else {
        sin_kernel_fast(r)
    });
    let magnitude = ziv(fast).unwrap_or_else(|| {
        // Accurate `Dint` path: re-reduce to a 128-bit `r` and round once.
        let (q, r) = payne_hanek_dint(x.abs());
        let v = if q & 1 != 0 {
            cos_dint(&r)
        } else {
            sin_dint(&r)
        };
        let v = if q & 2 != 0 { neg_dint(v) } else { v };
        v.to_f64()
    });

    if x.is_sign_negative() {
        -magnitude
    } else {
        magnitude
    }
}

/// Cosine
#[must_use]
#[inline]
pub fn cos(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    // |x| < 2⁻²⁷: cos(x) = 1 to within ½ ulp.
    if x.abs() < SMALL {
        return 1.0;
    }

    let (q, r) = rem_pio2(x.abs());

    // cos(|x|): even quadrants use cos(r), odd use sin(r); (q+1)&2 sets the sign.
    let need_sin = q & 1 != 0;
    let negate = q.wrapping_add(1) & 2 != 0;
    let signed = |v: DoubleDouble| if negate { neg(v) } else { v };

    let fast = signed(if need_sin {
        sin_kernel_fast(r)
    } else {
        cos_kernel_fast(r)
    });
    ziv(fast).unwrap_or_else(|| {
        // Accurate `Dint` path: re-reduce to a 128-bit `r` and round once.
        let (q, r) = payne_hanek_dint(x.abs());
        let v = if q & 1 != 0 {
            sin_dint(&r)
        } else {
            cos_dint(&r)
        };
        let v = if q.wrapping_add(1) & 2 != 0 {
            neg_dint(v)
        } else {
            v
        };
        v.to_f64()
    })
}

/// Simultaneous sine and cosine
#[must_use]
#[inline]
pub fn sincos(x: f64) -> (f64, f64) {
    if !x.is_finite() {
        return (f64::NAN, f64::NAN);
    }

    // |x| < 2⁻²⁷: (sin, cos) = (x, 1) to within ½ ulp; preserves ±0 in sin.
    if x.abs() < SMALL {
        return (x, 1.0);
    }

    let (q, r) = rem_pio2(x.abs());

    let (s, c) = sin_cos_kernel_fast(r);
    // Both components must pass the gate; otherwise recompute both accurately.
    let (sin, cos) = match (ziv(select_sin(q, s, c)), ziv(select_cos(q, s, c))) {
        (Some(sin), Some(cos)) => (sin, cos),
        _ => {
            // Accurate `Dint` path: re-reduce to a 128-bit `r` and round each once.
            let (q, r) = payne_hanek_dint(x.abs());
            let (s, c) = sin_cos_dint(&r);
            (
                select_sin_dint(q, s, c).to_f64(),
                select_cos_dint(q, s, c).to_f64(),
            )
        }
    };

    let sin = if x.is_sign_negative() { -sin } else { sin };
    (sin, cos)
}

/// Tangent
#[must_use]
#[inline]
pub fn tan(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    // |x| < 2⁻²⁷: tan(x) = x to within ½ ulp; preserves ±0.
    if x.abs() < SMALL {
        return x;
    }

    let (q, r) = rem_pio2(x.abs());

    // tan has period π, so tan(|x|) = tan(r) for even quadrants and −cot(r) =
    // −1/tan(r) for odd ones — one kernel, a reciprocal only half the time.
    let t = tan_kernel_fast(r);
    let fast = if q & 1 == 0 {
        t
    } else {
        // −1/t leanly: seed `y = −1/t.high` (the inner FMA's cancellation is
        // exact), fold `t.low` into the residual `e = 1 + y·t`, and take
        // `y·(1 + e)` — dropping `y·e²` ≈ 2⁻¹⁰⁴ relative, noise to the 2⁻⁵⁹
        // gate.  The full Newton `recip` (a double-double multiply, add, and
        // multiply on top of the divide) buys accuracy the gate cannot use.
        let y = -1.0 / t.high;
        let e = crate::fma(y, t.low, crate::fma(y, t.high, 1.0));
        DoubleDouble {
            high: y,
            low: y * e,
        }
    };
    let magnitude = ziv(fast).unwrap_or_else(|| {
        // Accurate `Dint` path: the sin/cos pair ratio in 128-bit fixed point.
        let (q, r) = payne_hanek_dint(x.abs());
        let (s, c) = sin_cos_dint(&r);
        let num = select_sin_dint(q, s, c);
        let den = select_cos_dint(q, s, c);
        num.mul(&recip_dint(&den)).to_f64()
    });

    if x.is_sign_negative() {
        -magnitude
    } else {
        magnitude
    }
}

/// The Fast2Sum-based folds of [`tan_kernel_fast`] need `|a| ≥ |b|`; prove the
/// orderings from coefficient-magnitude bounds at `v = w = (π/4)²`, the
/// octant's edge, with 2× margin (cf. the same-named module in `erf.rs`).
#[cfg(test)]
mod fold_ordering {
    use super::*;

    /// `sin_part_fast` / `cos_part_fast`: `1 ⊕ u·c₁ ⊕ u²·c₂ ⊕ u³·tail` with
    /// `u = r² ≤ (π/4)²`.
    #[test]
    fn sin_cos_leads() {
        let umax = core::f64::consts::FRAC_PI_4.powi(2) * 1.0001;
        let u2max = umax * umax;
        let u3max = umax.powi(3);
        let tail_mag = |tail: &[f64]| {
            tail.iter()
                .rev()
                .fold(0.0, |acc, c| crate::fast_mul_add(acc, umax, c.abs()))
        };

        for (c1, c2, tail) in [
            (
                NEG_FRAC_1_6.high.abs() + NEG_FRAC_1_6.low.abs(),
                FRAC_1_120.high + FRAC_1_120.low.abs(),
                &SIN_TAIL,
            ),
            (0.5, FRAC_1_24.high + FRAC_1_24.low.abs(), &COS_TAIL),
        ] {
            assert!(umax * c1 <= 0.5);
            let lead_min = 1.0 - umax * c1;
            assert!(u2max * c2 <= 0.5 * lead_min);
            let lead2_min = lead_min - u2max * c2;
            assert!(u3max * tail_mag(tail) <= 0.5 * lead2_min);
        }
    }

    /// The table-driven `abs_sinpi_dd_lean` folds the residual polynomials with
    /// `add_ordered` (`S0 ⊕ d²·(…)` and `C1 ⊕ d²·(…)`), which needs the leading
    /// coefficient to dominate the higher-order remainder.  `|d| ≤ ½`, so check
    /// the remainder stays under half the lead there.
    #[test]
    fn sinpi_table_leads() {
        let d2max = 0.25_f64; // (½)²
        let mag = |c: DoubleDouble| c.high.abs() + c.low.abs();
        let poly_mag = |c: &[f64]| {
            c.iter()
                .rev()
                .fold(0.0, |acc, c| crate::fast_mul_add(acc, d2max, c.abs()))
        };
        // sin: |S0| ≥ |d²·(S1 + d²(S2 + d²·S3))|
        assert!(d2max * poly_mag(&[SINPI_S1.high, SINPI_S2, SINPI_S3]) <= 0.5 * mag(SINPI_S0));
        // cos: |C1| ≥ |d²·(C2 + d²·C3)|
        assert!(d2max * poly_mag(&[SINPI_C2, SINPI_C3]) <= 0.5 * mag(SINPI_C1));
    }

    #[test]
    fn tan_leads() {
        // Slack for the rounding of r and w = r·r at the octant edge.
        let wmax = core::f64::consts::FRAC_PI_4.powi(2) * 1.0001;
        let mag = |c: DoubleDouble| c.high.abs() + c.low.abs();

        // p0/p1/p2 = L₂ₖ ⊕ w·L₂ₖ₊₁
        for pair in TAN_LEADS.chunks(2) {
            assert!(wmax * mag(pair[1]) <= 0.5 * pair[0].high.abs());
        }

        // inner = p1 ⊕ w²·p2, outer = p0 ⊕ w²·inner, t = outer ⊕ v⁶·tail
        let w2max = wmax * wmax;
        let p2_mag = mag(TAN_LEADS[4]) + wmax * mag(TAN_LEADS[5]);
        let p1_min = TAN_LEADS[2].high - wmax * mag(TAN_LEADS[3]);
        assert!(w2max * p2_mag <= 0.5 * p1_min);
        let inner_mag = mag(TAN_LEADS[2]) + wmax * mag(TAN_LEADS[3]) + w2max * p2_mag;
        let p0_min = TAN_LEADS[0].high - wmax * mag(TAN_LEADS[1]);
        assert!(w2max * inner_mag <= 0.5 * p0_min);
        let tail_mag = TAN_TAIL
            .iter()
            .rev()
            .fold(0.0, |acc, c| crate::fast_mul_add(acc, wmax, c.abs()));
        let outer_min = p0_min - w2max * inner_mag;
        assert!(wmax.powi(3) * tail_mag <= 0.5 * outer_min);
    }
}
