//! Trigonometric functions: `sin`, `cos`, `sincos`, `tan`.
//!
//! Double-double constants below were generated by `tools/gen_trig_f64.py`; the
//! accurate-path `Dint` constants (`PIO2_DINT`, `SIN_DINT`, `COS_DINT`) by
//! `tools/gen_dint_trig.py`.  Do not edit by hand; re-run the generators instead.
#![allow(clippy::unreadable_literal, clippy::excessive_precision)]

use super::dint::Dint;
use super::double::{DoubleDouble, fast_sum};
use super::pow::poly_dd;

/// `sin(r)/r` as a double-double in `u = r²`, low-degree first (max error ≈2⁻¹²⁷).
const SIN_KERNEL: [DoubleDouble; 13] = [
    DoubleDouble {
        high: 1.0,
        low: -5.098_701_855_402_968_3e-39,
    },
    DoubleDouble {
        high: -0.166_666_666_666_666_66,
        low: -9.251_858_538_542_97e-18,
    },
    DoubleDouble {
        high: 0.008_333_333_333_333_333,
        low: 1.156_482_317_317_869e-19,
    },
    DoubleDouble {
        high: -0.000_198_412_698_412_698_4,
        low: -1.720_955_829_251_609_2e-22,
    },
    DoubleDouble {
        high: 2.755_731_922_398_589_3e-06,
        low: -1.858_393_275_722_529e-22,
    },
    DoubleDouble {
        high: -2.505_210_838_544_172e-08,
        low: 1.448_815_918_662_123_7e-24,
    },
    DoubleDouble {
        high: 1.605_904_383_682_161_3e-10,
        low: 1.257_222_284_529_613_6e-26,
    },
    DoubleDouble {
        high: -7.647_163_731_819_815e-13,
        low: -4.606_435_501_111_483e-29,
    },
    DoubleDouble {
        high: 2.811_457_254_345_32e-15,
        low: 5.160_177_200_634_138e-32,
    },
    DoubleDouble {
        high: -8.220_635_246_177_278e-18,
        low: -5.582_599_714_358_412e-34,
    },
    DoubleDouble {
        high: 1.957_294_039_188_14e-20,
        low: 1.408_426_134_532_254_6e-36,
    },
    DoubleDouble {
        high: -3.868_105_107_347_916e-23,
        low: 2.208_071_984_067_889_7e-39,
    },
    DoubleDouble {
        high: 6.410_229_255_316_51e-26,
        low: 2.880_120_311_859_419e-42,
    },
];

/// `cos(r)` as a double-double in `u = r²`, low-degree first (max error ≈2⁻¹²²).
const COS_KERNEL: [DoubleDouble; 13] = [
    DoubleDouble {
        high: 1.0,
        low: -1.376_145_904_391_207_4e-37,
    },
    DoubleDouble {
        high: -0.5,
        low: 7.540_540_356_661_797e-35,
    },
    DoubleDouble {
        high: 0.041_666_666_666_666_664,
        low: 2.312_964_634_635_736e-18,
    },
    DoubleDouble {
        high: -0.001_388_888_888_888_889,
        low: 5.300_543_954_397_993e-20,
    },
    DoubleDouble {
        high: 2.480_158_730_158_73e-05,
        low: 2.151_194_334_305_486_2e-23,
    },
    DoubleDouble {
        high: -2.755_731_922_398_589e-07,
        low: -2.376_766_475_147_913e-23,
    },
    DoubleDouble {
        high: 2.087_675_698_786_81e-09,
        low: -1.210_873_184_327_318_3e-25,
    },
    DoubleDouble {
        high: -1.147_074_559_772_972_3e-11,
        low: -1.501_105_036_419_259_2e-28,
    },
    DoubleDouble {
        high: 4.779_477_332_386_843e-14,
        low: -3.985_232_858_135_9e-31,
    },
    DoubleDouble {
        high: -1.561_920_696_737_958e-16,
        low: 7.952_431_171_295_81e-33,
    },
    DoubleDouble {
        high: 4.110_317_442_059_798e-19,
        low: 1.383_540_106_404_519_5e-35,
    },
    DoubleDouble {
        high: -8.896_615_769_279_29e-22,
        low: 1.980_180_447_621_310_1e-38,
    },
    DoubleDouble {
        high: 1.601_824_914_091_273_4e-24,
        low: -7.728_223_090_239_399e-41,
    },
];

/// Fast-path tail of `sin(r)/r`: coefficients of the `u³` remainder after the
/// three exact leading terms are peeled off, low-degree first in `u = r²`
/// (`sin(r)/r = 1 − u/6 + u²/120 + u³·SIN_TAIL(u)`).  Approximation error on
/// `sin(r)/r` ≈ 2⁻⁷⁴, so once evaluated in plain `f64` the fast kernel is good
/// to ≈2⁻⁶⁰ — enough for the Ziv gate, far cheaper than the double-double Horner.
const SIN_TAIL: [f64; 6] = [
    -0.000_198_412_698_412_698_4,
    2.755_731_922_398_563_4e-06,
    -2.505_210_838_495_563e-08,
    1.605_904_350_052_775_5e-10,
    -7.647_058_546_227_501e-13,
    2.796_286_366_618_979_4e-15,
];

/// Fast-path tail of `cos(r)`: the `u³` remainder after the three exact leading
/// terms (`cos(r) = 1 − u/2 + u²/24 + u³·COS_TAIL(u)`).  Approximation error on
/// `cos(r)` ≈ 2⁻⁷⁰.  See [`SIN_TAIL`].
const COS_TAIL: [f64; 6] = [
    -0.001_388_888_888_888_889,
    2.480_158_730_158_681_4e-05,
    -2.755_731_922_306_274e-07,
    2.087_675_634_918_288e-09,
    -1.147_054_582_173_842_8e-11,
    4.750_660_993_437_302e-14,
];

/// Leading 6 terms of `tan(r)/r = Σ bₖ·v^k` (`v = r²`), as double-doubles,
/// low-degree first.  `tan`'s pole at `π/2` makes the series converge only
/// geometrically (like `asin`), so [`tan_kernel_fast`] carries these exactly and
/// fits the `v⁶` remainder ([`TAN_TAIL`]) in plain `f64`.  Generated by
/// `tools/gen_trig_f64.py`.
const TAN_LEADS: [DoubleDouble; 6] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.333_333_333_333_333_3,
        low: 1.850_371_707_708_594e-17,
    },
    DoubleDouble {
        high: 0.133_333_333_333_333_33,
        low: 1.850_371_707_708_594_2e-18,
    },
    DoubleDouble {
        high: 0.053_968_253_968_253_97,
        low: -2.555_275_215_407_106_5e-18,
    },
    DoubleDouble {
        high: 0.021_869_488_536_155_203,
        low: -1.737_782_953_006_748_5e-19,
    },
    DoubleDouble {
        high: 0.008_863_235_529_902_197,
        low: -7.633_005_801_718_31e-19,
    },
];

/// Fast-path tail of `tan(r)/r` in `v = r²`: the `v⁶` remainder after
/// [`TAN_LEADS`] is peeled into double-double.  Evaluated in plain `f64`; over the
/// `[−π/4, π/4]` octant the assembled kernel reaches ≈2⁻⁶¹ relative — enough that
/// the reciprocal of the odd-quadrant path still clears the `2⁻⁵⁹` gate.
const TAN_TAIL: [f64; 15] = [
    0.003_592_128_036_572_481,
    0.001_455_834_387_051_282,
    0.000_590_027_440_949_976_1,
    0.000_239_129_114_034_912_1,
    9.691_538_474_772_203e-05,
    3.927_824_672_895_707_5e-05,
    1.591_965_246_822_141e-05,
    6.446_748_601_957_79e-06,
    2.637_703_535_568_635_2e-06,
    9.839_484_146_788_608e-07,
    6.078_285_342_856_009e-07,
    -1.204_289_917_739_238e-07,
    3.992_883_067_012_166_7e-07,
    -2.002_701_768_462_033_7e-07,
    9.276_165_196_030_918e-08,
];

/// Relative half-width of the trig fast-path Ziv gate.  Over a dense sweep of
/// the `[-π/4, π/4]` octant the fast kernel's relative error peaks at ≈2⁻⁶¹·⁶
/// (cos) and ≈2⁻⁶⁵ (sin); `2⁻⁵⁹` keeps a ~6× margin over that while the gate
/// stays tight enough that only a few percent of inputs fall through to the
/// accurate kernel.
const TRIG_ZIV_EPS: f64 = 1.734_723_475_976_807e-18; // 2⁻⁵⁹

/// `1` as a double-double.
const ONE: DoubleDouble = DoubleDouble {
    high: 1.0,
    low: 0.0,
};

/// `1/120` as a double-double — the exact `u²` coefficient peeled from
/// `sin(r)/r`.  Carried in double-double so the term does not cap the fast
/// kernel at the `f64` rounding of `1/120` (≈2⁻⁵⁹).
const FRAC_1_120: DoubleDouble = DoubleDouble {
    high: 0.008_333_333_333_333_333,
    low: 1.156_482_317_317_871_4e-19,
};

/// `−1/6` as a double-double — the exact `u` coefficient peeled from
/// `sin(r)/r`, carried as a constant so the term is one double-double multiply
/// instead of `Div<f64>`'s two serial divisions.  See [`FRAC_1_120`].
const NEG_FRAC_1_6: DoubleDouble = DoubleDouble {
    high: -0.166_666_666_666_666_66,
    low: -9.251_858_538_542_97e-18,
};

/// `1/24` as a double-double — the exact `u²` coefficient peeled from `cos(r)`.
/// See [`FRAC_1_120`].
const FRAC_1_24: DoubleDouble = DoubleDouble {
    high: 0.041_666_666_666_666_664,
    low: 2.312_964_634_635_742_7e-18,
};

/// 2/π as f64, for the medium-range quotient `round(x·2/π)`.
const FRAC_2_PI_F64: f64 = 0.636_619_772_367_581_4;

/// π/2 in four words (≈2⁻¹⁵⁶ relative); each of `PIO2_1..PIO2_4` has ≥21 low
/// mantissa bits clear, so `q·PIO2_k` is exact for `|q| < 2²¹` (the medium range
/// `|x| < 2²⁰`).  The first three words are subtracted exactly (capturing every
/// residual), the fourth folds into the low part, leaving the reduced angle
/// accurate to ≈2⁻¹³⁰ — past the ≈117-bit ceiling of a 3-word split, which is what
/// keeps the relative Ziv gate sound near a multiple of π/2.
const PIO2_1: f64 = 1.570_796_326_734_125_6;
const PIO2_2: f64 = 6.077_100_506_303_966e-11;
const PIO2_3: f64 = 2.022_266_248_711_166_5e-21;
const PIO2_4: f64 = 8.478_427_660_348_229e-32;

/// π/2 as a double-double, for the Payne–Hanek reconstruction.
const PIO2: DoubleDouble = DoubleDouble {
    high: 1.570_796_326_794_896_6,
    low: 6.123_233_995_736_766e-17,
};

/// Below this magnitude `sin(x)` and `tan(x)` round to `x`, and `cos(x)` rounds
/// to `1`.  The corrections `x³/6` (sin), `x³/3` (tan) and `x²/2` (cos) all stay
/// under half an ulp here, so the fast return is correctly rounded (with a ~6×
/// margin) — the same short-circuit `core-math` takes, sparing the kernel on the
/// roughly half of all `f64` bit patterns that are this small.
const SMALL: f64 = 7.450_580_596_923_828e-9; // 2⁻²⁷

/// Fractional bits of 2/π, most-significant 64-bit group first (`FRAC_2_PI[0]`
/// holds bits 1..64).  Used by [`payne_hanek`] for `|x| ≥ 2²⁰`.
const FRAC_2_PI: [u64; 24] = [
    0xA2F9836E4E441529,
    0xFC2757D1F534DDC0,
    0xDB6295993C439041,
    0xFE5163ABDEBBC561,
    0xB7246E3A424DD2E0,
    0x06492EEA09D1921C,
    0xFE1DEB1CB129A73E,
    0xE88235F52EBB4484,
    0xE99C7026B45F7E41,
    0x3991D639835339F4,
    0x9C845F8BBDF9283B,
    0x1FF897FFDE05980F,
    0xEF2F118B5A0A6D1F,
    0x6D367ECF27CB09B7,
    0x4F463F669E5FEA2D,
    0x7527BAC7EBE5F17B,
    0x3D0739F78A5292EA,
    0x6BFB5FB11F8D5D08,
    0x56033046FC7B6BAB,
    0xF0CFBC209AF4361D,
    0xA9E391615EE61B08,
    0x6599855F14A06840,
    0x8DFFD8804D732731,
    0x06061556CA73A8C9,
];

// ---------------------------------------------------------------------------
// Accurate-path `Dint` (128-bit fixed-point) trig.
//
// The double-double accurate kernels above cap at ≈2⁻¹⁰⁶ — both in the
// `sin`/`cos` polynomial *and*, more critically, in the Payne–Hanek collapse of
// the 128-bit reduced fraction into a double-double `r`.  That ceiling mis-rounds
// the corpus's hardest near-ties (≈58-bit, needing ≈2⁻¹¹¹).  The `Dint` path
// feeds the reduced fraction's bits straight into a 128-bit significand (no dd
// collapse) and evaluates the Taylor kernels in `Dint` (≈2⁻¹²⁶), then rounds once
// with the sound `Dint::to_f64` (explicit round + sticky) — no hard-case database,
// exactly as the inverse-hyperbolic `ln`-of-a-double-double legs do.
//
// Constants below were generated by `tools/gen_dint_trig.py`; do not edit by hand.
// ---------------------------------------------------------------------------

/// π/2 as a `Dint`, for the accurate-path reconstruction `r = frac · π/2`.
const PIO2_DINT: Dint = Dint {
    sgn: false,
    ex: 0,
    m: 0xc90fdaa22168c234c4c6628b80dc1cd1,
};

/// `2` as a `Dint`, for the Newton reciprocal `y·(2 − c·y)` behind accurate `tan`.
const TWO_DINT: Dint = Dint {
    sgn: false,
    ex: 1,
    m: 0x80000000000000000000000000000000,
};

/// `sin(r)/r` as `Dint` minimax coefficients in `u = r²`, low-degree first.
/// 14 terms — the max error over `[0, (π/4)²]` is ≈2⁻¹³⁹ (≈2⁻¹³³ after
/// quantizing the coefficients to `Dint`), below the `Dint` arithmetic floor.
const SIN_DINT: [Dint; 14] = [
    Dint {
        sgn: false,
        ex: 0,
        m: 0x80000000000000000000000000000000,
    },
    Dint {
        sgn: true,
        ex: -3,
        m: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    },
    Dint {
        sgn: false,
        ex: -7,
        m: 0x88888888888888888888888888888304,
    },
    Dint {
        sgn: true,
        ex: -13,
        m: 0xd00d00d00d00d00d00d00d00cfd3c095,
    },
    Dint {
        sgn: false,
        ex: -19,
        m: 0xb8ef1d2ab6399c7d560e44714a1cf810,
    },
    Dint {
        sgn: true,
        ex: -26,
        m: 0xd7322b3faa271c7f3a3f1de7e8537244,
    },
    Dint {
        sgn: false,
        ex: -33,
        m: 0xb092309d43684be51bf8946b51ffd81a,
    },
    Dint {
        sgn: true,
        ex: -41,
        m: 0xd73f9f399dc0f88e072a304aab268f7a,
    },
    Dint {
        sgn: false,
        ex: -49,
        m: 0xca963b81856a506e6987c48d14c9f8fc,
    },
    Dint {
        sgn: true,
        ex: -57,
        m: 0x97a4da340a028ffc77b0b12c8f37e854,
    },
    Dint {
        sgn: false,
        ex: -66,
        m: 0xb8dc77b6c7a286d623f9a0ebf12f4b58,
    },
    Dint {
        sgn: true,
        ex: -75,
        m: 0xbb0da042577331ee2548b4a4a2bba83e,
    },
    Dint {
        sgn: false,
        ex: -84,
        m: 0x9f9dceae8bd1c3807edcb35637352631,
    },
    Dint {
        sgn: true,
        ex: -94,
        m: 0xe79967c7c1fd457e8bad5620ab5c78a2,
    },
];

/// `cos(r)` as `Dint` minimax coefficients in `u = r²`, low-degree first.
/// 14 terms — the max error over `[0, (π/4)²]` is ≈2⁻¹³⁴ (≈2⁻¹³³ after
/// quantizing the coefficients to `Dint`).
const COS_DINT: [Dint; 14] = [
    Dint {
        sgn: false,
        ex: 0,
        m: 0x80000000000000000000000000000000,
    },
    Dint {
        sgn: true,
        ex: -2,
        m: 0xfffffffffffffffffffffffffffffff4,
    },
    Dint {
        sgn: false,
        ex: -5,
        m: 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaa82ad,
    },
    Dint {
        sgn: true,
        ex: -10,
        m: 0xb60b60b60b60b60b60b60b60b53be8cd,
    },
    Dint {
        sgn: false,
        ex: -16,
        m: 0xd00d00d00d00d00d00d00cfc6ce73cc3,
    },
    Dint {
        sgn: true,
        ex: -22,
        m: 0x93f27dbbc4fae397780b5bbb83a5f0ac,
    },
    Dint {
        sgn: false,
        ex: -29,
        m: 0x8f76c77fc6c4bdaa269903347e0ad492,
    },
    Dint {
        sgn: true,
        ex: -37,
        m: 0xc9cba54603e4e904825156e42e86c60a,
    },
    Dint {
        sgn: false,
        ex: -45,
        m: 0xd73f9f399dc0f345a3a45aadb465b2fa,
    },
    Dint {
        sgn: true,
        ex: -53,
        m: 0xb413c31dcbddf25e5a6dd8bae52be772,
    },
    Dint {
        sgn: false,
        ex: -62,
        m: 0xf2a15d1fd60500d69438ba5d2031b4d0,
    },
    Dint {
        sgn: true,
        ex: -70,
        m: 0x8671cb1f833c0957987226ca65cb7c1a,
    },
    Dint {
        sgn: false,
        ex: -80,
        m: 0xf9666cf2db6b1cb738dd68ce5a1a05c4,
    },
    Dint {
        sgn: true,
        ex: -89,
        m: 0xc355ba2967b5ca732d6ab7f31ee13ec5,
    },
];

/// Negate a double-double.
#[inline]
fn neg(v: DoubleDouble) -> DoubleDouble {
    DoubleDouble {
        high: -v.high,
        low: -v.low,
    }
}

/// Payne–Hanek argument reduction for `|x| ≥ 2²⁰`.
///
/// Returns `(q, r)` with `q` the quadrant (low bits of `round(x·2/π)`) and `r ∈
/// [-π/4, π/4]` a double-double.  Multiplies the 53-bit significand by a 256-bit
/// window of 2/π selected by the exponent, reads off the integer part (for `q`)
/// and a 128-bit signed fraction, and scales the fraction by π/2.
#[inline]
fn payne_hanek(x: f64) -> (i64, DoubleDouble) {
    let bits = x.to_bits();
    let e = ((bits >> super::EXP_SHIFT) & 0x7ff) as i64; // biased exponent
    let sig = u128::from((bits & 0x000F_FFFF_FFFF_FFFF) | 0x0010_0000_0000_0000);

    // x = sig · 2ᵐ with m = e − 1023 − 52.  The 2/π bit aligning to 2⁰ of x·2/π is
    // index k = m; pick the 256-bit window starting two bits above that.
    let m = e - 1075;
    let w0 = (((m - 2).max(0)) / 64) as usize;

    let word = |i: usize| u128::from(*FRAC_2_PI.get(w0 + i).unwrap_or(&0));
    let (wa, wb, wc, wd) = (word(0), word(1), word(2), word(3));

    // P = sig · (wa·2¹⁹² + wb·2¹²⁸ + wc·2⁶⁴ + wd), as five 64-bit limbs.
    let (pa, pb, pc, pd) = (sig * wa, sig * wb, sig * wc, sig * wd);
    const MASK: u128 = 0xFFFF_FFFF_FFFF_FFFF;
    let p0 = pd as u64;
    let c = (pd >> 64) + (pc & MASK);
    let p1 = c as u64;
    let c = (c >> 64) + (pc >> 64) + (pb & MASK);
    let p2 = c as u64;
    let c = (c >> 64) + (pb >> 64) + (pa & MASK);
    let p3 = c as u64;
    let p4 = ((c >> 64) + (pa >> 64)) as u64;
    let p = [p0, p1, p2, p3, p4];

    // Units bit of x·2/π is at P bit `b = 256 + 64·w0 − m`.
    let b = 256 + 64 * w0 as i64 - m;
    let bit_at = |start: i64| -> u64 {
        let w = (start / 64) as usize;
        let o = (start % 64) as u32;
        let lo = p.get(w).copied().unwrap_or(0);
        let hi = p.get(w + 1).copied().unwrap_or(0);
        if o == 0 {
            lo
        } else {
            (lo >> o) | (hi << (64 - o))
        }
    };

    // 192-bit window [b−128, b+63]: top 64 bits are the integer part (quadrant),
    // low 128 bits are the signed fraction of x·2/π.
    let frac = (u128::from(bit_at(b - 64)) << 64) | u128::from(bit_at(b - 128));
    let q = bit_at(b) as i64;
    let frac = frac as i128;

    // round-to-nearest: a negative signed fraction means the integer rounded up.
    let quadrant = q.wrapping_sub((frac >> 127) as i64);

    // r = (frac / 2¹²⁸) · π/2 ∈ [-π/4, π/4], as a double-double.  Split the
    // 128-bit signed `frac` into two limbs (`frac = h·2⁶⁴ + l` in two's
    // complement) and convert with native `i64`/`u64` → `f64`: a direct
    // `frac as f64` (and the residual's `as i128`) lowers to the slow
    // `__floattidf`/`__fixdfti` compiler-rt libcalls.  `hf` carries the top
    // ≈53 bits; `lf` folds `h`'s lost low bits and `l` into the next ≈53, so the
    // pair keeps the same ≈2⁻¹⁰⁶ precision the i128 casts gave.
    let h = (frac >> 64) as i64;
    let l = frac as u64;
    let hf = h as f64;
    let hr = h.wrapping_sub(hf as i64);
    let lf = crate::fma(hr as f64, crate::exp2i(64), l as f64);
    let r = DoubleDouble {
        high: hf * crate::exp2i(-64),
        low: lf * crate::exp2i(-128),
    } * PIO2;

    (quadrant, r)
}

/// Payne–Hanek argument reduction to a 128-bit `Dint` reduced angle — the
/// accurate-path counterpart of [`payne_hanek`], called only on the Ziv
/// fallback (any finite `x ≥ 2⁻²⁷`, so it subsumes the medium Cody–Waite range
/// too).
///
/// Returns `(quadrant, r)` with `r ∈ [−π/4, π/4]` a `Dint`.  Unlike the
/// double-double path, the residual fraction of `x·2/π` is read out **normalized**
/// — a 128-bit window taken at its own leading bit — so it keeps full 128-bit
/// relative precision even when `x` lies very close to a multiple of `π/2` and the
/// residual is tiny (the leading zeros the dd path absorbs into its 53-bit `hi`).
/// A 5-word (320-bit) window of 2/π and a 256-bit fraction extraction give ample
/// headroom over the ≈61-bit worst-case cancellation.
#[inline]
fn payne_hanek_dint(x: f64) -> (i64, Dint) {
    let bits = x.to_bits();
    let e = ((bits >> super::EXP_SHIFT) & 0x7ff) as i64;
    let sig = u128::from((bits & 0x000F_FFFF_FFFF_FFFF) | 0x0010_0000_0000_0000);

    let m = e - 1075;
    let w0 = (((m - 2).max(0)) / 64) as usize;
    let word = |i: usize| u128::from(*FRAC_2_PI.get(w0 + i).unwrap_or(&0));
    let (wa, wb, wc, wd, we) = (word(0), word(1), word(2), word(3), word(4));

    // P = sig · (wa·2²⁵⁶ + wb·2¹⁹² + wc·2¹²⁸ + wd·2⁶⁴ + we), as six 64-bit limbs.
    let (pa, pb, pc, pd, pe) = (sig * wa, sig * wb, sig * wc, sig * wd, sig * we);
    const MASK: u128 = 0xFFFF_FFFF_FFFF_FFFF;
    let p0 = pe as u64;
    let c = (pe >> 64) + (pd & MASK);
    let p1 = c as u64;
    let c = (c >> 64) + (pd >> 64) + (pc & MASK);
    let p2 = c as u64;
    let c = (c >> 64) + (pc >> 64) + (pb & MASK);
    let p3 = c as u64;
    let c = (c >> 64) + (pb >> 64) + (pa & MASK);
    let p4 = c as u64;
    let p5 = ((c >> 64) + (pa >> 64)) as u64;
    let p = [p0, p1, p2, p3, p4, p5];

    // Units bit of x·2/π is at P bit `b = 320 + 64·w0 − m`.
    let b = 320 + 64 * w0 as i64 - m;

    // Bits [start, start+63] of the zero-extended P (any signed `start`).
    let safe_word = |start: i64| -> u64 {
        let idx = start.div_euclid(64);
        let off = start.rem_euclid(64) as u32;
        let get = |i: i64| -> u64 {
            if i < 0 {
                0
            } else {
                p.get(i as usize).copied().unwrap_or(0)
            }
        };
        let lo = get(idx);
        if off == 0 {
            lo
        } else {
            (lo >> off) | (get(idx + 1) << (64 - off))
        }
    };

    // 256-bit signed fraction window [b−256, b−1]; its top bit (b−1) is the 2⁻¹
    // place, so the window read as a two's-complement integer is `resid · 2²⁵⁶`.
    let hi = (u128::from(safe_word(b - 64)) << 64) | u128::from(safe_word(b - 128));
    let lo = (u128::from(safe_word(b - 192)) << 64) | u128::from(safe_word(b - 256));

    // Sign of the residual; a negative residual means the integer rounded up.
    let sgn = hi >> 127 == 1;
    let quadrant = (safe_word(b) as i64).wrapping_add(i64::from(sgn));

    // |resid| · 2²⁵⁶ as an unsigned 256-bit pair.
    let (mag_hi, mag_lo) = if sgn {
        let (nlo, carry) = (!lo).overflowing_add(1);
        ((!hi).wrapping_add(u128::from(carry)), nlo)
    } else {
        (hi, lo)
    };

    // Normalize to a 128-bit significand: shift the leading set bit to bit 255,
    // keep the top 128 bits.  `value = mag/2²⁵⁶ = m/2^(128+lz)`, so `ex = −1 − lz`.
    let lz = if mag_hi != 0 {
        mag_hi.leading_zeros()
    } else {
        128 + mag_lo.leading_zeros()
    };
    let m128 = if lz == 0 {
        mag_hi
    } else if lz < 128 {
        (mag_hi << lz) | (mag_lo >> (128 - lz))
    } else {
        mag_lo << (lz - 128)
    };

    let frac = Dint {
        sgn,
        ex: -1 - i64::from(lz),
        m: m128,
    };
    (quadrant, frac.mul(&PIO2_DINT))
}

/// Negate a `Dint`.
#[inline]
const fn neg_dint(v: Dint) -> Dint {
    Dint { sgn: !v.sgn, ..v }
}

/// Horner evaluation of a `Dint` polynomial in `u`, low-degree first.
#[inline]
fn poly_dint(u: &Dint, coeffs: &[Dint]) -> Dint {
    let mut acc = coeffs[coeffs.len() - 1];
    for c in coeffs[..coeffs.len() - 1].iter().rev() {
        acc = c.add(&u.mul(&acc));
    }
    acc
}

/// `(sin(r), cos(r))` for `r ∈ [−π/4, π/4]` as `Dint`s — the accurate kernel.
#[inline]
fn sin_cos_dint(r: &Dint) -> (Dint, Dint) {
    let u = r.mul(r);
    (r.mul(&poly_dint(&u, &SIN_DINT)), poly_dint(&u, &COS_DINT))
}

/// `sin(r)` for `r ∈ [−π/4, π/4]` as a `Dint`.
#[inline]
fn sin_dint(r: &Dint) -> Dint {
    let u = r.mul(r);
    r.mul(&poly_dint(&u, &SIN_DINT))
}

/// `cos(r)` for `r ∈ [−π/4, π/4]` as a `Dint`.
#[inline]
fn cos_dint(r: &Dint) -> Dint {
    let u = r.mul(r);
    poly_dint(&u, &COS_DINT)
}

/// `1 / c` as a `Dint`, two Newton steps `y·(2 − c·y)` from the `f64` seed
/// `1/c`.  `c = cos(|x|)` is well away from a catastrophic seed (`|c| ≥ ≈2⁻⁶¹`),
/// so two steps reach the `Dint` arithmetic floor — the divide behind accurate
/// `tan`.
#[inline]
fn recip_dint(c: &Dint) -> Dint {
    let mut y = Dint::from_f64(1.0 / c.to_f64());
    for _ in 0..2 {
        y = y.mul(&TWO_DINT.add(&neg_dint(c.mul(&y))));
    }
    y
}

/// Reconstruct `sin(|x|)` (`Dint`) from the kernel pair and quadrant `q`.
#[inline]
const fn select_sin_dint(q: i64, s: Dint, c: Dint) -> Dint {
    let v = if q & 1 == 0 { s } else { c };
    if q & 2 == 0 { v } else { neg_dint(v) }
}

/// Reconstruct `cos(|x|)` (`Dint`) from the kernel pair and quadrant `q`.
#[inline]
const fn select_cos_dint(q: i64, s: Dint, c: Dint) -> Dint {
    let v = if q & 1 == 0 { c } else { s };
    if q.wrapping_add(1) & 2 == 0 {
        v
    } else {
        neg_dint(v)
    }
}

/// Argument reduction: `x ≥ 0` finite → `(quadrant, r)` with `r ∈ [-π/4, π/4]`.
#[inline]
fn rem_pio2(x: f64) -> (i64, DoubleDouble) {
    // Medium range: Cody–Waite with the 4-word π/2 (q small enough that
    // q·PIO2_1..PIO2_4 are exact).  Handles `q = 0` (no reduction) too.
    if x < 1_048_576.0 {
        let q = (x * FRAC_2_PI_F64).round_ties_even();
        // Subtract `q·π/2` word by word.  Each `q·PIO2_k` (k ≤ 4) is exact
        // (cleared low bits, |q| < 2²¹), so the three 2Sums capture every
        // residual of the first three words exactly; the fourth word folds into
        // the accumulated low part and the tail beyond PIO2_4 (≈2⁻¹²² after the
        // `q` scale) is dropped.  This flat fold — versus renormalizing the pair
        // after each word — keeps `r` accurate to ≈2⁻¹³⁰, so the relative Ziv
        // gate stays sound for any |r| ≳ 2⁻⁷⁰, far below the medium range's
        // worst-case cancellation; tinier residuals fall through to the
        // `payne_hanek_dint` accurate path.
        let a = DoubleDouble::from_sum(x, q * -PIO2_1);
        let b = DoubleDouble::from_sum(a.high, q * -PIO2_2);
        let c = DoubleDouble::from_sum(b.high, q * -PIO2_3);
        let lo = crate::fma(-q, PIO2_4, a.low + b.low + c.low);
        // SAFETY: |q| < 2²⁰.
        return (unsafe { q.to_int_unchecked() }, fast_sum(c.high, lo));
    }

    payne_hanek(x)
}

/// `sin(r)` for `r ∈ [-π/4, π/4]` as a double-double, by full double-double
/// Horner of [`SIN_KERNEL`] (≈2⁻¹²⁷) — the accurate `sin` half.
#[inline]
fn sin_kernel(r: DoubleDouble) -> DoubleDouble {
    r * poly_dd(r * r, &SIN_KERNEL)
}

/// `cos(r)` for `r ∈ [-π/4, π/4]` as a double-double, by full double-double
/// Horner of [`COS_KERNEL`] (≈2⁻¹²²) — the accurate `cos` half.
#[inline]
fn cos_kernel(r: DoubleDouble) -> DoubleDouble {
    poly_dd(r * r, &COS_KERNEL)
}

/// The squares shared by the fast sin/cos parts: `uu = r²`, `u2 = uu²`, and
/// `u3 = uu.high³`.
#[inline]
fn fast_squares(r: DoubleDouble) -> (DoubleDouble, DoubleDouble, f64) {
    let uu = r * r;
    let u = uu.high;
    (uu, uu * uu, u * u * u)
}

/// `sin(r)` from the precomputed squares — the `sin` half of the fast path.
///
/// Peels the three exact leading terms of `sin(r)/r` into double-double and
/// evaluates only the tiny `u³` tail ([`SIN_TAIL`]) in plain `f64`, so the result
/// comes out to ≈2⁻⁶⁰ for a fraction of [`sin_kernel`]'s cost.
#[inline]
fn sin_part_fast(r: DoubleDouble, uu: DoubleDouble, u2: DoubleDouble, u3: f64) -> DoubleDouble {
    // sin(r)/r = 1 − u/6 + u²/120 + u³·SIN_TAIL(u); every addend stays under
    // half its lead at the octant edge (`fold_ordering` below), so the folds
    // are ordered Fast2Sums, and `−u/6` is a multiply by the double-double
    // constant rather than `Div<f64>`'s two serial divisions.
    let sin_lead = ONE
        .add_ordered(uu * NEG_FRAC_1_6)
        .add_ordered(u2 * FRAC_1_120);
    let sin_over_r = sin_lead.add_ordered(DoubleDouble {
        high: u3 * crate::poly(uu.high, &SIN_TAIL),
        low: 0.0,
    });
    r * sin_over_r
}

/// `cos(r)` from the precomputed squares — the `cos` half of the fast path.  See
/// [`sin_part_fast`]; the `u³` tail is [`COS_TAIL`].
#[inline]
fn cos_part_fast(uu: DoubleDouble, u2: DoubleDouble, u3: f64) -> DoubleDouble {
    // cos(r) = 1 − u/2 + u²/24 + u³·COS_TAIL(u); ordered Fast2Sum folds as in
    // [`sin_part_fast`] (`|u/2| ≤ 0.309` is the tightest — see `fold_ordering`).
    let cos_lead = ONE.add_ordered(uu * -0.5).add_ordered(u2 * FRAC_1_24);
    cos_lead.add_ordered(DoubleDouble {
        high: u3 * crate::poly(uu.high, &COS_TAIL),
        low: 0.0,
    })
}

/// `sin(r)` for `r ∈ [-π/4, π/4]`, the fast path — only the `sin` half.
#[inline]
fn sin_kernel_fast(r: DoubleDouble) -> DoubleDouble {
    let (uu, u2, u3) = fast_squares(r);
    sin_part_fast(r, uu, u2, u3)
}

/// `cos(r)` for `r ∈ [-π/4, π/4]`, the fast path — only the `cos` half.
#[inline]
fn cos_kernel_fast(r: DoubleDouble) -> DoubleDouble {
    let (uu, u2, u3) = fast_squares(r);
    cos_part_fast(uu, u2, u3)
}

/// Lean fast kernel computing both halves, for `sincos`.
#[inline]
fn sin_cos_kernel_fast(r: DoubleDouble) -> (DoubleDouble, DoubleDouble) {
    let (uu, u2, u3) = fast_squares(r);
    (sin_part_fast(r, uu, u2, u3), cos_part_fast(uu, u2, u3))
}

/// `tan(r)` for `r ∈ [−π/4, π/4]`, as a double-double, via the direct series
/// `tan(r) = r·T(r²)`.  The 6 leading terms of `T` are carried in double-double
/// ([`TAN_LEADS`], 2-way Estrin) and the `v⁶` remainder ([`TAN_TAIL`]) in plain
/// `f64`.  One kernel — versus the sin/cos pair plus a reciprocal — feeds [`tan`].
///
/// Every fold uses [`DoubleDouble::add_ordered`]: `tan`'s series coefficients
/// decay fast enough that each addend stays under half its lead even at
/// `v = (π/4)²` (asserted in `fold_ordering` below).
#[inline]
fn tan_kernel_fast(r: DoubleDouble) -> DoubleDouble {
    let w = r * r; // v = r²
    let v = w.high;
    let v2 = v * v;
    let v6 = v2 * v2 * v2;
    let w2 = w * w;
    let p0 = TAN_LEADS[0].add_ordered(w * TAN_LEADS[1]);
    let p1 = TAN_LEADS[2].add_ordered(w * TAN_LEADS[3]);
    let p2 = TAN_LEADS[4].add_ordered(w * TAN_LEADS[5]);
    let t = p0
        .add_ordered(w2 * p1.add_ordered(w2 * p2))
        .add_ordered(DoubleDouble {
            high: v6 * crate::poly(v, &TAN_TAIL),
            low: 0.0,
        });
    r * t
}

/// Reconstruct `sin(|x|)` from the kernel pair and quadrant `q` (before the sign
/// of `x` is restored).  Shared by the fast and accurate paths so they select
/// identically.
#[inline]
fn select_sin(q: i64, s: DoubleDouble, c: DoubleDouble) -> DoubleDouble {
    let v = if q & 1 == 0 { s } else { c };
    if q & 2 == 0 { v } else { neg(v) }
}

/// Reconstruct `cos(|x|)` from the kernel pair and quadrant `q`.
#[inline]
fn select_cos(q: i64, s: DoubleDouble, c: DoubleDouble) -> DoubleDouble {
    let v = if q & 1 == 0 { c } else { s };
    if q.wrapping_add(1) & 2 == 0 {
        v
    } else {
        neg(v)
    }
}

/// Ziv gate: round `v` to `f64` when both ends of its `±TRIG_ZIV_EPS` (relative)
/// error interval agree, else `None` to fall back to the accurate kernel.
#[inline]
fn ziv(v: DoubleDouble) -> Option<f64> {
    let eps = v.high.abs() * TRIG_ZIV_EPS;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    (lo == hi).then_some(lo)
}

/// π as a double-double, for `sin(πx)` (the lgamma reflection).
const PI_DD: DoubleDouble = DoubleDouble {
    high: 3.141_592_653_589_793,
    low: 1.224_646_799_147_353_2e-16,
};

/// `sin(πk/128)` as a double-double, `k = 0..=64` — the grid table of the lean
/// table-driven `|sin(πx)|` ([`abs_sinpi_dd_lean`]), CORE-MATH's `stpi`.  Indexing
/// it at `64 − k` gives `cos(πk/128)` by the complement identity, so one table
/// serves both the sine and cosine of the grid angle.
///
/// Generated to ≈2⁻¹⁰⁵ (200-bit MPFR, `tests/gen_sinpi_table.rs`).
const SINPI_TABLE: [DoubleDouble; 65] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.024_541_228_522_912_288,
        low: -9.186_849_012_577_878e-20,
    },
    DoubleDouble {
        high: 0.049_067_674_327_418_015,
        low: -6.796_103_720_518_28e-19,
    },
    DoubleDouble {
        high: 0.073_564_563_599_667_43,
        low: -2.778_494_150_627_359_3e-18,
    },
    DoubleDouble {
        high: 0.098_017_140_329_560_6,
        low: -1.634_582_362_244_256e-18,
    },
    DoubleDouble {
        high: 0.122_410_675_199_216_2,
        low: 2.835_450_148_996_533_5e-18,
    },
    DoubleDouble {
        high: 0.146_730_474_455_361_75,
        low: 3.726_947_147_046_568e-18,
    },
    DoubleDouble {
        high: 0.170_961_888_760_301_22,
        low: 9.191_998_018_175_91e-18,
    },
    DoubleDouble {
        high: 0.195_090_322_016_128_28,
        low: -7.991_079_068_461_731e-18,
    },
    DoubleDouble {
        high: 0.219_101_240_156_869_8,
        low: -3.651_381_229_915_077_6e-19,
    },
    DoubleDouble {
        high: 0.242_980_179_903_263_9,
        low: -8.751_431_529_719_663e-18,
    },
    DoubleDouble {
        high: 0.266_712_757_474_898_37,
        low: 2.094_122_257_882_668_8e-17,
    },
    DoubleDouble {
        high: 0.290_284_677_254_462_4,
        low: -1.892_797_870_777_425e-17,
    },
    DoubleDouble {
        high: 0.313_681_740_398_891_46,
        low: 1.456_044_729_996_891_2e-17,
    },
    DoubleDouble {
        high: 0.336_889_853_392_220_05,
        low: -4.200_094_003_347_509e-19,
    },
    DoubleDouble {
        high: 0.359_895_036_534_988_17,
        low: -1.760_168_712_383_928_2e-17,
    },
    DoubleDouble {
        high: 0.382_683_432_365_089_8,
        low: -1.005_077_269_646_158_8e-17,
    },
    DoubleDouble {
        high: 0.405_241_314_004_989_86,
        low: 9.911_140_194_289_988e-18,
    },
    DoubleDouble {
        high: 0.427_555_093_430_282_1,
        low: 9.411_189_816_295_473e-18,
    },
    DoubleDouble {
        high: 0.449_611_329_654_606_6,
        low: 4.883_192_423_203_524e-18,
    },
    DoubleDouble {
        high: 0.471_396_736_825_997_64,
        low: 6.516_678_136_069_013e-18,
    },
    DoubleDouble {
        high: 0.492_898_192_229_784_04,
        low: -1.025_783_167_656_218_6e-18,
    },
    DoubleDouble {
        high: 0.514_102_744_193_221_8,
        low: -4.571_270_752_361_562_4e-17,
    },
    DoubleDouble {
        high: 0.534_997_619_887_097_3,
        low: -5.368_313_270_835_813_4e-17,
    },
    DoubleDouble {
        high: 0.555_570_233_019_602_2,
        low: 4.709_410_940_561_677e-17,
    },
    DoubleDouble {
        high: 0.575_808_191_417_845_3,
        low: -3.790_949_545_894_273_4e-17,
    },
    DoubleDouble {
        high: 0.595_699_304_492_433_4,
        low: -1.343_864_193_657_946_7e-17,
    },
    DoubleDouble {
        high: 0.615_231_590_580_626_8,
        low: 2.623_141_776_726_695e-17,
    },
    DoubleDouble {
        high: 0.634_393_284_163_645_5,
        low: 1.042_090_192_928_003_5e-17,
    },
    DoubleDouble {
        high: 0.653_172_842_953_776_8,
        low: 8.569_564_206_002_624e-18,
    },
    DoubleDouble {
        high: 0.671_558_954_847_018_4,
        low: -4.048_903_774_929_669e-17,
    },
    DoubleDouble {
        high: 0.689_540_544_737_066_9,
        low: -1.588_932_329_480_679e-17,
    },
    DoubleDouble {
        high: 0.707_106_781_186_547_6,
        low: -4.833_646_656_726_457e-17,
    },
    DoubleDouble {
        high: 0.724_247_082_951_466_9,
        low: 2.919_847_133_440_300_4e-17,
    },
    DoubleDouble {
        high: 0.740_951_125_354_959_1,
        low: -1.470_861_695_229_734_5e-17,
    },
    DoubleDouble {
        high: 0.757_208_846_506_484_6,
        low: -1.990_909_877_733_550_2e-17,
    },
    DoubleDouble {
        high: 0.773_010_453_362_737,
        low: -3.256_590_703_364_977e-17,
    },
    DoubleDouble {
        high: 0.788_346_427_626_606_2,
        low: 3.439_699_315_405_971e-17,
    },
    DoubleDouble {
        high: 0.803_207_531_480_644_9,
        low: -3.306_060_980_481_491e-17,
    },
    DoubleDouble {
        high: 0.817_584_813_151_583_7,
        low: -1.488_314_981_242_677_2e-17,
    },
    DoubleDouble {
        high: 0.831_469_612_302_545_2,
        low: 1.407_385_698_472_802_4e-18,
    },
    DoubleDouble {
        high: 0.844_853_565_249_707_1,
        low: -4.363_136_029_687_964e-17,
    },
    DoubleDouble {
        high: 0.857_728_610_000_272_1,
        low: -4.818_344_793_633_662e-17,
    },
    DoubleDouble {
        high: 0.870_086_991_108_711_5,
        low: -4.188_851_086_854_997e-17,
    },
    DoubleDouble {
        high: 0.881_921_264_348_355,
        low: -1.984_324_840_589_056_2e-17,
    },
    DoubleDouble {
        high: 0.893_224_301_195_515_3,
        low: -4.116_123_915_190_891e-18,
    },
    DoubleDouble {
        high: 0.903_989_293_123_443_3,
        low: -6.609_754_468_748_431e-18,
    },
    DoubleDouble {
        high: 0.914_209_755_703_530_7,
        low: -3.631_618_252_781_442e-17,
    },
    DoubleDouble {
        high: 0.923_879_532_511_286_7,
        low: 1.764_504_708_433_667_7e-17,
    },
    DoubleDouble {
        high: 0.932_992_798_834_738_8,
        low: 4.204_141_555_538_435_5e-17,
    },
    DoubleDouble {
        high: 0.941_544_065_183_020_8,
        low: -2.789_637_954_769_834e-17,
    },
    DoubleDouble {
        high: 0.949_528_180_593_036_7,
        low: -7.554_415_192_804_33e-18,
    },
    DoubleDouble {
        high: 0.956_940_335_732_208_8,
        low: 4.055_386_986_187_57e-17,
    },
    DoubleDouble {
        high: 0.963_776_065_795_439_8,
        low: 2.646_395_056_122_003e-17,
    },
    DoubleDouble {
        high: 0.970_031_253_194_544,
        low: 1.836_530_034_842_884_4e-17,
    },
    DoubleDouble {
        high: 0.975_702_130_038_528_6,
        low: -2.557_255_608_125_968_6e-17,
    },
    DoubleDouble {
        high: 0.980_785_280_403_230_4,
        low: 1.854_693_999_782_500_6e-17,
    },
    DoubleDouble {
        high: 0.985_277_642_388_941_2,
        low: 2.315_563_702_790_020_7e-17,
    },
    DoubleDouble {
        high: 0.989_176_509_964_781,
        low: -4.098_730_993_704_711e-17,
    },
    DoubleDouble {
        high: 0.992_479_534_598_71,
        low: 3.109_305_509_542_890_6e-17,
    },
    DoubleDouble {
        high: 0.995_184_726_672_196_9,
        low: -4.248_691_367_830_441e-17,
    },
    DoubleDouble {
        high: 0.997_290_456_678_690_2,
        low: 9.164_769_537_110_173e-18,
    },
    DoubleDouble {
        high: 0.998_795_456_205_172_4,
        low: -1.229_169_333_707_546_5e-17,
    },
    DoubleDouble {
        high: 0.999_698_818_696_204_2,
        low: -2.985_148_640_379_975e-17,
    },
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
];

/// Taylor coefficients of `(cos(πd/128) − 1)/d² = C1 + d²(C2 + d²·C3)` in the grid
/// unit `d = 128·a − round(128·a) ∈ [−½, ½]` (`Cₖ = (−1)ᵏ(π/128)^{2k}/(2k)!`); the
/// leading `C1` is double-double, the rest `f64`.  Residual angle `|πd/128| ≤
/// π/256`, so the dropped `d⁸` term is ≈2⁻⁶⁶.  See [`abs_sinpi_dd_lean`].
const SINPI_C1: DoubleDouble = DoubleDouble {
    high: -0.000_301_196_423_373_088_3,
    low: -1.912_016_451_641_757_6e-20,
};
const SINPI_C2: f64 = 1.511_988_090_879_011_3e-8;
const SINPI_C3: f64 = -3.036_036_034_369_748e-13;

/// Taylor coefficients of `sin(πd/128)/d = S0 + d²(S1 + d²(S2 + d²·S3))`
/// (`Sₖ = (−1)ᵏ(π/128)^{2k+1}/(2k+1)!`); `S0`, `S1` double-double, the rest `f64`.
/// See [`SINPI_C1`].
const SINPI_S0: DoubleDouble = DoubleDouble {
    high: 0.024_543_692_606_170_26,
    low: 9.567_553_118_338_697e-19,
};
const SINPI_S1: DoubleDouble = DoubleDouble {
    high: -2.464_157_476_448_998_6e-6,
    low: 1.080_781_117_715_332_4e-22,
};
const SINPI_S2: f64 = 7.421_954_185_344_935e-11;
const SINPI_S3: f64 = -1.064_507_645_268_961e-15;

/// `sin(πx)` as a double-double for `|x| < 2⁵²`, where `x − q/2` is exact — the
/// accurate ≈2⁻¹²² kernel for the `lgamma` middle Ziv tier ([`abs_sinpi_dd`]).
///
/// Reduces `x = q/2 + r`, `r ∈ [−¼, ¼]`, and selects `±sin(πr)`/`±cos(πr)` by
/// `q mod 4`, with `πr ∈ [−π/4, π/4]` carried as a double-double into the full
/// double-double [`sin_kernel`]/[`cos_kernel`] (the middle tier needs their
/// ≈2⁻¹²² for its ≈2⁻⁹³ gate; the reflection *fast* leg takes the leaner
/// table-driven [`abs_sinpi_dd_lean`] instead).
#[inline]
fn sinpi_dd(x: f64) -> DoubleDouble {
    let q = (2.0 * x).round_ties_even();
    let theta = PI_DD * (x - q * 0.5);
    // SAFETY: `|x| < 2⁵²`, so `|q| < 2⁵³` fits an `i64`.
    match unsafe { q.to_int_unchecked::<i64>() } & 3 {
        0 => sin_kernel(theta),
        1 => cos_kernel(theta),
        2 => neg(sin_kernel(theta)),
        _ => neg(cos_kernel(theta)),
    }
}

/// `|sin(πx)|` as a double-double for `|x| < 2⁵²`, accurate ≈2⁻¹²² (see
/// [`sinpi_dd`]) — for the `lgamma` middle Ziv tier.
///
/// The lgamma reflection needs `ln|sin(πz)|` accurate even as `z` nears an
/// integer; there `|sin(πz)| ≈ π·|r|` with `r = z − round(z)` exact, so the
/// kernel's leading term keeps full relative accuracy.
#[inline]
pub(super) fn abs_sinpi_dd(x: f64) -> DoubleDouble {
    let v = sinpi_dd(x);
    if v.high < 0.0 { neg(v) } else { v }
}

/// `|sin(πx)|` as a double-double for `|x| < 2⁵²`, the lean table-driven kernel
/// (≈2⁻⁶⁶) — for the `lgamma` reflection *fast* leg, whose ≈2⁻⁶²–2⁻⁶⁶ gate has
/// ample room for it (the middle tier still uses the accurate [`abs_sinpi_dd`]).
///
/// Mirrors CORE-MATH's `as_sinpipid`.  `|sin(πx)| = sin(π·a)` with the period-1
/// even reduction `a = |x − round(x)| ∈ [0, ½]`; then `a = (k + d)/128` against the
/// [`SINPI_TABLE`] grid (`k = round(128·a)`, `d ∈ [−½, ½]`), and angle addition
///
/// `sin(π(k+d)/128) = sin(πk/128)·cos(πd/128) + cos(πk/128)·sin(πd/128)`
///
/// folds the tiny residual angle `πd/128 ∈ [−π/256, π/256]` through the short
/// [`SINPI_S0`]/[`SINPI_C1`] polynomials — far cheaper than a full-octant kernel.
/// Factoring `d` back out last keeps the leading `sin(π·a) ≈ π·a` exact as `a → 0`
/// (the near-integer case the gate cares about).  The result is non-negative
/// (`a ∈ [0, ½] ⇒ π·a ∈ [0, π/2]`), so no sign fixup.
#[inline]
pub(super) fn abs_sinpi_dd_lean(x: f64) -> DoubleDouble {
    let a = (x - x.round_ties_even()).abs();
    let s = a * 128.0;
    let kf = s.round_ties_even();
    let d = s - kf;
    // SAFETY: a ∈ [0, ½] ⇒ s ∈ [0, 64] ⇒ k ∈ 0..=64.
    let k = unsafe { kf.to_int_unchecked::<usize>() };
    let sg = SINPI_TABLE[k]; // sin(πk/128)
    let cg = SINPI_TABLE[64 - k]; // cos(πk/128) = sin(π(64−k)/128)

    let d2 = d * d;
    // sin(πd/128)/d = S0 + d²(S1 + d²(S2 + d²·S3))  (leading word double-double)
    let sin_over_d = SINPI_S0.add_ordered(DoubleDouble {
        high: d2 * crate::poly(d2, &[SINPI_S1.high, SINPI_S2, SINPI_S3]),
        low: 0.0,
    });
    // (cos(πd/128) − 1)/d² = C1 + d²(C2 + d²·C3)
    let cosm1_over_d2 = SINPI_C1.add_ordered(DoubleDouble {
        high: d2 * crate::poly(d2, &[SINPI_C2, SINPI_C3]),
        low: 0.0,
    });
    // sin(π·a) = sg + d·(cg·[sin θ/d] + sg·d·[(cos θ − 1)/d²]),  θ = πd/128.
    let bracket = cg * sin_over_d + sg * (cosm1_over_d2 * d);
    sg + bracket * d
}

/// sin(πi/64), i = 0..=32, as (short-high, low) — CORE-MATH sinpi `Sn`; the ≤25-bit highs keep the cross products below exact.
const SINCOSN_SN: [DoubleDouble; 33] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.049_067_676_067_352_295,
        low: -1.739_934_280_666_92e-09,
    },
    DoubleDouble {
        high: 0.098_017_141_222_953_8,
        low: -8.933_931_943_925_232e-10,
    },
    DoubleDouble {
        high: 0.146_730_467_677_116_4,
        low: 6.778_245_357_615_882e-09,
    },
    DoubleDouble {
        high: 0.195_090_323_686_599_73,
        low: -1.670_471_463_597_027_6e-09,
    },
    DoubleDouble {
        high: 0.242_980_182_170_867_92,
        low: -2.267_604_029_973_601e-09,
    },
    DoubleDouble {
        high: 0.290_284_678_339_958_2,
        low: -1.085_495_823_281_776_4e-09,
    },
    DoubleDouble {
        high: 0.336_889_848_113_06,
        low: 5.279_160_053_130_66e-09,
    },
    DoubleDouble {
        high: 0.382_683_426_141_738_9,
        low: 6.223_350_880_126_897e-09,
    },
    DoubleDouble {
        high: 0.427_555_099_129_676_8,
        low: -5.699_394_724_526_69e-09,
    },
    DoubleDouble {
        high: 0.471_396_744_251_251_2,
        low: -7.425_253_572_146_738e-09,
    },
    DoubleDouble {
        high: 0.514_102_742_075_920_1,
        low: 2.117_301_621_613_225e-09,
    },
    DoubleDouble {
        high: 0.555_570_229_887_962_3,
        low: 3.131_639_883_434_237_2e-09,
    },
    DoubleDouble {
        high: 0.595_699_310_302_734_4,
        low: -5.810_301_031_532_963e-09,
    },
    DoubleDouble {
        high: 0.634_393_289_685_249_3,
        low: -5.521_603_830_398_11e-09,
    },
    DoubleDouble {
        high: 0.671_558_961_272_239_7,
        low: -6.425_221_284_433_217e-09,
    },
    DoubleDouble {
        high: 0.707_106_783_986_091_6,
        low: -2.799_544_089_368_687e-09,
    },
    DoubleDouble {
        high: 0.740_951_120_853_424_1,
        low: 4.501_535_018_909_992e-09,
    },
    DoubleDouble {
        high: 0.773_010_447_621_345_5,
        low: 5.741_391_440_791_375e-09,
    },
    DoubleDouble {
        high: 0.803_207_531_571_388_2,
        low: -9.074_333_482_222_974e-11,
    },
    DoubleDouble {
        high: 0.831_469_610_333_442_7,
        low: 1.969_102_549_090_507e-09,
    },
    DoubleDouble {
        high: 0.857_728_615_403_175_4,
        low: -5.402_903_284_101_636e-09,
    },
    DoubleDouble {
        high: 0.881_921_261_548_996,
        low: 2.799_359_058_033_069_2e-09,
    },
    DoubleDouble {
        high: 0.903_989_300_131_797_8,
        low: -7.008_354_458_941_143_6e-09,
    },
    DoubleDouble {
        high: 0.923_879_534_006_118_8,
        low: -1.494_832_018_285_879_3e-09,
    },
    DoubleDouble {
        high: 0.941_544_070_839_881_9,
        low: -5.656_861_118_560_147e-09,
    },
    DoubleDouble {
        high: 0.956_940_338_015_556_3,
        low: -2.283_347_470_513_420_7e-09,
    },
    DoubleDouble {
        high: 0.970_031_246_542_930_6,
        low: 6.651_613_389_576_641e-09,
    },
    DoubleDouble {
        high: 0.980_785_280_466_079_7,
        low: -6.284_926_278_788_026e-11,
    },
    DoubleDouble {
        high: 0.989_176_511_764_526_4,
        low: -1.799_745_393_735_826_3e-09,
    },
    DoubleDouble {
        high: 0.995_184_719_562_530_5,
        low: 7.109_666_368_666_712e-09,
    },
    DoubleDouble {
        high: 0.998_795_449_733_734_1,
        low: 6.471_438_261_855_397e-09,
    },
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
];
/// sin(πj/2048), j = 0..=31, short-high — CORE-MATH sinpi `Sm`.
const SINCOSN_SM: [DoubleDouble; 32] = [
    DoubleDouble {
        high: 0.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.001_533_985_137_939_453_1,
        low: -4.951_654_687_512_696e-09,
    },
    DoubleDouble {
        high: 0.003_067_955_374_717_712_4,
        low: 1.388_248_263_867_801_6e-09,
    },
    DoubleDouble {
        high: 0.004_601_925_611_495_972,
        low: 5.089_525_990_852_142e-10,
    },
    DoubleDouble {
        high: 0.006_135_880_947_113_037,
        low: 3.702_041_438_250_265_2e-09,
    },
    DoubleDouble {
        high: 0.007_669_821_381_568_909,
        low: 7.357_962_188_783_592e-09,
    },
    DoubleDouble {
        high: 0.009_203_761_816_024_78,
        low: -7.033_964_960_958_335e-09,
    },
    DoubleDouble {
        high: 0.010_737_657_546_997_07,
        low: 1.620_267_421_101_041_4e-09,
    },
    DoubleDouble {
        high: 0.012_271_538_376_808_167,
        low: -9.108_824_042_449_799e-11,
    },
    DoubleDouble {
        high: 0.013_805_389_404_296_875,
        low: -8.762_364_842_765_772e-10,
    },
    DoubleDouble {
        high: 0.015_339_210_629_463_196,
        low: -4.344_475_094_756_629_4e-09,
    },
    DoubleDouble {
        high: 0.016_872_987_151_145_935,
        low: 7.961_357_789_957_462e-10,
    },
    DoubleDouble {
        high: 0.018_406_733_870_506_287,
        low: -3.964_701_465_693_727e-09,
    },
    DoubleDouble {
        high: 0.019_940_435_886_383_057,
        low: -7.334_868_616_996_781e-09,
    },
    DoubleDouble {
        high: 0.021_474_078_297_615_05,
        low: 1.977_854_456_148_843_7e-09,
    },
    DoubleDouble {
        high: 0.023_007_676_005_363_464,
        low: 5.463_475_908_531_014e-09,
    },
    DoubleDouble {
        high: 0.024_541_229_009_628_296,
        low: -4.867_160_078_667_03e-10,
    },
    DoubleDouble {
        high: 0.026_074_722_409_248_352,
        low: -4.580_144_452_217_713_4e-09,
    },
    DoubleDouble {
        high: 0.027_608_141_303_062_44,
        low: 4.475_903_302_647_511e-09,
    },
    DoubleDouble {
        high: 0.029_141_515_493_392_944,
        low: -6.729_199_220_273_736e-09,
    },
    DoubleDouble {
        high: 0.030_674_800_276_756_287,
        low: 2.899_880_339_312_927_2e-09,
    },
    DoubleDouble {
        high: 0.032_208_025_455_474_854,
        low: -4.717_026_914_923_44e-11,
    },
    DoubleDouble {
        high: 0.033_741_176_128_387_45,
        low: -4.277_009_866_338_159e-09,
    },
    DoubleDouble {
        high: 0.035_274_237_394_332_886,
        low: 1.503_881_064_953_040_8e-09,
    },
    DoubleDouble {
        high: 0.036_807_224_154_472_35,
        low: -1.213_113_518_749_886e-09,
    },
    DoubleDouble {
        high: 0.038_340_121_507_644_65,
        low: -1.134_091_957_521_976_4e-09,
    },
    DoubleDouble {
        high: 0.039_872_929_453_849_79,
        low: -1.866_109_981_351_89e-09,
    },
    DoubleDouble {
        high: 0.041_405_647_993_087_77,
        low: -7.016_011_028_543_694e-09,
    },
    DoubleDouble {
        high: 0.042_938_262_224_197_39,
        low: -5.289_256_564_618_188e-09,
    },
    DoubleDouble {
        high: 0.044_470_772_147_178_65,
        low: -2.922_399_832_767_137_4e-10,
    },
    DoubleDouble {
        high: 0.046_003_177_762_031_555,
        low: 4.368_883_073_638_521e-09,
    },
    DoubleDouble {
        high: 0.047_535_479_068_756_104,
        low: 5.088_203_201_777_006_5e-09,
    },
];
/// cos(πj/2048), j = 0..=31, short-high — CORE-MATH sinpi `Cm`.
const SINCOSN_CM: [DoubleDouble; 32] = [
    DoubleDouble {
        high: 1.0,
        low: 0.0,
    },
    DoubleDouble {
        high: 0.999_998_822_808_265_7,
        low: 6.434_362_238_938_694e-10,
    },
    DoubleDouble {
        high: 0.999_995_291_233_062_7,
        low: 2.576_513_427_370_955_3e-09,
    },
    DoubleDouble {
        high: 0.999_989_405_274_391_2,
        low: 5.807_537_199_303_066e-09,
    },
    DoubleDouble {
        high: 0.999_981_179_833_412_2,
        low: -4.550_811_027_753_166e-09,
    },
    DoubleDouble {
        high: 0.999_970_585_107_803_3,
        low: 1.323_170_765_261_301_7e-09,
    },
    DoubleDouble {
        high: 0.999_957_650_899_887_1,
        low: -6.347_923_218_627_816_6e-09,
    },
    DoubleDouble {
        high: 0.999_942_347_407_341,
        low: 2.268_682_899_721_971e-09,
    },
    DoubleDouble {
        high: 0.999_924_704_432_487_5,
        low: -2.593_342_946_871_322_3e-09,
    },
    DoubleDouble {
        high: 0.999_904_707_074_165_3,
        low: -5.991_312_499_669_271e-09,
    },
    DoubleDouble {
        high: 0.999_882_340_431_213_4,
        low: 7.022_999_146_726_8e-09,
    },
    DoubleDouble {
        high: 0.999_857_634_305_954,
        low: 6.699_869_852_087_387e-09,
    },
    DoubleDouble {
        high: 0.999_830_588_698_387_1,
        low: -6.902_563_723_980_372e-09,
    },
    DoubleDouble {
        high: 0.999_801_173_806_190_5,
        low: -3.918_306_258_833_877e-09,
    },
    DoubleDouble {
        high: 0.999_769_404_530_525_2,
        low: 8.206_901_141_380_857e-10,
    },
    DoubleDouble {
        high: 0.999_735_280_871_391_3,
        low: 7.389_170_418_050_369_5e-09,
    },
    DoubleDouble {
        high: 0.999_698_817_729_95,
        low: 9.662_542_689_438_906e-10,
    },
    DoubleDouble {
        high: 0.999_660_000_205_04,
        low: -3.461_080_731_579_902_5e-09,
    },
    DoubleDouble {
        high: 0.999_618_828_296_661_4,
        low: -5.801_482_779_836_294e-09,
    },
    DoubleDouble {
        high: 0.999_575_302_004_814_1,
        low: -5.958_064_891_169_264e-09,
    },
    DoubleDouble {
        high: 0.999_529_421_329_498_3,
        low: -3.828_405_127_935_921e-09,
    },
    DoubleDouble {
        high: 0.999_481_186_270_713_8,
        low: 6.954_531_594_847_833e-10,
    },
    DoubleDouble {
        high: 0.999_430_611_729_621_9,
        low: -7.174_160_115_188_023e-09,
    },
    DoubleDouble {
        high: 0.999_377_667_903_900_1,
        low: 2.484_102_734_197_949e-09,
    },
    DoubleDouble {
        high: 0.999_322_384_595_871,
        low: -7.521_470_783_466_49e-12,
    },
    DoubleDouble {
        high: 0.999_264_746_904_373_2,
        low: 3.822_212_906_968_520_6e-10,
    },
    DoubleDouble {
        high: 0.999_204_754_829_406_7,
        low: 3.788_957_157_211_7e-09,
    },
    DoubleDouble {
        high: 0.999_142_423_272_132_9,
        low: -4.547_315_934_063_858e-09,
    },
    DoubleDouble {
        high: 0.999_077_722_430_229_2,
        low: 5.322_416_195_877_063e-09,
    },
    DoubleDouble {
        high: 0.999_010_682_106_018_1,
        low: 3.748_055_265_759_627e-09,
    },
    DoubleDouble {
        high: 0.998_941_287_398_338_3,
        low: 5.788_518_532_762_837e-09,
    },
    DoubleDouble {
        high: 0.998_869_553_208_351_1,
        low: -3.294_067_547_934_001e-09,
    },
];

/// `sin(θ)/z` and `(cos(θ) − 1)/z²` residual Taylor coefficients in the
/// fixed-point scale `z = residual·2⁶³` of the grid unit (CORE-MATH sinpi's
/// `sn`/`cn`, verbatim): the reduction below keeps the residual as the low
/// bits of `x·2⁷⁵`, so the coefficients absorb the 2⁻⁶³ rescale.
const SINPI_ZS: [f64; 3] = [
    8.315_726_513_883_19e-23,
    -9.584_056_014_373_668e-68,
    3.313_749_950_895_967_4e-113,
];
const SINPI_ZC: [f64; 2] = [-3.457_565_372_684_991_5e-45, 1.992_459_659_126_081_7e-90];

/// Taylor coefficients of `(sin(πx) − πx)/x³` for the small band
/// `|x| ≤ 0x1.2p−5` (CORE-MATH sinpi's `c`, verbatim).
const SINPI_SMALL_C: [f64; 4] = [
    -5.167_712_780_049_968_5,
    2.550_164_039_866_476,
    -0.599_264_504_695_894_2,
    0.082_123_115_663_778_14,
];

/// Relative Ziv gate for the middle [`sinpi_dd`] tier: the double-double π
/// truncates at ≈2⁻¹⁰⁹ and the kernel/multiply roundings sit near 2⁻¹⁰⁴, so
/// `2⁻¹⁰¹` bounds the tier with margin (certified by
/// `ziv_soundness::sinpi_dd_tier_is_sound`); the rare survivors take the
/// 128-bit `Dint` kernels.
const SINPI_DD_EPS: f64 = crate::exp2i(-101);

/// `(sin, cos)` at the grid angle `s·π/2048` as loose double-doubles — a port
/// of CORE-MATH sinpi's `sincosn` two-level table.  `s` is taken modulo 4096
/// through two's-complement bit logic (works for negative `s` unchanged): the
/// low ten bits index within a quadrant (reflected in odd quadrants), split
/// into the π/64 level ([`SINCOSN_SN`], cosine by complement) and the π/2048
/// level ([`SINCOSN_SM`]/[`SINCOSN_CM`]); the angle-addition cross products of
/// the ≤25-bit table highs are exact, so one Fast2Sum per component
/// renormalizes the pair.  Bits 11/12 of `s` supply the half-turn signs.
#[inline]
pub fn sincosn(s: i64) -> (DoubleDouble, DoubleDouble) {
    let j0 = s & 0x3ff;
    let it = -((s >> 10) & 1); // odd quadrant: reflect j → 1024 − j
    let j = (!it & j0) - (it << 10) - (it & j0);
    let is = (j >> 5) as usize;
    let jm = (j & 0x1f) as usize;
    // Branchless sign bits: the quadrant bits flip the components by XOR on
    // the sign bit (a 50/50 data-dependent branch would mispredict on random
    // input).
    let ssgn = (((s >> 11) & 1) as u64) << 63;
    let csgn = ((((s + 1024) >> 11) & 1) as u64) << 63;

    // SAFETY: `j ∈ [0, 1024]` by the reflection above, so `is ∈ [0, 32]` and
    // `jm ∈ [0, 31]`; the compiler cannot see the range, and the elided bounds
    // checks are worth ≈1 ns on the hot path.
    let (sb, cb, sm, cm) = unsafe {
        (
            *SINCOSN_SN.get_unchecked(is),      // sin at is·π/64
            *SINCOSN_SN.get_unchecked(32 - is), // cos at is·π/64, by complement
            *SINCOSN_SM.get_unchecked(jm),      // sin at jm·π/2048
            *SINCOSN_CM.get_unchecked(jm),      // cos at jm·π/2048
        )
    };

    // Angle addition with exact high×high products (≤25-bit factors).
    let sbf = sb.high + sb.low;
    let cbf = cb.high + cb.low;
    // Not FMA sites: the ≤25-bit high×high products are exact, and the error
    // budget assumes each term rounds on its own.
    #[allow(clippy::suboptimal_flops)]
    let ch = cb.high * cm.high - sb.high * sm.high;
    #[allow(clippy::suboptimal_flops)]
    let cl = cm.high * cb.low - sm.high * sb.low + (cbf * cm.low - sbf * sm.low);
    #[allow(clippy::suboptimal_flops)]
    let sh = sb.high * cm.high + cb.high * sm.high;
    #[allow(clippy::suboptimal_flops)]
    let sl = sm.high * cb.low + cm.high * sb.low + (cbf * sm.low + sbf * cm.low);

    let (s2, c2) = (fast_sum(sh, sl), fast_sum(ch, cl));
    (
        DoubleDouble {
            high: f64::from_bits(s2.high.to_bits() ^ ssgn),
            low: f64::from_bits(s2.low.to_bits() ^ ssgn),
        },
        DoubleDouble {
            high: f64::from_bits(c2.high.to_bits() ^ csgn),
            low: f64::from_bits(c2.low.to_bits() ^ csgn),
        },
    )
}

/// Ziv gate for [`sinpi`]'s grid fast leg, an *absolute* bound on the
/// correction `r` (everything below the leading table word): the exact `u`
/// keeps the polynomial terms clean, so the slip is a handful of f64
/// roundings at `r`'s ≈2⁻⁶³ ulp scale.  Certified with ≥2× margin by
/// `ziv_soundness::sinpi_fast_leg_is_sound`; near-zero table words (inputs
/// within ≈2⁻⁹ of an integer) never certify and take the `Dint` tier.
const SINPIN_ERR: f64 = 5.5e-19;

/// Sine of π·x
///
/// Follows C23's special-value contract: `sinpi(±0) = ±0`, `sinpi(n) =
/// copysign(0, x)` for every integer `n` (parity-free), `sinpi(±(2k + ½)) =
/// ±1` and `sinpi(±(2k + 1 + ½)) = ∓1` exactly, and ±∞/NaN → NaN.
///
/// Mirrors CORE-MATH's `cr_sinpi` fast path: an integer reduction of the
/// signed mantissa puts the grid index (1/2048 half-turns) and the exact
/// residual bits in two shifts, [`sincosn`]'s two's-complement bit logic
/// folds quadrants and signs, and short plain-f64 residual polynomials feed
/// the absolute Ziv gate.  The small band `|x| ≤ 0x1.2p−5` keeps relative
/// accuracy through a double-double `π·x` with a cubic correction.
/// Straddles fall to the relative-gated [`sinpi_dd`] middle tier, and the
/// rare survivors to the 128-bit `Dint` sin/cos kernels (≈2⁻¹²⁵) — CORE-MATH
/// needs an exception database at this depth; the `Dint` tier does not.
#[must_use]
#[inline]
pub fn sinpi(x: f64) -> f64 {
    let ix = x.to_bits();
    let e = ((ix >> 52) & 0x7ff) as i64;

    // |x| ≥ 2⁴¹ (every value is a multiple of 1/2048), ±∞, NaN.
    if e >= 1064 {
        if e == 0x7ff {
            return if ix << 12 == 0 { f64::NAN } else { x + x };
        }
        if e > 1074 {
            return f64::copysign(0.0, x); // |x| ≥ 2⁵²: all integers
        }
        let sgn = (ix as i64) >> 63;
        let m = ((((ix & (u64::MAX >> 12)) | 1 << 52) as i64) ^ sgn) - sgn;
        // x·2048 is an exact integer here; two's complement keeps the sign.
        let iq = (m as u64).wrapping_shl((e - 1064) as u32);
        if iq & 2047 == 0 {
            return f64::copysign(0.0, x); // integer x
        }
        let (sg, _) = sincosn(iq as i64);
        return sg.high + sg.low; // exact grid point: the table is the answer
    }

    let ax = ix & (u64::MAX >> 1);
    // Small band |x| ≤ 0x1.2p−5: relative accuracy through double-double π·x.
    if ax <= 0x3fa2_0000_0000_0000 {
        if x == 0.0 {
            return x; // ±0 keeps its sign
        }
        // |x| < 2⁻⁵⁴: sin(πx) rounds as the product π·x.  Below 2⁻⁹⁷⁰ the
        // product is formed at 2¹⁰⁶ scale and folded down with one FMA so the
        // subnormal rounding happens exactly once (CORE-MATH's fold).
        if ax < 0x3c90_0000_0000_0000 {
            if ax < (53 << 52) {
                let t = x * crate::exp2i(106);
                let zh = PI_DD.high * t;
                #[allow(clippy::suboptimal_flops)] // CORE-MATH's exact op sequence
                let zl = crate::fma(PI_DD.high, t, -zh) + PI_DD.low * t;
                let rs = (zh + zl) * crate::exp2i(-106);
                let rt = rs * crate::exp2i(106);
                return crate::fma((zh - rt) + zl, crate::exp2i(-106), rs);
            }
            let zh = PI_DD.high * x;
            #[allow(clippy::suboptimal_flops)] // CORE-MATH's exact op sequence
            let zl = crate::fma(PI_DD.high, x, -zh) + PI_DD.low * x;
            return zh + zl;
        }
        // π·x as a double-double plus the odd Taylor correction.  The gate is
        // CORE-MATH's width with the x²-term half again wider — the measured
        // slip reaches 0.58× the original window, short of the 2× margin
        // `ziv_soundness::sinpi_small_band_is_sound` certifies.
        let zh = PI_DD.high * x;
        #[allow(clippy::suboptimal_flops)] // CORE-MATH's exact op sequence
        let zl = crate::fma(PI_DD.high, x, -zh) + PI_DD.low * x;
        let x2 = x * x;
        let x3 = x2 * x;
        let x4 = x2 * x2;
        let eps = x * crate::fast_mul_add(x2, 1.5 * crate::exp2i(-47), crate::exp2i(-102));
        #[allow(clippy::suboptimal_flops)] // CORE-MATH's certified splitting
        let zl = zl
            + x3 * ((SINPI_SMALL_C[0] + x2 * SINPI_SMALL_C[1])
                + x4 * (SINPI_SMALL_C[2] + x2 * SINPI_SMALL_C[3]));
        let lb = (zl - eps) + zh;
        let ub = (zl + eps) + zh;
        if lb == ub {
            return lb;
        }
        return sinpi_accurate(x);
    }

    // Main band 0x1.2p−5 < |x| < 2⁴¹ (e ∈ [1018, 1063]): integer reduction.
    let m0 = (ix & (u64::MAX >> 12)) | 1 << 52;
    let si = e - 1011;
    if si >= 0 && m0.wrapping_shl((si + 1) as u32) == 0 {
        // x is an integer or half-integer (si ≥ 7 in this band).
        if m0.wrapping_shl(si as u32) == 0 {
            return f64::copysign(0.0, x);
        }
        // |x| mod 2 = ½ → ±1; = 3/2 → ∓1.
        let t = m0.wrapping_shl((si - 1) as u32) >> 63;
        return if t == 0 {
            f64::copysign(1.0, x)
        } else {
            -f64::copysign(1.0, x)
        };
    }

    let sgn = (ix as i64) >> 63;
    let m = ((m0 as i64) ^ sgn) - sgn;
    let s = 1063 - e; // 0..=45
    let iq = ((m >> s) + 1) >> 1; // round(x·2048) in 1/2048 half-turns
    // The residual keeps all its bits: the shifted-out top is the integer
    // part already in `iq`.  The i64 → f64 rounding of the lowest bits is
    // inside the gate's budget.
    let k = (m as u64).wrapping_shl((e - 1000) as u32) as i64;
    let z = k as f64;
    let z2 = z * z;
    let fs = crate::fast_mul_add(
        z2,
        crate::fast_mul_add(z2, SINPI_ZS[2], SINPI_ZS[1]),
        SINPI_ZS[0],
    );
    let fc = crate::fast_mul_add(z2, SINPI_ZC[1], SINPI_ZC[0]);
    let (sg, cg) = sincosn(iq);
    #[allow(clippy::suboptimal_flops)] // the remaining splits are the certified budget
    let r = crate::fast_mul_add(cg.high, z * fs, sg.low + sg.high * (z2 * fc));
    let lb = (r - SINPIN_ERR) + sg.high;
    let ub = (r + SINPIN_ERR) + sg.high;
    if lb == ub {
        return lb;
    }

    // Middle tier: the ≈2⁻¹⁰⁴ double-double kernel, relative-gated.
    let v = sinpi_dd(x);
    let eps = v.high.abs() * SINPI_DD_EPS;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    if lo == hi {
        return lo;
    }
    sinpi_accurate(x)
}

/// Final [`sinpi`] tier: `2x − q` is exact (Sterbenz), so `π·(x − q/2)`
/// reaches the 128-bit sin/cos kernels at ≈2⁻¹²⁵ relative — the double-double
/// π (≈2⁻¹⁰⁹) cannot split the corpus' hardest ties.  The quadrant selection
/// carries the sign; the result is normal (|x − round(x)| ≥ 2⁻⁵³ here, so the
/// magnitude is ≥ 2⁻⁵¹), which `to_f64` requires.
#[cold]
fn sinpi_accurate(x: f64) -> f64 {
    let q = (2.0 * x).round_ties_even();
    #[allow(clippy::suboptimal_flops)] // 2x is exact; the subtraction is Sterbenz
    let theta = Dint::from_f64(2.0 * x - q).mul(&PIO2_DINT); // π(x − q/2) ∈ [−π/4, π/4]
    // SAFETY: |q| ≤ 2⁵³ fits an `i64`.
    let w = match unsafe { q.to_int_unchecked::<i64>() } & 3 {
        0 => sin_dint(&theta),
        1 => cos_dint(&theta),
        2 => neg_dint(sin_dint(&theta)),
        _ => neg_dint(cos_dint(&theta)),
    };
    w.to_f64()
}

/// Taylor coefficients of `(cos(πx) − 1)/x²` for the small band
/// `|x| ≤ 2⁻¹²` (CORE-MATH cospi's `c`, verbatim).
const COSPI_SMALL_C: [f64; 4] = [
    -4.934_802_200_544_677,
    4.058_712_126_397_995,
    -1.335_262_715_026_094_7,
    0.235_267_632_957_854_3,
];

/// Cosine of π·x
///
/// Follows C23's special-value contract: `cospi(±0) = 1`, `cospi(k + ½) = +0`
/// for every half-integer (sign-free), integers give ±1 by parity, and
/// ±∞/NaN → NaN.  The structure mirrors [`sinpi`] — the quarter-turn shift
/// rides the grid index (`+2048` before halving), the mantissa stays unsigned
/// (cosine is even), and the cross term flips sign — with the same
/// [`sincosn`] table, residual polynomials, and tier ladder.  The fast gate is
/// CORE-MATH's residual-proportional `z·2⁻¹²³` plus an absolute 2⁻⁷⁷ floor
/// for the table pair's own ≈2⁻⁷⁹ accuracy near grid points — without the
/// floor the slope window vanishes there while the table error does not
/// (certified at ≥2× margin by `ziv_soundness::cospi_fast_leg_is_sound`).
#[must_use]
#[inline]
pub fn cospi(x: f64) -> f64 {
    let ix = x.to_bits();
    let ax = ix & (u64::MAX >> 1);
    let e = (ax >> 52) as i64;

    // |x| ≥ 2⁴¹ (every value is a multiple of 1/2048), ±∞, NaN.
    if e >= 1064 {
        if e == 0x7ff {
            return if ix << 12 == 0 { f64::NAN } else { x + x };
        }
        if e > 1075 {
            return 1.0; // |x| ≥ 2⁵³: all even integers
        }
        let m = (ix & (u64::MAX >> 12)) | 1 << 52;
        // |x|·2048 + a quarter turn, exact; evenness needs no sign fold.
        let iq = m.wrapping_shl((e - 1064) as u32).wrapping_add(1024);
        if iq & 2047 == 0 {
            return 0.0; // half-integer x: +0 always
        }
        let (sg, _) = sincosn(iq as i64);
        return sg.high + sg.low; // exact grid point: the table is the answer
    }

    // Small band |x| ≤ 2⁻¹²: even Taylor around 1.
    if ax <= 0x3f30_0000_0000_0000 {
        // cos(πx) rounds to 1 for (πx)²/2 ≤ 2⁻⁵⁴ (the expression keeps
        // CORE-MATH's shape; round-to-nearest folds it to 1.0).
        if ax <= 0x3e2c_cf64_29be_6621 {
            return 1.0 - crate::exp2i(-55);
        }
        let x2 = x * x;
        let x4 = x2 * x2;
        let eps = x2 * 8.659_739_592_076_221e-15;
        #[allow(clippy::suboptimal_flops)] // CORE-MATH's certified splitting
        let p = x2
            * ((COSPI_SMALL_C[0] + x2 * COSPI_SMALL_C[1])
                + x4 * (COSPI_SMALL_C[2] + x2 * COSPI_SMALL_C[3]));
        let lb = (p - eps) + 1.0;
        let ub = (p + eps) + 1.0;
        if lb == ub {
            return lb;
        }
        return cospi_accurate(x);
    }

    // Main band 2⁻¹² < |x| < 2⁴¹ (e ∈ [1011, 1063]): integer reduction.
    let m = (ix & (u64::MAX >> 12)) | 1 << 52;
    let si = e - 1011;
    if si >= 0 && m.wrapping_shl(si as u32) == 1 << 63 {
        return 0.0; // half-integer x: +0 always
    }

    let s = 1063 - e; // 0..=52
    let iq = ((((m >> s).wrapping_add(2048)) & 8191).wrapping_add(1)) >> 1;
    let k = m.wrapping_shl((e - 1000) as u32) as i64;
    let z = k as f64;
    let z2 = z * z;
    let fs = crate::fast_mul_add(
        z2,
        crate::fast_mul_add(z2, SINPI_ZS[2], SINPI_ZS[1]),
        SINPI_ZS[0],
    );
    let fc = crate::fast_mul_add(z2, SINPI_ZC[1], SINPI_ZC[0]);
    let (sg, cg) = sincosn(iq as i64);
    let er = crate::fast_mul_add(z.abs(), crate::exp2i(-123), crate::exp2i(-77));
    #[allow(clippy::suboptimal_flops)] // the remaining splits are the certified budget
    let r = crate::fast_mul_add(cg.high, z * fs, sg.low + sg.high * (z2 * fc));
    let lb = (r - er) + sg.high;
    let ub = (r + er) + sg.high;
    if lb == ub {
        return lb;
    }

    // Middle tier: the ≈2⁻¹⁰⁴ double-double kernel, relative-gated.
    let v = cospi_dd(x);
    let eps = v.high.abs() * SINPI_DD_EPS;
    let lo = v.high + (v.low - eps);
    let hi = v.high + (v.low + eps);
    if lo == hi {
        return lo;
    }
    cospi_accurate(x)
}

/// `cos(πx)` as a double-double for `|x| < 2⁵²` — [`sinpi_dd`]'s quadrant
/// selection rotated a quarter turn.
#[inline]
fn cospi_dd(x: f64) -> DoubleDouble {
    let q = (2.0 * x).round_ties_even();
    let theta = PI_DD * (x - q * 0.5);
    // SAFETY: `|x| < 2⁵²`, so `|q| < 2⁵³` fits an `i64`.
    match unsafe { q.to_int_unchecked::<i64>() } & 3 {
        0 => cos_kernel(theta),
        1 => neg(sin_kernel(theta)),
        2 => neg(cos_kernel(theta)),
        _ => sin_kernel(theta),
    }
}

/// Final [`cospi`] tier — [`sinpi_accurate`] rotated a quarter turn.
#[cold]
fn cospi_accurate(x: f64) -> f64 {
    let q = (2.0 * x).round_ties_even();
    #[allow(clippy::suboptimal_flops)] // 2x is exact; the subtraction is Sterbenz
    let theta = Dint::from_f64(2.0 * x - q).mul(&PIO2_DINT); // π(x − q/2) ∈ [−π/4, π/4]
    // SAFETY: |q| ≤ 2⁵³ fits an `i64`.
    let w = match unsafe { q.to_int_unchecked::<i64>() } & 3 {
        0 => cos_dint(&theta),
        1 => neg_dint(sin_dint(&theta)),
        2 => neg_dint(cos_dint(&theta)),
        _ => sin_dint(&theta),
    };
    w.to_f64()
}

/// Sine
#[must_use]
#[inline]
pub fn sin(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    // |x| < 2⁻²⁷: sin(x) = x to within ½ ulp; preserves ±0.
    if x.abs() < SMALL {
        return x;
    }

    let (q, r) = rem_pio2(x.abs());

    // sin(|x|): even quadrants use sin(r), odd use cos(r); q&2 sets the sign.
    // Only the selected half is computed (vs. both for `sincos`).
    let need_cos = q & 1 != 0;
    let negate = q & 2 != 0;
    let signed = |v: DoubleDouble| if negate { neg(v) } else { v };

    let fast = signed(if need_cos {
        cos_kernel_fast(r)
    } else {
        sin_kernel_fast(r)
    });
    let magnitude = ziv(fast).unwrap_or_else(|| {
        // Accurate `Dint` path: re-reduce to a 128-bit `r` and round once.
        let (q, r) = payne_hanek_dint(x.abs());
        let v = if q & 1 != 0 {
            cos_dint(&r)
        } else {
            sin_dint(&r)
        };
        let v = if q & 2 != 0 { neg_dint(v) } else { v };
        v.to_f64()
    });

    if x.is_sign_negative() {
        -magnitude
    } else {
        magnitude
    }
}

/// Cosine
#[must_use]
#[inline]
pub fn cos(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    // |x| < 2⁻²⁷: cos(x) = 1 to within ½ ulp.
    if x.abs() < SMALL {
        return 1.0;
    }

    let (q, r) = rem_pio2(x.abs());

    // cos(|x|): even quadrants use cos(r), odd use sin(r); (q+1)&2 sets the sign.
    let need_sin = q & 1 != 0;
    let negate = q.wrapping_add(1) & 2 != 0;
    let signed = |v: DoubleDouble| if negate { neg(v) } else { v };

    let fast = signed(if need_sin {
        sin_kernel_fast(r)
    } else {
        cos_kernel_fast(r)
    });
    ziv(fast).unwrap_or_else(|| {
        // Accurate `Dint` path: re-reduce to a 128-bit `r` and round once.
        let (q, r) = payne_hanek_dint(x.abs());
        let v = if q & 1 != 0 {
            sin_dint(&r)
        } else {
            cos_dint(&r)
        };
        let v = if q.wrapping_add(1) & 2 != 0 {
            neg_dint(v)
        } else {
            v
        };
        v.to_f64()
    })
}

/// Simultaneous sine and cosine
#[must_use]
#[inline]
pub fn sincos(x: f64) -> (f64, f64) {
    if !x.is_finite() {
        return (f64::NAN, f64::NAN);
    }

    // |x| < 2⁻²⁷: (sin, cos) = (x, 1) to within ½ ulp; preserves ±0 in sin.
    if x.abs() < SMALL {
        return (x, 1.0);
    }

    let (q, r) = rem_pio2(x.abs());

    let (s, c) = sin_cos_kernel_fast(r);
    // Both components must pass the gate; otherwise recompute both accurately.
    let (sin, cos) = match (ziv(select_sin(q, s, c)), ziv(select_cos(q, s, c))) {
        (Some(sin), Some(cos)) => (sin, cos),
        _ => {
            // Accurate `Dint` path: re-reduce to a 128-bit `r` and round each once.
            let (q, r) = payne_hanek_dint(x.abs());
            let (s, c) = sin_cos_dint(&r);
            (
                select_sin_dint(q, s, c).to_f64(),
                select_cos_dint(q, s, c).to_f64(),
            )
        }
    };

    let sin = if x.is_sign_negative() { -sin } else { sin };
    (sin, cos)
}

/// Tangent
#[must_use]
#[inline]
pub fn tan(x: f64) -> f64 {
    if !x.is_finite() {
        return f64::NAN;
    }

    // |x| < 2⁻²⁷: tan(x) = x to within ½ ulp; preserves ±0.
    if x.abs() < SMALL {
        return x;
    }

    let (q, r) = rem_pio2(x.abs());

    // tan has period π, so tan(|x|) = tan(r) for even quadrants and −cot(r) =
    // −1/tan(r) for odd ones — one kernel, a reciprocal only half the time.
    let t = tan_kernel_fast(r);
    let fast = if q & 1 == 0 {
        t
    } else {
        // −1/t leanly: seed `y = −1/t.high` (the inner FMA's cancellation is
        // exact), fold `t.low` into the residual `e = 1 + y·t`, and take
        // `y·(1 + e)` — dropping `y·e²` ≈ 2⁻¹⁰⁴ relative, noise to the 2⁻⁵⁹
        // gate.  The full Newton `recip` (a double-double multiply, add, and
        // multiply on top of the divide) buys accuracy the gate cannot use.
        let y = -1.0 / t.high;
        let e = crate::fma(y, t.low, crate::fma(y, t.high, 1.0));
        DoubleDouble {
            high: y,
            low: y * e,
        }
    };
    let magnitude = ziv(fast).unwrap_or_else(|| {
        // Accurate `Dint` path: the sin/cos pair ratio in 128-bit fixed point.
        let (q, r) = payne_hanek_dint(x.abs());
        let (s, c) = sin_cos_dint(&r);
        let num = select_sin_dint(q, s, c);
        let den = select_cos_dint(q, s, c);
        num.mul(&recip_dint(&den)).to_f64()
    });

    if x.is_sign_negative() {
        -magnitude
    } else {
        magnitude
    }
}

/// The Fast2Sum-based folds of [`tan_kernel_fast`] need `|a| ≥ |b|`; prove the
/// orderings from coefficient-magnitude bounds at `v = w = (π/4)²`, the
/// octant's edge, with 2× margin (cf. the same-named module in `erf.rs`).
#[cfg(test)]
mod fold_ordering {
    use super::*;

    /// `sin_part_fast` / `cos_part_fast`: `1 ⊕ u·c₁ ⊕ u²·c₂ ⊕ u³·tail` with
    /// `u = r² ≤ (π/4)²`.
    #[test]
    fn sin_cos_leads() {
        let umax = core::f64::consts::FRAC_PI_4.powi(2) * 1.0001;
        let u2max = umax * umax;
        let u3max = umax.powi(3);
        let tail_mag = |tail: &[f64]| {
            tail.iter()
                .rev()
                .fold(0.0, |acc, c| crate::fast_mul_add(acc, umax, c.abs()))
        };

        for (c1, c2, tail) in [
            (
                NEG_FRAC_1_6.high.abs() + NEG_FRAC_1_6.low.abs(),
                FRAC_1_120.high + FRAC_1_120.low.abs(),
                &SIN_TAIL,
            ),
            (0.5, FRAC_1_24.high + FRAC_1_24.low.abs(), &COS_TAIL),
        ] {
            assert!(umax * c1 <= 0.5);
            let lead_min = 1.0 - umax * c1;
            assert!(u2max * c2 <= 0.5 * lead_min);
            let lead2_min = lead_min - u2max * c2;
            assert!(u3max * tail_mag(tail) <= 0.5 * lead2_min);
        }
    }

    /// The table-driven `abs_sinpi_dd_lean` folds the residual polynomials with
    /// `add_ordered` (`S0 ⊕ d²·(…)` and `C1 ⊕ d²·(…)`), which needs the leading
    /// coefficient to dominate the higher-order remainder.  `|d| ≤ ½`, so check
    /// the remainder stays under half the lead there.
    #[test]
    fn sinpi_table_leads() {
        let d2max = 0.25_f64; // (½)²
        let mag = |c: DoubleDouble| c.high.abs() + c.low.abs();
        let poly_mag = |c: &[f64]| {
            c.iter()
                .rev()
                .fold(0.0, |acc, c| crate::fast_mul_add(acc, d2max, c.abs()))
        };
        // sin: |S0| ≥ |d²·(S1 + d²(S2 + d²·S3))|
        assert!(d2max * poly_mag(&[SINPI_S1.high, SINPI_S2, SINPI_S3]) <= 0.5 * mag(SINPI_S0));
        // cos: |C1| ≥ |d²·(C2 + d²·C3)|
        assert!(d2max * poly_mag(&[SINPI_C2, SINPI_C3]) <= 0.5 * mag(SINPI_C1));
    }

    #[test]
    fn tan_leads() {
        // Slack for the rounding of r and w = r·r at the octant edge.
        let wmax = core::f64::consts::FRAC_PI_4.powi(2) * 1.0001;
        let mag = |c: DoubleDouble| c.high.abs() + c.low.abs();

        // p0/p1/p2 = L₂ₖ ⊕ w·L₂ₖ₊₁
        for pair in TAN_LEADS.chunks(2) {
            assert!(wmax * mag(pair[1]) <= 0.5 * pair[0].high.abs());
        }

        // inner = p1 ⊕ w²·p2, outer = p0 ⊕ w²·inner, t = outer ⊕ v⁶·tail
        let w2max = wmax * wmax;
        let p2_mag = mag(TAN_LEADS[4]) + wmax * mag(TAN_LEADS[5]);
        let p1_min = TAN_LEADS[2].high - wmax * mag(TAN_LEADS[3]);
        assert!(w2max * p2_mag <= 0.5 * p1_min);
        let inner_mag = mag(TAN_LEADS[2]) + wmax * mag(TAN_LEADS[3]) + w2max * p2_mag;
        let p0_min = TAN_LEADS[0].high - wmax * mag(TAN_LEADS[1]);
        assert!(w2max * inner_mag <= 0.5 * p0_min);
        let tail_mag = TAN_TAIL
            .iter()
            .rev()
            .fold(0.0, |acc, c| crate::fast_mul_add(acc, wmax, c.abs()));
        let outer_min = p0_min - w2max * inner_mag;
        assert!(wmax.powi(3) * tail_mag <= 0.5 * outer_min);
    }
}

/// MPFR-certified soundness of `sinpi`'s lean-table-leg Ziv gate.  The gate may
/// only confirm a rounding when its relative half-width [`SINPI_ZIV_EPS`] truly
/// exceeds the leg's error.  Run with `--features mpfr`.
#[cfg(all(test, feature = "mpfr"))]
mod ziv_soundness {
    use super::*;
    use rug::Float;

    fn mix(i: u64) -> u64 {
        let mut z = i.wrapping_mul(0x2545_F491_4F6C_DD1D);
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Worst `|leg(x) − sin(πx)| / SINPIN_ERR` for the main-band integer-
    /// reduction leg — its unrounded value is `sg.high + r` with `sg.high`
    /// exact, so the absolute gate is sound iff the slip stays below the
    /// window.  Value-uniform over `(0x1.2p−5, 4]` (every grid cell ×
    /// residual; sign-symmetric by construction); a ratio `< 0.5` certifies
    /// the 2× soundness margin.
    #[test]
    fn sinpi_fast_leg_is_sound() {
        let mut worst = 0.0f64;
        let mut worst_x = 0.5;
        for i in 0..30_000_000u64 {
            let x = 0.035_156_25 + mix(i) as f64 / (u64::MAX / 4) as f64;
            let ix = x.to_bits();
            let e = ((ix >> 52) & 0x7ff) as i64;
            let m = ((ix & (u64::MAX >> 12)) | 1 << 52) as i64;
            let s = 1063 - e;
            let iq = ((m >> s) + 1) >> 1;
            let k = (m as u64).wrapping_shl((e - 1000) as u32) as i64;
            let z = k as f64;
            let z2 = z * z;
            let fs = crate::fast_mul_add(
                z2,
                crate::fast_mul_add(z2, SINPI_ZS[2], SINPI_ZS[1]),
                SINPI_ZS[0],
            );
            let fc = crate::fast_mul_add(z2, SINPI_ZC[1], SINPI_ZC[0]);
            let (sg, cg) = sincosn(iq);
            let r = crate::fast_mul_add(cg.high, z * fs, sg.low + sg.high * (z2 * fc));
            let got = Float::with_val(250, sg.high) + Float::with_val(250, r);
            let truth = Float::with_val(250, x).sin_pi();
            let abs = Float::with_val(250, &got - &truth).abs().to_f64();
            let ratio = abs / SINPIN_ERR;
            if ratio > worst {
                worst = ratio;
                worst_x = x;
            }
        }
        println!("sinpi fast leg: worst |err|/gate = {worst:.4} at x={worst_x:e}");
        assert!(
            worst < 0.5,
            "sinpi gate covers only {:.2}× the slip at x={worst_x:e}",
            1.0 / worst
        );
    }

    /// Worst `|leg(x) − sin(πx)| / eps(x)` for the small band
    /// `(2⁻⁵⁴, 0x1.2p−5]`, representation-uniform so every binade appears.
    /// The gate width is CORE-MATH's `x·(x²·2⁻⁴⁷ + 2⁻¹⁰²)` with the x²-term
    /// widened 1.5× to restore the 2× margin.
    #[test]
    fn sinpi_small_band_is_sound() {
        let (lb, hb) = (0x3c90_0000_0000_0000u64, 0x3fa2_0000_0000_0000);
        let mut worst = 0.0f64;
        let mut worst_x = 0.5;
        for i in 0..30_000_000u64 {
            let x = f64::from_bits(lb + mix(i) % (hb - lb + 1));
            let zh = PI_DD.high * x;
            let zl = crate::fma(PI_DD.high, x, -zh) + PI_DD.low * x;
            let x2 = x * x;
            let x3 = x2 * x;
            let x4 = x2 * x2;
            let eps = x * crate::fast_mul_add(x2, 1.5 * crate::exp2i(-47), crate::exp2i(-102));
            let zl = zl
                + x3 * ((SINPI_SMALL_C[0] + x2 * SINPI_SMALL_C[1])
                    + x4 * (SINPI_SMALL_C[2] + x2 * SINPI_SMALL_C[3]));
            let got = Float::with_val(250, zh) + Float::with_val(250, zl);
            let truth = Float::with_val(250, x).sin_pi();
            let abs = Float::with_val(250, &got - &truth).abs().to_f64();
            let ratio = abs / eps;
            if ratio > worst {
                worst = ratio;
                worst_x = x;
            }
        }
        println!("sinpi small band: worst |err|/gate = {worst:.4} at x={worst_x:e}");
        assert!(
            worst < 0.5,
            "sinpi small-band gate covers only {:.2}× the slip at x={worst_x:e}",
            1.0 / worst
        );
    }

    /// Worst relative `|sinpi_dd(x) − sin(πx)| / (SINPI_DD_EPS·|high|)` over
    /// the middle tier's traffic: uniform across the band plus near-integer
    /// clusters (the fast leg's systematic straddles).  A ratio `< 0.5`
    /// certifies the 2× soundness margin.
    #[test]
    fn sinpi_dd_tier_is_sound() {
        let mut worst = 0.0f64;
        let mut worst_x = 0.5;
        for i in 0..20_000_000u64 {
            let h = mix(i);
            let x = if i & 1 == 0 {
                h as f64 / (u64::MAX / 4) as f64
            } else {
                // near-integer: k ± tiny, the fast leg's straddle population
                let k = ((h >> 32) % 8) as f64;
                let delta = f64::from_bits(0x3c90_0000_0000_0000 + (h & 0xF_FFFF_FFFF));
                if h & 16 == 0 { k + delta } else { k - delta }
            };
            if x == 0.0 || x.fract() == 0.0 {
                continue;
            }
            let v = sinpi_dd(x);
            let got = Float::with_val(250, v.high) + Float::with_val(250, v.low);
            let truth = Float::with_val(250, x).sin_pi();
            let abs = Float::with_val(250, &got - &truth).abs().to_f64();
            let ratio = abs / (SINPI_DD_EPS * v.high.abs());
            if ratio > worst {
                worst = ratio;
                worst_x = x;
            }
        }
        println!("sinpi dd tier: worst |err|/gate = {worst:.4} at x={worst_x:e}");
        assert!(
            worst < 0.5,
            "sinpi dd-tier gate covers only {:.2}× the slip at x={worst_x:e}",
            1.0 / worst
        );
    }

    /// Worst `|leg(x) − cos(πx)| / er(z)` for the cospi main-band leg, whose
    /// gate is CORE-MATH's residual-proportional `z·2⁻¹²³` plus the 2⁻⁷⁷
    /// absolute floor covering the table pair's own accuracy near grid
    /// points.  Value-uniform over `(2⁻¹², 4]`; `< 0.5` certifies the 2×
    /// margin.
    #[test]
    fn cospi_fast_leg_is_sound() {
        let mut worst = 0.0f64;
        let mut worst_x = 0.5;
        for i in 0..30_000_000u64 {
            let x = 2.44e-4 + mix(i) as f64 / (u64::MAX / 4) as f64;
            let ix = x.to_bits();
            let e = ((ix >> 52) & 0x7ff) as i64;
            let m = (ix & (u64::MAX >> 12)) | 1 << 52;
            let s = 1063 - e;
            let iq = ((((m >> s).wrapping_add(2048)) & 8191).wrapping_add(1)) >> 1;
            let k = m.wrapping_shl((e - 1000) as u32) as i64;
            let z = k as f64;
            let z2 = z * z;
            let fs = crate::fast_mul_add(
                z2,
                crate::fast_mul_add(z2, SINPI_ZS[2], SINPI_ZS[1]),
                SINPI_ZS[0],
            );
            let fc = crate::fast_mul_add(z2, SINPI_ZC[1], SINPI_ZC[0]);
            let (sg, cg) = sincosn(iq as i64);
            let er = crate::fast_mul_add(z.abs(), crate::exp2i(-123), crate::exp2i(-77));
            let r = crate::fast_mul_add(cg.high, z * fs, sg.low + sg.high * (z2 * fc));
            let got = Float::with_val(250, sg.high) + Float::with_val(250, r);
            let truth = Float::with_val(250, x).cos_pi();
            let abs = Float::with_val(250, &got - &truth).abs().to_f64();
            let ratio = abs / er;
            if ratio > worst {
                worst = ratio;
                worst_x = x;
            }
        }
        println!(
            "cospi fast leg: worst |err|/gate = {worst:.4} at x={worst_x:e} bits={:016x}",
            worst_x.to_bits()
        );
        assert!(
            worst < 0.5,
            "cospi gate covers only {:.2}× the slip at x={worst_x:e}",
            1.0 / worst
        );
    }

    /// Worst `|leg(x) − cos(πx)| / (x²·2⁻⁴⁷·⁵)` for the small band
    /// `(2⁻²⁶·⁵, 2⁻¹²]`, representation-uniform across its binades.
    #[test]
    fn cospi_small_band_is_sound() {
        let (lb, hb) = (0x3e2c_cf64_29be_6622u64, 0x3f30_0000_0000_0000);
        let mut worst = 0.0f64;
        let mut worst_x = 0.5;
        for i in 0..30_000_000u64 {
            let x = f64::from_bits(lb + mix(i) % (hb - lb + 1));
            let x2 = x * x;
            let x4 = x2 * x2;
            let eps = x2 * 8.659_739_592_076_221e-15;
            let p = x2
                * ((COSPI_SMALL_C[0] + x2 * COSPI_SMALL_C[1])
                    + x4 * (COSPI_SMALL_C[2] + x2 * COSPI_SMALL_C[3]));
            let got = Float::with_val(250, 1.0) + Float::with_val(250, p);
            let truth = Float::with_val(250, x).cos_pi();
            let abs = Float::with_val(250, &got - &truth).abs().to_f64();
            let ratio = abs / eps;
            if ratio > worst {
                worst = ratio;
                worst_x = x;
            }
        }
        println!("cospi small band: worst |err|/gate = {worst:.4} at x={worst_x:e}");
        assert!(
            worst < 0.5,
            "cospi small-band gate covers only {:.2}× the slip at x={worst_x:e}",
            1.0 / worst
        );
    }

    /// Worst relative `|cospi_dd(x) − cos(πx)| / (SINPI_DD_EPS·|high|)` over
    /// uniform and near-half-integer inputs (the fast leg's straddles).
    #[test]
    fn cospi_dd_tier_is_sound() {
        let mut worst = 0.0f64;
        let mut worst_x = 0.5;
        for i in 0..20_000_000u64 {
            let h = mix(i);
            let x = if i & 1 == 0 {
                h as f64 / (u64::MAX / 4) as f64
            } else {
                let k = ((h >> 32) % 8) as f64 + 0.5;
                let delta = f64::from_bits(0x3c90_0000_0000_0000 + (h & 0xF_FFFF_FFFF));
                if h & 16 == 0 { k + delta } else { k - delta }
            };
            if x == 0.0 || (2.0 * x).fract() == 0.0 {
                continue;
            }
            let v = cospi_dd(x);
            let got = Float::with_val(250, v.high) + Float::with_val(250, v.low);
            let truth = Float::with_val(250, x).cos_pi();
            let abs = Float::with_val(250, &got - &truth).abs().to_f64();
            let ratio = abs / (SINPI_DD_EPS * v.high.abs());
            if ratio > worst {
                worst = ratio;
                worst_x = x;
            }
        }
        println!("cospi dd tier: worst |err|/gate = {worst:.4} at x={worst_x:e}");
        assert!(
            worst < 0.5,
            "cospi dd-tier gate covers only {:.2}× the slip at x={worst_x:e}",
            1.0 / worst
        );
    }
}
