#!/usr/bin/env python3
"""Generate the triple-double tables for `f64::lgamma`'s accurate path.

Two groups of constants live in `src/f64_/gamma_td_tables.rs` (this script's
stdout, redirect it there) and a handful of inline constants in `gamma.rs`:

  * `LOGD_*` — the two-level `ln` reduction tables, transcribed verbatim from
    CORE-MATH's `as_logd_accurate`
    (`core-math-sys/vendor/src/binary64/lgamma/lgamma.c`).  The hex-float
    literals are parsed exactly and re-emitted as shortest round-tripping
    decimals.
  * `SINPI_OVER_ARG_TD` / `COSPI_TD` — `sin(πr)/(πr)` and `cos(πr)` even Taylor
    series in `w = r²` (printed by `--inline`).
  * `LGAMMA_ROOT1_TD` / `LGAMMA_ROOT2_TD` — result-anchored `ln Γ(1+x)` /
    `ln Γ(2+x)` Taylor series for `|x| < 2⁻⁴`.
  * `LGAMMA_TAIL_TD`, `LN2_TD`, `LN_PI_TD`, `HALF_LN_2PI_M_HALF_TD`, `THIRD_TD`
    — printed by `--inline` for manual placement in `gamma.rs`.

Usage:
    tools/gen_lgamma_td.py            > src/f64_/gamma_td_tables.rs   # LOGD_* + roots
    tools/gen_lgamma_td.py --inline                                  # inline consts
"""
import re
import sys

LGAMMA_C = "/home/jdh8/src/core-math-sys/vendor/src/binary64/lgamma/lgamma.c"


def to_f64(tok):
    tok = tok.strip()
    try:
        return float.fromhex(tok)
    except ValueError:
        return float(tok)


def rc(tok):
    return repr(to_f64(tok))


# ── CORE-MATH `as_logd_accurate` table extraction ────────────────────────────
def extract_logd():
    src = open(LGAMMA_C).read()
    body = src[src.index("double as_logd_accurate(double x, double *l, double *l_){"):
               src.index("static const double stpi")]

    def table(name):
        m = re.search(r"static const [^\n]*\b" + re.escape(name) + r"\b[^=]*=\s*\{", body)
        i = m.end() - 1
        depth = 0
        j = i
        while j < len(body):
            if body[j] == "{":
                depth += 1
            elif body[j] == "}":
                depth -= 1
                if depth == 0:
                    break
            j += 1
        return body[i:j + 1]

    def rows(t):
        inner = t.strip()[1:-1]
        out, depth, cur = [], 0, ""
        for ch in inner:
            if ch == "{":
                if depth == 0:
                    cur = ""
                depth += 1
                if depth == 1:
                    continue
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    out.append(cur)
                    continue
            if depth >= 1:
                cur += ch
        return [[t.strip() for t in r.split(",") if t.strip()] for r in out]

    def flat(t):
        return [x.strip() for x in t.strip()[1:-1].split(",") if x.strip()]

    return {
        "B": rows(table("B")),
        "r1": flat(table("r1")),
        "r2": flat(table("r2")),
        "h1": rows(table("h1")),
        "h2": rows(table("h2")),
        "c": rows(table("c")),
    }


def emit_logd():
    t = extract_logd()
    print("// Triple-double natural-log lookup tables for [`ln_td`], ported from CORE-MATH's")
    print("// `as_logd_accurate` (binary64/lgamma/lgamma.c).  Generated by")
    print("// tools/gen_lgamma_td.py - do not edit by hand.")
    print()
    print("// LOGD_B: (c0, c1) index-correction pairs for the two-level log reduction.")
    print("#[rustfmt::skip]")
    print(f"const LOGD_B: [(u16, i16); {len(t['B'])}] = [")
    for c0, c1 in t["B"]:
        print(f"    ({int(c0)}, {int(c1)}),")
    print("];")
    for nm in ("r1", "r2"):
        print(f"#[rustfmt::skip]")
        print(f"const LOGD_{nm.upper()}: [f64; {len(t[nm])}] = [")
        print("    " + ", ".join(rc(x) for x in t[nm]))
        print("];")
    for nm in ("h1", "h2"):
        print(f"const LOGD_{nm.upper()}: [[f64; 3]; {len(t[nm])}] = [")
        for row in t[nm]:
            print("    [" + ", ".join(rc(x) for x in row) + "],")
        print("];")
    print(f"const LOGD_C: [DoubleDouble; {len(t['c'])}] = [")
    for hi, lo in t["c"]:
        print(f"    DoubleDouble {{ high: {rc(hi)}, low: {rc(lo)} }},")
    print("];")


# ── Series tables (need mpmath) ──────────────────────────────────────────────
def emit_roots():
    from mpmath import mp, mpf, zeta, euler
    mp.dps = 80

    def td(v):
        v = mpf(v)
        out = []
        for _ in range(3):
            d = float(v)
            out.append(d)
            v -= mpf(d)
        return out

    def c1(k):
        return -euler if k == 1 else (-1) ** k * zeta(k) / k

    def c2(k):
        return (1 - euler) if k == 1 else (-1) ** k * (zeta(k) - 1) / k

    def emit(name, c, n):
        print("#[rustfmt::skip]")
        print(f"const {name}: [TripleDouble; {n + 1}] = [")
        print("    TripleDouble { high: 0.0, mid: 0.0, low: 0.0 },")
        for k in range(1, n + 1):
            w = td(c(k))
            print(f"    TripleDouble {{ high: {w[0]!r}, mid: {w[1]!r}, low: {w[2]!r} }},")
        print("];")

    print()
    print("// Result-anchored Taylor series of ln Γ near its roots, for |x| < 2^-4.")
    print("// LGAMMA_ROOT1_TD: ln Γ(1+x) = Σ cₖ xᵏ (c₁ = −γ, cₖ = (−1)ᵏ ζ(k)/k).")
    print("// LGAMMA_ROOT2_TD: ln Γ(2+x) = Σ cₖ xᵏ (c₁ = 1−γ, cₖ = (−1)ᵏ (ζ(k)−1)/k).")
    emit("LGAMMA_ROOT1_TD", c1, 41)
    emit("LGAMMA_ROOT2_TD", c2, 33)


def emit_inline():
    from mpmath import mp, mpf, pi, factorial, log, bernoulli
    mp.dps = 120

    def td(v):
        v = mpf(v)
        out = []
        for _ in range(3):
            d = float(v)
            out.append(d)
            v -= mpf(d)
        return out

    def arr(name, coeffs):
        print(f"const {name}: [TripleDouble; {len(coeffs)}] = [")
        for c in coeffs:
            w = td(c)
            print(f"    TripleDouble {{ high: {w[0]!r}, mid: {w[1]!r}, low: {w[2]!r} }},")
        print("];")

    S = [(-1) ** k * pi ** (2 * k) / factorial(2 * k + 1) for k in range(21)]
    C = [(-1) ** k * pi ** (2 * k) / factorial(2 * k) for k in range(21)]
    arr("SINPI_OVER_ARG_TD", S)
    arr("COSPI_TD", C)
    tail = [bernoulli(2 * k) / (2 * k * (2 * k - 1)) for k in range(1, 11)]
    arr("LGAMMA_TAIL_TD", tail)
    for name, v in (("LN2_TD list", log(2)), ("THIRD_TD", mpf(1) / 3),
                    ("LN_PI_TD", log(pi)), ("HALF_LN_2PI_M_HALF_TD", mpf('0.5') * log(2 * pi) - mpf('0.5'))):
        print(f"// {name}: {td(v)}")


if __name__ == "__main__":
    if "--inline" in sys.argv:
        emit_inline()
        emit_roots()
    else:
        emit_logd()
        emit_roots()
