#!/usr/bin/env python3
"""Generate `src/f128_/rsqrt_tables.rs`: the fixed-point seed constants of the
binary128 reciprocal square root.

Everything here is a *mathematical* constant computed from scratch with mpmath:
the value, first derivative, and half second derivative of m^(-1/2) at the 64
interval centers c = 1 + (2i+1)/128 covering m in [1, 2), plus the Newton
constants 2^(-w/2)/2 that fold the octave scaling into the seed's single
integer Newton step.  A degree-2 Taylor expansion from the nearest center is a
truncated series, not a fitted approximation — no minimax coefficients, no
transcription from another library.

Usage:
    python3 tools/gen_rsqrt_f128.py > src/f128_/rsqrt_tables.rs
"""
from mpmath import mp, mpf, nint

mp.prec = 200


def rows(values, per_row=4):
    lines = []
    for start in range(0, len(values), per_row):
        chunk = ", ".join(f"{v:#018x}" for v in values[start : start + per_row])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


centers = [1 + mpf(2 * i + 1) / 128 for i in range(64)]
value = [int(nint(c ** (mpf(-1) / 2) * 2**63)) for c in centers]
slope = [int(nint(c ** (mpf(-3) / 2) / 2 * 2**65)) for c in centers]
curve = [int(nint(c ** (mpf(-5) / 2) * 3 / 8 * 2**65)) for c in centers]
newton = [int(nint(mpf(2) ** (mpf(-w) / 2) * 2**63)) for w in range(2)]

print(
    f'''//! Generated by tools/gen_rsqrt_f128.py - do not edit by hand.
//!
//! Fixed-point seed constants for the binary128 reciprocal square root.  Every
//! entry is a mathematical constant evaluated to 200 bits with mpmath: the
//! degree-2 Taylor data of m^(-1/2) at the 64 interval centers
//! c = 1 + (2i+1)/128, and the Newton constants 2^(-w/2) for the two octaves
//! of [1, 4).
#![allow(clippy::unreadable_literal)]

/// c^(-1/2), scaled by 2^63 and rounded.
#[rustfmt::skip]
pub const SEED_VALUE: [u64; 64] = [
{rows(value)}
];

/// c^(-3/2)/2 = |d(m^(-1/2))/dm| at c, scaled by 2^65 and rounded.
#[rustfmt::skip]
pub const SEED_SLOPE: [u64; 64] = [
{rows(slope)}
];

/// 3c^(-5/2)/8 = d²(m^(-1/2))/dm²/2 at c, scaled by 2^65 and rounded.
#[rustfmt::skip]
pub const SEED_CURVE: [u64; 64] = [
{rows(curve)}
];

/// 2^(-w/2), scaled by 2^63 and rounded.
#[rustfmt::skip]
pub const NEWTON: [u64; 2] = [
{rows(newton)}
];'''
)
