#!/usr/bin/env python3
"""Generate the exact-`z` reduction cells for the f64 `log2` fast leg.

Same cell geometry and reciprocal lattice as `gen_ln_exact_f64.py` (that file
documents the exactness argument for `z = fma(r, m, -1)`); only the `l` words
change base:

    log2(2^e·m) = e + log2(r·m) − log2 r = e + l1 + l2 + log2(1 + z)

`l1` is `−log2 r` rounded to the nearest integer multiple of 2⁻⁴², so the
exponent join `e + l1` is **exact as a plain add**: a sum of integer multiples
of 2⁻⁴² bounded by `1074 + 1 < 2¹¹`, hence at most 2⁵³ multiples.  (Base 2 is
the whole win: base e needs `e·LN2_HI` and a trailing `e·LN2_LO` fold; here the
exponent costs one exact add and nothing on the low word.)

The kernel's linear term is no longer exact — `log2(1+z) ≈ z·log2 e` — so the
leg forms `zh = RN(z·LOG2_E_HI)` and keeps its exact FMA residual.  The
Fast2Sum ordering must therefore hold against `max|zh| ≤ max|z|·LOG2_E_HI·(1+ε)`
(one rounding), checked per cell in exact rational arithmetic:

  e = 0:   l1 ≥ max|zh|                     (also rejects r = 1, where l1 = 0)
  e = −1:  l1 == 1 (cell 127, r = ½: e + l1 = 0, Fast2Sum trivially exact)
           or 1 − l1 ≥ max|zh|
  otherwise |e + l1| ≥ 1 − max l1 + 1 > 1 > max|zh| since l1 ≤ 1.
"""

import struct
from fractions import Fraction

from mpmath import mp, mpf
from mpmath import log as mlog

mp.prec = 250

N = 128  # cells over m in [1, 2)
RGRID = 256  # r = q/RGRID; exactness bound |z| <= 2^53·(2^-8·2^-52) = 2/RGRID
BOUND = Fraction(2, RGRID)
ULP = Fraction(1, 1 << 52)
GRID42 = 1 << 42


def f64(x):
    return struct.unpack("<d", struct.pack("<d", float(x)))[0]


# LOG2_E_HI exactly as log.rs defines it (RN of log2 e; LO is the RN residual).
log2e = 1 / mlog(2)
L2E_HI = f64(log2e)
assert L2E_HI == 1.4426950408889634
# Fast2Sum bound |zh| = |RN(z·L2E_HI)| ≤ max|z|·L2E_HI·(1 + 2⁻⁵³), as a Fraction.
ZH_INFLATE = Fraction(L2E_HI) * (1 + Fraction(1, 1 << 53))

cells = []
z_max = Fraction(0)
margin_e0 = None  # min(l1 - max|zh|) over cells: e = 0 Fast2Sum slack
margin_e1 = None  # min((1 - l1) - max|zh|) over cells with l1 != 1

for j in range(N):
    a = 1 + Fraction(j, N)
    b_max = 1 + Fraction(j + 1, N) - ULP
    best = None
    for q in range(RGRID // 2, RGRID + 1):
        r = Fraction(q, RGRID)
        maxz = max(abs(r * a - 1), abs(r * b_max - 1))
        if maxz > BOUND:
            continue
        maxzh = maxz * ZH_INFLATE
        lgr = -mlog(mpf(q) / RGRID, 2)
        k1 = int(mp.nint(lgr * GRID42))
        if Fraction(k1, GRID42) < maxzh:  # e = 0 ordering
            continue
        d = abs(k1 - GRID42)
        if d != 0 and Fraction(d, GRID42) < maxzh:  # e = -1 ordering
            continue
        if best is None or maxz < best[0]:
            best = (maxz, q, k1, lgr)
    assert best is not None, f"cell {j}: no feasible r"
    maxz, q, k1, lgr = best

    l1 = k1 / float(GRID42)
    assert Fraction(l1) == Fraction(k1, GRID42), "l1 not exact"
    assert abs(k1) + 1074 * GRID42 < 1 << 53, "e + l1 not exact"
    l2 = f64(lgr - mpf(l1))
    assert abs(l2) <= 2.0**-43, "l2 exceeds half the l1 grid"
    assert abs(mpf(l1) + mpf(l2) - lgr) < mpf(2) ** -96, "l1 + l2 off -log2 r"
    assert mpf(l1) <= 1, "l1 above 1"

    z_max = max(z_max, maxz)
    e0 = Fraction(k1, GRID42) - maxz * ZH_INFLATE
    margin_e0 = e0 if margin_e0 is None else min(margin_e0, e0)
    if k1 != GRID42:
        e1 = Fraction(abs(k1 - GRID42), GRID42) - maxz * ZH_INFLATE
        margin_e1 = e1 if margin_e1 is None else min(margin_e1, e1)
    cells.append((q, l1, l2))

print(f"// Generated by `tools/gen_log2_exact_f64.py`; do not edit by hand.")
print(f"// max |z| over all cells: {float(z_max):.6e} = 2^{float(mlog(z_max, 2)):.3f}")
print(f"// Fast2Sum slack, e =  0: min(l1 − max|zh|)       = {float(margin_e0):.3e}")
print(f"// Fast2Sum slack, e = −1: min((1 − l1) − max|zh|) = {float(margin_e1):.3e}")
print(f"const LOG2_CELLS: [LnCell; {N}] = [")
for q, l1, l2 in cells:
    r = q / RGRID
    print(f"    LnCell {{ r: {r!r}, l1: {l1!r}, l2: {l2!r} }},")
print("];")
