#!/usr/bin/env python3
"""Generate `src/f128_/asin_tables.rs`: the fixed-point constants of the
binary128 `asinq`/`acosq` fast leg.

The root-band tables are mathematical constants computed with mpmath:
for the dyadic breakpoints `sin(phi_j) = j/128` it tabulates `cos(phi_j) =
sqrt(1 - j^2/2^14)` and `phi_j = asin(j/128)`.  The reduction is the sine
difference `sin(A - phi_j) = sin(A)*cos(phi_j) - cos(A)*sin(phi_j)`: with
`sin(phi_j)` dyadic, one side of the difference is an exact small-integer
product, and no division appears anywhere. The small-argument polynomials are
independent Remez.jl fits, rounded to the kernel's Q128/64-bit coefficients and
certified with exact rational Bernstein bounds and a Taylor remainder.

Usage:
    python3 tools/gen_asin_f128.py > src/f128_/asin_tables.rs
"""
from fractions import Fraction as F
from math import comb
import subprocess
import sys

from mpmath import mp, mpf, asin, sqrt, nint, floor

mp.prec = 2000

# Breakpoints `sin(phi_j) = j/DENOM`; the reduced argument `u = min(x, sqrt(1 -
# x^2))` never exceeds sqrt(2)/2, so `j` stops at `round(DENOM * sqrt(2)/2)`.
DENOM = 128
COUNT = int(nint(DENOM * sqrt(mpf(2)) / 2)) + 1

# `cos(phi_j)` is a plain 256-bit fraction (it is below 1 for every `j >= 1`);
# `phi_j` rides the fast leg's 2^-253 frame, `atan2q`'s.
COS_FRAME = 256
PHI_FRAME = 253


def hexs(value, digits):
    """Underscore-grouped hex literal of `value` padded to `digits` nibbles."""
    text = format(value, f"0{digits}x")
    groups = [text[i:i + 16] for i in range(0, len(text), 16)]
    return "0x" + "_".join(groups)


def limbs(value, count):
    """`value` as `count` little-endian 128-bit limbs."""
    assert 0 <= value < 1 << (128 * count), value
    parts = [hexs(value >> (128 * i) & (1 << 128) - 1, 32) for i in range(count)]
    return "[" + ", ".join(parts) + "]"


print(f"""//! Generated by tools/gen_asin_f128.py - do not edit by hand.
//!
//! Fixed-point constants for the binary128 `asinq`/`acosq` fast leg. The root
//! tables are mathematical constants evaluated to 2000 bits with mpmath: for the
//! dyadic breakpoints `sin(phi_j) = j/{DENOM}`, the cosines `sqrt(1 - j^2/{DENOM**2})`
//! and the angles `asin(j/{DENOM})` themselves. The small-argument polynomials
//! are independent Remez.jl fits, certified after fixed-point rounding.
#![allow(clippy::unreadable_literal)]

/// `sqrt(1 - (j/{DENOM})^2)`, scaled by 2^{COS_FRAME} and truncated.  Entry 0 would
/// be 2^{COS_FRAME} itself and is never read: a zero sector is the relative band.
#[rustfmt::skip]
pub const COS: [[u128; 2]; {COUNT}] = [""")
for j in range(COUNT):
    v = sqrt(1 - (mpf(j) / DENOM) ** 2) * mpf(2) ** COS_FRAME if j else 0
    print(f"    {limbs(int(floor(v)), 2)},")
print("];")


def certify(coefficients, lo, hi, bits):
    """Bound the actual mixed-width polynomial by exact Bernstein subdivision."""
    degree = len(coefficients) + 8
    taylor = [F(comb(2*k+2, k+1), 4**(k+1)*(2*k+3)) for k in range(degree + 2)]
    delta = [taylor[k] - (F(coefficients[k], 1 << 128)
             if k < len(coefficients) else 0) for k in range(degree + 1)]
    # Change variable u = lo + (hi-lo)*t, then power basis to Bernstein on [0,1].
    power = [(hi-lo)**j * sum(delta[k]*comb(k, j)*lo**(k-j)
             for k in range(j, degree + 1)) for j in range(degree + 1)]
    bernstein = [sum(power[j]*F(comb(k, j), comb(degree, j))
                 for j in range(k + 1)) for k in range(degree + 1)]
    # Positive, decreasing Taylor coefficients bound the entire omitted tail.
    remainder = taylor[degree + 1]*hi**(degree + 1)/(1-hi)
    limit = F(1, 1 << bits)
    pending = [(bernstein, 0)]
    worst = F(0)
    while pending:
        row, depth = pending.pop()
        bound = max(map(abs, row)) + remainder
        if bound < limit:
            worst = max(worst, bound)
            continue
        assert depth < 12, (bits, bound)
        left, right = [row[0]], [row[-1]]
        while len(row) > 1:
            row = [(a+b)/2 for a, b in zip(row, row[1:])]
            left.append(row[0])
            right.append(row[-1])
        pending.extend(((left, depth+1), (right[::-1], depth+1)))
    print(f"ASIN polynomial on [{lo}, {hi}]: exact rational bound < 2^-{bits}", file=sys.stderr)


for name, degree, lo, hi, narrow, bound in [
    ("ASIN_NARROW", 10, F(0), F(1, 256), 7, 115),
    ("ASIN_BROAD", 13, F(1, 256), F(1, 64), 10, 123),
]:
    command = (
        "using Remez; setprecision(512); "
        "f(u) = iszero(u) ? BigFloat(1)/6 : (asin(sqrt(u))/sqrt(u)-1)/u; "
        f"n, d, e, x = Remez.ratfn_minimax(f, (BigFloat({lo.numerator})/{lo.denominator}, "
        f"BigFloat({hi.numerator})/{hi.denominator}), {degree}, 0); "
        "foreach(c -> println(round(BigInt, c*BigFloat(2)^128)), n); "
        "foreach(u -> println(sqrt(u[1])), x)"
    )
    result = subprocess.run(["julia", "--startup-file=no", "-e", command],
                            check=True, capture_output=True, text=True).stdout.splitlines()
    coefficients = list(map(int, result[:degree + 1]))
    assert all(0 < c < 1 << 128 for c in coefficients)
    actual = [c if k < narrow else c >> 64 << 64 for k, c in enumerate(coefficients)]
    certify(actual, lo, hi, bound)
    print(f"""
/// Degree-{degree} minimax of `(asin(sqrt(u))/sqrt(u)-1)/u` on `[{lo}, {hi}]`,
/// in Q128. After narrowing coefficients {narrow} onward to 64 bits, the exact
/// rational certificate in the generator gives absolute error < 2^-{bound}.
/// Generated independently with:
/// `julia --startup-file=no -e '{command}'`
#[rustfmt::skip]
pub const {name}: [u128; {degree + 1}] = [""")
    for c in coefficients:
        print(f"    {hexs(c, 32)},")
    print("];")
    extrema = result[degree + 1:]
    assert len(extrema) == degree + 2
    print(f"""
/// The fit's extrema in the original `x = sqrt(u)` coordinate, for gate checks.
#[cfg(all(test, feature = "mpfr"))]
#[rustfmt::skip]
pub const {name}_EXTREMA: [f128; {len(extrema)}] = [""")
    for x in extrema:
        print(f"    {mp.nstr(mpf(x), 45, min_fixed=0, max_fixed=0)}_f128,")
    print("];")

print(f"""
/// `asin(j/{DENOM})`, scaled by 2^{PHI_FRAME} and rounded: the fast leg's frame.
#[rustfmt::skip]
pub const PHI: [[u128; 2]; {COUNT}] = [""")
for j in range(COUNT):
    print(f"    {limbs(int(nint(asin(mpf(j) / DENOM) * mpf(2) ** PHI_FRAME)), 2)},")
print("];")
