#!/usr/bin/env python3
"""Generate the constants for `f64::exp` (table + reduction + DD poly).

Run:  python3 tools/gen_exp_f64.py  > src/f64/exp_consts.in   (or paste output)

Design (small-table + low-degree double-double):
  n = round(x * 128 / ln2),  j = n & 127,  q = n >> 7,  r = x - n*(ln2/128)
  exp(x) = 2^q * 2^(j/128) * exp(r),   |r| <= ln2/256 ~ 0.00271
The degree-8 DD polynomial for exp(r) is generated by rminimax (see below);
the table 2^(j/128) and the extended-precision ln2/128 are generated here.

rminimax command for the exp(r) coefficients (DD, hex):
  ratapprox --function="exp(x)" --dom="[-0.002708,0.002708]" \
            --type=[8,0] --numF="[DD]" --dispCoeff=hex
"""
from mpmath import mp, mpf, mpf as MPF, log, power
import struct
mp.prec = 250

def f64(x):                       # round a high-precision value to nearest f64
    return struct.unpack('<d', struct.pack('<d', float(x)))[0]

def dd(x):                        # split a high-precision value into (hi, lo) doubles
    hi = f64(x)
    lo = f64(x - mpf(hi))
    return hi, lo

def hexf(v):
    return repr(float(v))

ln2 = log(2)
N = 128

# --- extended-precision ln2/128: hi has >=17 trailing zero bits (n up to ~2^17) ---
step = ln2 / N
hi_full = f64(step)
# clear low 17 bits of the significand so n*hi is exact for |n| < 2^(53-35)
b = struct.unpack('<Q', struct.pack('<d', hi_full))[0]
b &= ~((1 << 17) - 1)
LN2_OVER_N_HI = struct.unpack('<d', struct.pack('<Q', b))[0]
LN2_OVER_N_LO = f64(step - mpf(LN2_OVER_N_HI))

print("// generated by tools/gen_exp_f64.py")
print(f"const LN2_OVER_N_HI: f64 = {hexf(LN2_OVER_N_HI)};")
print(f"const LN2_OVER_N_LO: f64 = {hexf(LN2_OVER_N_LO)};")
print(f"// check: HI low 17 bits = {struct.unpack('<Q', struct.pack('<d', LN2_OVER_N_HI))[0] & ((1<<17)-1)}")
err = (mpf(LN2_OVER_N_HI) + mpf(LN2_OVER_N_LO) - step) / step
print(f"// rel err of (HI+LO) vs ln2/128: 2^{float(mp.log(abs(err),2)):.1f}")

# --- table 2^(j/128) as (hi, lo) double-double ---
print(f"\nconst EXP2_TABLE: [(f64, f64); {N}] = [")
for j in range(N):
    hi, lo = dd(power(2, mpf(j) / N))
    print(f"    ({hexf(hi)}, {hexf(lo)}),")
print("];")

# --- exp(r) polynomial coefficients (double-double), from the rminimax run above ---
# Extended-precision hex literals as printed by ratapprox (more than f64 precision):
EXPR_COEFFS_HEX = [
    "0x1p+0",
    "0xf.fffffffffffffffffffffe9cd6p-4",
    "0x8.0000000000000000000002746ep-4",
    "0x2.aaaaaaaaaaaaaaaad128281bfcp-4",
    "0xa.aaaaaaaaaaaaaaa8e207de2426p-8",
    "0x2.2222222222101d0222ebe0ddccp-8",
    "0x5.b05b05b05b5c6c19e918168d1bp-12",
    "0xd.00d03eff3dcba0f544ddde5d6p-16",
    "0x1.a019fed465426867f60f2e84dd8p-16",
]

def parse_hexfloat(s):            # parse an arbitrary-precision hex float to mpf
    s = s.lower().replace("0x", "")
    mant, _, exp = s.partition("p")
    exp = int(exp)
    intpart, _, frac = mant.partition(".")
    val = mpf(int(intpart, 16)) if intpart else mpf(0)
    if frac:
        val += mpf(int(frac, 16)) / mpf(16) ** len(frac)
    return val * mpf(2) ** exp

print(f"\nconst EXP_R_COEFFS: [(f64, f64); {len(EXPR_COEFFS_HEX)}] = [")
for s in EXPR_COEFFS_HEX:
    hi, lo = dd(parse_hexfloat(s))
    print(f"    ({hexf(hi)}, {hexf(lo)}),")
print("];")

# --- constants for exp10: 10^x = exp(x·ln10) = 2^q · 2^(j/N) · exp(r) ---
from mpmath import log as mlog
ln10 = mlog(10)
ln10_hi, ln10_lo = dd(ln10)
print(f"\npub(super) const LN10_HI: f64 = {hexf(ln10_hi)};")
print(f"pub(super) const LN10_LO: f64 = {hexf(ln10_lo)};")
# 128 · log2(10), the scale mapping x to the reduction index for exp10
n_log2_10 = f64(mpf(N) * mlog(10) / mlog(2))
print(f"pub(super) const N_LOG2_10: f64 = {hexf(n_log2_10)};")

# --- S(x) = (exp(x) - 1) / x = sum_{k>=0} x^k/(k+1)! for the small-x expm1 path ---
# Double-double coefficients 1/(k+1)! (degree 9), evaluated by DD Horner so that
# expm1(x) = x * S(x) keeps full relative accuracy near zero.
from mpmath import factorial
print(f"\npub(super) const EXPM1_S_COEFFS: [(f64, f64); 10] = [")
for k in range(10):
    hi, lo = dd(mpf(1) / factorial(k + 1))
    print(f"    ({hexf(hi)}, {hexf(lo)}),")
print("];")

# --- two-level (N2 = 4096) table for exp's lean fast leg ----------------------
# exp(x) = 2^q · 2^(j/4096) · exp(dx),  j = t & 4095,  q = t >> 12,
#   t = round(x · 4096/ln2),  |dx| <= ln2/8192 ~ 2^-13.5.
# 2^(j/4096) factors as EXP2_T0[j>>6] · EXP2_T1[j&63] with
#   EXP2_T0[i] = 2^(i/64),  EXP2_T1[i] = 2^(i/4096),  0 <= i < 64.
# The finer grid (vs the N=128 table above) makes the `tl·(exp(dx)-1)` cross term
# negligible, so the fold reduces to `fl = tl + (th·dx)·p` with a degree-3 f64
# tail `p = (exp(dx)-1)/dx` — CORE-MATH's structure (no DD exp(r), no DD×DD poly).
N2 = 4096
print(f"\nconst N_OVER_LN2_4096: f64 = {hexf(f64(mpf(N2) / ln2))};")
# ln2/4096 with the low 24 significand bits of HI cleared: t·HI exact for |t| < 2^24.
step2 = ln2 / N2
b2 = struct.unpack('<Q', struct.pack('<d', f64(step2)))[0] & ~((1 << 24) - 1)
L2H = struct.unpack('<d', struct.pack('<Q', b2))[0]
L2L = f64(step2 - mpf(L2H))
print(f"const LN2_OVER_4096_HI: f64 = {hexf(L2H)};")
print(f"const LN2_OVER_4096_LO: f64 = {hexf(L2L)};")
err2 = (mpf(L2H) + mpf(L2L) - step2) / step2
print(f"// rel err of (HI+LO) vs ln2/4096: 2^{float(mp.log(abs(err2),2)):.1f}")
# p(z) = (exp(z)-1)/z = sum z^k/(k+1)!, degree 3 (Taylor; truncation ~2^-74 in result)
print(f"\nconst EXP_FAST3_COEFFS: [f64; 4] = [")
for k in range(4):
    print(f"    {hexf(f64(mpf(1) / factorial(k + 1)))},")
print("];")
for name, denom in (("EXP2_T0", 64), ("EXP2_T1", N2)):
    print(f"\nconst {name}: [(f64, f64); 64] = [")
    for i in range(64):
        hi, lo = dd(power(2, mpf(i) / denom))
        print(f"    ({hexf(hi)}, {hexf(lo)}),")
    print("];")
