#!/usr/bin/env python3
"""Generate original mathematical constants for the binary128 gamma family.

python3 tools/gen_gamma_f128.py > src/f128_/gamma_tables.rs

The local log-Gamma coefficients are derivatives, not fitted polynomials:
log Gamma(c+h) = log Gamma(c) + psi(c)h + sum (-1)^k*zeta(k,c)*h^k/k.
The asymptotic coefficients are exact Bernoulli rationals (DLMF 5.11.1).
All constants have 512 significand bits; narrow legs read their leading limbs.
"""
import mpmath as mp
mp.mp.prec = 720
W = 512


def literal(x):
    x = mp.mpf(x)
    negative = x < 0
    x = abs(x)
    if not x:
        return '(false, 0, [0; 8])'
    e = int(mp.floor(mp.log(x, 2))) + 1
    n = int(mp.floor(mp.ldexp(x, W-e)))
    assert 1 << (W-1) <= n < 1 << W
    words = ', '.join(f'0x{(n >> (64*j)) & ((1<<64)-1):016x}' for j in range(8))
    return f'({str(negative).lower()}, {e}, [{words}])'


def scalar(name, x):
    print('#[rustfmt::skip]')
    print(f'pub const {name}: Constant = {literal(x)};')


def table(name, values, doc):
    print(f'\n/// {doc}')
    print('/// Generate: `python3 tools/gen_gamma_f128.py > src/f128_/gamma_tables.rs`.')
    print('#[rustfmt::skip]')
    print(f'pub const {name}: [Constant; {len(values)}] = [')
    for x in values:
        print(f'    {literal(x)},')
    print('];')


print('''//! Generated by tools/gen_gamma_f128.py; do not edit by hand.
//! Mathematical derivatives, exact Bernoulli rationals, and elementary constants.
#![allow(clippy::unreadable_literal)]
pub type Constant = (bool, i32, [u64; 8]);''')
scalar('LN2', mp.log(2))
scalar('LOG2E', 1/mp.log(2))
scalar('PI', mp.pi)
scalar('HALF_LOG_TAU', mp.log(2*mp.pi)/2)
table('LOG', [mp.log(mp.mpf(j)/64) for j in range(64, 129)], 'ln(j/64), j=64..128.')
table('EXP2', [mp.power(2, mp.mpf(j)/64) for j in range(64)], '2^(j/64), j=0..63.')
table('LOG_COEF', [mp.mpf(1)/k for k in range(1, 79)],
      'Exact Taylor magnitudes 1/k, k=1..78, for log(1+z).')
table('EXP_COEF', [1/mp.factorial(k) for k in range(49)],
      'Exact Taylor constants 1/k!, k=0..48, for exp(r).')
table('SINC_COEF', [1/mp.factorial(2*k+1) for k in range(55)],
      'Exact Taylor magnitudes 1/(2k+1)!, k=0..54, for sin(t)/t.')
table('STIRLING', [mp.bernoulli(2*k)/(2*k*(2*k-1)) for k in range(1, 113)],
      'B_(2k)/(2k(2k-1)), k=1..112 (DLMF 5.11.1).')
print('\n/// Taylor derivatives of log Gamma at c=1+j/16, j=0..16.')
print('/// Generate: `python3 tools/gen_gamma_f128.py > src/f128_/gamma_tables.rs`.')
print('#[rustfmt::skip]')
print('pub const LGAMMA: [[Constant; 105]; 17] = [')
for j in range(17):
    c = 1 + mp.mpf(j)/16
    values = [mp.loggamma(c), mp.digamma(c)]
    values += [(-1)**k * mp.zeta(k, c)/k for k in range(2, 105)]
    print('    [')
    for x in values:
        print(f'        {literal(x)},')
    print('    ],')
print('];')
# First omitted Stirling term bounds the remainder on the positive real axis.
assert abs(mp.bernoulli(226)/(226*225*mp.mpf(64)**225)) < mp.ldexp(1,-517)
assert abs(mp.bernoulli(42)/(42*41*mp.mpf(64)**41)) < mp.ldexp(1,-197)
assert mp.zeta(105)*mp.mpf(1/32)**105/105 * 32/31 < mp.ldexp(1,-530)
assert mp.zeta(37)*mp.mpf(1/32)**37/37 * 32/31 < mp.ldexp(1,-190)
assert mp.mpf(1/128)**28/28 * 128/127 < mp.ldexp(1,-200)
assert mp.mpf(1/128)**79/79 * 128/127 < mp.ldexp(1,-552)
assert (mp.log(2)/64)**21/mp.factorial(21)*mp.exp(mp.log(2)/64) < mp.ldexp(1,-202)
assert (mp.log(2)/64)**49/mp.factorial(49)*mp.exp(mp.log(2)/64) < mp.ldexp(1,-528)
assert (mp.pi/2)**52/mp.factorial(53) < mp.ldexp(1,-197)
assert (mp.pi/2)**110/mp.factorial(111) < mp.ldexp(1,-527)
# Positive integer arguments can yield exact results and true midpoints; the
# factorials are integers, rounded with integer arithmetic, not MPFR values.
factorials=[]
p=1
for n in range(1, 1757):
    if n > 1:
        p *= n-1
    e=p.bit_length()-1
    s=e-112
    if s > 0:
        m,r=divmod(p,1<<s)
        half=1<<(s-1)
        m += r>half or (r==half and m&1)
        if m == 1<<113:
            m >>= 1
            e += 1
    else:
        m=p << -s
    b=((e+16383)<<112) + m-(1<<112) if e<16384 else 0x7fff<<112
    factorials.append(b)
print('\n/// Exactly rounded (n-1)!, n=1..1756, generated with Python integers.')
print('/// Generate: `python3 tools/gen_gamma_f128.py > src/f128_/gamma_tables.rs`.')
print('#[rustfmt::skip]')
print(f'pub const FACTORIAL: [u128; {len(factorials)}] = [')
for i in range(0,len(factorials),4):
    print('    '+', '.join(f'0x{x:032x}' for x in factorials[i:i+4])+',')
print('];')
