#!/usr/bin/env python3
"""Generate the constants for `f64::tgamma` (and shared `gamma.rs` pieces).

Run:  python3 tools/gen_gamma_f64.py        (paste the output into src/f64/gamma.rs)

Design (recurrence around a central minimax, mirroring `f32::tgamma`):
  Reduce z into [2.375, 3.375] by `i = round(z − 2.875)`, evaluate Γ(2.875 + d)
  with a double-double minimax (`d ∈ [−½, ½]`), then walk the recurrence
  Γ(z) = Γ(z−i)·∏(z−k)  (i > 0)  or  Γ(z) = Γ(z−i)/∏(z+k)  (i < 0).  The factors
  are formed exactly as double-doubles (`from_sum(z, k)`), and for very negative z
  the divisor product is accumulated with a binary exponent so it never overflows.

The accurate path runs entirely in double-double (≈2⁻¹¹⁰); residual hard-to-round
cases are caught by the MPFR corpus and patched with `match` fixups.
"""
from mpmath import mp, mpf, gamma, chebyfit, floor, pi, sin, log, bernoulli
import struct

mp.prec = 400


def f64(x):
    return struct.unpack('<d', struct.pack('<d', float(x)))[0]


def dd(x):
    hi = f64(x)
    lo = f64(x - mpf(hi))
    return hi, lo


def hexf(v):
    return repr(float(v))


def fit(f, a, b, target):
    for n in range(4, 32):
        coeffs, err = chebyfit(f, [a, b], n, error=True)
        if err < target:
            return list(reversed(coeffs)), err, n - 1
    coeffs, err = chebyfit(f, [a, b], 32, error=True)
    return list(reversed(coeffs)), err, 31


def print_dd_array(name, coeffs, doc):
    print(f"\n/// {doc}")
    print(f"const {name}: [DoubleDouble; {len(coeffs)}] = [")
    for c in coeffs:
        hi, lo = dd(c)
        print(f"    DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }},")
    print("];")


TARGET = mpf(2) ** -110
CENTER = mpf("2.875")

print("// generated by tools/gen_gamma_f64.py")

# --- Γ(2.875 + d) on d ∈ [−½, ½] ------------------------------------------
coeffs, err, deg = fit(lambda d: gamma(CENTER + d), mpf("-0.5"), mpf("0.5"), TARGET)
print(f"// Γ(2.875 + d), d ∈ [−½, ½]: degree {deg}, err 2^{float(mp.log(err,2)):.1f}")
print(f"\n/// Center of the tgamma minimax interval, `Γ(TGAMMA_CENTER + d)`")
print(f"const TGAMMA_CENTER: f64 = {hexf(f64(CENTER))};")
print_dd_array("TGAMMA_DD", coeffs,
               f"Accurate `Γ(2.875 + d)` minimax, double-double (degree {deg}, ≈2⁻¹¹⁰)")

# --- tgamma fast-leg table (per-cell minimax, mixed precision) --------------
# Per cell i (centre 2.875 + i/8) a degree-TABLE_DEG minimax of
# Γ(2.875 + i/8 + h) in h ∈ [−1/16, 1/16].  c0..c3 are stored double-double,
# c4.. as a plain-f64 tail (those terms are ≲2⁻¹⁹ of Γ, so f64 lands them near
# 2⁻⁷¹).  Ziv-gated against TGAMMA_DD (the accurate path).  The `GammaCell`
# struct is hand-written in gamma.rs; this emits only the `TGAMMA_TABLE` array.
TABLE_W = mpf(1) / 16          # half-width: cells of width 1/8
TABLE_DEG = 11                 # c0..c11; c4..c11 form the f64 tail
TABLE_ILO, TABLE_IHI = -4, 4   # centre 2.875 + i/8, covering d ∈ [−½, ½]

table_rows = []
table_worst = -mp.inf
tail_worst = -mp.inf           # |c4|·W⁴ relative to Γ: the f64 tail's share
for i in range(TABLE_ILO, TABLE_IHI + 1):
    ci = CENTER + mpf(i) / 8
    coeffs, err = chebyfit(lambda h, ci=ci: gamma(ci + h), [-TABLE_W, TABLE_W],
                           TABLE_DEG + 1, error=True)
    coeffs = list(reversed(coeffs))
    table_rows.append(coeffs)
    table_worst = max(table_worst, mp.log(err, 2))
    tail_worst = max(tail_worst, mp.log(abs(coeffs[4]) * TABLE_W ** 4 / gamma(ci), 2))

print(f"\n/// Fast-path table for `Γ(2.875 + d)`, `d ∈ [−½, ½]`: per-cell minimax of")
print(f"/// `Γ(2.875 + i/8 + h)` in `h ∈ [−1/16, 1/16]`, cells of width 1/8,")
print(f"/// `i ∈ [{TABLE_ILO}, {TABLE_IHI}]`.  Degree {TABLE_DEG} (`c0..c3` double-double, `c4..c{TABLE_DEG}` plain")
print(f"/// `f64`); worst-cell minimax error 2^{float(table_worst):.0f}, f64 tail ≤ 2^{float(tail_worst):.0f} of Γ.")
print(f"/// From `tools/gen_gamma_f64.py`.")
print(f"const TGAMMA_TABLE: [GammaCell; {TABLE_IHI - TABLE_ILO + 1}] = [")
for coeffs in table_rows:
    print("    GammaCell {")
    for k in range(4):
        hi, lo = dd(coeffs[k])
        print(f"        c{k}: DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }},")
    tail = ", ".join(hexf(f64(c)) for c in coeffs[4:])
    print(f"        tail: [{tail}],")
    print("    },")
print("];")

# --- thresholds -----------------------------------------------------------
MAX = mpf(f64(__import__('sys').float_info.max))
MAX_HALF_ULP = MAX + mpf(2) ** (1024 - 53 - 1)   # MAX + ½ ulp(MAX): rounds to +∞ above this
# overflow: smallest z with Γ(z) >= MAX + ½ ulp
lo, hi = mpf(171), mpf(172)
for _ in range(200):
    mid = (lo + hi) / 2
    if gamma(mid) >= MAX_HALF_ULP:
        hi = mid
    else:
        lo = mid
overflow = f64(hi)
# tiny: |z| below which Γ(z) ≈ 1/z overflows.  Γ(z) = 1/z − γ + …, rounds to ∞
# when 1/z − γ >= MAX + ½ ulp, i.e. z <= 1/(MAX_HALF_ULP + γ).
gamma_const = mpf("0.5772156649015328606")
tiny = f64(1 / (MAX_HALF_ULP + gamma_const))
# underflow: most-negative-but-one half-integer hump still ≥ ½ smallest subnormal.
# Below the z where every hump rounds to 0, return a signed zero.
SUBN_HALF = mpf(2) ** (-1074 - 1)
z = mpf("-180.5")
while abs(gamma(z)) >= SUBN_HALF:
    z -= 1
underflow = f64(z + 1)   # last half-integer with a representable hump, minus margin

print(f"\n/// `Γ(z)` overflows to `+∞` at and above this `z`")
print(f"const TGAMMA_OVERFLOW: f64 = {hexf(overflow)};")
print(f"\n/// Below this `|z|`, the pole `Γ(z) ≈ 1/z` overflows to `±∞`")
print(f"const TGAMMA_TINY: f64 = {hexf(tiny)};")
print(f"\n/// At or below this `z`, every `Γ(z)` hump rounds to a signed zero")
print(f"const TGAMMA_UNDERFLOW: f64 = {hexf(underflow)};")
print(f"// checks: Γ(overflow)≈{float(gamma(mpf(overflow))):.3e} (MAX={float(MAX):.3e}); "
      f"Γ(tiny)≈{float(1/mpf(tiny)):.3e}; |Γ(underflow)|≈{float(abs(gamma(mpf(underflow)))):.3e}")

# --- lgamma constants -----------------------------------------------------
# ln Γ(t) for t ≥ CUTOFF via Stirling; below it, reduce up by ln Γ(y) = ln Γ(t)
# − ln ∏(y+j).  The asymptotic tail Σ_{k≥1} B_2k/(2k(2k−1)) t^(1−2k) = P(u)/t with
# u = 1/t² is carried in double-double (its leading 1/(12t) needs > f64 precision).


def dd_const(name, value, doc):
    hi, lo = dd(value)
    print(f"\n/// {doc}")
    print(f"const {name}: DoubleDouble = DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }};")


# A high cutoff keeps the Bernoulli tail short (K ≈ 10): with few terms the
# coefficients stay O(1), so Horner over them does not catastrophically cancel (at
# t = 14 the K = 19 terms reach 3·10¹¹ and lose ~42 bits; at t = 40, ~4 bits).
LGAMMA_CUTOFF = 40
print(f"\n/// Argument above which the Stirling series for `ln Γ` converges fast enough for")
print(f"/// the **accurate** double-double path (a long Bernoulli tail, ≈2⁻¹⁰⁸ at `t = 40`)")
print(f"const LGAMMA_CUTOFF: f64 = {hexf(f64(LGAMMA_CUTOFF))};")

# The lean leg only needs ≈2⁻⁵⁶ (its Ziv gate), so it starts Stirling far below the
# accurate cutoff: at t = 8 the 10-term f64 tail truncates below 2⁻⁵⁹ and its terms
# still shrink monotonically (no Horner cancellation).  Below this, the lean leg
# reduces with a recurrence of ≤ 8 steps (was ≤ 40).
LGAMMA_FAST_CUTOFF = 8
print(f"\n/// Argument above which the **fast** leg takes Stirling directly (no recurrence)")
print("///")
print("/// The lean leg only needs ≈2⁻⁵⁶ (its Ziv gate), so it can start Stirling far")
print("/// below the accurate path's [`LGAMMA_CUTOFF`]: the 10-term [`LGAMMA_TAIL_F64`]")
print("/// truncates below 2⁻⁵⁹ at `t = 8` and its terms still shrink monotonically there")
print("/// (no Horner cancellation).  Dropping the cutoff from 40 to 8 turns the whole")
print("/// `[8, 40)` band into a recurrence-free direct Stirling and caps the `[½, 8)`")
print("/// recurrence at ≤ 8 steps (was ≤ 40) — the dominant cost for moderate `z`.")
print(f"const LGAMMA_FAST_CUTOFF: f64 = {hexf(f64(LGAMMA_FAST_CUTOFF))};")

dd_const("LN_PI", log(pi),
         "`ln π` as a double-double, the additive constant of the lgamma reflection\n///\n"
         "/// Precomputed so the reflection never pays a logarithm for the constant `π`.")
dd_const("HALF_LN_2PI", log(2 * pi) / 2, "`½·ln(2π)`, the additive Stirling constant")

# Stirling tail coefficients c_k = B_2k / (2k(2k−1)), as P(u) = Σ c_k u^(k-1).
# Pick K so the truncation residual at t = CUTOFF is below 2⁻¹⁰⁵.
def tail_partial(t, K):
    return sum(bernoulli(2 * k) / (2 * k * (2 * k - 1)) * t ** (1 - 2 * k) for k in range(1, K + 1))

t = mpf(LGAMMA_CUTOFF)
true_tail = tail_partial(t, 60)
K = 1
while abs(tail_partial(t, K) - true_tail) > mpf(2) ** -105 and K < 30:
    K += 1
resid = abs(tail_partial(t, K) - true_tail)
coeffs = [bernoulli(2 * k) / (2 * k * (2 * k - 1)) for k in range(1, K + 1)]
print(f"// lgamma Stirling tail: {K} double-double coeffs, residual at t={LGAMMA_CUTOFF} is "
      f"2^{float(mp.log(resid,2)):.1f}, max|c|={float(max(abs(c) for c in coeffs)):.2e}")
print_dd_array("LGAMMA_TAIL_DD", coeffs,
               f"Stirling tail `P(u) = Σ B_2k/(2k(2k−1)) u^(k−1)`, `u = 1/t²` ({K} terms, double-double)")

# The Ziv fast legs evaluate the tail in plain f64 over two regimes, each taking
# just enough terms that the truncation at its floor `t` is under the 2⁻⁵⁶ gate.
# The series is asymptotic (it diverges past its minimum term near 2k ≈ 2πt), so
# the truncation after N terms is the first omitted term, not the difference to a
# longer — divergent — partial sum.

def first_omitted(N, t):
    j = N + 1
    return abs(bernoulli(2 * j) / (2 * j * (2 * j - 1)) * mpf(t) ** (1 - 2 * j))

# Cutoff-8 leg (`lgamma_pos_fast`, reduces to t ≥ LGAMMA_FAST_CUTOFF): take all K
# terms.  At t = 8 they truncate well under the gate yet still shrink monotonically
# (c_k grows ~×8 per term, u = 1/t² ≤ 2⁻⁶ shrinks ×64), so the f64 Horner does not
# cancel.
TAIL_F64 = K
fast_resid = first_omitted(TAIL_F64, LGAMMA_FAST_CUTOFF)
f64_tail = ", ".join(hexf(f64(c)) for c in coeffs[:TAIL_F64])
print(f"\n/// Stirling tail in plain `f64` for the cutoff-8 fast leg (all {TAIL_F64} high words of")
print(f"/// [`LGAMMA_TAIL_DD`])")
print("///")
print(f"/// [`lgamma_pos_fast`] reduces to `t ≥ LGAMMA_FAST_CUTOFF = {LGAMMA_FAST_CUTOFF}`, where")
print(f"/// `u = 1/t² ≤ 2⁻⁶`.  The {TAIL_F64} terms truncate at 2^{float(mp.log(fast_resid,2)):.1f}"
      " there (and still shrink")
print("/// monotonically — no Horner cancellation), inside the leg's 2⁻⁵⁶ Ziv gate.  The")
print("/// hot `z ≥ 40` leg uses the shorter [`LGAMMA_TAIL_F64_FAR`]; the accurate fallback")
print("/// and the reduced/reflection paths use the double-double [`LGAMMA_TAIL_DD`].")
print(f"const LGAMMA_TAIL_F64: [f64; {TAIL_F64}] = [{f64_tail}];")

# Large-z leg (`lgamma_stirling_fast`, z ≥ LGAMMA_CUTOFF): the smallest N whose
# first omitted term at t = CUTOFF is far below the result's ulp (2⁻⁷⁰ ≪ the gate
# and the large-z ln_fast floor), i.e. the validated original count.
TAIL_FAR = next(N for N in range(1, K + 1) if first_omitted(N, LGAMMA_CUTOFF) < mpf(2) ** -70)
far_resid = first_omitted(TAIL_FAR, LGAMMA_CUTOFF)
far_tail = ", ".join(hexf(f64(c)) for c in coeffs[:TAIL_FAR])
print(f"\n/// Stirling tail in plain `f64` for the hot large-`z` leg (the leading {TAIL_FAR} high words")
print(f"/// of [`LGAMMA_TAIL_DD`])")
print("///")
print(f"/// [`lgamma_stirling_fast`] runs only at `z ≥ LGAMMA_CUTOFF = {LGAMMA_CUTOFF}`, where")
print(f"/// `u = 1/z² ≤ 2⁻¹⁰·⁶`, so {TAIL_FAR} terms truncate at 2^{float(mp.log(far_resid,2)):.1f}"
      " — far below the result's")
print("/// ulp — no need to evaluate the extra terms [`LGAMMA_TAIL_F64`] carries to `t = 8`.")
print(f"const LGAMMA_TAIL_F64_FAR: [f64; {TAIL_FAR}] = [{far_tail}];")
