#!/usr/bin/env python3
"""Generate the exact-`z` reduction cells for the f64 `ln` fast leg.

Geometry: `x = 2^e·m`, `m ∈ [1, 2)`, `j` = top 7 fraction bits, so the cell is
`m ∈ [a, b)`, `a = 1 + j/128`, `b = a + 1/128`.  Each cell stores a reciprocal
`r` that is an integer multiple of 2⁻⁸ chosen so that `z = r·m − 1` is **exact**
in one `f64` for every mantissa `m` in the cell:

    r·m is an integer multiple of 2⁻⁸·2⁻⁵² = 2⁻⁶⁰, hence so is z = r·m − 1;
    |z| ≤ 2⁻⁷ keeps z within 2⁵³ multiples of 2⁻⁶⁰, so z is representable
    and `fma(r, m, −1)` rounds to it exactly.

This is a pure lattice argument — the generator verifies `|z| ≤ 2⁻⁷` at both
cell ends in exact rational arithmetic (z is monotonic in m), no per-cell
floating-point proof needed.  Among the feasible `r` it picks the one with the
smallest max |z| over the cell, so the kernel range stays near 2⁻⁸ (the global
maximum is printed below and quoted in `log.rs`).

The cell also stores `−ln r` as `l1 + l2` with `l1` the nearest integer
multiple of 2⁻⁴², mirroring `LN2_HI`'s split: `e·LN2_HI + l1` is then a sum of
two integer multiples of 2⁻⁴² bounded by `1074·ln2 + ln2 < 746 < 2¹¹`, hence
exact in a single `fma(e, LN2_HI, l1)` (at most 2⁵³ multiples of 2⁻⁴²).
`l2 = RN(−ln r − l1)` with `|l2| ≤ 2⁻⁴³` completes `−ln r` to within 2⁻⁹⁶.

Orderings asserted per cell so `fast_sum(e·LN2_HI + l1, z)` is a valid Fast2Sum:
  e = 0:   l1 ≥ max|z|                       (also rejects r = 1, where l1 = 0)
  e = −1:  l1 − LN2_HI == 0 (cell 127, r = ½) or LN2_HI − l1 ≥ max|z|
  otherwise |e·LN2_HI + l1| ≥ 2·LN2_HI − max l1 > 0.69 > max|z| since l1 ≤ ln 2.
"""

import struct
from fractions import Fraction

from mpmath import mp, mpf
from mpmath import log as mlog

mp.prec = 250

N = 128  # cells over m in [1, 2)
RGRID = 256  # r = q/RGRID; exactness bound |z| <= 2^53·(2^-8·2^-52) = 2/RGRID
BOUND = Fraction(2, RGRID)
ULP = Fraction(1, 1 << 52)
GRID42 = 1 << 42


def f64(x):
    return struct.unpack("<d", struct.pack("<d", float(x)))[0]


# LN2_HI exactly as log.rs defines it (low 11 bits cleared => multiple of 2^-42)
ln2 = mlog(2)
bits = struct.unpack("<Q", struct.pack("<d", f64(ln2)))[0] & ~((1 << 11) - 1)
LN2_HI = struct.unpack("<d", struct.pack("<Q", bits))[0]
K_LN2 = Fraction(LN2_HI) * GRID42
assert K_LN2.denominator == 1
K_LN2 = int(K_LN2)

cells = []
z_max = Fraction(0)
margin_e0 = None  # min(l1 - max|z|) over cells: e = 0 Fast2Sum slack
margin_e1 = None  # min(|l1 - LN2_HI| - max|z|) over cells with l1 != LN2_HI

for j in range(N):
    a = 1 + Fraction(j, N)
    b_max = 1 + Fraction(j + 1, N) - ULP
    best = None
    for q in range(RGRID // 2, RGRID + 1):
        r = Fraction(q, RGRID)
        maxz = max(abs(r * a - 1), abs(r * b_max - 1))
        if maxz > BOUND:
            continue
        lnr = -mlog(mpf(q) / RGRID)
        k1 = int(mp.nint(lnr * GRID42))
        if Fraction(k1, GRID42) < maxz:  # e = 0 ordering
            continue
        d = abs(k1 - K_LN2)
        if d != 0 and Fraction(d, GRID42) < maxz:  # e = -1 ordering
            continue
        if best is None or maxz < best[0]:
            best = (maxz, q, k1, lnr)
    assert best is not None, f"cell {j}: no feasible r"
    maxz, q, k1, lnr = best

    l1 = k1 / float(GRID42)
    assert Fraction(l1) == Fraction(k1, GRID42), "l1 not exact"
    assert abs(k1) + 1074 * K_LN2 < 1 << 53, "e*LN2_HI + l1 not exact"
    l2 = f64(lnr - mpf(l1))
    assert abs(l2) <= 2.0**-43, "l2 exceeds half the l1 grid"
    assert abs(mpf(l1) + mpf(l2) - lnr) < mpf(2) ** -96, "l1 + l2 off -ln r"
    assert mpf(l1) <= ln2, "l1 above ln 2"

    z_max = max(z_max, maxz)
    e0 = Fraction(k1, GRID42) - maxz
    margin_e0 = e0 if margin_e0 is None else min(margin_e0, e0)
    if k1 != K_LN2:
        e1 = Fraction(abs(k1 - K_LN2), GRID42) - maxz
        margin_e1 = e1 if margin_e1 is None else min(margin_e1, e1)
    cells.append((q, l1, l2))

print(f"// Generated by `tools/gen_ln_exact_f64.py`; do not edit by hand.")
print(f"// max |z| over all cells: {float(z_max):.6e} = 2^{float(mlog(z_max, 2)):.3f}")
print(f"// Fast2Sum slack, e =  0: min(l1 − max|z|)          = {float(margin_e0):.3e}")
print(f"// Fast2Sum slack, e = −1: min(|l1 − LN2_HI| − max|z|) = {float(margin_e1):.3e}")
print(f"const LN_CELLS: [LnCell; {N}] = [")
for q, l1, l2 in cells:
    r = q / RGRID
    print(f"    LnCell {{ r: {r!r}, l1: {l1!r}, l2: {l2!r} }},")
print("];")
