#!/usr/bin/env python3
"""Generate Dint (128-bit) accurate-path constants for f64 trig.

Emits PIO2_DINT, SIN_DINT (Taylor of sin(r)/r in u=r^2), COS_DINT (Taylor of
cos(r) in u=r^2), and TWO_DINT, as Dint literals matching dint_consts.rs.

Value = (-1)^sgn * (m / 2^127) * 2^ex, m normalized so bit 127 set.
"""
from mpmath import mp, mpf, factorial, pi, log, floor, nint

mp.prec = 600


def to_dint(x):
    x = mpf(x)
    sgn = x < 0
    a = abs(x)
    if a == 0:
        return (False, 0, 0)
    ex = int(floor(log(a, 2)))
    mant = a / mpf(2) ** ex            # in [1, 2)
    m = int(nint(mant * mpf(2) ** 127))
    if m >= (1 << 128):                # rounding overflow
        m >>= 1
        ex += 1
    assert (1 << 127) <= m < (1 << 128)
    return (bool(sgn), ex, m)


def emit_one(name, x):
    sgn, ex, m = to_dint(x)
    print(f"const {name}: Dint = Dint {{")
    print(f"    sgn: {'true' if sgn else 'false'},")
    print(f"    ex: {ex},")
    print(f"    m: 0x{m:032x},")
    print("};\n")


def emit_array(name, values):
    print(f"const {name}: [Dint; {len(values)}] = [")
    for x in values:
        sgn, ex, m = to_dint(x)
        print("    Dint {")
        print(f"        sgn: {'true' if sgn else 'false'},")
        print(f"        ex: {ex},")
        print(f"        m: 0x{m:032x},")
        print("    },")
    print("];\n")


U_MAX = (pi / 4) ** 2

# sin(r)/r = sum_k (-1)^k u^k / (2k+1)!  ; cos(r) = sum_k (-1)^k u^k / (2k)!
# Pick term counts so the truncation tail < 2^-130 at u = U_MAX.
def n_terms(coeff, target_bits=130):
    n = 1
    while True:
        tail = abs(coeff(n)) * U_MAX ** n
        if tail < mpf(2) ** (-target_bits):
            return n
        n += 1


sin_c = lambda k: mpf((-1) ** k) / factorial(2 * k + 1)
cos_c = lambda k: mpf((-1) ** k) / factorial(2 * k)

NSIN = n_terms(sin_c)
NCOS = n_terms(cos_c)

print(f"// Dint accurate-path trig constants. GENERATED by tools/gen_dint_trig.py.")
print(f"// sin uses {NSIN} terms (tail ~2^{float(log(abs(sin_c(NSIN))*U_MAX**NSIN,2)):.1f}),"
      f" cos uses {NCOS} terms (tail ~2^{float(log(abs(cos_c(NCOS))*U_MAX**NCOS,2)):.1f}).")
print()
emit_one("PIO2_DINT", pi / 2)
emit_one("TWO_DINT", 2)
emit_array("SIN_DINT", [sin_c(k) for k in range(NSIN)])
emit_array("COS_DINT", [cos_c(k) for k in range(NCOS)])
