#!/usr/bin/env python3
"""Generate the constants for `f64::tgamma` (and shared `gamma.rs` pieces).

Run:  python3 tools/gen_gamma_f64.py        (paste the output into src/f64/gamma.rs)

Design (recurrence around a central minimax, mirroring `f32::tgamma`):
  Reduce z into [2.375, 3.375] by `i = round(z − 2.875)`, evaluate Γ(2.875 + d)
  with a double-double minimax (`d ∈ [−½, ½]`), then walk the recurrence
  Γ(z) = Γ(z−i)·∏(z−k)  (i > 0)  or  Γ(z) = Γ(z−i)/∏(z+k)  (i < 0).  The factors
  are formed exactly as double-doubles (`from_sum(z, k)`), and for very negative z
  the divisor product is accumulated with a binary exponent so it never overflows.

The accurate path runs entirely in double-double (≈2⁻¹¹⁰); residual hard-to-round
cases are caught by the MPFR corpus and patched with `match` fixups.
"""
from mpmath import mp, mpf, gamma, chebyfit, floor, pi, sin, log, bernoulli
import struct

mp.prec = 400


def f64(x):
    return struct.unpack('<d', struct.pack('<d', float(x)))[0]


def dd(x):
    hi = f64(x)
    lo = f64(x - mpf(hi))
    return hi, lo


def hexf(v):
    return repr(float(v))


def fit(f, a, b, target):
    for n in range(4, 32):
        coeffs, err = chebyfit(f, [a, b], n, error=True)
        if err < target:
            return list(reversed(coeffs)), err, n - 1
    coeffs, err = chebyfit(f, [a, b], 32, error=True)
    return list(reversed(coeffs)), err, 31


def print_dd_array(name, coeffs, doc):
    print(f"\n/// {doc}")
    print(f"const {name}: [DoubleDouble; {len(coeffs)}] = [")
    for c in coeffs:
        hi, lo = dd(c)
        print(f"    DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }},")
    print("];")


TARGET = mpf(2) ** -110
TARGET_FAST = mpf(2) ** -72
CENTER = mpf("2.875")

print("// generated by tools/gen_gamma_f64.py")

# --- Γ(2.875 + d) on d ∈ [−½, ½] ------------------------------------------
coeffs, err, deg = fit(lambda d: gamma(CENTER + d), mpf("-0.5"), mpf("0.5"), TARGET)
print(f"// Γ(2.875 + d), d ∈ [−½, ½]: degree {deg}, err 2^{float(mp.log(err,2)):.1f}")
print(f"\n/// Center of the tgamma minimax interval, `Γ(TGAMMA_CENTER + d)`")
print(f"const TGAMMA_CENTER: f64 = {hexf(f64(CENTER))};")
print_dd_array("TGAMMA_DD", coeffs,
               f"Accurate `Γ(2.875 + d)` minimax, double-double (degree {deg}, ≈2⁻¹¹⁰)")

fcoeffs, ferr, fdeg = fit(lambda d: gamma(CENTER + d), mpf("-0.5"), mpf("0.5"), TARGET_FAST)
print_dd_array("TGAMMA_FAST", fcoeffs,
               f"Fast lower-degree `Γ(2.875 + d)` minimax (degree {fdeg}, ≈2⁻⁷²)")

# --- thresholds -----------------------------------------------------------
MAX = mpf(f64(__import__('sys').float_info.max))
MAX_HALF_ULP = MAX + mpf(2) ** (1024 - 53 - 1)   # MAX + ½ ulp(MAX): rounds to +∞ above this
# overflow: smallest z with Γ(z) >= MAX + ½ ulp
lo, hi = mpf(171), mpf(172)
for _ in range(200):
    mid = (lo + hi) / 2
    if gamma(mid) >= MAX_HALF_ULP:
        hi = mid
    else:
        lo = mid
overflow = f64(hi)
# tiny: |z| below which Γ(z) ≈ 1/z overflows.  Γ(z) = 1/z − γ + …, rounds to ∞
# when 1/z − γ >= MAX + ½ ulp, i.e. z <= 1/(MAX_HALF_ULP + γ).
gamma_const = mpf("0.5772156649015328606")
tiny = f64(1 / (MAX_HALF_ULP + gamma_const))
# underflow: most-negative-but-one half-integer hump still ≥ ½ smallest subnormal.
# Below the z where every hump rounds to 0, return a signed zero.
SUBN_HALF = mpf(2) ** (-1074 - 1)
z = mpf("-180.5")
while abs(gamma(z)) >= SUBN_HALF:
    z -= 1
underflow = f64(z + 1)   # last half-integer with a representable hump, minus margin

print(f"\n/// `Γ(z)` overflows to `+∞` at and above this `z`")
print(f"const TGAMMA_OVERFLOW: f64 = {hexf(overflow)};")
print(f"\n/// Below this `|z|`, the pole `Γ(z) ≈ 1/z` overflows to `±∞`")
print(f"const TGAMMA_TINY: f64 = {hexf(tiny)};")
print(f"\n/// At or below this `z`, every `Γ(z)` hump rounds to a signed zero")
print(f"const TGAMMA_UNDERFLOW: f64 = {hexf(underflow)};")
print(f"// checks: Γ(overflow)≈{float(gamma(mpf(overflow))):.3e} (MAX={float(MAX):.3e}); "
      f"Γ(tiny)≈{float(1/mpf(tiny)):.3e}; |Γ(underflow)|≈{float(abs(gamma(mpf(underflow)))):.3e}")

# --- lgamma constants -----------------------------------------------------
# ln Γ(t) for t ≥ CUTOFF via Stirling; below it, reduce up by ln Γ(y) = ln Γ(t)
# − ln ∏(y+j).  The asymptotic tail Σ_{k≥1} B_2k/(2k(2k−1)) t^(1−2k) = P(u)/t with
# u = 1/t² is carried in double-double (its leading 1/(12t) needs > f64 precision).


def dd_const(name, value, doc):
    hi, lo = dd(value)
    print(f"\n/// {doc}")
    print(f"const {name}: DoubleDouble = DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }};")


# A high cutoff keeps the Bernoulli tail short (K ≈ 10): with few terms the
# coefficients stay O(1), so Horner over them does not catastrophically cancel (at
# t = 14 the K = 19 terms reach 3·10¹¹ and lose ~42 bits; at t = 40, ~4 bits).
LGAMMA_CUTOFF = 40
print(f"\n/// Argument above which the Stirling series for `ln Γ` converges fast enough")
print(f"const LGAMMA_CUTOFF: f64 = {hexf(f64(LGAMMA_CUTOFF))};")

dd_const("GAMMA_PI", pi, "π as a double-double (the lgamma reflection's `ln π`)")
dd_const("HALF_LN_2PI", log(2 * pi) / 2, "`½·ln(2π)`, the additive Stirling constant")

# Stirling tail coefficients c_k = B_2k / (2k(2k−1)), as P(u) = Σ c_k u^(k-1).
# Pick K so the truncation residual at t = CUTOFF is below 2⁻¹⁰⁵.
def tail_partial(t, K):
    return sum(bernoulli(2 * k) / (2 * k * (2 * k - 1)) * t ** (1 - 2 * k) for k in range(1, K + 1))

t = mpf(LGAMMA_CUTOFF)
true_tail = tail_partial(t, 60)
K = 1
while abs(tail_partial(t, K) - true_tail) > mpf(2) ** -105 and K < 30:
    K += 1
resid = abs(tail_partial(t, K) - true_tail)
coeffs = [bernoulli(2 * k) / (2 * k * (2 * k - 1)) for k in range(1, K + 1)]
print(f"// lgamma Stirling tail: {K} double-double coeffs, residual at t={LGAMMA_CUTOFF} is "
      f"2^{float(mp.log(resid,2)):.1f}, max|c|={float(max(abs(c) for c in coeffs)):.2e}")
print_dd_array("LGAMMA_TAIL_DD", coeffs,
               f"Stirling tail `P(u) = Σ B_2k/(2k(2k−1)) u^(k−1)`, `u = 1/t²` ({K} terms, double-double)")
