#!/usr/bin/env python3
"""Generate the constants for `f64::erf` / `f64::erfc`.

Run:  python3 tools/gen_erf_f64.py        (paste the output into src/f64/erf.rs)

Design
------
* erf_small (|x| < 0.4375):  erf(x) = x·P(x²), with P a double-double minimax of
  erf(√u)/√u on u ∈ [0, 0.4375²].  c[0] is the correctly-rounded 2/√π.

* erfc (x ≥ 0.4375):  erfc(x) = t·exp(Q(t) − x²) with t = 2/(2+x), where
  Q(t) = x² + ln(erfc(x)) − ln(t)  is a smooth O(1) function (it tends to a
  constant as x → ∞ because the t-factor pulls out the leading 1/x asymptotic).
  A *single* high-degree monomial fit of Q over the whole interval cancels
  catastrophically (coeffs ~1e7), so we DOMAIN-SPLIT x into a few segments and
  fit Q per segment in the small anchored variable v = t − t_anchor (v ≥ 0,
  v ≤ width), so high-degree terms shrink and the coefficients stay O(1) — a
  well-conditioned double-double Horner.

Targets ≈2⁻¹¹⁰ approximation error so the double-double evaluation lands well
inside f64 correct-rounding hardness (the rare residual cases are caught by the
core-math sweep and patched with `match` fixups, like the f32 trig functions).
"""
from mpmath import mp, mpf, erf, erfc, log, sqrt, chebyfit, polyval
import struct

mp.prec = 400


def f64(x):                       # round a high-precision value to nearest f64
    return struct.unpack('<d', struct.pack('<d', float(x)))[0]


def dd(x):                        # split a high-precision value into (hi, lo) f64
    hi = f64(x)
    lo = f64(x - mpf(hi))
    return hi, lo


def hexf(v):
    return repr(float(v))


TARGET = mpf(2) ** -110       # accurate (double-double) path
TARGET_FAST = mpf(2) ** -72   # fast (plain-f64) leg, Ziv-gated against the accurate path


def fit(f, a, b, target=TARGET):
    """Minimal-degree monomial minimax of f on [a, b] reaching `target`.

    Returns coefficients low-degree-first and the achieved error.
    """
    for n in range(2, 30):
        coeffs, err = chebyfit(f, [a, b], n, error=True)
        if err < target:
            return list(reversed(coeffs)), err, n - 1
    coeffs, err = chebyfit(f, [a, b], 30, error=True)
    return list(reversed(coeffs)), err, 29


def print_dd_array(name, coeffs, doc):
    print(f"\n/// {doc}")
    print(f"const {name}: [DoubleDouble; {len(coeffs)}] = [")
    for c in coeffs:
        hi, lo = dd(c)
        print(f"    DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }},")
    print("];")


# --- erf_small: erf(√u)/√u on u ∈ [0, 0.4375²] -----------------------------
A = mpf("0.4375")
U_HI = A * A


def erf_over_x(u):
    if u == 0:
        return 2 / sqrt(mp.pi)
    s = sqrt(u)
    return erf(s) / s


coeffs, err, deg = fit(erf_over_x, mpf(0), U_HI)
print("// generated by tools/gen_erf_f64.py")
print(f"// erf(x) = x·P(x²) on |x| < 0.4375;  P degree {deg} in u=x², err 2^{float(mp.log(err,2)):.1f}")
print(f"const ERF_SMALL_DD: [DoubleDouble; {len(coeffs)}] = [")
for c in coeffs:
    hi, lo = dd(c)
    print(f"    DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }},")
print("];")

# The fast (Ziv-gated) leg uses a separate *lower-degree minimax*, still stored as
# double-double: a plain-f64 polynomial cannot gate (erfc's relative error equals
# Q's *absolute* error, and an f64 evaluation only reaches ≈2⁻⁵²), and a prefix of
# the accurate fit does not converge (its dropped tail is ≈2⁻⁴¹).
fcoeffs, ferr, fdeg = fit(erf_over_x, mpf(0), U_HI, TARGET_FAST)
print_dd_array("ERF_SMALL_FAST", fcoeffs,
               f"Fast double-double `P(x²)` for `erf` (degree {fdeg}, err 2^{float(mp.log(ferr,2)):.1f})")

# --- erfc segments ---------------------------------------------------------
# x breakpoints (the last is the erfc→0 underflow threshold).
BREAKS = [mpf("0.4375"), mpf(1), mpf(2), mpf(4), mpf(8),
          mpf("27.226017111108362")]


def t_of_x(x):
    return 2 / (2 + x)


def x_of_t(t):
    return 2 / t - 2


def Q_of_t(t):
    x = x_of_t(t)
    return x * x + log(erfc(x)) - log(t)


anchors = []
seg_coeffs = []
seg_fcoeffs = []
print()
print(f"// erfc(x) = t·exp(Q(t) − x²), t = 2/(2+x); Q fit per x-segment in v = t − anchor")
print(f"/// Upper x-bounds of the {len(BREAKS) - 1} erfc segments (last = erfc→0 threshold)")
print(f"const ERFC_BREAKS: [f64; {len(BREAKS) - 1}] = [")
for b in BREAKS[1:]:
    print(f"    {hexf(f64(b))},")
print("];")

for i in range(len(BREAKS) - 1):
    xlo, xhi = BREAKS[i], BREAKS[i + 1]
    t_lo = t_of_x(xhi)          # smaller t (x larger)
    t_hi = t_of_x(xlo)          # larger t
    anchor = f64(t_lo)
    width = t_hi - mpf(anchor)

    def g(v, anchor=anchor):
        return Q_of_t(mpf(anchor) + v)

    coeffs, err, deg = fit(g, mpf(0), width)
    fcoeffs, ferr, fdeg = fit(g, mpf(0), width, TARGET_FAST)
    anchors.append(anchor)
    seg_coeffs.append(coeffs)
    seg_fcoeffs.append(fcoeffs)
    cmax = max(abs(float(c)) for c in coeffs)
    print(f"// segment {i}: x∈[{float(xlo):g},{float(xhi):g}] t∈[{float(t_lo):.4f},{float(t_hi):.4f}]"
          f" deg {deg}/{fdeg} err 2^{float(mp.log(err,2)):.1f}/2^{float(mp.log(ferr,2)):.1f} max|c|={cmax:.2e}")

print(f"\n/// Per-segment anchors `t_anchor` (the segment's smallest `t`)")
print(f"const ERFC_ANCHORS: [f64; {len(anchors)}] = [")
for a in anchors:
    print(f"    {hexf(a)},")
print("];")

for i, coeffs in enumerate(seg_coeffs):
    print(f"\n/// Q(t) for erfc segment {i}, double-double, in v = t − ERFC_ANCHORS[{i}]")
    print(f"const ERFC_Q{i}: [DoubleDouble; {len(coeffs)}] = [")
    for c in coeffs:
        hi, lo = dd(c)
        print(f"    DoubleDouble {{ high: {hexf(hi)}, low: {hexf(lo)} }},")
    print("];")

for i, fcoeffs in enumerate(seg_fcoeffs):
    print_dd_array(f"ERFC_QF{i}", fcoeffs,
                   f"Fast double-double Q(t) for erfc segment {i}, in v = t − ERFC_ANCHORS[{i}]")
