#!/usr/bin/env python3
"""Generate `src/f128_/trig_tables.rs`: the fixed-point constants of the
binary128 `sinq`, `cosq`, and `tanq`.

The mathematical constants are computed from scratch with mpmath:
the bits of 2/pi for the Payne-Hanek reduction, pi/2 for the reconstruction, the
sines, cosines, and tangents of the breakpoints j*pi/256, and the Taylor
coefficients of sin, cos, and tan (1/(2k+1)!, 1/(2k+2)!, and the Bernoulli
form 2^(2k+2)(2^(2k+2)-1)|B_{2k+2}|/(2k+2)!).  SIN_FAST and TAN_FAST are independent
rminimax fits; its command and validation are below. Nothing is transcribed
from another library.

Usage:
    python3 tools/gen_trig_f128.py > src/f128_/trig_tables.rs
"""
from fractions import Fraction
from math import factorial as ifactorial

from mpmath import bernfrac, mp, mpf, pi, sin, cos, tan, factorial, floor, nint

# 2/pi must reach past the largest finite binary128 exponent (2^16383) plus the
# widest window the accurate leg reads (10 limbs of 64 bits) - see LIMBS.
mp.prec = 17200

# Little-endian 64-bit limbs of 2/pi: `FRAC_2_PI[i]` holds bits `64i+1 ..= 64i+64`
# after the binary point.  A window starts at limb `(e - 114) / 64` for an
# unbiased exponent `e`, so the accurate leg's ten limbs reach index 263 at
# `e = 16383`.
LIMBS = 264

# Breakpoints `j*pi/256` for `j = 0..128`: the reduced angle stays within
# `pi/512 < 2^-7.34`, so short polynomials suffice on the fast leg.
SECTORS = 128

# Taylor terms of the accurate leg: `u^18/37!` for `u < 2^-14.69` is below 2^-407,
# far past the 384-bit frame.
TERMS = 18

# Accurate-leg frame: values are `S * 2^-FRAME` in 384-bit limbs; the fast leg
# reads the top 256 bits (scale 2^-256) or the top limb (2^-128).
FRAME = 384

# tanq's breakpoint tangents reach `tan(127*pi/256) = cot(pi/256) < 2^7`, so
# their frame keeps seven integer bits: values are `T * 2^-TAN_FRAME`.
TAN_FRAME = FRAME - 7

# Taylor terms of tanq's accurate leg: the tangent's coefficients fall only
# geometrically, `T_k u^k ~ 2^(-0.30 - 16k)` for `u < 2^-14.69`, so twenty-five
# terms are needed to pass 2^-384 (the 26th is below 2^-416).
TAN_TERMS = 25


def hexs(value, digits):
    """Underscore-grouped hex literal of `value` padded to `digits` nibbles."""
    text = format(value, f"0{digits}x")
    groups = [text[i:i + 16] for i in range(0, len(text), 16)]
    return "0x" + "_".join(groups)


def limbs(value, count):
    """`value` as `count` little-endian 128-bit limbs."""
    assert 0 <= value < 1 << (128 * count), value
    parts = [hexs(value >> (128 * i) & (1 << 128) - 1, 32) for i in range(count)]
    return "[" + ", ".join(parts) + "]"


def fixed_fraction(fraction):
    """`fraction * 2^FRAME` rounded to nearest, exactly."""
    v = (fraction.numerator << FRAME) * 2 + fraction.denominator
    v //= 2 * fraction.denominator
    assert 0 <= v < 1 << FRAME, fraction
    return v


def tan_coefficient(k):
    """The exact Taylor coefficient of `tan` at `theta^(2k+1)`."""
    n = 2 * k + 2
    p, q = bernfrac(n)
    return Fraction(abs(int(p)) * (1 << n) * ((1 << n) - 1), int(q) * ifactorial(n))


assert tan_coefficient(0) == 1 and tan_coefficient(1) == Fraction(1, 3)
assert tan_coefficient(2) == Fraction(2, 15) and tan_coefficient(3) == Fraction(17, 315)


def fixed(value, saturate=False):
    """`value * 2^FRAME` rounded to nearest; 1 saturates to all ones on request."""
    v = int(nint(value * mpf(2) ** FRAME))
    if v == 1 << FRAME:
        assert saturate, value
        v -= 1
    assert 0 <= v < 1 << FRAME, value
    return v


print(f"""//! Generated by tools/gen_trig_f128.py - do not edit by hand.
//!
//! Fixed-point constants for binary128 `sinq`, `cosq`, and `tanq`. Except for
//! the independent rminimax fits SIN_FAST and TAN_FAST, entries are mathematical constants
//! evaluated to {mp.prec} bits with mpmath:
//! the bits of 2/pi that the Payne-Hanek reduction windows, pi/2 for the
//! reconstruction, the sines, cosines, and tangents of the breakpoints
//! j*pi/{2 * SECTORS}, and the Taylor coefficients of the sine, cosine, and
//! tangent (the last exact rationals from the Bernoulli numbers).
#![allow(clippy::unreadable_literal)]""")

two_over_pi = 2 / pi
scaled = int(floor(two_over_pi * mpf(2) ** (64 * LIMBS)))
print(f"""
/// 2/pi as little-endian 64-bit limbs: `FRAC_2_PI[i]` holds bits `64i+1 ..=
/// 64i+64` after the binary point, most significant limb first.
#[rustfmt::skip]
pub const FRAC_2_PI: [u64; {LIMBS}] = [""")
for i in range(LIMBS):
    limb = scaled >> (64 * (LIMBS - 1 - i)) & (1 << 64) - 1
    print(f"    {hexs(limb, 16)},")
print("];")

half_pi = pi / 2
print(f"""
/// `pi/2` scaled by 2^127 and rounded: the fast leg's reconstruction constant.
pub const PIO2_128: u128 = {hexs(int(nint(half_pi * mpf(2) ** 127)), 32)};

/// `pi/2` scaled by 2^383 and rounded, little-endian: the accurate leg's.
#[rustfmt::skip]
pub const PIO2_384: [u128; 3] = {limbs(int(nint(half_pi * mpf(2) ** 383)), 3)};""")

print(f"""
/// `[sin(j*pi/{2 * SECTORS}), cos(j*pi/{2 * SECTORS})]` for `j = 0..{SECTORS}`, scaled by
/// 2^{FRAME} and rounded, little-endian.  `cos(0) = 1` saturates to all ones, one
/// unit low, which the frames absorb.  The fast leg reads the top two limbs of
/// each.
#[rustfmt::skip]
pub const SINCOS: [[[u128; 3]; 2]; {SECTORS}] = [""")
for j in range(SECTORS):
    angle = mpf(j) * pi / (2 * SECTORS)
    s = fixed(sin(angle))
    c = fixed(cos(angle), saturate=True)
    print(f"    [{limbs(s, 3)}, {limbs(c, 3)}],")
print("];")

# Independent rminimax fit, with 140-bit coefficients before Q128 rounding:
# ratapprox --function="(1-sin(sqrt(x))/sqrt(x))/x" --dom="[8.7e-19,3.765e-5]" --type=[4,0] --numF="[140]" --prec=400 --dispCoeff=hex
SIN_FAST_HEX = [
    "0x2.aaaaaaaaaaaaaaaaaaaaaaaaaaa8b20314cp-4",
    "-0x2.222222222222222222221fa2fd12429be5p-8",
    "0xd.00d00d00d00d00c7f4be42e1a6409d95ep-16",
    "-0x2.e3bc74aad85378e3e9d9c3058a37d5da418p-20",
    "0x6.b99115ea3fd77eea5743ff7be5de64bc63p-28",
]


def fast_sine_coefficients():
    """Round the fit to Q128 and check its error and positive partial sums."""
    with mp.workprec(400):
        coefficients = []
        for text in SIN_FAST_HEX:
            mantissa, exponent = text.lstrip("-")[2:].split("p")
            whole, fraction = mantissa.split(".")
            value = mpf(int(whole + fraction, 16)) * mpf(2)**(int(exponent) - 4*len(fraction))
            coefficients.append(int(nint(value * mpf(2)**128)))
        c = [mpf(v) / mpf(2)**128 for v in coefficients]
        end = (pi / 512)**2
        worst = mpf(0)
        for i in range(4097):
            u = end * i / 4096
            p = c[-1]
            for a in reversed(c[:-1]):
                p = a - u*p
                assert p > 0
            exact = (1 - sin(mp.sqrt(u))/mp.sqrt(u))/u if u else mpf(1)/6
            worst = max(worst, abs(exact - p))
        assert worst < mpf(2)**-114, worst
        # Certify between grid points using exact rational arithmetic. Compare
        # with Taylor through u^5; its alternating remainder is <= u^6/15!.
        from fractions import Fraction as F
        from math import factorial as fact
        end_bound, steps = F("3.765e-5"), 8192
        delta = [(-1)**k * (F(1, fact(2*k+3)) -
                 (F(coefficients[k], 1 << 128) if k < 5 else 0)) for k in range(6)]
        derivative = sum(k*abs(delta[k])*end_bound**(k-1) for k in range(1, 6))
        grid = F(0)
        for i in range(steps + 1):
            u = end_bound*i/steps
            p = delta[-1]
            for a in reversed(delta[:-1]):
                p = a + u*p
            grid = max(grid, abs(p))
        bound = grid + derivative*end_bound/(2*steps) + end_bound**6/fact(15)
        assert bound < F(1, 1 << 114), bound
        import sys
        print(f"SIN_FAST rational error bound: 2^{float(mp.log(mpf(bound.numerator)/bound.denominator, 2)):.4f}", file=sys.stderr)
        print(f"SIN_FAST sampled Q128 error: 2^{float(mp.log(worst, 2)):.4f}", file=sys.stderr)
        return coefficients


print("""
/// Magnitudes of the degree-4 minimax coefficients of `(1-sin(sqrt(u))/sqrt(u))/u`,
/// in Q128, alternating signs. Certified error < 2^-114 on `[0, 3.765e-5]`, containing `(pi/512)^2`.
/// Generated independently with:
/// `ratapprox --function="(1-sin(sqrt(x))/sqrt(x))/x" --dom="[8.7e-19,3.765e-5]" --type=[4,0] --numF="[140]" --prec=400 --dispCoeff=hex`
#[rustfmt::skip]
pub const SIN_FAST: [u128; 5] = [""")
for c in fast_sine_coefficients():
    print(f"    {hexs(c, 32)},")
print("];")

print(f"""
/// `1/(2k+3)!` for `k = 0..{TERMS}`, scaled by 2^{FRAME}: the Taylor coefficients
/// of the accurate leg's `sin(t)/t = 1 - sum_k (-1)^k SIN_COEF[k] (t^2)^(k+1)`.
#[rustfmt::skip]
pub const SIN_COEF: [[u128; 3]; {TERMS}] = [""")
for k in range(TERMS):
    print(f"    {limbs(fixed(1 / factorial(2 * k + 3)), 3)},")
print("];")

print(f"""
/// `1/(2k+2)!` for `k = 0..{TERMS}`, scaled by 2^{FRAME}: the Taylor coefficients
/// of `1 - cos(t) = sum_k (-1)^k COS_COEF[k] (t^2)^(k+1)`.
#[rustfmt::skip]
pub const COS_COEF: [[u128; 3]; {TERMS}] = [""")
for k in range(TERMS):
    print(f"    {limbs(fixed(1 / factorial(2 * k + 2)), 3)},")
print("];")

print(f"""
/// `tan(j*pi/{2 * SECTORS})` for `j = 0..{SECTORS}`, scaled by 2^{TAN_FRAME} and rounded,
/// little-endian: seven integer bits, as `tan(127*pi/256) < 2^7`.  The fast
/// leg reads the top two limbs of each.
#[rustfmt::skip]
pub const TAN: [[u128; 3]; {SECTORS}] = [""")
for j in range(SECTORS):
    v = int(nint(tan(mpf(j) * pi / (2 * SECTORS)) * mpf(2) ** TAN_FRAME))
    assert 0 <= v < 1 << FRAME, j
    print(f"    {limbs(v, 3)},")
print("];")

print(f"""
/// The Taylor coefficients of `tan(t)/t = 1 + sum_k TAN_COEF[k] (t^2)^(k+1)`
/// for `k = 0..{TAN_TERMS}`, scaled by 2^{FRAME}: `2^(2k+4)(2^(2k+4)-1)|B_(2k+4)|/(2k+4)!`,
/// every one positive. Used by the accurate leg; the fast leg uses TAN_FAST.
#[rustfmt::skip]
pub const TAN_COEF: [[u128; 3]; {TAN_TERMS}] = [""")
for k in range(TAN_TERMS):
    print(f"    {limbs(fixed_fraction(tan_coefficient(k + 1)), 3)},")
print("];")

# Independent fixed-point fit; the accurate leg keeps its Taylor coefficients.
TAN_FAST_HEX = [
    "0x5.5555555555555555555555555555557f638p-4",
    "0x2.2222222222222222222222221b9bcea7fap-4",
    "0xd.d0dd0dd0dd0dd0dd0dd38200b3a6091f97p-8",
    "0x5.993d220b043e7cc4eccff964379021cf84p-8",
    "0x2.44dc6abcd84f0406a8ad5cc032d0d049f1cp-8",
    "0xe.b69e86c3eedfafe36e7e2350d69c3a9fdep-12",
    "0x5.f6a27076f954f0619fd21efe9d36bbaf408p-12",
]


def fast_tangent_coefficients():
    """Certify the rounded polynomial against exact Taylor data on the full interval."""
    from fractions import Fraction as F
    import sys

    coefficients = []
    for text in TAN_FAST_HEX:
        mantissa, exponent = text[2:].split("p")
        whole, fraction = mantissa.split(".")
        value = F(int(whole + fraction, 16)) * F(2)**(int(exponent) - 4*len(fraction))
        coefficients.append(round(value * (1 << 128)))
    actual = [c if k < 4 else c >> 64 << 64 for k, c in enumerate(coefficients)]
    end, steps = F("3.765e-5"), 8192
    delta = [tan_coefficient(k + 1) -
             (F(actual[k], 1 << 128) if k < len(actual) else 0)
             for k in range(9)]
    derivative = sum(k*abs(delta[k])*end**(k-1) for k in range(1, len(delta)))
    grid = F(0)
    for i in range(steps + 1):
        u = end*i/steps
        p = delta[-1]
        for a in reversed(delta[:-1]):
            p = a + u*p
        grid = max(grid, abs(p))
    # All tangent coefficients are in (0,1]: induction in tan' = 1 + tan^2.
    # Thus the omitted Taylor tail is bounded by the geometric series.
    bound = grid + derivative*end/(2*steps) + end**9/(1-end)
    assert bound < F(1, 1 << 120), bound
    print(f"TAN_FAST rational error bound: 2^{float(mp.log(mpf(bound.numerator)/bound.denominator, 2)):.4f}", file=sys.stderr)
    return coefficients


print("""
/// Degree-6 minimax coefficients of `(tan(sqrt(u))/sqrt(u)-1)/u`, in Q128.
/// After narrowing coefficients 4 onward to Q64, certified error < 2^-120
/// on `[0, 3.765e-5]`, containing `(pi/512)^2`.
/// Generated independently with:
/// `ratapprox --function="(tan(sqrt(x))/sqrt(x)-1)/x" --dom="[8.7e-19,3.765e-5]" --type=[6,0] --numF="[140]" --prec=400 --dispCoeff=hex`
#[rustfmt::skip]
pub const TAN_FAST: [u128; 7] = [""")
for c in fast_tangent_coefficients():
    print(f"    {hexs(c, 32)},")
print("];")
