#!/usr/bin/env python3
"""Generate `src/f128_/trig_tables.rs`: the fixed-point constants of the
binary128 `sinq`, `cosq`, and `tanq`.

Everything here is a *mathematical* constant computed from scratch with mpmath:
the bits of 2/pi for the Payne-Hanek reduction, pi/2 for the reconstruction, the
sines, cosines, and tangents of the breakpoints j*pi/256, and the Taylor
coefficients of sin, cos, and tan (1/(2k+1)!, 1/(2k+2)!, and the Bernoulli
form 2^(2k+2)(2^(2k+2)-1)|B_{2k+2}|/(2k+2)!).  No fitted approximation
coefficients, no transcription from another library.

Usage:
    python3 tools/gen_trig_f128.py > src/f128_/trig_tables.rs
"""
from fractions import Fraction
from math import factorial as ifactorial

from mpmath import bernfrac, mp, mpf, pi, sin, cos, tan, factorial, floor, nint

# 2/pi must reach past the largest finite binary128 exponent (2^16383) plus the
# widest window the accurate leg reads (10 limbs of 64 bits) - see LIMBS.
mp.prec = 17200

# Little-endian 64-bit limbs of 2/pi: `FRAC_2_PI[i]` holds bits `64i+1 ..= 64i+64`
# after the binary point.  A window starts at limb `(e - 114) / 64` for an
# unbiased exponent `e`, so the accurate leg's ten limbs reach index 263 at
# `e = 16383`.
LIMBS = 264

# Breakpoints `j*pi/256` for `j = 0..128`: the reduced angle stays within
# `pi/512 < 2^-7.34`, so the fast leg's Taylor sums converge in six terms.
SECTORS = 128

# Taylor terms of the accurate leg: `u^18/37!` for `u < 2^-14.69` is below 2^-407,
# far past the 384-bit frame.
TERMS = 18

# Accurate-leg frame: values are `S * 2^-FRAME` in 384-bit limbs; the fast leg
# reads the top 256 bits (scale 2^-256) or the top limb (2^-128).
FRAME = 384

# tanq's breakpoint tangents reach `tan(127*pi/256) = cot(pi/256) < 2^7`, so
# their frame keeps seven integer bits: values are `T * 2^-TAN_FRAME`.
TAN_FRAME = FRAME - 7

# Taylor terms of tanq's accurate leg: the tangent's coefficients fall only
# geometrically, `T_k u^k ~ 2^(-0.30 - 16k)` for `u < 2^-14.69`, so twenty-five
# terms are needed to pass 2^-384 (the 26th is below 2^-416).
TAN_TERMS = 25


def hexs(value, digits):
    """Underscore-grouped hex literal of `value` padded to `digits` nibbles."""
    text = format(value, f"0{digits}x")
    groups = [text[i:i + 16] for i in range(0, len(text), 16)]
    return "0x" + "_".join(groups)


def limbs(value, count):
    """`value` as `count` little-endian 128-bit limbs."""
    assert 0 <= value < 1 << (128 * count), value
    parts = [hexs(value >> (128 * i) & (1 << 128) - 1, 32) for i in range(count)]
    return "[" + ", ".join(parts) + "]"


def fixed_fraction(fraction):
    """`fraction * 2^FRAME` rounded to nearest, exactly."""
    v = (fraction.numerator << FRAME) * 2 + fraction.denominator
    v //= 2 * fraction.denominator
    assert 0 <= v < 1 << FRAME, fraction
    return v


def tan_coefficient(k):
    """The exact Taylor coefficient of `tan` at `theta^(2k+1)`."""
    n = 2 * k + 2
    p, q = bernfrac(n)
    return Fraction(abs(int(p)) * (1 << n) * ((1 << n) - 1), int(q) * ifactorial(n))


assert tan_coefficient(0) == 1 and tan_coefficient(1) == Fraction(1, 3)
assert tan_coefficient(2) == Fraction(2, 15) and tan_coefficient(3) == Fraction(17, 315)


def fixed(value, saturate=False):
    """`value * 2^FRAME` rounded to nearest; 1 saturates to all ones on request."""
    v = int(nint(value * mpf(2) ** FRAME))
    if v == 1 << FRAME:
        assert saturate, value
        v -= 1
    assert 0 <= v < 1 << FRAME, value
    return v


print(f"""//! Generated by tools/gen_trig_f128.py - do not edit by hand.
//!
//! Fixed-point constants for binary128 `sinq`, `cosq`, and `tanq`.  Every
//! entry is a mathematical constant evaluated to {mp.prec} bits with mpmath:
//! the bits of 2/pi that the Payne-Hanek reduction windows, pi/2 for the
//! reconstruction, the sines, cosines, and tangents of the breakpoints
//! j*pi/{2 * SECTORS}, and the Taylor coefficients of the sine, cosine, and
//! tangent (the last exact rationals from the Bernoulli numbers).
#![allow(clippy::unreadable_literal)]""")

two_over_pi = 2 / pi
scaled = int(floor(two_over_pi * mpf(2) ** (64 * LIMBS)))
print(f"""
/// 2/pi as little-endian 64-bit limbs: `FRAC_2_PI[i]` holds bits `64i+1 ..=
/// 64i+64` after the binary point, most significant limb first.
#[rustfmt::skip]
pub const FRAC_2_PI: [u64; {LIMBS}] = [""")
for i in range(LIMBS):
    limb = scaled >> (64 * (LIMBS - 1 - i)) & (1 << 64) - 1
    print(f"    {hexs(limb, 16)},")
print("];")

half_pi = pi / 2
print(f"""
/// `pi/2` scaled by 2^127 and rounded: the fast leg's reconstruction constant.
pub const PIO2_128: u128 = {hexs(int(nint(half_pi * mpf(2) ** 127)), 32)};

/// `pi/2` scaled by 2^383 and rounded, little-endian: the accurate leg's.
#[rustfmt::skip]
pub const PIO2_384: [u128; 3] = {limbs(int(nint(half_pi * mpf(2) ** 383)), 3)};""")

print(f"""
/// `[sin(j*pi/{2 * SECTORS}), cos(j*pi/{2 * SECTORS})]` for `j = 0..{SECTORS}`, scaled by
/// 2^{FRAME} and rounded, little-endian.  `cos(0) = 1` saturates to all ones, one
/// unit low, which the frames absorb.  The fast leg reads the top two limbs of
/// each.
#[rustfmt::skip]
pub const SINCOS: [[[u128; 3]; 2]; {SECTORS}] = [""")
for j in range(SECTORS):
    angle = mpf(j) * pi / (2 * SECTORS)
    s = fixed(sin(angle))
    c = fixed(cos(angle), saturate=True)
    print(f"    [{limbs(s, 3)}, {limbs(c, 3)}],")
print("];")

print(f"""
/// `1/(2k+3)!` for `k = 0..{TERMS}`, scaled by 2^{FRAME}: the Taylor coefficients
/// of `sin(t)/t = 1 - sum_k (-1)^k SIN_COEF[k] (t^2)^(k+1)`.  The top limb is
/// the same coefficient scaled by 2^128, which is all the fast leg reads.
#[rustfmt::skip]
pub const SIN_COEF: [[u128; 3]; {TERMS}] = [""")
for k in range(TERMS):
    print(f"    {limbs(fixed(1 / factorial(2 * k + 3)), 3)},")
print("];")

print(f"""
/// `1/(2k+2)!` for `k = 0..{TERMS}`, scaled by 2^{FRAME}: the Taylor coefficients
/// of `1 - cos(t) = sum_k (-1)^k COS_COEF[k] (t^2)^(k+1)`.
#[rustfmt::skip]
pub const COS_COEF: [[u128; 3]; {TERMS}] = [""")
for k in range(TERMS):
    print(f"    {limbs(fixed(1 / factorial(2 * k + 2)), 3)},")
print("];")

print(f"""
/// `tan(j*pi/{2 * SECTORS})` for `j = 0..{SECTORS}`, scaled by 2^{TAN_FRAME} and rounded,
/// little-endian: seven integer bits, as `tan(127*pi/256) < 2^7`.  The fast
/// leg reads the top two limbs of each.
#[rustfmt::skip]
pub const TAN: [[u128; 3]; {SECTORS}] = [""")
for j in range(SECTORS):
    v = int(nint(tan(mpf(j) * pi / (2 * SECTORS)) * mpf(2) ** TAN_FRAME))
    assert 0 <= v < 1 << FRAME, j
    print(f"    {limbs(v, 3)},")
print("];")

print(f"""
/// The Taylor coefficients of `tan(t)/t = 1 + sum_k TAN_COEF[k] (t^2)^(k+1)`
/// for `k = 0..{TAN_TERMS}`, scaled by 2^{FRAME}: `2^(2k+4)(2^(2k+4)-1)|B_(2k+4)|/(2k+4)!`,
/// every one positive.  The top limb is the same coefficient scaled by 2^128,
/// which is all the fast leg reads.
#[rustfmt::skip]
pub const TAN_COEF: [[u128; 3]; {TAN_TERMS}] = [""")
for k in range(TAN_TERMS):
    print(f"    {limbs(fixed_fraction(tan_coefficient(k + 1)), 3)},")
print("];")
