#!/usr/bin/env python3
"""Generate `src/f128_/cbrt_tables.rs`: the fixed-point seed constants of the
binary128 cube root.

Everything here is a *mathematical* constant computed from scratch with mpmath:
the value, first derivative, and half second derivative of m^(-1/3) at the 64
interval centers c = 1 + (2i+1)/128 covering m in [1, 2), plus the Newton
constants 2^(-w/3)/3 that fold the octave scaling into the seed's single
integer Newton step.  A degree-2 Taylor expansion from the nearest center is a
truncated series, not a fitted approximation — no minimax coefficients, no
transcription from another library.

Usage:
    python3 tools/gen_cbrt_f128.py > src/f128_/cbrt_tables.rs
"""
from mpmath import mp, mpf, nint

mp.prec = 200


def rows(values, per_row=4):
    lines = []
    for start in range(0, len(values), per_row):
        chunk = ", ".join(f"{v:#018x}" for v in values[start : start + per_row])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


centers = [1 + mpf(2 * i + 1) / 128 for i in range(64)]
value = [int(nint(c ** (mpf(-1) / 3) * 2**63)) for c in centers]
slope = [int(nint(c ** (mpf(-4) / 3) / 3 * 2**65)) for c in centers]
curve = [int(nint(c ** (mpf(-7) / 3) * 2 / 9 * 2**66)) for c in centers]
newton = [int(nint(mpf(2) ** (mpf(-w) / 3) / 3 * 2**65)) for w in range(3)]

print(
    f'''//! Generated by tools/gen_cbrt_f128.py - do not edit by hand.
//!
//! Fixed-point seed constants for the binary128 cube root.  Every entry is a
//! mathematical constant evaluated to 200 bits with mpmath: the degree-2
//! Taylor data of m^(-1/3) at the 64 interval centers c = 1 + (2i+1)/128, and
//! the Newton constants 2^(-w/3)/3 for the three octaves of [1, 8).
#![allow(clippy::unreadable_literal)]

/// c^(-1/3), scaled by 2^63 and rounded.
#[rustfmt::skip]
pub const SEED_VALUE: [u64; 64] = [
{rows(value)}
];

/// c^(-4/3)/3 = |d(m^(-1/3))/dm| at c, scaled by 2^65 and rounded.
#[rustfmt::skip]
pub const SEED_SLOPE: [u64; 64] = [
{rows(slope)}
];

/// 2c^(-7/3)/9 = d²(m^(-1/3))/dm²/2 at c, scaled by 2^66 and rounded.
#[rustfmt::skip]
pub const SEED_CURVE: [u64; 64] = [
{rows(curve)}
];

/// 2^(-w/3)/3, scaled by 2^65 and rounded.
#[rustfmt::skip]
pub const NEWTON: [u64; 3] = [
{rows(newton)}
];'''
)
