#!/usr/bin/env python3
"""Original Taylor constants for binary128 erf and erfc.

python3 tools/gen_erf_f128.py > src/f128_/erf_tables.rs

No fitted or borrowed coefficients. erfcx(c(1+t))/erfcx(c) has alternating
Taylor coefficients b[k] = c**k * integral((2*u)**k * exp(-u*u-2*c*u),u=0..inf)
                         / (k! * integral(exp(-u*u-2*c*u),u=0..inf)).
They obey b[k+1] = 2*c*c*(b[k-1]-b[k])/(k+1). The high working precision
absorbs the cancellation of this recurrence at the largest centers.
"""
from mpmath import mp

mp.prec = 2500
BITS = 383
COUNT = 78


def fixed(x, scale=BITS):
    n = int(mp.nint(x * mp.mpf(2)**scale))
    assert 0 <= n < 1 << 384
    limbs = [f'{(n >> k) & ((1 << 128)-1):032x}' for k in (0, 128, 256)]
    return '[' + ', '.join('0x' + s[:16] + '_' + s[16:] for s in limbs) + ']'


print('''//! Generated by tools/gen_erf_f128.py; do not edit by hand.
//! Original Taylor constants, independently evaluated at 2500 bits.
#![allow(clippy::unreadable_literal)]''')
print('''\n/// erf(x)/x: (2/sqrt(pi)) / (k! (2k+1)), with alternating signs.
/// Generate: `python3 tools/gen_erf_f128.py > src/f128_/erf_tables.rs`.
#[rustfmt::skip]
pub const ERF: [[u128; 3]; 64] = [''')
for k in range(64):
    print('    ' + fixed(2/mp.sqrt(mp.pi)/(mp.factorial(k)*(2*k+1))) + ',')
print('];')
print('''\n/// Normalized erfcx(c) and its exponent, c=(33+2*j)*2^(e-5).
/// Generate: `python3 tools/gen_erf_f128.py > src/f128_/erf_tables.rs`.
#[rustfmt::skip]
pub const VALUES: [(i32, [u128; 3]); 128] = [''')
rows = []
for e in range(-1, 7):
    for j in range(16):
        c = mp.mpf(33+2*j) * mp.power(2, e-5)
        a0 = mp.exp(c*c) * mp.erfc(c)
        exponent = int(mp.floor(mp.log(a0,2)))
        print(f'    ({exponent}, {fixed(a0 * mp.power(2,-exponent))}),')
        b = [mp.mpf(1), 2*c/(mp.sqrt(mp.pi)*a0)-2*c*c]
        for k in range(1, COUNT-1):
            b.append(2*c*c*(b[k-1]-b[k])/(k+1))
        assert all(0 < v <= 1 for v in b)
        rows.append(b)
print('];')
# |t| <= 1/33, b[k] <= 1 (the exponential measure weighted by the
# decreasing function exp(-v*v/(4*c*c)) has no larger moments).
assert mp.power(33,-28)/(1-mp.mpf(1)/33) < mp.power(2,-140)
assert mp.power(33,-COUNT)/(1-mp.mpf(1)/33) < mp.power(2,-393)
print(f'''\n/// Magnitudes of the Taylor coefficients erfcx(c*(1+t))/erfcx(c), at 2^383.
/// Each coefficient is at most one, and |t| <= 1/33. The first 28 terms
/// leave a tail below 2^-140; all {COUNT} leave a tail below 2^-393.
/// Generate: `python3 tools/gen_erf_f128.py > src/f128_/erf_tables.rs`.
#[rustfmt::skip]
pub const RATIO: [[[u128; 3]; {COUNT}]; 128] = [''')
for row in rows:
    print('    [')
    for b in row:
        print('        ' + fixed(b) + ',')
    print('    ],')
print('];')
