#!/usr/bin/env python3
"""Generate Dint (128-bit) accurate-path constants for f64 atan.

Emits PIO2_DINT (pi/2), TWO_DINT (2), ATAN_TABLE_DINT (atan(k/8), k=0..8) and
ATAN_COEFFS_DINT (the odd-series coefficients (-1)^k/(2k+1) of atan(u)/u in
v=u^2, low-degree first), as Dint literals matching dint_consts.rs / trig.rs.

The accurate atan kernel mirrors the double-double one (`atan_cell`): a cell
reduction `u = (q - c)/(1 + q*c)` with `c = k/8`, `|u| <= 1/16`, then
`atan(c + ...) = atan(k/8) + u * P(u^2)`.  So the series variable is `v = u^2`
with `v <= 1/256`, and the coefficient of `v^k` is `(-1)^k/(2k+1)`.

Note: atan2's hardest hard-to-round corpus tie is ~2^-154 relative, beyond a
128-bit significand's reach, so atan2's accurate fallback uses the wider 192-bit
`Tint` path instead (a port of CORE-MATH's atan2 P/Q rational and tint.h, whose
constants are copied verbatim from CORE-MATH's atan2.c, not generated here).

Value = (-1)^sgn * (m / 2^127) * 2^ex, m normalized so bit 127 set.
"""
from mpmath import mp, mpf, atan, pi, log, floor, nint

mp.prec = 600


def to_dint(x):
    x = mpf(x)
    sgn = x < 0
    a = abs(x)
    if a == 0:
        return (False, 0, 0)
    ex = int(floor(log(a, 2)))
    mant = a / mpf(2) ** ex            # in [1, 2)
    m = int(nint(mant * mpf(2) ** 127))
    if m >= (1 << 128):                # rounding overflow
        m >>= 1
        ex += 1
    assert (1 << 127) <= m < (1 << 128)
    return (bool(sgn), ex, m)


def emit_one(name, x):
    sgn, ex, m = to_dint(x)
    print(f"const {name}: Dint = Dint {{")
    print(f"    sgn: {'true' if sgn else 'false'},")
    print(f"    ex: {ex},")
    print(f"    m: 0x{m:032x},")
    print("};\n")


def emit_array(name, values):
    print(f"const {name}: [Dint; {len(values)}] = [")
    for x in values:
        sgn, ex, m = to_dint(x)
        print("    Dint {")
        print(f"        sgn: {'true' if sgn else 'false'},")
        print(f"        ex: {ex},")
        print(f"        m: 0x{m:032x},")
        print("    },")
    print("];\n")


# v = u^2 with |u| <= 1/16, so v <= 1/256.  Pick term count so the truncation
# tail < 2^-130 at v = V_MAX.
V_MAX = mpf(1) / 256

# atan(u)/u = sum_k (-1)^k v^k / (2k+1)
atan_c = lambda k: mpf((-1) ** k) / (2 * k + 1)


def n_terms(coeff, target_bits=130):
    n = 1
    while True:
        tail = abs(coeff(n)) * V_MAX ** n
        if tail < mpf(2) ** (-target_bits):
            return n
        n += 1


NATAN = n_terms(atan_c)

print("// Dint accurate-path atan constants. GENERATED by tools/gen_dint_atan.py.")
print(f"// atan series uses {NATAN} terms"
      f" (tail at v=1/256 ~2^{float(log(abs(atan_c(NATAN)) * V_MAX ** NATAN, 2)):.1f}).")
print()
emit_one("PIO2_DINT", pi / 2)
emit_one("TWO_DINT", 2)
emit_array("ATAN_TABLE_DINT", [atan(mpf(k) / 8) for k in range(9)])
emit_array("ATAN_COEFFS_DINT", [atan_c(k) for k in range(NATAN)])
