#!/usr/bin/env python3
"""Generate `src/f128_/exp_tables.rs`: the fixed-point constants of the
binary128 exponential family.

Everything here is a *mathematical* constant computed from scratch with mpmath:
the 2^(j/2^k) lookup tables, the Taylor coefficients ln(2)^k/k! of 2^t - 1, and
the log2(e) / log2(10) reduction limbs, and the exp2m1/exp10m1 Taylor ratios.  No fitted coefficients, no transcription
from another library.

Usage:
    python3 tools/gen_exp_f128.py > src/f128_/exp_tables.rs
"""
from mpmath import mp, mpf, log, factorial

mp.prec = 1500

LN2 = log(2)


def hexs(value, digits):
    """Underscore-grouped hex literal of `value` padded to `digits` nibbles."""
    text = format(value, f"0{digits}x")
    groups = [text[i:i + 16] for i in range(0, len(text), 16)]
    return "0x" + "_".join(groups)


def pair(value, scale):
    """`value * 2**scale` rounded to a 256-bit integer, as little-endian limbs."""
    fixed = int(mp.nint(value * mpf(2) ** scale))
    assert 0 <= fixed < 1 << 256, value
    return f"[{hexs(fixed & (1 << 128) - 1, 32)}, {hexs(fixed >> 128, 32)}]"


def table(name, step, doc):
    """A 64-entry table of 2^(j/step) as 256-bit values scaled by 2^255."""
    print(f"\n/// {doc}")
    print("#[rustfmt::skip]")
    print(f"pub const {name}: [[u128; 2]; 64] = [")
    for j in range(64):
        print(f"    {pair(mpf(2) ** (mpf(j) / step), 255)},")
    print("];")


def reduction(name, value, doc):
    """`value` as a 252-bit-scaled 256-bit head plus a 128-bit tail at 2^-380."""
    head = int(mp.floor(value * mpf(2) ** 252))
    tail = int(mp.floor((value - mpf(head) * mpf(2) ** -252) * mpf(2) ** 380))
    assert 0 <= tail < 1 << 128
    print(f"\n/// {doc}")
    print(f"pub const {name}: Reduction = Reduction {{")
    print("    head: [")
    print(f"        {hexs(head & (1 << 128) - 1, 32)},")
    print(f"        {hexs(head >> 128, 32)},")
    print("    ],")
    print(f"    tail: {hexs(tail, 32)},")
    print("};")


print("""// Generated by tools/gen_exp_f128.py - do not edit by hand.
//!
//! Fixed-point constants for the binary128 exponential family.  Every entry is
//! a mathematical constant evaluated to 1500 bits with mpmath: the reduction
//! limbs of log2(e) and log2(10), the three levels of 2^(j/2^k) lookup tables,
//! and Taylor coefficients for 2^t - 1 and the base-specific expm1 ratios.
#![allow(clippy::unreadable_literal)]

/// Reduction constant `L = head/2^252 + tail/2^380` for `2^(x*L)`.
pub struct Reduction {
    /// Leading 256 bits of `L`, scaled by 2^252 and truncated.
    pub head: [u128; 2],
    /// The truncated remainder `L - head/2^252`, scaled by 2^380.
    pub tail: u128,
}""".replace("// Generated", "//! Generated"))

reduction("LOG2E", 1 / LN2, "log2(e), for `expq`.")
reduction("ONE", mpf(1), "One, for `exp2q`.  The reduction is then exact.")
reduction("LOG2_10", log(10) / LN2, "log2(10), for `exp10q`.")

table("T0", 64, "2^(j/64), scaled by 2^255.")
table("T1", 4096, "2^(j/4096), scaled by 2^255.")
table("T2", 262144, "2^(j/262144), scaled by 2^255.")

print("""
/// `ln(2)^k / k!` for `k = 1..=13`, scaled by 2^256: the Taylor coefficients of
/// `2^t - 1 = sum_k COEF[k-1] * t^k`.  The fast path stops at `k = 6`, where the
/// tail is below 2^-142 for `t < 2^-18`.
#[rustfmt::skip]
pub const COEF: [[u128; 2]; 13] = [""")
for k in range(1, 14):
    print(f"    {pair(LN2 ** k / factorial(k), 256)},")
print("];")

print("""
/// `1/(j + 2)!` for `j = 0..=14`, scaled by 2^128: the Taylor coefficients of
/// `h(x) = (e^x - 1 - x)/x^2`, whose sign-folded Horner sums drive the
/// `expm1q` fast legs below 2^-6.
#[rustfmt::skip]
pub const INV_FACT: [u128; 15] = [""")
for k in range(2, 17):
    fixed = int(mp.nint(1 / factorial(k) * mpf(2) ** 128))
    assert 0 < fixed < 1 << 128
    print(f"    {hexs(fixed, 32)},")
print("];")

# The base-specific expm1 ratios retain their irrational slope even when x is
# subnormal.  The fast leg uses the top limb (scale 2^126); the accurate leg
# uses all three (scale 2^382), followed by an exact significand product.
for base in (2, 10):
    slope = log(base)
    omitted = slope**45 / factorial(45) * mpf(2)**(-6 * 44)
    assert omitted * mp.exp(slope * mpf(2)**-6) < mpf(2)**-390
    # Lagrange remainder bounds for the fast leg's two term counts.
    assert (slope**19 / factorial(19) * mpf(2)**(-6 * 18)
            * mp.exp(slope * mpf(2)**-6)) < mpf(2)**-141
    assert (slope**8 / factorial(8) * mpf(2)**(-19 * 7)
            * mp.exp(slope * mpf(2)**-19)) < mpf(2)**-138
    print(f"""
/// `ln({base})^(j+1)/(j+1)!`, `j = 0..43`, rounded at scale 2^382.
/// Taylor constants for `(exp{base}(x) - 1)/x` on `|x| < 2^-6`.
/// Generate: `python3 tools/gen_exp_f128.py > src/f128_/exp_tables.rs`.
#[rustfmt::skip]
pub const EXP{base}M1_COEF: [[u128; 3]; 44] = [""")
    for j in range(44):
        fixed = int(mp.nint(slope**(j+1) / factorial(j+1) * mpf(2)**382))
        assert 0 < fixed < 1 << 384
        limbs = [hexs((fixed >> k) & ((1 << 128) - 1), 32) for k in (0, 128, 256)]
        print(f"    [{', '.join(limbs)}],")
    print("];")
