#!/usr/bin/env python3
"""Generate `src/f128_/atan2_tables.rs`: the fixed-point constants of the
binary128 `atan2q`.

Everything here is a *mathematical* constant computed from scratch with mpmath:
the arc tangents of the dyadic sector breakpoints i/64, the quadrant offsets 0,
pi/2 and pi, the Taylor coefficients 1/(2k+3) of `atan(T)/T`, and the bit
pattern of 3pi/4 for the infinity edge cases.  No fitted approximation
coefficients, no transcription from another library.

The script also audits every constant the reduction can return *exactly* (a
ratio `|y/x|` landing precisely on a breakpoint makes the result a pure table
sum): each such sum must keep a comfortable distance from the nearest binary128
rounding boundary, so the 384-bit accurate frame provably decides it.

Usage:
    python3 tools/gen_atan2_f128.py > src/f128_/atan2_tables.rs
"""
from mpmath import mp, mpf, atan, pi, floor, log, nint

mp.prec = 2000

# Accurate-leg frame: a value is `S * 2^-FRAME` with `S` a signed 384-bit
# integer.  The fast leg reuses the top 256 bits, i.e. the scale `2^-(FRAME-128)`.
# pi (the largest result) needs 2 integer bits, leaving a sign bit and headroom.
FRAME = 381

# Sector breakpoints are `i/SECTORS`, so the reduced tangent stays below
# `(0.505/SECTORS) < 2^-6.98` (the sector pick is off by at most 0.505 units).
SECTORS = 64

# Taylor terms of `atan(T)/T = 1 - T^2/3 + T^4/5 - ...`: the accurate leg uses
# 18, where the tail is below 2^-269 for `T^2 < 2^-13.9`; two spares cost
# nothing.  The fast leg stops at 10, where the tail is below 2^-157.
TERMS = 20

# Every exact table sum must clear the nearest rounding boundary by this much,
# so the accurate frame (table error < 2^-379) decides it with room to spare.
AUDIT = mpf(2) ** -300


def hexs(value, digits):
    """Underscore-grouped hex literal of `value` padded to `digits` nibbles."""
    text = format(value, f"0{digits}x")
    groups = [text[i:i + 16] for i in range(0, len(text), 16)]
    return "0x" + "_".join(groups)


def limbs(value, count):
    """`value` as `count` little-endian 128-bit limbs."""
    assert 0 <= value < 1 << (128 * count), value
    parts = [hexs(value >> (128 * i) & (1 << 128) - 1, 32) for i in range(count)]
    return "[" + ", ".join(parts) + "]"


def to_bits(v):
    """The binary128 bit pattern of a positive `v`, rounded to nearest."""
    e = int(floor(log(v, 2)))
    m = int(nint(v * mpf(2) ** (112 - e)))
    if m == 1 << 113:
        m >>= 1
        e += 1
    assert 1 << 112 <= m < 1 << 113
    return (e + 16383) << 112 | (m - (1 << 112))


def boundary_distance(v):
    """Distance from `v` to the nearest binary128 rounding boundary."""
    e = int(floor(log(v, 2)))
    frac = v * mpf(2) ** (112 - e)
    return abs(frac - floor(frac) - mpf(1) / 2) * mpf(2) ** (e - 112)


def audit():
    """Exact-ratio results are pure table sums; check they round decisively."""
    worst = None
    phi = [atan(mpf(i) / SECTORS) for i in range(SECTORS + 1)]
    sums = [p for p in phi if p > 0]
    sums += [pi / 2 + s * p for p in phi for s in (1, -1)]
    sums += [pi - p for p in phi]
    for v in sums:
        d = boundary_distance(v)
        assert d > AUDIT, (v, d)
        worst = d if worst is None else min(worst, d)
    return worst


worst = audit()

print(f"""//! Generated by tools/gen_atan2_f128.py - do not edit by hand.
//!
//! Fixed-point constants for binary128 `atan2q`.  Every entry is a mathematical
//! constant evaluated to 2000 bits with mpmath: the arc tangents of the sector
//! breakpoints i/{SECTORS}, the quadrant offsets 0, pi/2 and pi, the Taylor
//! coefficients 1/(2k+3) of `atan(T)/T`, and 3pi/4 for the infinity edges.
//!
//! The generator audits every sum of these constants that an exact ratio
//! `|y/x| = i/{SECTORS}` can turn into the whole result: each clears the nearest
//! rounding boundary by at least 2^{float(log(worst, 2)):.1f}, so the 384-bit
//! accurate frame decides such inputs outright.
#![allow(clippy::unreadable_literal)]""")

print(f"""
/// `atan(i/{SECTORS})`, scaled by 2^{FRAME} and rounded.  The fast leg reads the top
/// two limbs, the accurate leg all three.
#[rustfmt::skip]
pub const PHI: [[u128; 3]; {SECTORS + 1}] = [""")
for i in range(SECTORS + 1):
    print(f"    {limbs(int(nint(atan(mpf(i) / SECTORS) * mpf(2) ** FRAME)), 3)},")
print("];")

print(f"""
/// The quadrant offsets 0, pi/2, and pi, scaled by 2^{FRAME} and rounded.
#[rustfmt::skip]
pub const QOFF: [[u128; 3]; 3] = [""")
for v in (mpf(0), pi / 2, pi):
    print(f"    {limbs(int(nint(v * mpf(2) ** FRAME)), 3)},")
print("];")

print(f"""
/// `1/(2k+3)` for `k = 0..{TERMS}`, scaled by 2^384: the Taylor coefficients of
/// `atan(T)/T = 1 - sum_k (-1)^k COEF[k] (T^2)^(k+1)`.  The top limb is the
/// same coefficient scaled by 2^128, which is all the fast leg reads.
#[rustfmt::skip]
pub const COEF: [[u128; 3]; {TERMS}] = [""")
for k in range(TERMS):
    print(f"    {limbs(int(nint(mpf(2) ** 384 / (2 * k + 3))), 3)},")
print("];")

print(f"""
/// The bit pattern of 3pi/4 rounded to binary128, for `atan2q(±inf, -inf)`.
pub const FRAC_3PI_4: u128 = {hexs(to_bits(3 * pi / 4), 32)};""")
