#!/usr/bin/env python3
"""Generate Dint (128-bit) accurate-path constants for f64 trig.

Emits PIO2_DINT, SIN_DINT (minimax of sin(r)/r in u=r^2), COS_DINT (minimax of
cos(r) in u=r^2), and TWO_DINT, as Dint literals matching dint_consts.rs.

The kernels were Taylor series (16 sin / 17 cos terms to reach a 2^-130
truncation at u = (pi/4)^2).  A minimax (near-minimax Chebyshev) fit reaches the
SAME 2^-130 bound in 14 terms each, and 14-term truncation (sin ~2^-139,
cos ~2^-134) stays well below the Dint arithmetic floor (~2^-126), so the
accurate path is at least as accurate as the Taylor version while running with
fewer `Dint::mul`s per evaluation (the accurate-path cost is one Dint mul per
term).  This cascades to sin/cos/sincos/tan, which all share these kernels.

Value = (-1)^sgn * (m / 2^127) * 2^ex, m normalized so bit 127 set.
"""
from mpmath import mp, mpf, pi, sin, cos, sqrt, log, floor, nint, chebyfit, polyval

mp.prec = 600


def to_dint(x):
    x = mpf(x)
    sgn = x < 0
    a = abs(x)
    if a == 0:
        return (False, 0, 0)
    ex = int(floor(log(a, 2)))
    mant = a / mpf(2) ** ex            # in [1, 2)
    m = int(nint(mant * mpf(2) ** 127))
    if m >= (1 << 128):                # rounding overflow
        m >>= 1
        ex += 1
    assert (1 << 127) <= m < (1 << 128)
    return (bool(sgn), ex, m)


def dint_to_mpf(x):
    """Inverse of to_dint — the value a Dint literal represents."""
    sgn, ex, m = to_dint(x)
    v = mpf(m) / mpf(2) ** 127 * mpf(2) ** ex
    return -v if sgn else v


def emit_one(name, x):
    sgn, ex, m = to_dint(x)
    print(f"const {name}: Dint = Dint {{")
    print(f"    sgn: {'true' if sgn else 'false'},")
    print(f"    ex: {ex},")
    print(f"    m: 0x{m:032x},")
    print("};\n")


def emit_array(name, values):
    print(f"const {name}: [Dint; {len(values)}] = [")
    for x in values:
        sgn, ex, m = to_dint(x)
        print("    Dint {")
        print(f"        sgn: {'true' if sgn else 'false'},")
        print(f"        ex: {ex},")
        print(f"        m: 0x{m:032x},")
        print("    },")
    print("];\n")


U_MAX = (pi / 4) ** 2

# Kernels as functions of u = r^2 over [0, U_MAX]:
#   sin(r)/r = sin(sqrt(u))/sqrt(u)   (=1 at u=0)
#   cos(r)   = cos(sqrt(u))
g_sin = lambda u: sin(sqrt(u)) / sqrt(u) if u > 0 else mpf(1)
g_cos = lambda u: cos(sqrt(u))


def minimax(f, target_bits=130):
    """Smallest-degree near-minimax (Chebyshev) power-basis fit of f on
    [0, U_MAX] whose max error < 2^-target_bits.  Returns (coeffs_low_first, N).

    The error is re-measured (a) for the exact fit and (b) after quantizing every
    coefficient to a 128-bit Dint, both on a dense sweep, so the emitted table is
    certified, not trusted from chebyfit's own estimate."""
    n = 4
    while True:
        coeffs_hi_first, _ = chebyfit(f, [0, U_MAX], n, error=True)
        coeffs = coeffs_hi_first[::-1]  # mpmath polyval is high-degree-first
        # dense max-error of the exact fit and of the Dint-quantized fit
        qcoeffs_hi = [dint_to_mpf(c) for c in coeffs_hi_first]
        err = qerr = mpf(0)
        for i in range(0, 2001):
            u = U_MAX * mpf(i) / 2000
            truth = f(u)
            err = max(err, abs(polyval(coeffs_hi_first, u) - truth))
            qerr = max(qerr, abs(polyval(qcoeffs_hi, u) - truth))
        if err < mpf(2) ** (-target_bits):
            return coeffs, n, err, qerr
        n += 1


sin_coeffs, NSIN, sin_err, sin_qerr = minimax(g_sin)
cos_coeffs, NCOS, cos_err, cos_qerr = minimax(g_cos)

# Certify the quantized tables still clear the Dint arithmetic floor (~2^-126)
# with margin, so correct rounding is preserved.
assert sin_qerr < mpf(2) ** -128, f"sin quantized err {float(log(sin_qerr,2)):.1f}"
assert cos_qerr < mpf(2) ** -128, f"cos quantized err {float(log(cos_qerr,2)):.1f}"

print("// Dint accurate-path trig constants. GENERATED by tools/gen_dint_trig.py.")
print(f"// Minimax in u = r^2 over [0, (pi/4)^2]: sin {NSIN} terms "
      f"(err ~2^{float(log(sin_err,2)):.1f}, quantized ~2^{float(log(sin_qerr,2)):.1f}),")
print(f"// cos {NCOS} terms (err ~2^{float(log(cos_err,2)):.1f}, "
      f"quantized ~2^{float(log(cos_qerr,2)):.1f}).")
print()
emit_one("PIO2_DINT", pi / 2)
emit_one("TWO_DINT", 2)
emit_array("SIN_DINT", sin_coeffs)
emit_array("COS_DINT", cos_coeffs)
