#!/usr/bin/env python3
"""Emit the f64 atan fast-path tables, ported verbatim from CORE-MATH's atan.c.

CORE-MATH's `cr_atan` reduces |x| with a 129-entry fine tangent table
`A[i] = tan(i·π/256)` (double-double), picks the cell `i` from |x|'s bits via a
per-bucket quadratic (`c[31][3]`), and finishes with a degree-7 odd polynomial
`ch` in plain f64.  Rust cannot spell C hex-float literals, so this script parses
them from the vendored atan.c and prints round-tripping decimal literals for the
`ATAN_FAST_*` constants in src/f64_/atan.rs.

Usage:
    tools/gen_atan_fast_f64.py [path/to/atan.c]
"""
import re
import sys
from pathlib import Path

DEFAULT = Path.home() / "src/core-math-sys/vendor/src/binary64/atan/atan.c"

HEXF = re.compile(r"[+-]?0x[0-9a-fA-F.]+p[+-]?\d+")


def f(s: str) -> str:
    """C hex-float string -> a Rust f64 literal that round-trips to the same bits."""
    return repr(float.fromhex(s))


def block(src: str, decl: str) -> str:
    """Body of the `{...}` initializer following `decl`."""
    start = src.index(decl) + len(decl)
    depth = 0
    for end in range(start, len(src)):
        if src[end] == "{":
            depth += 1
        elif src[end] == "}":
            depth -= 1
            if depth == 0:
                return src[start : end + 1]
    raise ValueError(decl)


def main() -> None:
    path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT
    src = path.read_text()

    # A[][2]: 129 double-double tangent table entries.
    a_body = block(src, "static const double A[][2] =")
    pairs = re.findall(r"\{\s*(" + HEXF.pattern + r")\s*,\s*(" + HEXF.pattern + r")\s*\}", a_body)
    # 128 data entries (i = 0..=127); the fast path's reflection (i = 128) uses
    # -1/x and never indexes the table, and the trailing {0,0} sentinel has no
    # hex floats so it is already excluded.
    assert len(pairs) == 128, len(pairs)
    print(
        "/// CORE-MATH's fine atan reduction table: `A[i] = tan(i·π/256)` as a\n"
        "/// double-double, `i = 0..=127`.  Picking the cell `i` from `|x|`'s bits puts\n"
        "/// the residual angle within `tan(π/512)`, so a single f64 division and a\n"
        "/// degree-7 poly reach correct rounding without double-double reduction.\n"
        "/// Generated by tools/gen_atan_fast_f64.py from CORE-MATH atan.c."
    )
    print("const ATAN_FAST_TABLE: [DoubleDouble; 128] = [")
    for hi, lo in pairs:
        print(f"    DoubleDouble {{ high: {f(hi)}, low: {f(lo)} }},")
    print("];\n")

    # c[31][3]: per-bucket index-fit coefficients (kept as u64 to avoid casts).
    c_body = block(src, "static const uint16_t c[31][3] =")
    triples = re.findall(r"\{\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}", c_body)
    assert len(triples) == 31, len(triples)
    print(
        "/// Per-exponent-bucket index-fit (CORE-MATH's `c[31][3]`): a quadratic in\n"
        "/// `|x|`'s top mantissa bits that yields the fine cell `i`, avoiding an atan\n"
        "/// to pick the cell.  Kept as `u64` so the index arithmetic needs no casts."
    )
    print("const ATAN_FAST_IDX: [[u64; 3]; 31] = [")
    for a, b, cc in triples:
        print(f"    [{a}, {b}, {cc}],")
    print("];\n")

    # ch[]: degree-7 odd poly atan(h)/h on |h| <= tan(pi/512).
    ch = HEXF.findall(block(src, "static const double ch[] ="))
    print("/// `atan(h)/h ≈ Σ ch[k]·h²ᵏ` on `|h| ≤ tan(π/512)`, low-degree first.")
    print(f"const ATAN_FAST_CH: [f64; 4] = [{', '.join(f(v) for v in ch)}];\n")

    # ch2[]: small-|x| poly, atan(x) = x + x^3*ch2(x^2).
    ch2 = HEXF.findall(block(src, "static const double ch2[] ="))
    print("/// Small-`|x|` poly: `atan(x) = x + x³·Σ ch2[k]·x²ᵏ`, low-degree first.")
    print(f"const ATAN_FAST_CH2: [f64; 4] = [{', '.join(f(v) for v in ch2)}];\n")

    # Scalar constants used by the fast path.
    named = {
        "ATAN_STEP_HI": "0x1.921fb54442dp-7",      # i*pi/256 lead per unit i
        "ATAN_STEP_LO": "0x1.8469898cc517p-55",    # ...its low word per unit i
        "ATAN_PI2_HI": "0x1.921fb54442d18p+0",     # pi/2 lead (big-|x| reflection)
        "ATAN_PI2_LO": "0x1.1a62633145c07p-54",    # pi/2 low
        "ATAN_TINY_NUDGE": "0x1p-54",              # |x|<2^-27 correction
        "ATAN_ZIV_E": "0x3.fp-52",                 # main-gate half-width / |h|
        "ATAN_SMALL_UB": "0x4.8p-52",              # small-|x| gate upper bound
        "ATAN_SMALL_LB": "0x2.8p-52",              # small-|x| gate lower bound
    }
    for name, hx in named.items():
        print(f"const {name}: f64 = {f(hx)}; // {hx}")


if __name__ == "__main__":
    main()
