#!/usr/bin/env python3
"""Exact Taylor rationals for asinh and the extended natural-log kernel.

python3 tools/gen_invhyp_f128.py > src/f128_/invhyp_tables.rs
"""
from fractions import Fraction
from math import comb


def table(name, values, scale, doc):
    print(f'\n/// {doc}')
    print('/// Generate: `python3 tools/gen_invhyp_f128.py > src/f128_/invhyp_tables.rs`.')
    print('#[rustfmt::skip]')
    print(f'pub const {name}: [[u128; 3]; {len(values)}] = [')
    for value in values:
        n, r = divmod(value.numerator << scale, value.denominator)
        n += 2*r > value.denominator or (2*r == value.denominator and n % 2)
        assert 0 <= n < 1 << 384
        limbs = [f'{(n >> k) & ((1 << 128)-1):032x}' for k in (0, 128, 256)]
        print('    [' + ', '.join('0x' + s[:16] + '_' + s[16:] for s in limbs) + '],')
    print('];')


print('''//! Generated by tools/gen_invhyp_f128.py; do not edit by hand.
//! Exact rational Taylor coefficients, rounded with integer arithmetic.
#![allow(clippy::unreadable_literal)]''')
c = [Fraction(comb(2*k, k), 4**k*(2*k+1)) for k in range(1, 49)]
# asinh(x)/x = 1 - u*(c0 - u*(c1 - ...)), u=x²<2^-8.
assert c[15] * Fraction(1, 256)**16 < Fraction(1, 2**135)
assert Fraction(comb(98, 49), 4**49*99) * Fraction(1, 256)**49 < Fraction(1, 2**399)
table('ASINH', c, 384, 'Magnitudes of asinh terms x^(2k+1), k=1..48, at 2^384.')
table('LOG', [Fraction(1, k) for k in range(1, 21)], 383,
      '1/k, k=1..20, at 2^383, for the reduced logarithm |z|<2^-18.')
