#!/usr/bin/env python3
"""Generate `src/f128_/asin_tables.rs`: the fixed-point constants of the
binary128 `asinq`/`acosq` root-band fast leg.

Everything here is a *mathematical* constant computed from scratch with mpmath:
for the dyadic breakpoints `sin(phi_j) = j/128` it tabulates `cos(phi_j) =
sqrt(1 - j^2/2^14)` and `phi_j = asin(j/128)`.  The reduction is the sine
difference `sin(A - phi_j) = sin(A)*cos(phi_j) - cos(A)*sin(phi_j)`: with
`sin(phi_j)` dyadic, one side of the difference is an exact small-integer
product, and no division appears anywhere.  No fitted approximation
coefficients, no transcription from another library.

Usage:
    python3 tools/gen_asin_f128.py > src/f128_/asin_tables.rs
"""
from mpmath import mp, mpf, asin, sqrt, nint, floor

mp.prec = 2000

# Breakpoints `sin(phi_j) = j/DENOM`; the reduced argument `u = min(x, sqrt(1 -
# x^2))` never exceeds sqrt(2)/2, so `j` stops at `round(DENOM * sqrt(2)/2)`.
DENOM = 128
COUNT = int(nint(DENOM * sqrt(mpf(2)) / 2)) + 1

# `cos(phi_j)` is a plain 256-bit fraction (it is below 1 for every `j >= 1`);
# `phi_j` rides the fast leg's 2^-253 frame, `atan2q`'s.
COS_FRAME = 256
PHI_FRAME = 253


def hexs(value, digits):
    """Underscore-grouped hex literal of `value` padded to `digits` nibbles."""
    text = format(value, f"0{digits}x")
    groups = [text[i:i + 16] for i in range(0, len(text), 16)]
    return "0x" + "_".join(groups)


def limbs(value, count):
    """`value` as `count` little-endian 128-bit limbs."""
    assert 0 <= value < 1 << (128 * count), value
    parts = [hexs(value >> (128 * i) & (1 << 128) - 1, 32) for i in range(count)]
    return "[" + ", ".join(parts) + "]"


print(f"""//! Generated by tools/gen_asin_f128.py - do not edit by hand.
//!
//! Fixed-point constants for the binary128 `asinq`/`acosq` root band.  Every
//! entry is a mathematical constant evaluated to 2000 bits with mpmath: for the
//! dyadic breakpoints `sin(phi_j) = j/{DENOM}`, the cosines `sqrt(1 - j^2/{DENOM**2})`
//! and the angles `asin(j/{DENOM})` themselves.
#![allow(clippy::unreadable_literal)]

/// `sqrt(1 - (j/{DENOM})^2)`, scaled by 2^{COS_FRAME} and truncated.  Entry 0 would
/// be 2^{COS_FRAME} itself and is never read: a zero sector is the relative band.
#[rustfmt::skip]
pub const COS: [[u128; 2]; {COUNT}] = [""")
for j in range(COUNT):
    v = sqrt(1 - (mpf(j) / DENOM) ** 2) * mpf(2) ** COS_FRAME if j else 0
    print(f"    {limbs(int(floor(v)), 2)},")
print("];")

print(f"""
/// `asin(j/{DENOM})`, scaled by 2^{PHI_FRAME} and rounded: the fast leg's frame.
#[rustfmt::skip]
pub const PHI: [[u128; 2]; {COUNT}] = [""")
for j in range(COUNT):
    print(f"    {limbs(int(nint(asin(mpf(j) / DENOM) * mpf(2) ** PHI_FRAME)), 2)},")
print("];")
