name: Benchmark
on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run benchmarks
      run: cargo bench -- --output-format bencher 2>&1 | tee bench-output.txt

    - name: Publish benchmark numbers
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: cargo
        output-file-path: bench-output.txt
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true
        gh-pages-branch: gh-pages
        benchmark-data-dir-path: dev/bench
        alert-threshold: 200%
        comment-on-alert: false
        fail-on-alert: false